

all: setup


setup:
	install -d ./local
	cp -n mxlib.makefile.inc ./local
	cp -n mx.makefile ./local
	cp -n mx.makefile.inc ./local

overwrite:
	install -d ./local
	cp mxlib.makefile.inc ./local
	cp mx.makefile ./local
	cp mx.makefile.inc ./local
	
