mxlib: ao/aoPaths.hpp File Reference
aoPaths.hpp File Reference
Wavefront Propagation » Adaptive Optics » Adaptive Optics Files
Standardized paths for the mx::AO system.
Standardized paths for the mx::AO system.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file aoPaths.hpp.
#include <mx/environment.hpp>
#include <boost/filesystem.hpp>
Namespaces
mx
The mxlib c++ namespace.
mx::AO::path
Namespace for paths.
mx::AO::path::basis
Namespace for basis paths.
Functions
std::string mx::AO::path::basis::root (const std::string &basisName, bool create=false)
The root path for basis files.
std::string mx::AO::path::dm::root (const std::string &dmName, bool create=false)
The root path for deformable mirror (DM) files.
std::string mx::AO::path::dm::influenceFunctions (const std::string &dmName, bool create=false)
The path for the deformable mirror (DM) influence functions.
std::string mx::AO::path::dm::actuatorPositions (const std::string &dmName, bool create=false)
The path for the deformable mirror (DM) actuator positions.
std::string mx::AO::path::dm::pseudoInverse (const std::string &dmName, bool create=false)
The path for the deformable mirror (DM) influence function pseudo-inverse.
std::string mx::AO::path::dm::mirrorModes (const std::string &dmName, bool create=false)
The path for the deformable mirror (DM) influence function based mirror modes.
std::string mx::AO::path::dm::singularValues (const std::string &dmName, bool create=false)
The path for the deformable mirror (DM) influence function pseudo-inverse singular values.
std::string mx::AO::path::dm::basisRoot (const std::string &dmName, const std::string &basisName, bool create=false)
The root path for the deformable mirror (DM) basis related files.
std::string mx::AO::path::dm::M2c (const std::string &dmName, const std::string &basisName, bool create=false)
The path for the modes-to-commands (M2c) matrix for a deformable mirror (DM) and a basis set.
std::string mx::AO::path::dm::projectedModes (const std::string &dmName, const std::string &basisName, bool create=false)
The path for the projected modes for a deformable mirror (DM) and a basis set.
std::string mx::AO::path::pupil::root (const std::string &pupilName, bool create=false)
The root path for pupil files.
std::string mx::AO::path::pupil::pupilFile (const std::string &pupilName, bool create=false)
The path for the pupil FITS file.
std::string mx::AO::path::sys::root (const std::string &sysName, bool create=false)
The root path for system files.
std::string mx::AO::path::sys::cal::root (const std::string &sysName, bool create=false)
The root path for system calibration files.
std::string mx::AO::path::sys::cal::sysResp (const std::string &sysName, const std::string &dmName, const std::string &wfsName, const std::string &pupilName, const std::string &basisName, bool create=false)
Path for the system response calibration.
std::string mx::AO::path::sys::cal::rMat (const std::string &sysName, const std::string &dmName, const std::string &wfsName, const std::string &pupilName, const std::string &basisName, const std::string &id, bool create=false)
Path for the system response calibration.
std::string mx::AO::path::sys::cal::rImages (const std::string &sysName, const std::string &dmName, const std::string &wfsName, const std::string &pupilName, const std::string &basisName, const std::string &id, bool create=false)
Path for the system response calibration.
std::string mx::AO::path::sys::cal::iMat (const std::string &sysName, const std::string &dmName, const std::string &wfsName, const std::string &pupilName, const std::string &basisName, const std::string &id, bool create=false)
Path for the system response interaction matrix.
Function Documentation
std::string mx::AO::path::dm::actuatorPositions (const std::string & dmName, bool create = false)
The path for the deformable mirror (DM) actuator positions.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the DM actuator positions
Definition at line 127 of file aoPaths.hpp.
References mx::AO::path::dm::actuatorPositions(), and mx::AO::path::basis::root().
Referenced by mx::AO::path::dm::actuatorPositions().
std::string mx::AO::path::dm::basisRoot (const std::string & dmName, const std::string & basisName, bool create = false)
The root path for the deformable mirror (DM) basis related files.
Parameters
[in] dmName the name of the DM
[in] basisName the name of the basis set
[in] create [optional] create the root directory if it noes not exist.
Returns
the root path for the DM basis related files
Definition at line 184 of file aoPaths.hpp.
References mx::AO::path::dm::basisRoot(), and mx::AO::path::basis::root().
Referenced by mx::AO::path::dm::basisRoot(), mx::AO::path::dm::M2c(), and mx::AO::path::dm::projectedModes().
std::string mx::AO::path::sys::cal::iMat (const std::string & sysName, const std::string & dmName, const std::string & wfsName, const std::string & pupilName, const std::string & basisName, const std::string & id, bool create = false)
Path for the system response interaction matrix.
Definition at line 456 of file aoPaths.hpp.
References mx::AO::path::sys::cal::iMat(), and mx::AO::path::sys::cal::sysResp().
Referenced by mx::AO::path::sys::cal::iMat().
std::string mx::AO::path::dm::influenceFunctions (const std::string & dmName, bool create = false)
The path for the deformable mirror (DM) influence functions.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the DM influence functions.
Definition at line 113 of file aoPaths.hpp.
References mx::AO::path::dm::influenceFunctions(), and mx::AO::path::basis::root().
Referenced by mx::AO::path::dm::influenceFunctions().
std::string mx::AO::path::dm::M2c (const std::string & dmName, const std::string & basisName, bool create = false)
The path for the modes-to-commands (M2c) matrix for a deformable mirror (DM) and a basis set.
Parameters
[in] dmName the name of the DM
[in] basisName the name of the basis set
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containting the M2c matrix for a DM and a basis set.
Definition at line 204 of file aoPaths.hpp.
References mx::AO::path::dm::basisRoot(), and mx::AO::path::dm::M2c().
Referenced by mx::AO::path::dm::M2c().
std::string mx::AO::path::dm::mirrorModes (const std::string & dmName, bool create = false)
The path for the deformable mirror (DM) influence function based mirror modes.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the DM influence function based mirror modes
Definition at line 155 of file aoPaths.hpp.
References mx::AO::path::dm::mirrorModes().
Referenced by mx::AO::path::dm::mirrorModes().
std::string mx::AO::path::dm::projectedModes (const std::string & dmName, const std::string & basisName, bool create = false)
The path for the projected modes for a deformable mirror (DM) and a basis set.
Parameters
[in] dmName the name of the DM
[in] basisName the name of the basis set
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containting the Mortho2c matrix for a DM and a basis set.These are the modes as reproduced by the DM actuators.
Parameters
[in] dmName the name of the DM
[in] basisName the name of the basis set
[in] pupilName the name of the pupil
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containting the M2c matrix for a DM and a basis set.
Definition at line 253 of file aoPaths.hpp.
References mx::AO::path::dm::basisRoot(), and mx::AO::path::dm::projectedModes().
Referenced by mx::AO::path::dm::projectedModes().
std::string mx::AO::path::dm::pseudoInverse (const std::string & dmName, bool create = false)
The path for the deformable mirror (DM) influence function pseudo-inverse.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the DM influence function pseudo-inverse matrix
Definition at line 141 of file aoPaths.hpp.
References mx::AO::path::dm::pseudoInverse(), and mx::AO::path::basis::root().
Referenced by mx::AO::path::dm::pseudoInverse().
std::string mx::AO::path::pupil::pupilFile (const std::string & pupilName, bool create = false)
The path for the pupil FITS file.
Parameters
[in] pupilName the name of the pupil file
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the pupil as a 1/0 mask
Definition at line 332 of file aoPaths.hpp.
References mx::AO::path::pupil::pupilFile(), and mx::AO::path::basis::root().
Referenced by mx::AO::path::pupil::pupilFile().
std::string mx::AO::path::sys::cal::rImages (const std::string & sysName, const std::string & dmName, const std::string & wfsName, const std::string & pupilName, const std::string & basisName, const std::string & id, bool create = false)
Path for the system response calibration.
Definition at line 435 of file aoPaths.hpp.
References mx::AO::path::sys::cal::rImages(), and mx::AO::path::sys::cal::sysResp().
Referenced by mx::AO::path::sys::cal::rImages().
std::string mx::AO::path::sys::cal::rMat (const std::string & sysName, const std::string & dmName, const std::string & wfsName, const std::string & pupilName, const std::string & basisName, const std::string & id, bool create = false)
Path for the system response calibration.
Definition at line 414 of file aoPaths.hpp.
References mx::AO::path::sys::cal::rMat(), and mx::AO::path::sys::cal::sysResp().
Referenced by mx::AO::path::sys::cal::rMat().
std::string mx::AO::path::dm::root (const std::string & dmName, bool create = false)
The root path for deformable mirror (DM) files.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the directory if it noes not exist.
Returns
the root path for DM files.
Definition at line 92 of file aoPaths.hpp.
References mx::getEnv().
std::string mx::AO::path::pupil::root (const std::string & pupilName, bool create = false)
The root path for pupil files.
Parameters
[in] pupilName the name of the basis
[in] create [optional] create the directory if it noes not exist.
Returns
the root path for pupil files.
Definition at line 308 of file aoPaths.hpp.
References mx::getEnv().
std::string mx::AO::path::sys::root (const std::string & sysName, bool create = false)
The root path for system files.
Parameters
[in] sysName the name of the system
[in] create [optional] create the directory if it noes not exist.
Returns
the root path for calibration files.
Definition at line 353 of file aoPaths.hpp.
References mx::getEnv().
Referenced by mx::AO::path::sys::cal::root().
std::string mx::AO::path::sys::cal::root (const std::string & sysName, bool create = false)
The root path for system calibration files.
Parameters
[in] sysName the name of the system
[in] create [optional] create the directory if it noes not exist.
Returns
the root path for calibration files.
Definition at line 377 of file aoPaths.hpp.
References mx::AO::path::sys::root().
std::string mx::AO::path::dm::singularValues (const std::string & dmName, bool create = false)
The path for the deformable mirror (DM) influence function pseudo-inverse singular values.
Parameters
[in] dmName the name of the DM
[in] create [optional] create the root directory if it noes not exist.
Returns
the path to the FITS file containing the DM influence function pseudo-inverse singular values
Definition at line 169 of file aoPaths.hpp.
References mx::AO::path::basis::root(), and mx::AO::path::dm::singularValues().
Referenced by mx::AO::path::dm::singularValues().
std::string mx::AO::path::sys::cal::sysResp (const std::string & sysName, const std::string & dmName, const std::string & wfsName, const std::string & pupilName, const std::string & basisName, bool create = false)
Path for the system response calibration.
Definition at line 393 of file aoPaths.hpp.
References mx::AO::path::basis::root(), and mx::AO::path::sys::cal::sysResp().
Referenced by mx::AO::path::sys::cal::iMat(), mx::AO::path::sys::cal::rImages(), mx::AO::path::sys::cal::rMat(), and mx::AO::path::sys::cal::sysResp().