mxlib: ao/basis.hpp File Reference
basis.hpp File Reference
Wavefront Propagation » Adaptive Optics » Adaptive Optics Files
Utilities for working with a modal basis.
Utilities for working with a modal basis.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file basis.hpp.
#include <mx/fourierModes.hpp>
#include <mx/fitsFile.hpp>
#include <mx/gramSchmidt.hpp>
#include <mx/eigenUtils.hpp>
#include <mx/imageFilters.hpp>
#include <mx/imagePads.hpp>
#include <mx/signalWindows.hpp>
#include "aoPaths.hpp"
Namespaces
mx
The mxlib c++ namespace.
Macros
#define MXAO_ORTHO_METHOD_SGS 0
Constant to specify using the stabilized Gramm Schmidt (SGS) orthogonalization procedure.
#define MXAO_ORTHO_METHOD_SVD 1
Constant to specify using the singular value decomposition (SVD) for orthogonalizing a modal basis.
Functions
template<typename realT >
void mx::AO::applyPupil2Basis (mx::eigenCube< realT > &modes, const std::string &basisName, const std::string &pupilName, realT fwhm=0)
Multiply a raw modal basis by a pupil mask.
template<typename realT >
void mx::AO::orthogonalizeBasis (const std::string &orthoName, const std::string &basisName, const std::string &pupilName, int method)
Calculate an orthogonal projection of a basis on a pupil.
Macro Definition Documentation
#define MXAO_ORTHO_METHOD_SGS 0
Constant to specify using the stabilized Gramm Schmidt (SGS) orthogonalization procedure.
Definition at line 76 of file basis.hpp.
Referenced by mx::AO::orthogonalizeBasis().
#define MXAO_ORTHO_METHOD_SVD 1
Constant to specify using the singular value decomposition (SVD) for orthogonalizing a modal basis.
Definition at line 81 of file basis.hpp.
Referenced by mx::AO::orthogonalizeBasis().
Function Documentation
template<typename realT > void mx::AO::applyPupil2Basis (mx::eigenCube< realT > & modes, const std::string & basisName, const std::string & pupilName, realT fwhm = 0)
Multiply a raw modal basis by a pupil mask.
Definition at line 29 of file basis.hpp.
References mx::AO::applyPupil2Basis(), mx::improc::filterImage(), and mx::improc::padImage().
Referenced by mx::AO::applyPupil2Basis(), and mx::AO::orthogonalizeBasis().
template<typename realT > void mx::AO::orthogonalizeBasis (const std::string & orthoName, const std::string & basisName, const std::string & pupilName, int method)
Calculate an orthogonal projection of a basis on a pupil.
Can use either the stabilized Gramm Schmidt (SGS) procedure, or Singular Value Decomposition (SVD). This calls applyPupil2Basis as a first step..
Parameters
[in] basisName the name of the basis to orthogonalize
[in] pupilName the name of the pupil on which to orthogonalize.
[in] method either MXAO_ORTHO_METHOD_SGS (for SGS) or MXAO_ORTHO_METHOD_SVD (for SVD)
Template Parameters
realT
Definition at line 155 of file basis.hpp.
References mx::AO::applyPupil2Basis(), mx::improc::cutPaddedImage(), mx::improc::filterImage(), MXAO_ORTHO_METHOD_SGS, MXAO_ORTHO_METHOD_SVD, and mx::improc::padImage().