mxlib: mx::gnuPlot Class Reference
mx::gnuPlot Class Reference
General Mathematics » Plotting Data
A c++ interface to gnuplot.
Spawns a gnuplot sesssion and communicates with it.
Todo:
Use mxError for error reporting.
An example of using gnuPlot to plot data from a file:
gnuPlot gp; //This automatically connects, and is now ready to plot.
gp.plot("my_data_file.dat", "u 1:2 w l"); //Plots the data in the file
std::cout << gp.getResponse("show terminal") << "\n"; //Sends the command to gnuplot, gets the response.
Error checking and reporting is not straightforward since gnuplot does not return a result if there is no error. If there is an error, it can take several hundred milliseconds for a response to be available. So for a typical plot command, say, one does not want to try to read the stderr ouput just in case as this will just time out with a delay.
For cases where a response is expected, the following example shows how to check for errors.
errno = 0;
std::string response = gp.getResponse("show terminal"); //Waits up to 0.5 seconds, or a user specified timeout.
if(response == "") //This indicates some error occurred, or a timeout.
{
  if(gp.gpError())
  {
     std::cerr << "gnuplot returned error:\n" << gp.gpErrorMsg() << "\n";
  }
  else if(errno)
  {
     perror("error getting response: ");
  }
  else
  {
     std::cerr << "timed out\n";
  }
}
else
{
  std::cout << response << "\n";
}
Definition at line 137 of file gnuPlot.hpp.
#include <gnuPlot.hpp>
Public Member Functions
int connect ()
Connect to gnuplot.
bool gpError ()
Return the value of the gpError flag.
std::string gpErrorMsg ()
Return the gnuplot error message.
int command (const std::string &com, bool flush=true)
Send a command to gnuplot.
int checkResponse (std::string &response, double timeout=0)
Check for a response from gnuplot.
std::string getResponse (const std::string &com, double timeout=0.5)
Get a response from gnuplot for a given command.
int replot ()
Issue the replot command.
int logy ()
Set the y axis to log scale.
int logx ()
Set the x axis to log scale.
int logxy ()
Set the x and y axes to log scale.
int ulogy ()
Unset the y axis from log scale.
int ulogx ()
Unset the x axis from log scale.
int ulogxy ()
Unset the x and y axes from log scale.
int plot (const std::string &fname, const std::string &modifiers="")
Issue a plot command with a n separate lines specified by gplot_spec structures.
template<typename dataT >
int plot (const dataT *y, size_t N, const std::string &modifiers="", const std::string &title="")
Plot data from an array.
template<typename dataT >
int plot (const std::vector< dataT > &y, const std::string &modifiers="", const std::string &title="")
Plot data from a vector.
template<typename dataTx , typename dataTy >
int plot (const dataTx *x, const dataTy *y, size_t N, const std::string &modifiers="", const std::string &title="")
Plot y vs. x data from arrays.
template<typename dataTx , typename dataTy >
int plot (const std::vector< dataTx > &x, const std::vector< dataTy > &y, const std::string &modifiers="", const std::string &title="")
Plot y vs. x data from vectors.
Protected Member Functions
FILE * openTempFile (char *fname)
Open a temporary binary file, and provide the filename.
Protected Attributes
bool _gpError
Set to true if the response indicates a gnuplot error.
FILE * _pipeH
File stream for the gnuplot interface.
std::string _errLocation
Where to create gnuplot stderr fifo.
std::string _errFName
File name of the gnuplot stderr fifo.
int _errFD
File descriptor for the gnuplot stderr fifo.
std::string _tempLocation
Location of temporary files.
std::vector< std::string > _tempFiles
Vector of all temporary file names opened, used for removal on destruction.
bool _deleteTemp
Flag to control whether temporary files are deleted on destruction. Default is true (files deleted).
Member Function Documentation
int mx::gnuPlot::checkResponse (std::string & response, double timeout = 0) inline
Check for a response from gnuplot.
It typically takes some time for a response from gnuplot to become readable, whether an error occurs or not. It is often 0.3 seconds or more. If there is no error, there will be no response so waiting for a response to check for errors after every command can be very time consuming. Thus it is a choice whether to check for errors from gnuplot after every command, and what timeout to use.
gnuplot terminates all outputs with \n\n, so this reads up to these two characters. It then strips any leading and trailing whitespace.
If the response begins with gnuplot>, then the response is an error. In this case, checkResponse returns -1 and the gpError flag is set. If gpError is not set but the return value is -1, then some other error occurred (check errno).
Parameters
[out] response contains the response from gnuplot, but is empty on timeout or error.
[in] timeout [optional] is the length of time, in seconds, to wait for a response. Default is 0, but a minimum of 0.5 if a response is expected.
Return values
0 on timeout or successful read
-1 on error, or if the gnuplot response indicates an error.
Definition at line 580 of file gnuPlot.hpp.
References MXE_GNUPLOTERR, MXE_TIMEOUT, mxError, and mxPError.
int mx::gnuPlot::command (const std::string & com, bool flush = true) inline
Send a command to gnuplot.
The newline is appended to the command, and then it is sent to gnuplot.
Parameters
[in] com is the command string
[in] flush [optional] if true, then the output stream is flushed once the command is written.
Return values
0 on success
-1 on error
Definition at line 566 of file gnuPlot.hpp.
Referenced by mx::math::eigenPseudoInverse(), and mx::AO::influenceFunctionsGaussian().
int mx::gnuPlot::connect () inline
Connect to gnuplot.
Spawns a gnuplot session using popen with stderr redirected to a temporary file. The temporary file is opened for reading.
Return values
0 on success
-1 on error
Definition at line 493 of file gnuPlot.hpp.
References MX_GP_FC_RETRIES, MX_GP_FC_TIME, MX_GP_FNAME_SZ, MXE_PROCERR, mxError, and mxPError.
std::string mx::gnuPlot::getResponse (const std::string & com, double timeout = 0.5) inline
Get a response from gnuplot for a given command.
This should only be used if a response is expected.
Parameters
[in] com is the command string
[in] timeout [optional] is the length of time, in seconds, to wait for a response. Default is 0.5, which is the minimum that should be used.
Returns
"" (empty string) on timeout or error (errno and gpError() should be checked), and the response from gnuplot otherwise.
Definition at line 683 of file gnuPlot.hpp.
bool mx::gnuPlot::gpError () inline
Return the value of the gpError flag.
This flag is set if gnuplot returns an error message (see checkResponse()). The error message can be accessed with gpErrorMsg().
Return values
0 if no error
-1 if an error has occurred.
Definition at line 554 of file gnuPlot.hpp.
std::string mx::gnuPlot::gpErrorMsg () inline
Return the gnuplot error message.
The error message is extracted by checkResponse() when the response from gnuplot begins with "gnuplot>".
Definition at line 560 of file gnuPlot.hpp.
int mx::gnuPlot::logx () inline
Set the x axis to log scale.
Sends the command:
 set log x
Return values
0 on success
-1 on error
Definition at line 707 of file gnuPlot.hpp.
int mx::gnuPlot::logxy () inline
Set the x and y axes to log scale.
Sends the commands:
 set log x
 set log y
Return values
0 on success
-1 on error
Definition at line 713 of file gnuPlot.hpp.
int mx::gnuPlot::logy () inline
Set the y axis to log scale.
Sends the command:
 set log y
Return values
0 on success
-1 on error
Definition at line 701 of file gnuPlot.hpp.
Referenced by mx::math::eigenPseudoInverse().
FILE * mx::gnuPlot::openTempFile (char * fname) protected
Open a temporary binary file, and provide the filename.
Definition at line 906 of file gnuPlot.hpp.
References MX_GP_TEMP_SZ.
int mx::gnuPlot::plot (const std::string & fname, const std::string & modifiers = "")
Issue a plot command with a n separate lines specified by gplot_spec structures.
Forms the plot command as follows
  plot <plot_specs[0]>, /
       <plot_specs[1]>, /
       ---
       <plot_specs[n-1]>
Plot from a file Forms the gnuplot plot command as follows:
plot "<fname>" <modifiers>
The modifiers string can contain any modifiers such as using, title, etc.
Parameters
[in] fname is the name of the file containing data to plot
[in] modifiers [optional] contains any modifiers to the plot command.
Return values
0 on success
-1 on error
Definition at line 744 of file gnuPlot.hpp.
Referenced by mx::math::eigenPseudoInverse(), and mx::AO::influenceFunctionsGaussian().
template<typename dataT > int mx::gnuPlot::plot (const dataT * y, size_t N, const std::string & modifiers = "", const std::string & title = "")
Plot data from an array.
Copies the data in the array to a temporary binary file, and then forms the gnuplot plot command as follows:
 plot "temp-file-name" binary format="%dataT" u 1 t "title" <modifiers>
The modifiers string must NOT contain the binary, format, using, or the title modifiers, but can contain any other modifiers. Title is specified so that the name of the temporary file name is not printed on the plot.
Parameters
[in] y is a pointer to an array of data
[in] N is the length of the array
[in] modifiers [optional] contains any modifiers to the plot command other than binary, format, using, and title.
[in] title [optional] contains the title of the data set, default is an empty string and no key on the plot
Return values
0 on success
-1 on error
Definition at line 769 of file gnuPlot.hpp.
References MX_GP_TEMP_SZ.
template<typename dataT > int mx::gnuPlot::plot (const std::vector< dataT > & y, const std::string & modifiers = "", const std::string & title = "")
Plot data from a vector.
Copies the data in the vector to a temporary binary file, and then forms the gnuplot plot command as follows:
 plot "temp-file-name" binary format="%dataT" u 1 t "title" <modifiers>
The modifiers string must NOT contain the binary, format, using, or the title modifiers, but can contain any other modifiers. Title is specified so that the name of the temporary file name is not printed on the plot.
Parameters
[in] y is the vector containing the data
[in] modifiers [optional] contains any modifiers to the plot command other than binary, format, using, and title.
[in] title [optional] contains the title of the data set, default is an empty string and no key on the plot
Return values
0 on success
-1 on error
Definition at line 808 of file gnuPlot.hpp.
template<typename dataTx , typename dataTy > int mx::gnuPlot::plot (const dataTx * x, const dataTy * y, size_t N, const std::string & modifiers = "", const std::string & title = "")
Plot y vs. x data from arrays.
Copies the data in the arrays to a temporary binary file, and then forms the gnuplot plot command as follows:
 plot "temp-file-name" binary format="%dataTx%dataTy" u 1:2 t "title" <modifiers>
The modifiers string must NOT contain the binary, format, using, or the title modifiers, but can contain any other modifiers. Title is specified so that the name of the temporary file name is not printed on the plot.
Parameters
[in] x is a pointer to an array of data for the independent variable
[in] y is a pointer to an array of data for the dependent variable
[in] N is the length of the arrays
[in] modifiers [optional] contains any modifiers to the plot command other than binary, format, using, and title.
[in] title [optional] contains the title of the data set, default is an empty string and no key on the plot
Return values
0 on success
-1 on error
Definition at line 814 of file gnuPlot.hpp.
References MX_GP_TEMP_SZ.
template<typename dataTx , typename dataTy > int mx::gnuPlot::plot (const std::vector< dataTx > & x, const std::vector< dataTy > & y, const std::string & modifiers = "", const std::string & title = "")
Plot y vs. x data from vectors.
Copies the data in the vectors to a temporary binary file, and then forms the gnuplot plot command as follows:
 plot "temp-file-name" binary format="%dataTx%dataTy" u 1:2 t "title" <modifiers>
The modifiers string must NOT contain the binary, format, using, or the title modifiers, but can contain any other modifiers. Title is specified so that the name of the temporary file name is not printed on the plot.
Parameters
[in] x is a vector of data for the independent variable
[in] y is a vector of data for the dependent variable
[in] modifiers [optional] contains any modifiers to the plot command other than binary, format, using, and title.
[in] title [optional] contains the title of the data set, default is an empty string and no key on the plot
Return values
0 on success
-1 on error
Definition at line 901 of file gnuPlot.hpp.
int mx::gnuPlot::replot () inline
Issue the replot command.
Return values
0 on success
-1 on error
Definition at line 695 of file gnuPlot.hpp.
int mx::gnuPlot::ulogx () inline
Unset the x axis from log scale.
Sends the command:
 unset log x
Return values
0 on success
-1 on error
Definition at line 729 of file gnuPlot.hpp.
int mx::gnuPlot::ulogxy () inline
Unset the x and y axes from log scale.
Sends the command:
 unset log x
 unset log y
Return values
0 on success
-1 on error
Definition at line 735 of file gnuPlot.hpp.
int mx::gnuPlot::ulogy () inline
Unset the y axis from log scale.
Sends the command:
 unset log y
Return values
0 on success
-1 on error
Definition at line 723 of file gnuPlot.hpp.
Member Data Documentation
bool mx::gnuPlot::_deleteTemp protected
Flag to control whether temporary files are deleted on destruction. Default is true (files deleted).
Definition at line 170 of file gnuPlot.hpp.
int mx::gnuPlot::_errFD protected
File descriptor for the gnuplot stderr fifo.
Definition at line 159 of file gnuPlot.hpp.
std::string mx::gnuPlot::_errFName protected
File name of the gnuplot stderr fifo.
Definition at line 156 of file gnuPlot.hpp.
std::string mx::gnuPlot::_errLocation protected
Where to create gnuplot stderr fifo.
Default is /dev/shm/
Definition at line 153 of file gnuPlot.hpp.
bool mx::gnuPlot::_gpError protected
Set to true if the response indicates a gnuplot error.
Definition at line 144 of file gnuPlot.hpp.
FILE* mx::gnuPlot::_pipeH protected
File stream for the gnuplot interface.
Definition at line 148 of file gnuPlot.hpp.
std::vector<std::string> mx::gnuPlot::_tempFiles protected
Vector of all temporary file names opened, used for removal on destruction.
Definition at line 167 of file gnuPlot.hpp.
std::string mx::gnuPlot::_tempLocation protected
Location of temporary files.
Default is /dev/shm/
Definition at line 164 of file gnuPlot.hpp.
The documentation for this class was generated from the following file:
gnuPlot.hpp