mxlib: mx::improc::eigenCube< dataT > Class Template Reference
mx::improc::eigenCube< dataT > Class Template Reference
Image Processing » Image Processing with Eigen
template<typename dataT>
class mx::improc::eigenCube< dataT >
An image cube with an Eigen-like API.
Definition at line 34 of file eigenCube.hpp.
#include <improc/eigenCube.hpp>
Public Member Functions
Map< Array< dataT, Dynamic, Dynamic > > cube ()
Returns a 2D Eigen::Map pointed at the entire cube.
Map< Array< dataT, Dynamic, Dynamic > > image (Index n)
Returns a 2D Eigen::Map pointed at the specified image.
Map< Array< dataT, Dynamic, Dynamic >, Unaligned, Stride< Dynamic, Dynamic > > pixel (Index i, Index j)
Returns an Eigen::Map-ed vector of the pixels at the given coordinate.
Map< Array< dataT, Dynamic, Dynamic > > asVectors ()
Return an Eigen::Map of the cube where each image is a vector.
void Covar (Matrix< dataT, Dynamic, Dynamic > &cv)
Calculate the covariance matrix of the images in the cube.
template<typename eigenT >
void mean (eigenT &mim)
Calculate the mean image of the cube.
template<typename eigenT , typename eigenCubeT >
void mean (eigenT &mim, eigenCubeT &mask)
Calculate the mean image of the cube with a mask.
template<typename eigenT >
void mean (eigenT &mim, std::vector< dataT > &weights)
Calculate the weighted mean image of the cube.
template<typename eigenT , typename eigenCubeT >
void mean (eigenT &mim, std::vector< dataT > &weights, eigenCubeT &mask)
Calculate the weighted mean image of the cube, with a mask cube.
template<typename eigenT >
void median (eigenT &mim)
Calculate the median image of the cube.
template<typename eigenT >
void sigmaMean (eigenT &mim, Scalar sigma)
Calculate the sigma clipped mean image of the cube.
template<typename eigenT , typename eigenCubeT >
void sigmaMean (eigenT &mim, eigenCubeT &mask, Scalar sigma)
Calculate the sigma clipped mean image of the cube, with a mask cube.
template<typename eigenT >
void sigmaMean (eigenT &mim, std::vector< dataT > &weights, Scalar sigma)
Calculate the sigma clipped weighted mean image of the cube.
template<typename eigenT , typename eigenCubeT >
void sigmaMean (eigenT &mim, std::vector< dataT > &weights, eigenCubeT &mask, Scalar sigma)
Calculate the sigma clipped weighted mean image of the cube, with a mask cube.
Member Function Documentation
template<typename dataT > Map< Array< dataT, Dynamic, Dynamic > > mx::improc::eigenCube< dataT >::asVectors ()
Return an Eigen::Map of the cube where each image is a vector.
Definition at line 368 of file eigenCube.hpp.
Referenced by mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::worker().
template<typename dataT> void mx::improc::eigenCube< dataT >::Covar (Matrix< dataT, Dynamic, Dynamic > & cv)
Calculate the covariance matrix of the images in the cube.
Definition at line 374 of file eigenCube.hpp.
template<typename dataT > Map< Array< dataT, Dynamic, Dynamic > > mx::improc::eigenCube< dataT >::cube ()
Returns a 2D Eigen::Map pointed at the entire cube.
Definition at line 350 of file eigenCube.hpp.
Referenced by mx::AO::analysis::fourierVarVec(), and mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::worker().
template<typename dataT > Map< Array< dataT, Dynamic, Dynamic > > mx::improc::eigenCube< dataT >::image (Index n)
Returns a 2D Eigen::Map pointed at the specified image.
Definition at line 356 of file eigenCube.hpp.
Referenced by mx::improc::HCIobservation< _realT >::coaddImages(), mx::AO::analysis::fourierVarVec(), mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake(), mx::improc::ADIobservation< _realT, _derotFunctObj >::makeMaskCube(), and mx::AO::sim::directPhaseReconstructor< realT >::reconstruct().
template<typename dataT > template<typename eigenT > void mx::improc::eigenCube< dataT >::mean (eigenT & mim)
Calculate the mean image of the cube.
Template Parameters
eigenT an Eigen-like type.
Parameters
[out] mim the resultant mean image. Is resized.
Definition at line 381 of file eigenCube.hpp.
Referenced by mx::improc::HCIobservation< _realT >::coaddImages().
template<typename dataT > template<typename eigenT , typename eigenCubeT > void mx::improc::eigenCube< dataT >::mean (eigenT & mim, eigenCubeT & mask)
Calculate the mean image of the cube with a mask.
Template Parameters
eigenT an Eigen-like type.
eigenCubeT an eigenCube type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] mask a mask cube. Only pixels with value 1 are included in the mean calculation.
Definition at line 397 of file eigenCube.hpp.
References mx::astro::constants::k(), and mx::vectorMean().
template<typename dataT> template<typename eigenT > void mx::improc::eigenCube< dataT >::mean (eigenT & mim, std::vector< dataT > & weights)
Calculate the weighted mean image of the cube.
Template Parameters
eigenT an Eigen-like type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] weights a vector of weights to use for calculating the mean
Definition at line 436 of file eigenCube.hpp.
References mx::astro::constants::k(), and mx::vectorMean().
template<typename dataT> template<typename eigenT , typename eigenCubeT > void mx::improc::eigenCube< dataT >::mean (eigenT & mim, std::vector< dataT > & weights, eigenCubeT & mask)
Calculate the weighted mean image of the cube, with a mask cube.
Template Parameters
eigenT an Eigen-like type.
eigenCubeT an eigenCube type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] weights a vector of weights to use for calculating the mean
[in] mask a mask cube. Only pixels with value 1 are included in the mean calculation.
Definition at line 463 of file eigenCube.hpp.
References mx::astro::constants::k(), and mx::vectorMean().
template<typename dataT > template<typename eigenT > void mx::improc::eigenCube< dataT >::median (eigenT & mim)
Calculate the median image of the cube.
Template Parameters
eigenT an Eigen-like type.
Parameters
[out] mim the resultant median image. Is resized.
Definition at line 504 of file eigenCube.hpp.
References mx::improc::imageMedian().
Referenced by mx::improc::HCIobservation< _realT >::coaddImages().
template<typename dataT > Map< Array< dataT, Dynamic, Dynamic >, Unaligned, Stride< Dynamic, Dynamic > > mx::improc::eigenCube< dataT >::pixel (Index i, Index j)
Returns an Eigen::Map-ed vector of the pixels at the given coordinate.
Definition at line 362 of file eigenCube.hpp.
template<typename dataT > template<typename eigenT > void mx::improc::eigenCube< dataT >::sigmaMean (eigenT & mim, Scalar sigma)
Calculate the sigma clipped mean image of the cube.
Template Parameters
eigenT an Eigen-like type.
Parameters
[out] mim the resultant mean image
[in] sigma the sigma value at which to clip.
Definition at line 522 of file eigenCube.hpp.
References mx::astro::constants::k(), and mx::vectorSigmaMean().
template<typename dataT > template<typename eigenT , typename eigenCubeT > void mx::improc::eigenCube< dataT >::sigmaMean (eigenT & mim, eigenCubeT & mask, Scalar sigma)
Calculate the sigma clipped mean image of the cube, with a mask cube.
Template Parameters
eigenT an Eigen-like type.
eigenCubeT an eigenCube type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] mask a mask cube. Only pixels with value 1 are included in the mean calculation.
[in] sigma the sigma value at which to clip.
Definition at line 549 of file eigenCube.hpp.
References mx::astro::constants::k(), and mx::vectorSigmaMean().
template<typename dataT> template<typename eigenT > void mx::improc::eigenCube< dataT >::sigmaMean (eigenT & mim, std::vector< dataT > & weights, Scalar sigma)
Calculate the sigma clipped weighted mean image of the cube.
Template Parameters
eigenT an Eigen-like type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] weights a vector of weights to use for calculating the mean
[in] sigma the sigma value at which to clip.
Definition at line 587 of file eigenCube.hpp.
References mx::astro::constants::k(), and mx::vectorSigmaMean().
template<typename dataT> template<typename eigenT , typename eigenCubeT > void mx::improc::eigenCube< dataT >::sigmaMean (eigenT & mim, std::vector< dataT > & weights, eigenCubeT & mask, Scalar sigma)
Calculate the sigma clipped weighted mean image of the cube, with a mask cube.
Template Parameters
eigenT an Eigen-like type.
eigenCubeT an eigenCube type.
Parameters
[out] mim the resultant mean image. Is resized.
[in] weights a vector of weights to use for calculating the mean
[in] mask a mask cube. Only pixels with value 1 are included in the mean calculation.
[in] sigma the sigma value at which to clip.
Definition at line 614 of file eigenCube.hpp.
References mx::astro::constants::k(), and mx::vectorSigmaMean().
The documentation for this class was generated from the following file:
improc/eigenCube.hpp