mxlib: mxException Class Reference
mxException Class Reference
Error Handling
The mxlib exception class.
Provides a rich error report via the standard what().
Definition at line 19 of file mxException.hpp.
#include <mxException.hpp>
Inherits exception.
Public Member Functions
mxException () noexcept
Default constructor.
mxException (const mxException &e) noexcept
Copy constructor.
mxException (const std::string &esrc, const int &ec, const std::string &emnem, const std::string &efile, const int &line, const std::string &expl)
Construct and fill in each of the values.
mxException & operator= (const mxException &e) noexcept
Assignment operator.
virtual ~mxException () throw ()
Destructor.
virtual void build_what ()
Build the what string.
virtual const char * what () const noexcept
Return the details of the exception as a single string.
Public Attributes
std::string except_code_source
The source of the exception, such as stdlib or cfitisio.
int except_code
The source specific error code.
std::string except_code_mnem
The mnemonic associated with the error code.
std::string except_file
The source file where the exception originated.
int except_line
The line number of the file where the exception originated.
std::string except_explanation
The long explanation of the error.
Protected Attributes
char whatstr [4096]
Contains the what() string.
Constructor & Destructor Documentation
mxException::mxException () inline noexcept
Default constructor.
Definition at line 47 of file mxException.hpp.
References build_what().
mxException::mxException (const mxException & e) inline noexcept
Copy constructor.
Definition at line 56 of file mxException.hpp.
References build_what().
mxException::mxException (const std::string & esrc, const int & ec, const std::string & emnem, const std::string & efile, const int & line, const std::string & expl) inline
Construct and fill in each of the values.
Definition at line 69 of file mxException.hpp.
References build_what().
virtual mxException::~mxException () throw () inline virtual
Destructor.
Definition at line 96 of file mxException.hpp.
Member Function Documentation
virtual void mxException::build_what () inline virtual
Build the what string.
Must be called after updating any values, since the what() method is const const.
Definition at line 103 of file mxException.hpp.
Referenced by mxException(), and operator=().
mxException& mxException::operator= (const mxException & e) inline noexcept
Assignment operator.
Definition at line 83 of file mxException.hpp.
References build_what(), and except_code_source.
virtual const char* mxException::what () const inline virtual noexcept
Return the details of the exception as a single string.
Definition at line 120 of file mxException.hpp.
References whatstr.
Member Data Documentation
int mxException::except_code
The source specific error code.
Definition at line 32 of file mxException.hpp.
std::string mxException::except_code_mnem
The mnemonic associated with the error code.
Definition at line 35 of file mxException.hpp.
std::string mxException::except_code_source
The source of the exception, such as stdlib or cfitisio.
Definition at line 29 of file mxException.hpp.
Referenced by operator=().
std::string mxException::except_explanation
The long explanation of the error.
Definition at line 44 of file mxException.hpp.
std::string mxException::except_file
The source file where the exception originated.
Definition at line 38 of file mxException.hpp.
int mxException::except_line
The line number of the file where the exception originated.
Definition at line 41 of file mxException.hpp.
char mxException::whatstr[4096] protected
Contains the what() string.
Definition at line 24 of file mxException.hpp.
Referenced by what().
The documentation for this class was generated from the following file:
mxException.hpp