mxlib: mx::improc::fitsHeader Class Reference
mx::improc::fitsHeader Class Reference
Image Processing » FITS Files
Class to manage a complete fits header.
Manages tasks such as insertion (avoiding duplicates), and keyword lookup. The cards are stored in a std::list to preserve order, but a std::unordered_multimap is used to provide fast keyword lookup.
Definition at line 33 of file fitsHeader.hpp.
#include <improc/fitsHeader.hpp>
Public Types
typedef std::list< fitsHeaderCard >::iterator headerIterator
The iterator type for the cards list.
typedef std::unordered_multimap< std::string, headerIterator >::iterator mapIterator
The iterator type for the card map.
Public Member Functions
fitsHeader ()
Default c'tor.
fitsHeader (const fitsHeader &head)
Copy constructor.
~fitsHeader ()
Destructor.
fitsHeader & operator= (const fitsHeader &head)
Assignment.
headerIterator begin ()
Get iterator to the beginning of the cards list.
headerIterator end ()
Get iterator to the end of the cards list.
headerIterator iterator (const std::string &keyword)
Get iterator pointing to a specific element.
bool empty ()
Test whether the header is empty.
size_t size ()
Get number of cards currently stored in the header.
void clear ()
Clear all cards from the header.
void erase (const std::string &keyword)
Erase card by keyword.
void erase (headerIterator it)
Erase card by iterator.
void eraseStandardTop ()
Erase the standard entries at the top of the header.
void append (fitsHeaderCard card)
Append a fitsHeaderCard to the end of the header.
template<typename typeT >
void append (const std::string &k, const typeT &v, const std::string &c)
Append a card to the end of the header, from the three components of a card.
template<typename typeT >
void append (const std::string &k, const typeT &v)
Append a card to the end of the header, from the components of a card with no comment.
void append (const std::string &k)
Append a card to the end of the header, with just a keyword.
void append (fitsHeader &head)
Append a fitsHeader to the end of the header.
void insert_before (headerIterator it, fitsHeaderCard card)
Insert a card before another card.
template<typename typeT >
void insert_before (headerIterator it, const std::string &k, typeT v, const std::string &c)
Insert a card before another card, specifying the card by its components.
template<typename typeT >
void insert_before (headerIterator it, const std::string &k, typeT v)
Insert a card before another card, specifying the card by its components.
void insert_after (headerIterator it, fitsHeaderCard card)
Insert a card after another card.
template<typename typeT >
void insert_after (headerIterator it, const std::string &k, typeT v, const std::string &c)
Insert a card after another card, specifying the card by its components.
template<typename typeT >
void insert_after (headerIterator it, const std::string &k, typeT v)
Insert a card after another card, specifying the card by its components.
fitsHeaderCard & operator[] (const std::string &keyword)
Card access by keyword operator.
const fitsHeaderCard & operator[] (const std::string &keyword) const
Card access by keyword operator (const version)
Protected Attributes
std::list< fitsHeaderCard > cards
The storage for the FITS header cards.
std::unordered_multimap< std::string, headerIterator > cardMap
This multimap allows for fast lookup by keyword.
Member Typedef Documentation
typedef std::list<fitsHeaderCard>::iterator mx::improc::fitsHeader::headerIterator
The iterator type for the cards list.
Definition at line 39 of file fitsHeader.hpp.
typedef std::unordered_multimap<std::string, headerIterator>::iterator mx::improc::fitsHeader::mapIterator
The iterator type for the card map.
Definition at line 42 of file fitsHeader.hpp.
Constructor & Destructor Documentation
mx::improc::fitsHeader::fitsHeader () inline
Default c'tor.
Definition at line 245 of file fitsHeader.hpp.
mx::improc::fitsHeader::fitsHeader (const fitsHeader & head) inline
Copy constructor.
Must be explicitly defined to handle creation of new iterators in the cardMap
Parameters
head The fitsHeader to copy
Definition at line 250 of file fitsHeader.hpp.
References operator=().
mx::improc::fitsHeader::~fitsHeader () inline
Destructor.
Definition at line 257 of file fitsHeader.hpp.
References clear().
Member Function Documentation
void mx::improc::fitsHeader::append (fitsHeaderCard card) inline
Append a fitsHeaderCard to the end of the header.
Parameters
card is a fitsHeaderCard already populated
Definition at line 385 of file fitsHeader.hpp.
References cardMap, cards, mx::improc::fitsHeaderCard::keyword, and mx::improc::fitsHeaderCard::type.
Referenced by append(), mx::improc::ADIobservation< _realT, _derotFunctObj >::derotate(), mx::improc::fitsHeaderGitStatus(), mx::AO::analysis::fourierVarVec(), operator[](), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC(), mx::improc::HCIobservation< _realT >::outputPSFSub(), mx::improc::HCIobservation< _realT >::readFiles(), mx::improc::fitsFile< dataT >::readHeader(), and mx::improc::HCIobservation< _realT >::writeFinim().
template<typename typeT > void mx::improc::fitsHeader::append (const std::string & k, const typeT & v, const std::string & c)
Append a card to the end of the header, from the three components of a card.
Template Parameters
typeT is the data type of the value
Parameters
k is the keyword string
v is the value of typeT
c is the comment string
Definition at line 420 of file fitsHeader.hpp.
References append().
template<typename typeT > void mx::improc::fitsHeader::append (const std::string & k, const typeT & v)
Append a card to the end of the header, from the components of a card with no comment.
Template Parameters
typeT is the data type of the value
Parameters
k is the keyword string
v is the value of typeT
Definition at line 427 of file fitsHeader.hpp.
References append().
void mx::improc::fitsHeader::append (const std::string & k) inline
Append a card to the end of the header, with just a keyword.
Appens a headerCard with unknownType
Parameters
k is the keyword string
Definition at line 433 of file fitsHeader.hpp.
References append().
void mx::improc::fitsHeader::append (fitsHeader & head) inline
Append a fitsHeader to the end of the header.
Parameters
head is a populated fitsHeader
Definition at line 408 of file fitsHeader.hpp.
References append(), begin(), and end().
fitsHeader::headerIterator mx::improc::fitsHeader::begin () inline
Get iterator to the beginning of the cards list.
Definition at line 281 of file fitsHeader.hpp.
References cards.
Referenced by append(), eraseStandardTop(), mx::improc::fitsFile< dataT >::readHeader(), and mx::improc::fitsFile< dataT >::write().
void mx::improc::fitsHeader::clear () inline
Clear all cards from the header.
Definition at line 312 of file fitsHeader.hpp.
References cardMap, and cards.
Referenced by ~fitsHeader().
bool mx::improc::fitsHeader::empty () inline
Test whether the header is empty.
Definition at line 300 of file fitsHeader.hpp.
References cards.
fitsHeader::headerIterator mx::improc::fitsHeader::end () inline
Get iterator to the end of the cards list.
Definition at line 287 of file fitsHeader.hpp.
References cards.
Referenced by append(), eraseStandardTop(), mx::improc::fitsFile< dataT >::readHeader(), and mx::improc::fitsFile< dataT >::write().
void mx::improc::fitsHeader::erase (const std::string & keyword) inline
Erase card by keyword.
This can not be used to erase COMMENT or HISTORY cards.
Parameters
keyword the keyword of the card to delete
Definition at line 319 of file fitsHeader.hpp.
References cardMap, and cards.
Referenced by eraseStandardTop(), and mx::improc::fitsFile< dataT >::readHeader().
void mx::improc::fitsHeader::erase (headerIterator it) inline
Erase card by iterator.
This handles COMMENT and HISTORY cards, deleting only the one pointed to by it
Parameters
it is a headerIterator pointing to the card to delete.
Definition at line 331 of file fitsHeader.hpp.
References cardMap, and cards.
void mx::improc::fitsHeader::eraseStandardTop () inline
Erase the standard entries at the top of the header.
Erases each entry down to BSCALE. This is useful for appending a header to a newly created file.
Definition at line 344 of file fitsHeader.hpp.
References begin(), end(), and erase().
void mx::improc::fitsHeader::insert_after (headerIterator it, fitsHeaderCard card) inline
Insert a card after another card.
Parameters
it points to the element after which to insert
card contains the card to insert
Definition at line 473 of file fitsHeader.hpp.
References cardMap, cards, mx::improc::fitsHeaderCard::keyword, and mx::improc::fitsHeaderCard::type.
Referenced by insert_after().
template<typename typeT > void mx::improc::fitsHeader::insert_after (headerIterator it, const std::string & k, typeT v, const std::string & c)
Insert a card after another card, specifying the card by its components.
Template Parameters
typeT is the type of the value, which is converted to string for insertion
Parameters
it points to the element after which to insert
k is the keyword
v is the value
c is the comment
Definition at line 496 of file fitsHeader.hpp.
References insert_after().
template<typename typeT > void mx::improc::fitsHeader::insert_after (headerIterator it, const std::string & k, typeT v)
Insert a card after another card, specifying the card by its components.
Template Parameters
typeT is the type of the value, which is converted to string for insertion
Parameters
it points to the element after which to insert
k is the keyword
v is the value
Definition at line 502 of file fitsHeader.hpp.
References insert_after().
void mx::improc::fitsHeader::insert_before (headerIterator it, fitsHeaderCard card) inline
Insert a card before another card.
Parameters
it points to the element before which to insert
card contains the card to insert
Definition at line 439 of file fitsHeader.hpp.
References cardMap, cards, mx::improc::fitsHeaderCard::keyword, and mx::improc::fitsHeaderCard::type.
Referenced by insert_before().
template<typename typeT > void mx::improc::fitsHeader::insert_before (headerIterator it, const std::string & k, typeT v, const std::string & c)
Insert a card before another card, specifying the card by its components.
Template Parameters
typeT is the type of the value, which is converted to string for insertion
Parameters
it points to the element before which to insert
k is the keyword
v is the value
c is the comment
Definition at line 460 of file fitsHeader.hpp.
References insert_before().
template<typename typeT > void mx::improc::fitsHeader::insert_before (headerIterator it, const std::string & k, typeT v)
Insert a card before another card, specifying the card by its components.
Template Parameters
typeT is the type of the value, which is converted to string for insertion
Parameters
it points to the element before which to insert
k is the keyword
v is the value
Definition at line 467 of file fitsHeader.hpp.
References insert_before().
fitsHeader::headerIterator mx::improc::fitsHeader::iterator (const std::string & keyword) inline
Get iterator pointing to a specific element.
Parameters
keyword The keyword to look up
Definition at line 293 of file fitsHeader.hpp.
References cardMap.
fitsHeader & mx::improc::fitsHeader::operator= (const fitsHeader & head) inline
Assignment.
Must be explicitly defined to handle creation of new iterators in the cardMap
Parameters
head The fitsHeader to copy
Definition at line 263 of file fitsHeader.hpp.
References cardMap, and cards.
Referenced by fitsHeader().
fitsHeaderCard & mx::improc::fitsHeader::operator[] (const std::string & keyword) inline
Card access by keyword operator.
Looks up the card by its keyword, and returns a reference to it.
Parameters
keyword is the header keyword to look up
Return values
fitsHeaderCard& reference to the fitsHeaderCard
Definition at line 508 of file fitsHeader.hpp.
References append(), and cardMap.
const fitsHeaderCard & mx::improc::fitsHeader::operator[] (const std::string & keyword) const inline
Card access by keyword operator (const version)
Looks up the card by its keyword, and returns a reference to it.
Parameters
keyword is the header keyword to look up
Return values
fitsHeaderCard& const reference to the fitsHeaderCard
Definition at line 525 of file fitsHeader.hpp.
References cardMap.
size_t mx::improc::fitsHeader::size () inline
Get number of cards currently stored in the header.
Definition at line 306 of file fitsHeader.hpp.
References cards.
Referenced by mx::improc::fitsFile< dataT >::readHeader().
Member Data Documentation
std::unordered_multimap<std::string, headerIterator> mx::improc::fitsHeader::cardMap protected
This multimap allows for fast lookup by keyword.
Use unordered_multimap to handle HISTORY and COMMENT properly, and be as efficient as possible.
Definition at line 54 of file fitsHeader.hpp.
Referenced by append(), clear(), erase(), insert_after(), insert_before(), iterator(), operator=(), and operator[]().
std::list<fitsHeaderCard> mx::improc::fitsHeader::cards protected
The storage for the FITS header cards.
We use a list, rather than forward_list, so that append (insert at end) is constant time.
Definition at line 49 of file fitsHeader.hpp.
Referenced by append(), begin(), clear(), empty(), end(), erase(), insert_after(), insert_before(), operator=(), and size().
The documentation for this class was generated from the following file:
improc/fitsHeader.hpp