mxlib: mx::AO::analysis::aoAtmosphere< _realT > Class Template Reference
mx::AO::analysis::aoAtmosphere< _realT > Class Template Reference
Wavefront Propagation » Adaptive Optics » Analysis of Adaptive Optics
template<typename _realT>
class mx::AO::analysis::aoAtmosphere< _realT >
A class to specify atmosphere parameters and perform related calculations.
Todo:
Add layer outer scales.
Add calculation of f_G and tau_0.
Template Parameters
realT is the real floating type in which all calculations are performed.
Definition at line 44 of file aoAtmosphere.hpp.
#include <ao/analysis/aoAtmosphere.hpp>
Public Types
typedef _realT realT
The real floating type in which all calculations are performed.
Public Member Functions
aoAtmosphere ()
Constructor.
realT r_0 ()
Get the value of Fried's parameter r_0 at the reference wavelength lam_0.
realT r_0 (const realT &lam)
Get the value of Fried's parameter r_0 at the specified wavelength.
void r_0 (const realT &r0, const realT &l0)
Set the value of Fried's parameter and the reference wavelength.
realT lam_0 ()
Get the current value of the reference wavelength.
realT L_0 ()
Get the value of the outer scale.
void L_0 (const realT &L0)
Set the value of the outer scale.
realT layer_z (const int n)
Get the height of a single layer.
std::vector< realT > layer_z ()
Get the vector layer heights.
void layer_z (const std::vector< realT > &layz)
Set the vector of layer heights.
realT h_obs ()
Get the height of the observatory.
void h_obs (realT nh)
Set the height of the observatory.
realT H ()
Get the atmospheric scale height.
void H (realT nH)
Set the atmospheric scale height.
realT layer_Cn2 (const int n)
Get the strength of a single layer.
std::vector< realT > layer_Cn2 ()
Get the vector of layer strengths.
void layer_Cn2 (const std::vector< realT > &cn2, const realT l0=0)
Set the vector layer strengths, possibly calculating r_0.
realT layer_v_wind (const int n)
Get the wind speed of a single layer.
std::vector< realT > layer_v_wind ()
Get the vector of layer windspeeds.
void layer_v_wind (const std::vector< realT > &spd)
Set the vector of layer windspeeds.
realT layer_dir (const int n)
Get the wind direction of a single layer.
std::vector< realT > layer_dir ()
Get the vector of layer wind directions.
void layer_dir (const std::vector< realT > &d)
Set the vector of layer wind directions.
int n_layers ()
Get the number of layers.
realT v_wind ()
Get the weighted mean wind speed.
realT dir_wind ()
Get the weighted mean wind direction.
void v_wind (const realT &vw)
Set the weighted mean _v_wind and renormalize the layer wind speeds.
realT z_mean ()
Get the weighted mean layer height.
void z_mean (const realT &zm)
Set the weighted mean _z_mean and renormalize the layer heights.
realT X (realT k, realT lam_sci, realT secZ)
The fraction of the turbulence PSD in phase after Fresnel propagation.
realT dX (realT k, realT lam_sci, realT lam_wfs)
The differential fraction of the turbulence PSD in phase after Fresnel propagation.
realT Y (realT k, realT lam_sci, realT secZ)
The fraction of the turbulence PSD in amplitude after Fresnel propagation.
realT dY (realT k, realT lam_sci, realT lam_wfs)
The differential fraction of the turbulence PSD in amplitude after Fresnel propagation.
realT n_air (realT lam)
realT X_Z (realT k, realT lambda_sci, realT lambda_wfs, realT secZ)
realT fwhm (realT lam_sci)
Calculate the full-width at half-maximum of a seeing limited image for this atmosphere.
void loadGuyon2005 ()
Load the default atmosphere model from Guyon (2005).
void loadLCO ()
Load parameters corresponding to the median atmosphere of the GMT site survey at LCO.
void setSingleLayer (realT lz, realT vw, realT dir)
Set a single layer model.
template<typename iosT >
iosT & dumpAtmosphere (iosT &ios)
Output current parameters to a stream.
Protected Member Functions
void update_v_wind ()
Recalculate _v_wind.
void update_z_mean ()
Recalculate _z_mean.
Protected Attributes
realT _r_0
Fried's parameter, in m.
realT _lam_0
Wavelength of Fried's paraemter, in m.
realT _L_0
The outer scale, in m.
std::vector< realT > _layer_z
Vector of layer heights, in m, above the observatory.
realT _h_obs
Height of the observatory above sea level, in m.
realT _H
The atmospheric scale height, in m.
std::vector< realT > _layer_Cn2
Vector of layer strengths.
std::vector< realT > _layer_v_wind
Vector of layer wind speeds, in m/s.
std::vector< realT > _layer_dir
Vector of layer wind directions, in radians.
bool _v_wind_updated
whether or not _v_wind has been updated after changes
realT _v_wind
\(C_n^2 \) averaged windspeed
realT _dir_wind
\(C_n^2 \) averaged direction
bool _z_mean_updated
whether or not _z_mean has been update after changes
realT _z_mean
\(C_n^2 \) averaged layer height
Member Typedef Documentation
template<typename _realT> typedef _realT mx::AO::analysis::aoAtmosphere< _realT >::realT
The real floating type in which all calculations are performed.
Definition at line 48 of file aoAtmosphere.hpp.
Constructor & Destructor Documentation
template<typename realT > mx::AO::analysis::aoAtmosphere< realT >::aoAtmosphere ()
Constructor.
Definition at line 405 of file aoAtmosphere.hpp.
Member Function Documentation
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::dir_wind ()
Get the weighted mean wind direction.
Returns the weighted mean wind direction according to the 5/3's turbulence moment. This is defined as
\[ \bar{\theta} = \left[\sum_i C_N^2(z_i) \theta_i^{5/3} \right]^{3/5} \]
See Hardy (1998) Section 3.3.6. [hardy_1998].
This is only re-calculated if either _layer_Cn2 or _layer_v_wind is changed, otherwise this just returns the value of _dir_wind.
Returns
the current value of _dir_wind.
Definition at line 597 of file aoAtmosphere.hpp.
template<typename realT > template<typename iosT > iosT & mx::AO::analysis::aoAtmosphere< realT >::dumpAtmosphere (iosT & ios)
Output current parameters to a stream.
Prints a formatted list of all current parameters.
Template Parameters
iosT is a std::ostream-like type.
Parameters
[in] ios a std::ostream-like stream.
Definition at line 834 of file aoAtmosphere.hpp.
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::dumpAOSystem().
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::dX (realT k, realT lam_sci, realT lam_wfs)
The differential fraction of the turbulence PSD in phase after Fresnel propagation.
See Equation (25) of Guyon (2005) [guyon_2005].
Returns
the value of the dX function.
Parameters
[in] k the spatial frequency, in inverse meters.
[in] lam_sci is the science observation wavelength.
[in] lam_wfs is the wavefront sensor wavelength.
Definition at line 722 of file aoAtmosphere.hpp.
References mx::astro::constants::c().
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C4var().
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::dY (realT k, realT lam_sci, realT lam_wfs)
The differential fraction of the turbulence PSD in amplitude after Fresnel propagation.
See Equation (27) of Guyon (2005) [guyon_2005].
Returns
the value of the dY function.
Parameters
[in] k the spatial frequency, in inverse meters.
[in] lam_sci is the science observation wavelength.
[in] lam_wfs is the wavefront sensor wavelength.
Definition at line 750 of file aoAtmosphere.hpp.
References mx::astro::constants::c().
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::fwhm (realT lam_sci)
Calculate the full-width at half-maximum of a seeing limited image for this atmosphere.
Calculate the FWHM of a seeing limited image with the current parameters according to Floyd et al. (2010) [floyd_2010]
\[ \epsilon_0 = 0.98\frac{\lambda_{sci}}{r_0(\lambda_sci)}. \]
If there is an outer scale (_L_0 > 0), then a correction is applied according to Tokovinin (2002) [tokovinin_2002]
\[ \left(\frac{\epsilon_{vK}}{\epsilon_0}\right)^2 = 1 - 2.183\left(\frac{r_0(\lambda_{sci}}{L_0}\right)^{0.356} \]
Returns
the value of the FWHM (\(\epsilon_{0/vK} \)) for the current atmosphere parameters.
Parameters
[in] lam_sci the wavelength of the science observation.
Definition at line 789 of file aoAtmosphere.hpp.
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::H ()
Get the atmospheric scale height.
Returns
the current value of _H.
Definition at line 489 of file aoAtmosphere.hpp.
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::H (realT nH)
Set the atmospheric scale height.
Parameters
[in] nH the new value of _H [m]
Definition at line 495 of file aoAtmosphere.hpp.
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::h_obs ()
Get the height of the observatory.
Returns
the current value of _h_obs.
Definition at line 477 of file aoAtmosphere.hpp.
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::h_obs (realT nh)
Set the height of the observatory.
Parameters
[in] nh the new height of the observatory [m]
Definition at line 483 of file aoAtmosphere.hpp.
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::L_0 ()
Get the value of the outer scale.
Returns
the current value of _L_0.
Definition at line 453 of file aoAtmosphere.hpp.
Referenced by mx::AO::analysis::vonKarmanSpectrum< realT >::fittingError(), mx::AO::analysis::fourierVarVec(), and mx::AO::analysis::vonKarmanSpectrum< realT >::operator()().
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::L_0 (const realT & L0)
Set the value of the outer scale.
Parameters
[in] L0 is the new value of _L_0
Definition at line 459 of file aoAtmosphere.hpp.
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::lam_0 ()
Get the current value of the reference wavelength.
This is the wavelength at which r_0 is specified.
Returns
the current value of _lam_0.
Definition at line 447 of file aoAtmosphere.hpp.
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C0var(), mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C1var(), mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C4var(), mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C7var(), mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::fittingError(), mx::AO::analysis::vonKarmanSpectrum< realT >::operator()(), mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::optimumTauWFS(), and mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::timeDelayError().
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::layer_Cn2 (const int n)
Get the strength of a single layer.
Returns
the value of _layer_Cn2[n].
Parameters
[in] n specifies the layer.
Definition at line 508 of file aoAtmosphere.hpp.
template<typename realT > std::vector< realT > mx::AO::analysis::aoAtmosphere< realT >::layer_Cn2 ()
Get the vector of layer strengths.
Returns
a copy of the vector of layer strengths: _layer_Cn2.
Definition at line 514 of file aoAtmosphere.hpp.
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::layer_Cn2 (const std::vector< realT > & cn2, const realT l0 = 0)
Set the vector layer strengths, possibly calculating r_0.
If a reference wavelength is specified (l0 > 0), then r_0 is set from the layer strengths according to
Regardless of what units the strengths are specified in, they are stored normalized so that \(\sum_n C_n^2 = 1 \).
Parameters
[in] cn2 is a vector containing the layer strengths
[in] l0 [optional] if l0 > 0, then r_0 is set from the layer strengths.
Definition at line 520 of file aoAtmosphere.hpp.
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::layer_dir (const int n)
Get the wind direction of a single layer.
Returns
the value of _layer_dir[n].
Parameters
[in] n specifies the layer.
Definition at line 565 of file aoAtmosphere.hpp.
template<typename realT > std::vector< realT > mx::AO::analysis::aoAtmosphere< realT >::layer_dir ()
Get the vector of layer wind directions.
Returns
a copy of the vector of layer wind directions: _layer_dir.
Definition at line 571 of file aoAtmosphere.hpp.
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::layer_dir (const std::vector< realT > & d)
Set the vector of layer wind directions.
Parameters
Parameters
[in] d the new vector, which is copied to _layer_dir.
Definition at line 577 of file aoAtmosphere.hpp.
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::layer_v_wind (const int n)
Get the wind speed of a single layer.
Returns
the value of _layer_v_wind[n].
Parameters
[in] n specifies the layer.
Definition at line 545 of file aoAtmosphere.hpp.
template<typename realT > std::vector< realT > mx::AO::analysis::aoAtmosphere< realT >::layer_v_wind ()
Get the vector of layer windspeeds.
Returns
a copy of the vector of layer windspeeds: _layer_v_wind.
Definition at line 552 of file aoAtmosphere.hpp.
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::layer_v_wind (const std::vector< realT > & spd)
Set the vector of layer windspeeds.
Parameters
Parameters
[in] spd the new vector, which is copied to _layer_v_wind.
Definition at line 558 of file aoAtmosphere.hpp.
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::layer_z (const int n)
Get the height of a single layer.
Returns
the value of _layer_z[n].
Parameters
[in] n specifies the layer.
Definition at line 465 of file aoAtmosphere.hpp.
template<typename realT > std::vector< realT > mx::AO::analysis::aoAtmosphere< realT >::layer_z ()
Get the vector layer heights.
Returns
a copy of the vector of layer heights: _layer_z.
Definition at line 471 of file aoAtmosphere.hpp.
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::layer_z (const std::vector< realT > & layz)
Set the vector of layer heights.
Parameters
[in] layz new vector of layer heights, which is copied to _layer_z.
Definition at line 501 of file aoAtmosphere.hpp.
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::loadGuyon2005 ()
Load the default atmosphere model from Guyon (2005).
Sets the parameters from Table 4 of Guyon (2005) [guyon_2005].
Definition at line 804 of file aoAtmosphere.hpp.
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::loadGuyon2005().
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::loadLCO ()
Load parameters corresponding to the median atmosphere of the GMT site survey at LCO.
Definition at line 817 of file aoAtmosphere.hpp.
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::loadMagAOX().
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::n_air (realT lam)
Parameters
[in] lam The wavelength
Definition at line 763 of file aoAtmosphere.hpp.
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C6var().
template<typename realT > int mx::AO::analysis::aoAtmosphere< realT >::n_layers ()
Get the number of layers.
Returns
the size of the _layer_Cn2 vector.
Definition at line 584 of file aoAtmosphere.hpp.
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::r_0 ()
Get the value of Fried's parameter r_0 at the reference wavelength lam_0.
Returns
the curret value of _r_0.
Definition at line 419 of file aoAtmosphere.hpp.
Referenced by mx::AO::analysis::vonKarmanSpectrum< realT >::fittingError(), mx::AO::analysis::fourierVarVec(), and mx::AO::analysis::vonKarmanSpectrum< realT >::operator()().
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::r_0 (const realT & lam)
Get the value of Fried's parameter r_0 at the specified wavelength.
Note
This does not set the value of r_0.
Returns
the current value of _r_0 * pow(lam, 6/5).
Parameters
[in] lam the wavelength at which to calculate r_0
Definition at line 425 of file aoAtmosphere.hpp.
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::r_0 (const realT & r0, const realT & l0)
Set the value of Fried's parameter and the reference wavelength.
If the provided reference wavelength is <=0, then 0.5 microns is used.
Parameters
[in] r0 is the new value of _r_0
[in] l0 is the new value of _lam_0, if 0 then 0.5 microns is the default.
Definition at line 431 of file aoAtmosphere.hpp.
template<typename _realT> void mx::AO::analysis::aoAtmosphere< _realT >::setSingleLayer (realT lz, realT vw, realT dir) inline
Set a single layer model.
Parameters
[in] lz the layer height
[in] vw the layer wind-seed
[in] dir the layer wind direction.
Definition at line 384 of file aoAtmosphere.hpp.
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::update_v_wind () protected
Recalculate _v_wind.
Called by v_wind() whenever _v_wind_updated is true.
Todo:
handle dir_wind averaging across 0/2pi
Definition at line 604 of file aoAtmosphere.hpp.
References mx::astro::constants::c().
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::update_z_mean () protected
Recalculate _z_mean.
Called by z_mean() whenever _z_mean_updated is true.
Definition at line 665 of file aoAtmosphere.hpp.
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::v_wind ()
Get the weighted mean wind speed.
Returns the weighted mean wind speed according to the 5/3's turbulence moment. This is defined as
\[ \bar{v} = \left[\sum_i C_N^2(z_i) v_i^{5/3} \right]^{3/5} \]
See Hardy (1998) Section 3.3.6. [hardy_1998].
This is only re-calculated if either _layer_Cn2 or _layer_v_wind is changed, otherwise this just returns the value of _v_wind.
Returns
the current value of _v_wind.
Definition at line 590 of file aoAtmosphere.hpp.
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::optimumTauWFS(), and mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::timeDelayError().
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::v_wind (const realT & vw)
Set the weighted mean _v_wind and renormalize the layer wind speeds.
Calling this function changes the values of _layer_v_wind so that the Layer averaged 5/3 \(C_n^2\) moment of wind speed is the new value specified by vw.
Parameters
[in] vw the new value of _v_wind.
Definition at line 639 of file aoAtmosphere.hpp.
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::X (realT k, realT lam_sci, realT secZ)
The fraction of the turbulence PSD in phase after Fresnel propagation.
See Equation (14) of Guyon (2005) [guyon_2005].
Returns
the value of the X function.
Parameters
[in] k the spatial frequency, in inverse meters.
[in] lam_sci is the science observation wavelength.
[in] secZ is the secant of the zenith distance.
Definition at line 707 of file aoAtmosphere.hpp.
References mx::astro::constants::c().
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C0var(), mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C_(), mx::AO::analysis::vonKarmanSpectrum< realT >::operator()(), mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::optimumTauWFS(), and mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::timeDelayError().
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::X_Z (realT k, realT lambda_sci, realT lambda_wfs, realT secZ)
Parameters
[in] k the spatial frequency, in inverse metes
[in] lambda_sci is the science observation wavelength.
[in] lambda_wfs is the wavefront sensor wavelength.
[in] secZ is the secant of the zenith distance.
Definition at line 771 of file aoAtmosphere.hpp.
References mx::astro::constants::c().
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C7var(), and mx::AO::analysis::vonKarmanSpectrum< realT >::operator()().
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::Y (realT k, realT lam_sci, realT secZ)
The fraction of the turbulence PSD in amplitude after Fresnel propagation.
See Equation (15) of Guyon (2005) [guyon_2005].
Returns
the value of the Y function.
Parameters
[in] k the spatial frequency, in inverse meters.
[in] lam_sci is the science observation wavelength.
[in] secZ is the secant of the zenith distance.
Definition at line 735 of file aoAtmosphere.hpp.
References mx::astro::constants::c().
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C1var(), mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C_(), and mx::AO::analysis::vonKarmanSpectrum< realT >::operator()().
template<typename realT > realT mx::AO::analysis::aoAtmosphere< realT >::z_mean ()
Get the weighted mean layer height.
Returns the weighted layer height according to the 5/3's turbulence moment. This is defined as
\[ \bar{z} = \left[\sum_i C_N^2(z_i) z_i^{5/3} \right]^{3/5} \]
See Hardy (1998) Section 3.3.6 and 3.7.2. [hardy_1998].
This is only re-calculated if either _layer_Cn2 or _layer_z is changed, otherwise this just returns the value of _z_mean.
Returns
the current value of _z_mean.
Definition at line 658 of file aoAtmosphere.hpp.
template<typename realT > void mx::AO::analysis::aoAtmosphere< realT >::z_mean (const realT & zm)
Set the weighted mean _z_mean and renormalize the layer heights.
Calling this function changes the values of _layer_z so that the Layer averaged 5/3 \(C_n^2\) moment of the height is the new value specified.
Parameters
[in] zm is the new value of _v_wind.
Definition at line 688 of file aoAtmosphere.hpp.
Member Data Documentation
template<typename _realT> realT mx::AO::analysis::aoAtmosphere< _realT >::_dir_wind protected
\(C_n^2 \) averaged direction
Definition at line 76 of file aoAtmosphere.hpp.
template<typename _realT> realT mx::AO::analysis::aoAtmosphere< _realT >::_H protected
The atmospheric scale height, in m.
Definition at line 64 of file aoAtmosphere.hpp.
template<typename _realT> realT mx::AO::analysis::aoAtmosphere< _realT >::_h_obs protected
Height of the observatory above sea level, in m.
Definition at line 62 of file aoAtmosphere.hpp.
template<typename _realT> realT mx::AO::analysis::aoAtmosphere< _realT >::_L_0 protected
The outer scale, in m.
Definition at line 58 of file aoAtmosphere.hpp.
template<typename _realT> realT mx::AO::analysis::aoAtmosphere< _realT >::_lam_0 protected
Wavelength of Fried's paraemter, in m.
Definition at line 56 of file aoAtmosphere.hpp.
template<typename _realT> std::vector<realT> mx::AO::analysis::aoAtmosphere< _realT >::_layer_Cn2 protected
Vector of layer strengths.
Definition at line 66 of file aoAtmosphere.hpp.
template<typename _realT> std::vector<realT> mx::AO::analysis::aoAtmosphere< _realT >::_layer_dir protected
Vector of layer wind directions, in radians.
Definition at line 70 of file aoAtmosphere.hpp.
template<typename _realT> std::vector<realT> mx::AO::analysis::aoAtmosphere< _realT >::_layer_v_wind protected
Vector of layer wind speeds, in m/s.
Definition at line 68 of file aoAtmosphere.hpp.
template<typename _realT> std::vector<realT> mx::AO::analysis::aoAtmosphere< _realT >::_layer_z protected
Vector of layer heights, in m, above the observatory.
Definition at line 60 of file aoAtmosphere.hpp.
template<typename _realT> realT mx::AO::analysis::aoAtmosphere< _realT >::_r_0 protected
Fried's parameter, in m.
Definition at line 54 of file aoAtmosphere.hpp.
template<typename _realT> realT mx::AO::analysis::aoAtmosphere< _realT >::_v_wind protected
\(C_n^2 \) averaged windspeed
Definition at line 74 of file aoAtmosphere.hpp.
template<typename _realT> bool mx::AO::analysis::aoAtmosphere< _realT >::_v_wind_updated protected
whether or not _v_wind has been updated after changes
Definition at line 72 of file aoAtmosphere.hpp.
template<typename _realT> realT mx::AO::analysis::aoAtmosphere< _realT >::_z_mean protected
\(C_n^2 \) averaged layer height
Definition at line 80 of file aoAtmosphere.hpp.
template<typename _realT> bool mx::AO::analysis::aoAtmosphere< _realT >::_z_mean_updated protected
whether or not _z_mean has been update after changes
Definition at line 78 of file aoAtmosphere.hpp.
The documentation for this class was generated from the following file:
ao/analysis/aoAtmosphere.hpp