mxlib: mx::improc::ds9Interface Class Reference
mx::improc::ds9Interface Class Reference
Image ProcessingGeneral Mathematics » | Plotting Data
An interface to the ds9 image viewer.
Handles spawning the ds9 window, and manages shared memory segments, one for each frame.
This makes use of system() calls. In each case the result is checked and if SIGINT or SIGQUIT was caught by the ds9 child process, it will be re-raised in the calling process.
Definition at line 45 of file ds9Interface.hpp.
#include <improc/ds9Interface.hpp>
Public Member Functions
ds9Interface ()
Default c'tor.
template<typename arrayT >
ds9Interface (const arrayT &array, int frame=1)
Constructor which, after initialization, proceeds to display an Eigen-like array in ds9.
~ds9Interface ()
Destructor.
int init ()
Initialize the ds9Interface structure.
std::string title ()
Get the title of the ds9Interface.
int title (const std::string &new_title)
Set the title of the ds9Interface.
int port ()
Get the port of the ds9Interface.
int port (const int &new_port)
Set the port of the ds9Interface.
int spawn ()
Spawn (open) the ds9 image viewer.
int addsegment (int frame)
Add a segment corresponding to a particular frame in ds9.
int addframe (int frame)
Open a frame in ds9.
template<typename dataT >
int display (const dataT *im, size_t dim1, size_t dim2, size_t dim3, int frame=1)
Display an image in ds9.
template<typename arrayT >
int display (const arrayT &array, int frame=1)
Display an Eigen-like array in ds9.
template<typename arrayT >
int operator() (const arrayT &array, int frame=1)
Display an Eigen-like array in ds9.
int shutdown ()
Shutdown the ds9 interface.
Protected Attributes
std::string _title
The title of the window, which sets the XPA access point.
int _port
The port to use (normally 0)
sharedmem_segment * segs
An array of shared memory segments, one per frame.
size_t nsegs
The number of segments in segs.
Constructor & Destructor Documentation
mx::improc::ds9Interface::ds9Interface () inline
Default c'tor.
Definition at line 208 of file ds9Interface.hpp.
References init().
template<typename arrayT > mx::improc::ds9Interface::ds9Interface (const arrayT & array, int frame = 1)
Constructor which, after initialization, proceeds to display an Eigen-like array in ds9.
see display<typename arrayT>(arrayT & array, int frame=1) for more.
Parameters
[in] array An array containing an image or cube of images
[in] frame [optional] the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 214 of file ds9Interface.hpp.
References display(), and init().
mx::improc::ds9Interface::~ds9Interface () inline
Destructor.
Definition at line 223 of file ds9Interface.hpp.
References shutdown().
Member Function Documentation
int mx::improc::ds9Interface::addframe (int frame) inline
Open a frame in ds9.
Nothing is done if the frame already exists. First calls addsegment.
This makes use of system() calls. In each case the result is checked and if SIGINT or SIGQUIT was caught by the ds9 child process, it will be re-raised in the calling process.
Parameters
frame is
Return values
0 on sucess
-1 on an error
Parameters
[in] frame the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 341 of file ds9Interface.hpp.
References _title, addsegment(), and DS9_CMD_MAX_LENGTH.
int mx::improc::ds9Interface::addsegment (int frame) inline
Add a segment corresponding to a particular frame in ds9.
Nothing is done if the frame already exists. Note that this does not open a new frame in ds9.
This makes use of system() calls. In each case the result is checked and if SIGINT or SIGQUIT was caught by the ds9 child process, it will be re-raised in the calling process.
Parameters
frame is the number of the new frame to initialize. Note frame must be >= 1.
Return values
0 on sucess
-1 on an error
Parameters
[in] frame the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 317 of file ds9Interface.hpp.
References nsegs, segs, sharedmem_segment_initialize(), and sharedmem_segment_set_key().
Referenced by addframe(), and display().
template<typename dataT > int mx::improc::ds9Interface::display (const dataT * im, size_t dim1, size_t dim2, size_t dim3, int frame = 1)
Display an image in ds9.
A new ds9 instance is opened if necessary, and a new sharedmemory segment is added if necessary. The image is described by a pointer and its 2 or 3 dimensions.
This makes use of system() calls. In each case the result is checked and if SIGINT or SIGQUIT was caught by the ds9 child process, it will be re-raised in the calling process.
Return values
0 on sucess
-1 on an error
Parameters
[in] im the address of the image
[in] dim1 the first dimension of the image (in pixels)
[in] dim2 the second dimension of the image (in pixels)
[in] dim3 the third dimension of the image (in pixels), set to 1 if not a cube.
[in] frame [optional] the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 360 of file ds9Interface.hpp.
References _title, addsegment(), DS9_CMD_MAX_LENGTH, nsegs, segs, sharedmem_segment_create(), sharedmem_segment_detach(), sharedmem_segment::shmemid, and spawn().
Referenced by display(), ds9Interface(), and operator()().
template<typename arrayT > int mx::improc::ds9Interface::display (const arrayT & array, int frame = 1)
Display an Eigen-like array in ds9.
Uses the rows(), cols(), and possibly planes(), methods of arrayT.
see display<typename dataT>(const dataT *im, size_t dim1, size_t dim2, size_t dim3, int frame=1) for more.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Return values
0 on sucess
-1 on an error
Parameters
[in] array An array containing an image or cube of images
[in] frame [optional] the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 445 of file ds9Interface.hpp.
References display().
int mx::improc::ds9Interface::init () inline
Initialize the ds9Interface structure.
The title is set to "ds9", the port is set to 0, segs is set to NULL, and nsegs to 0.
Return values
0 on sucess
-1 on an error
Definition at line 229 of file ds9Interface.hpp.
References _port, nsegs, segs, and title().
Referenced by ds9Interface().
template<typename arrayT > int mx::improc::ds9Interface::operator() (const arrayT & array, int frame = 1)
Display an Eigen-like array in ds9.
see display<typename arrayT>(arrayT & array, int frame=1) for more.
Return values
0 on sucess
-1 on an error
Parameters
[in] array An array containing an image or cube of images
[in] frame [optional] the number of the new frame to initialize.
Note
frame must be >= 1.
Definition at line 455 of file ds9Interface.hpp.
References display().
int mx::improc::ds9Interface::port () inline
Get the port of the ds9Interface.
Returns
the current value of _port
Definition at line 256 of file ds9Interface.hpp.
References _port.
int mx::improc::ds9Interface::port (const int & new_port) inline
Set the port of the ds9Interface.
Return values
0 on sucess
-1 on an error
Parameters
[in] new_port the port to set.
Definition at line 262 of file ds9Interface.hpp.
References _port.
int mx::improc::ds9Interface::shutdown () inline
Shutdown the ds9 interface.
Mainly detaches from the shared memory segments
Return values
0 on sucess
-1 on an error
Definition at line 463 of file ds9Interface.hpp.
References nsegs, segs, and sharedmem_segment_detach().
Referenced by ~ds9Interface().
int mx::improc::ds9Interface::spawn () inline
Spawn (open) the ds9 image viewer.
This makes use of system() calls. In each case the result is checked and if SIGINT or SIGQUIT was caught by the ds9 child process, it will be re-raised in the calling process.
Return values
0 on sucess
-1 on an error, which may be caused by a response timeout.
Definition at line 271 of file ds9Interface.hpp.
References _port, _title, command_response(), and DS9_CMD_MAX_LENGTH.
Referenced by display().
std::string mx::improc::ds9Interface::title () inline
Get the title of the ds9Interface.
Returns
the current value of _title
Definition at line 242 of file ds9Interface.hpp.
References _title.
Referenced by init().
int mx::improc::ds9Interface::title (const std::string & new_title) inline
Set the title of the ds9Interface.
The title is used as the name of the XPA access point
Return values
0 on sucess
-1 on an error
Parameters
[in] new_title the title to set.
Definition at line 248 of file ds9Interface.hpp.
References _title.
Member Data Documentation
int mx::improc::ds9Interface::_port protected
The port to use (normally 0)
Definition at line 54 of file ds9Interface.hpp.
Referenced by init(), port(), and spawn().
std::string mx::improc::ds9Interface::_title protected
The title of the window, which sets the XPA access point.
Definition at line 51 of file ds9Interface.hpp.
Referenced by addframe(), display(), spawn(), and title().
size_t mx::improc::ds9Interface::nsegs protected
The number of segments in segs.
Definition at line 60 of file ds9Interface.hpp.
Referenced by addsegment(), display(), init(), and shutdown().
sharedmem_segment* mx::improc::ds9Interface::segs protected
An array of shared memory segments, one per frame.
Definition at line 57 of file ds9Interface.hpp.
Referenced by addsegment(), display(), init(), and shutdown().
The documentation for this class was generated from the following file:
improc/ds9Interface.hpp