mxlib: mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT > Class Template Reference
mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT > Class Template Reference
template<typename _realT, typename _wfsT, typename _reconT, typename _filterT, typename _dmT, typename _turbSeqT>
class mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >
A simulated AO system.
Minimum requirement for _turbSeqT:
{
   int wfPS(realT ps); //Sets the wavefront platescale (only needed for cascaded systems).
   int frames(); //Returns the number of frames, sets the number of iterations to run.
   int nextWF(wavefront<realT> & wf); //Fills in the wavefront with phase and amplitude
};
Definition at line 77 of file simulatedAOSystem.hpp.
#include <ao/sim/simulatedAOSystem.hpp>
Public Types
typedef _realT realT
The floating point type used for all calculations.
typedef mx::AO::sim::wavefront< realT > wavefrontT
The wavefront type.
typedef Eigen::Array< realT, Eigen::Dynamic, Eigen::Dynamic > imageT
The real image type.
typedef mx::imagingArray< std::complex< realT >, mx::fftwAllocator< std::complex< realT > >, 0 > complexImageT
The complex image type.
Public Member Functions
simulatedAOSystem ()
Default c'tor.
~simulatedAOSystem ()
Destructor.
int initSystem (const std::string &sysName, typename dmT::specT &dmSpec, const std::string &wfsName, const std::string &pupilName, const std::string &pupilMaskName, const int &wfSz)
Initialize the system.
void takeResponseMatrix (realT amp, std::string rmatName, int nmodes=0)
Measure the system response matrix.
Public Attributes
std::string _sysName
The system name for use in mx::AO::path.
std::string _wfsName
The WFS name for use in the mx::AO::path.
std::string _pupilName
The pupil name for use in the mx::AO::path.
std::string _pupilMaskName
The pupil mask name for use in the mx::AO::path.
imageT _pupil
The system pupil. This is generally a binary mask and will be applied at various points in the propagation.
imageT _pupilMask
A pupil mask which is applied once at the beginning of propagation. Could be apodized and/or different from _pupil.
long _saveFrameStart
Member Typedef Documentation
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > typedef mx::imagingArray<std::complex<realT>, mx::fftwAllocator<std::complex<realT> >, 0> mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::complexImageT
The complex image type.
Definition at line 89 of file simulatedAOSystem.hpp.
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > typedef Eigen::Array<realT, Eigen::Dynamic, Eigen::Dynamic> mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::imageT
The real image type.
Definition at line 87 of file simulatedAOSystem.hpp.
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > typedef _realT mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::realT
The floating point type used for all calculations.
Definition at line 83 of file simulatedAOSystem.hpp.
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > typedef mx::AO::sim::wavefront<realT> mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::wavefrontT
The wavefront type.
Definition at line 85 of file simulatedAOSystem.hpp.
Constructor & Destructor Documentation
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::simulatedAOSystem ()
Default c'tor.
Definition at line 236 of file simulatedAOSystem.hpp.
References mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_saveFrameStart.
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::~simulatedAOSystem ()
Destructor.
Definition at line 256 of file simulatedAOSystem.hpp.
References mx::convertToString().
Member Function Documentation
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > int mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::initSystem (const std::string & sysName, typename dmT::specT & dmSpec, const std::string & wfsName, const std::string & pupilName, const std::string & pupilMaskName, const int & wfSz)
Initialize the system.
Initializes the basic parts of the system.
Returns
0 on success
-1 on an error (simulation should not continue if this happens).
Parameters
[in] sysName System name.
[in] dmSpec DM Specification.
[in] wfsName WFS Name.
[in] pupilName Name of the system pupil.
[in] pupilMaskName Name of the pupil mask, possibly apodized. If empty string "", then pupilName is used.
[in] wfSz Size of the wavefront used for propagation.
Definition at line 287 of file simulatedAOSystem.hpp.
References mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_pupil, mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_pupilMask, mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_pupilMaskName, mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_pupilName, mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_sysName, mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_wfsName, MXE_SIZEERR, mxError, and mx::improc::fitsFile< dataT >::read().
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > void mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix (realT amp, std::string rmatName, int nmodes = 0)
Measure the system response matrix.
System should be initialized with initSystemCal.
Parameters
amp
rmatName
nmodes
Definition at line 439 of file simulatedAOSystem.hpp.
References mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_pupil, mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_pupilMask, mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_pupilName, mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_saveFrameStart, mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_sysName, mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_wfsName, mx::AO::sim::wavefront< _realT >::amplitude, mx::convertToString(), mx::get_curr_time(), mx::AO::sim::wavefront< _realT >::iterNo, mx::improc::padImage(), mx::AO::sim::wavefront< _realT >::phase, mx::wfp::fraunhoferPropagator< _wavefrontT >::propagatePupilToFocal(), and mx::improc::fitsFile< dataT >::write().
Member Data Documentation
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > imageT mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_pupil
The system pupil. This is generally a binary mask and will be applied at various points in the propagation.
Definition at line 205 of file simulatedAOSystem.hpp.
Referenced by mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::initSystem(), and mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix().
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > imageT mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_pupilMask
A pupil mask which is applied once at the beginning of propagation. Could be apodized and/or different from _pupil.
Definition at line 206 of file simulatedAOSystem.hpp.
Referenced by mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::initSystem(), and mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix().
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > std::string mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_pupilMaskName
The pupil mask name for use in the mx::AO::path.
Definition at line 100 of file simulatedAOSystem.hpp.
Referenced by mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::initSystem().
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > std::string mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_pupilName
The pupil name for use in the mx::AO::path.
Definition at line 99 of file simulatedAOSystem.hpp.
Referenced by mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::initSystem(), and mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix().
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > long mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_saveFrameStart
Image outputs
Definition at line 143 of file simulatedAOSystem.hpp.
Referenced by mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::simulatedAOSystem(), and mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix().
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > std::string mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_sysName
The system name for use in mx::AO::path.
Definition at line 97 of file simulatedAOSystem.hpp.
Referenced by mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::initSystem(), and mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix().
template<typename _realT , typename _wfsT , typename _reconT , typename _filterT , typename _dmT , typename _turbSeqT > std::string mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::_wfsName
The WFS name for use in the mx::AO::path.
Definition at line 98 of file simulatedAOSystem.hpp.
Referenced by mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::initSystem(), and mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix().
The documentation for this class was generated from the following file:
ao/sim/simulatedAOSystem.hpp