mxlib: mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine > Class Template Reference
mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine > Class Template Reference
General Utilities » Multi-threading Utilities
template<class _outputT = std::ostream, bool _printPretty = true, bool _printLoops = true, bool _printPercent = true, bool _printNLine = true>
class mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >
A class to track the number of iterations in an OMP parallelized loop.
Uses omp critical directives to deconflict updates by different loops. Example:
ompLoopWatcher<> watcher(1000, std::cout); //Uses defaults
#pragma omp parallel for
int(i=0; i<1000; ++i)
{
   watcher.incrementAndOutputStatus();
   //Do loop work
   ...
}
This will result in the following output
1 / 1000 (0.1%)
2 / 1000 (0.2%)
3 / 1000 (0.3%)
and so on.
Note
This can reduce performance due to critical points it creates if used in fast loops (e.g. do not use inside the inner most loop!).
The behavior of the output is controlled through template parameters. A different output-type can be specified, which needs to accept size_t, and optionally float, and character input using the << operator.
Template Parameters
outputT a type which accepts size_t, float, and character input via the << operator (default is std::ostream).
_printPretty flag to control whether the output is nicely formatted, if false then just the numbers are sent to the output with no spaces or delimiters (default is true).
_printLoops flag to control whether the number of loops is sent to the output each time (default is true).
_printPercent flag to control whether the percentage complete is calculated (default is true).
_printNLine flag to control whether the newline '\n' is sent ot output (default is true).
Definition at line 53 of file ompLoopWatcher.hpp.
#include <ompLoopWatcher.hpp>
Public Member Functions
ompLoopWatcher (int nLoops, outputT &output)
Constructor.
void increment ()
Increment the counter.
void outputStatus ()
Output current status.
void incrementAndOutputStatus ()
Increment and output status.
Protected Member Functions
void _increment ()
Increment the counter.
void _outputStatus ()
Perform the output.
Protected Attributes
size_t _nLoops
The total number of loops.
size_t _counter
The current counter.
outputT * _output
Pointer to the instance of type outputT.
Constructor & Destructor Documentation
template<class _outputT = std::ostream, bool _printPretty = true, bool _printLoops = true, bool _printPercent = true, bool _printNLine = true> mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::ompLoopWatcher (int nLoops, outputT & output) inline
Constructor.
Registers the output and sets the number of loops.
Parameters
nLoops is the total number of loops.
output is the instance of type outputT to which the output will be sent.
Definition at line 105 of file ompLoopWatcher.hpp.
Member Function Documentation
template<class _outputT = std::ostream, bool _printPretty = true, bool _printLoops = true, bool _printPercent = true, bool _printNLine = true> void mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_increment () inline protected
Increment the counter.
Definition at line 66 of file ompLoopWatcher.hpp.
References mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_counter.
Referenced by mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::increment(), and mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::incrementAndOutputStatus().
template<class _outputT = std::ostream, bool _printPretty = true, bool _printLoops = true, bool _printPercent = true, bool _printNLine = true> void mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_outputStatus () inline protected
Perform the output.
Definition at line 72 of file ompLoopWatcher.hpp.
References mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_counter, and mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_nLoops.
Referenced by mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::incrementAndOutputStatus(), and mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::outputStatus().
template<class _outputT = std::ostream, bool _printPretty = true, bool _printLoops = true, bool _printPercent = true, bool _printNLine = true> void mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::increment () inline
Increment the counter.
Call this once per loop. It contains an omp critical directive.
Definition at line 116 of file ompLoopWatcher.hpp.
References mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_increment().
template<class _outputT = std::ostream, bool _printPretty = true, bool _printLoops = true, bool _printPercent = true, bool _printNLine = true> void mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::incrementAndOutputStatus () inline
Increment and output status.
Call this to increment and then give a status update. Has only one omp critical directive for the two steps.
Definition at line 134 of file ompLoopWatcher.hpp.
References mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_increment(), and mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_outputStatus().
Referenced by mx::AO::analysis::fourierVarVec(), and mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::makePSDGrid().
template<class _outputT = std::ostream, bool _printPretty = true, bool _printLoops = true, bool _printPercent = true, bool _printNLine = true> void mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::outputStatus () inline
Output current status.
Call this whenever you want a status update. It contains an omp critical directive.
Definition at line 125 of file ompLoopWatcher.hpp.
References mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_outputStatus().
Member Data Documentation
template<class _outputT = std::ostream, bool _printPretty = true, bool _printLoops = true, bool _printPercent = true, bool _printNLine = true> size_t mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_counter protected
The current counter.
Definition at line 60 of file ompLoopWatcher.hpp.
Referenced by mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_increment(), and mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_outputStatus().
template<class _outputT = std::ostream, bool _printPretty = true, bool _printLoops = true, bool _printPercent = true, bool _printNLine = true> size_t mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_nLoops protected
The total number of loops.
Definition at line 59 of file ompLoopWatcher.hpp.
Referenced by mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_outputStatus().
template<class _outputT = std::ostream, bool _printPretty = true, bool _printLoops = true, bool _printPercent = true, bool _printNLine = true> outputT* mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::_output protected
Pointer to the instance of type outputT.
Definition at line 63 of file ompLoopWatcher.hpp.
The documentation for this class was generated from the following file:
ompLoopWatcher.hpp