mxlib: mx::improc::fitsFile< dataT > Class Template Reference
mx::improc::fitsFile< dataT > Class Template Reference
Image Processing » FITS Files
template<typename dataT>
class mx::improc::fitsFile< dataT >
Class to manage interactions with a FITS file.
This class wraps the functionality of cfitsio.
Template Parameters
dataT is the datatype to use for in-memory storage of the image. This does not have to match the data type stored on disk.
Definition at line 37 of file fitsFile.hpp.
#include <improc/fitsFile.hpp>
Public Member Functions
fitsFile ()
Default constructor.
fitsFile (const std::string &fname, bool doopen=true)
Constructor with _fileName, and option to open.
~fitsFile ()
Destructor.
std::string fileName ()
Get the current value of _fileName.
int fileName (const std::string &fname, bool doopen=true)
Set the file path, and optionally open the file.
int naxis ()
Get the current value of _naxis.
long naxes (int dim)
Get the current value of _naxes for the specified dimension.
int open ()
Open the file.
int open (const std::string &fname)
Open the file, first setting the file path.
int close ()
Close the file.
int getDimensions ()
Get the number of dimensions (i.e. _naxis)
long getSize ()
Get the total size.
long getSize (size_t axis)
Get the size of a specific dimension.
Reading Basic Arrays
These methods read FITS data into basic or raw arrays specified by a pointer.
int read (dataT *data)
Read the contents of the FITS file into an array.
int read (dataT *data, fitsHeader &head)
Read the contents of the FITS file into an array.
int read (dataT *data, const std::string &fname)
Read the contents of the FITS file into an array.
int read (dataT *data, fitsHeader &head, const std::string &fname)
Read the contents of the FITS file into an array and read the header.
int read (dataT *im, const std::vector< std::string > &flist)
Read data from a vector list of files into an image cube.
int read (dataT *im, std::vector< fitsHeader > &heads, const std::vector< std::string > &flist)
Read data from a vector of files into an image cube with individual headers.
Reading Eigen Arrays
These methods read FITS data into array types with an Eigen-like interface.
template<typename arrT >
int read (arrT &data)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
template<typename arrT >
int read (arrT &data, fitsHeader &head)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
template<typename arrT >
int read (arrT &data, const std::string &fname)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
template<typename arrT >
int read (arrT &data, fitsHeader &head, const std::string &fname)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
template<typename cubeT >
int read (cubeT &cube, const std::vector< std::string > &flist, std::vector< fitsHeader > *heads=0)
Read data from a vector list of files into an image cube.
template<typename cubeT >
int read (cubeT &cube, std::vector< fitsHeader > &heads, const std::vector< std::string > &flist)
Read data from a vector of files into an image cube with individual headers.
Reading Headers
int readHeader (fitsHeader &head)
Read the header from the fits file.
int readHeader (fitsHeader &head, const std::string &fname)
Read the header from the fits file.
int readHeader (std::vector< fitsHeader > &heads, const std::vector< std::string > &flist)
Read the headers from a list of FITS files.
Writing Basic Arrays
These methods write basic arrays specified by a pointer to FITS.
int write (const dataT *im, int d1, int d2, int d3, fitsHeader *head)
Write the contents of a raw array to the FITS file.
int write (const dataT *im, int d1, int d2, int d3)
Write the contents of a raw array to the FITS file.
int write (const dataT *im, int d1, int d2, int d3, fitsHeader &head)
Write the contents of a raw array to the FITS file.
int write (std::string fname, const dataT *im, int d1, int d2, int d3)
Write the contents of a raw array to the FITS file.
int write (std::string fname, const dataT *im, int d1, int d2, int d3, fitsHeader &head)
Write the contents of a raw array to the FITS file.
Writing Eigen Arrays
These methods write array types with an Eigen-like interface.
template<typename arrT >
int write (std::string fname, const arrT &im)
Write the contents of an Eigen-type array to a FITS file.
template<typename arrT >
int write (std::string fname, const arrT &im, fitsHeader &head)
Write the contents of an Eigen-type array to a FITS file.
Reading Subsets
It is often desirable to read only a subset of an image or images into memory. These methods allow you to specify this.
void setReadSize ()
Set to read all the pixels in the file.
void setReadSize (long x0, long y0, long xpix, long ypix)
Set to read only a subset of the pixels in the file.
Protected Member Functions
void construct ()
One time initialization common to all constructors.
Protected Attributes
std::string _fileName
The path to the file.
fitsfile * _fptr
The cfitsio data structure.
int _naxis
The dimensions of the image (1D, 2D, 3D etc)
long * _naxes
The size of each dimension.
bool _isOpen
Flag indicating whether the file is open or not.
dataT _nulval
The value to replace null values with.
int _anynul
Records whether any null values were replaced.
int _noComment
Flag to control whether the comment string is read.
long _x0
The starting x-pixel to read from.
long _y0
The starting y-pixel to read from.
long _xpix
The number of x-pixels to read.
long _ypix
The number of y-pixels to read.
Constructor & Destructor Documentation
template<typename dataT > mx::improc::fitsFile< dataT >::fitsFile ()
Default constructor.
Definition at line 532 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::construct().
template<typename dataT > mx::improc::fitsFile< dataT >::fitsFile (const std::string & fname, bool doopen = true)
Constructor with _fileName, and option to open.
Parameters
fname File name to set on construction
doopen If true, then the file is opened (the default).
Definition at line 538 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::construct(), and mx::improc::fitsFile< dataT >::fileName().
template<typename dataT > mx::improc::fitsFile< dataT >::~fitsFile ()
Destructor.
Definition at line 545 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::_naxes, and mx::improc::fitsFile< dataT >::close().
Member Function Documentation
template<typename dataT > int mx::improc::fitsFile< dataT >::close ()
Close the file.
Returns
0 on success
-1 on error
Definition at line 642 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_fileName, mx::improc::fitsFile< dataT >::_fptr, mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::_naxes, MXE_FILECERR, and mxError.
Referenced by mx::improc::fitsFile< dataT >::fileName(), mx::improc::fitsFile< dataT >::write(), and mx::improc::fitsFile< dataT >::~fitsFile().
template<typename dataT > void mx::improc::fitsFile< dataT >::construct () protected
One time initialization common to all constructors.
Definition at line 517 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_anynul, mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::_naxes, mx::improc::fitsFile< dataT >::_noComment, mx::improc::fitsFile< dataT >::_nulval, and mx::improc::fitsFile< dataT >::setReadSize().
Referenced by mx::improc::fitsFile< dataT >::fitsFile().
template<typename dataT > std::string mx::improc::fitsFile< dataT >::fileName ()
Get the current value of _fileName.
Returns
the current value of _fileName.
Definition at line 553 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_fileName.
Referenced by mx::improc::fitsFile< dataT >::fitsFile(), mx::improc::fitsFile< dataT >::open(), mx::improc::fitsFile< dataT >::read(), mx::improc::fitsFile< dataT >::readHeader(), and mx::improc::fitsFile< dataT >::write().
template<typename dataT > int mx::improc::fitsFile< dataT >::fileName (const std::string & fname, bool doopen = true)
Set the file path, and optionally open the file.
Returns
0 on success
-1 on success
Parameters
fname The new file name.
doopen If true, then the file is opened (the default).
Definition at line 559 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_fileName, mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::close(), and mx::improc::fitsFile< dataT >::open().
template<typename dataT > int mx::improc::fitsFile< dataT >::getDimensions ()
Get the number of dimensions (i.e. _naxis)
Definition at line 674 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::_naxes, and mx::improc::fitsFile< dataT >::_naxis.
template<typename dataT > long mx::improc::fitsFile< dataT >::getSize ()
Get the total size.
Definition at line 682 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::_naxes, mx::improc::fitsFile< dataT >::_naxis, mx::improc::fitsFile< dataT >::_x0, mx::improc::fitsFile< dataT >::_xpix, mx::improc::fitsFile< dataT >::_y0, and mx::improc::fitsFile< dataT >::_ypix.
Referenced by mx::improc::fitsFile< dataT >::read().
template<typename dataT > long mx::improc::fitsFile< dataT >::getSize (size_t axis)
Get the size of a specific dimension.
Definition at line 701 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::_naxes, mx::improc::fitsFile< dataT >::_naxis, mx::improc::fitsFile< dataT >::_x0, mx::improc::fitsFile< dataT >::_xpix, mx::improc::fitsFile< dataT >::_y0, and mx::improc::fitsFile< dataT >::_ypix.
template<typename dataT > long mx::improc::fitsFile< dataT >::naxes (int dim)
Get the current value of _naxes for the specified dimension.
Returns
the current value of _naxes for the specified dimension
Parameters
[in] dim the dimension
Definition at line 584 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_naxes.
template<typename dataT > int mx::improc::fitsFile< dataT >::naxis ()
Get the current value of _naxis.
Returns
the current value of _naxis
Definition at line 578 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_naxis.
template<typename dataT > int mx::improc::fitsFile< dataT >::open ()
Open the file.
File name needs to already have been set.
Returns
0 on success
-1 on error
Definition at line 590 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_fileName, mx::improc::fitsFile< dataT >::_fptr, mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::_naxes, mx::improc::fitsFile< dataT >::_naxis, MXE_FILEOERR, MXE_FILERERR, and mxError.
Referenced by mx::improc::fitsFile< dataT >::fileName(), mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::readHeader().
template<typename dataT > int mx::improc::fitsFile< dataT >::open (const std::string & fname)
Open the file, first setting the file path.
Returns
0 on success
-1 on error
Parameters
fname The name of the file to open.
Definition at line 636 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::fileName().
template<typename dataT > int mx::improc::fitsFile< dataT >::read (dataT * data)
Read the contents of the FITS file into an array.
The array pointed to by data must have been allocated.
Returns
0 on success
-1 on error
Parameters
[out] data an allocated arrray large enough to hold the entire image
Definition at line 721 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_anynul, mx::improc::fitsFile< dataT >::_fileName, mx::improc::fitsFile< dataT >::_fptr, mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::_naxes, mx::improc::fitsFile< dataT >::_naxis, mx::improc::fitsFile< dataT >::_nulval, mx::improc::fitsFile< dataT >::_x0, mx::improc::fitsFile< dataT >::_xpix, mx::improc::fitsFile< dataT >::_y0, mx::improc::fitsFile< dataT >::_ypix, MXE_FILERERR, mxError, and mx::improc::fitsFile< dataT >::open().
Referenced by mx::AO::analysis::fourierVarVec(), mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::initSystem(), mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadApodizer(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadLyotStop(), mx::wfp::idealCoronagraph< _realT >::loadPupil(), mx::improc::fitsFile< dataT >::read(), mx::improc::HCIobservation< _realT >::readFiles(), and mx::AO::sim::turbAtmosphere< _realT >::setup().
template<typename dataT > int mx::improc::fitsFile< dataT >::read (dataT * data, fitsHeader & head)
Read the contents of the FITS file into an array.
The array pointed to by data must have been allocated.
Returns
0 on success
-1 on error
Parameters
[out] data an allocated arrray large enough to hold the entire image
[out] head a fitsHeader object which is passed to readHeader
Definition at line 782 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::readHeader().
template<typename dataT > int mx::improc::fitsFile< dataT >::read (dataT * data, const std::string & fname)
Read the contents of the FITS file into an array.
The array pointed to by data must have been allocated.
Returns
0 on success
-1 on error
Parameters
[out] data is an allocated arrray large enough to hold the entire image
[in] fname is the file path, which is passed to fileName
Definition at line 793 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::fileName(), and mx::improc::fitsFile< dataT >::read().
template<typename dataT > int mx::improc::fitsFile< dataT >::read (dataT * data, fitsHeader & head, const std::string & fname)
Read the contents of the FITS file into an array and read the header.
The array pointed to by data must have been allocated.
Returns
0 on success
-1 on error
Parameters
[out] data an allocated arrray large enough to hold the entire image
[out] head a fitsHeader object which is passed to readHeader
[in] fname the file path, which is passed to fileName
Definition at line 802 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::fileName(), mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::readHeader().
template<typename dataT > int mx::improc::fitsFile< dataT >::read (dataT * im, const std::vector< std::string > & flist)
Read data from a vector list of files into an image cube.
Parameters
[out] im An allocated array large enough to hold all the images
[in] flist The list of files to read.
Definition at line 813 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::fileName(), mx::improc::fitsFile< dataT >::getSize(), MXE_PARAMNOTSET, mxError, and mx::improc::fitsFile< dataT >::read().
template<typename dataT > int mx::improc::fitsFile< dataT >::read (dataT * im, std::vector< fitsHeader > & heads, const std::vector< std::string > & flist)
Read data from a vector of files into an image cube with individual headers.
Parameters
[out] im An allocated array large enough to hold all the images
[in,out] heads The vector of fits headers, allocated to contain one per image.
[in] flist The list of files to read.
Definition at line 839 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::fileName(), mx::improc::fitsFile< dataT >::getSize(), MXE_PARAMNOTSET, mxError, mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::readHeader().
template<typename dataT > template<typename arrT > int mx::improc::fitsFile< dataT >::read (arrT & data)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
The type arrT can be any type with the following members defined:
resize(int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef arrT::Scalar (is the data type, does not have to be dataT)
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] data is the array, which will be resized as necessary using its resize(int, int) member
Definition at line 895 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_anynul, mx::improc::fitsFile< dataT >::_fileName, mx::improc::fitsFile< dataT >::_fptr, mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::_naxes, mx::improc::fitsFile< dataT >::_naxis, mx::improc::fitsFile< dataT >::_nulval, mx::improc::fitsFile< dataT >::_x0, mx::improc::fitsFile< dataT >::_xpix, mx::improc::fitsFile< dataT >::_y0, mx::improc::fitsFile< dataT >::_ypix, MXE_FILERERR, mxError, and mx::improc::fitsFile< dataT >::open().
template<typename dataT > template<typename arrT > int mx::improc::fitsFile< dataT >::read (arrT & data, fitsHeader & head)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
The type arrT can be any type with the following members defined:
resize(int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef arrT::Scalar (is the data type, does not have to be dataT)
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] data is the array, which will be resized as necessary using its resize(int, int) member
[out] head is a fitsHeader object which is passed to readHeader
Definition at line 970 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::readHeader().
template<typename dataT > template<typename arrT > int mx::improc::fitsFile< dataT >::read (arrT & data, const std::string & fname)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
The type arrT can be any type with the following members defined:
resize(int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef arrT::Scalar (is the data type, does not have to be dataT)
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] data is the array, which will be resized as necessary using its resize(int, int) member
[in] fname is the file path, which is passed to fileName
Definition at line 979 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::fileName(), and mx::improc::fitsFile< dataT >::read().
template<typename dataT > template<typename arrT > int mx::improc::fitsFile< dataT >::read (arrT & data, fitsHeader & head, const std::string & fname)
Read the contents of the FITS file into an Eigen array type (not a simple pointer).
The type arrT can be any type with the following members defined:
resize(int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef arrT::Scalar (is the data type, does not have to be dataT)
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] data the array, which will be resized as necessary using its resize(int, int) member
[out] head a fitsHeader object which is passed to readHeader
[in] fname the file path, which is passed to fileName
Definition at line 990 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::fileName(), mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::readHeader().
template<typename dataT > template<typename cubeT > int mx::improc::fitsFile< dataT >::read (cubeT & cube, const std::vector< std::string > & flist, std::vector< fitsHeader > * heads = 0)
Read data from a vector list of files into an image cube.
The type cubeT can be any type with the following members defined:
resize(int, int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef cubeT::Scalar (is the data type, does not have to be dataT)
Note
The images must all be the same size, or all be as large or larger than the subset specified.
Template Parameters
cubeT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] cube A cube which will be resized using its resize(int, int, int) member.
[in] flist The list of files to read.
[out] heads [optional] A vector of fits headers, allocated to contain one per image.
Definition at line 1005 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_anynul, mx::improc::fitsFile< dataT >::_fileName, mx::improc::fitsFile< dataT >::_fptr, mx::improc::fitsFile< dataT >::_naxes, mx::improc::fitsFile< dataT >::_naxis, mx::improc::fitsFile< dataT >::_nulval, mx::improc::fitsFile< dataT >::_x0, mx::improc::fitsFile< dataT >::_xpix, mx::improc::fitsFile< dataT >::_y0, mx::improc::fitsFile< dataT >::_ypix, mx::improc::fitsFile< dataT >::fileName(), MXE_FILERERR, MXE_PARAMNOTSET, mxError, and mx::improc::fitsFile< dataT >::readHeader().
template<typename dataT > template<typename cubeT > int mx::improc::fitsFile< dataT >::read (cubeT & cube, std::vector< fitsHeader > & heads, const std::vector< std::string > & flist)
Read data from a vector of files into an image cube with individual headers.
The type cubeT can be any type with the following members defined:
resize(int, int, int) (allocates memory)
data() (returns a pointer to the underlying array)
typedef cubeT::Scalar (is the data type, does not have to be dataT)
Template Parameters
cubeT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[out] cube A cube which will be resized using its resize(int, int, int) member.
[out] heads The vector of fits headers, allocated to contain one per image.
[in] flist The list of files to read.
Definition at line 1118 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::read().
template<typename dataT > int mx::improc::fitsFile< dataT >::readHeader (fitsHeader & head)
Read the header from the fits file.
If head is not empty, then only the keywords already in head are updated. Otherwise the complete header is read.
Returns
0 on success
-1 on error
Parameters
[out] head a fitsHeader object
Definition at line 1127 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_fileName, mx::improc::fitsFile< dataT >::_fptr, mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::_noComment, mx::improc::fitsHeader::append(), mx::improc::fitsHeader::begin(), mx::improc::fitsHeader::end(), mx::improc::fitsHeader::erase(), MXE_FILERERR, mxError, mx::improc::fitsFile< dataT >::open(), and mx::improc::fitsHeader::size().
Referenced by mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::readHeader().
template<typename dataT > int mx::improc::fitsFile< dataT >::readHeader (fitsHeader & head, const std::string & fname)
Read the header from the fits file.
If head is not empty, then only the keywords already in head are updated. Otherwise the complete header is read.
Returns
0 on success
-1 on error
Parameters
[out] head a fitsHeader object
[in] fname the file path, which is passed to fileName
Definition at line 1244 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::fileName(), and mx::improc::fitsFile< dataT >::readHeader().
template<typename dataT > int mx::improc::fitsFile< dataT >::readHeader (std::vector< fitsHeader > & heads, const std::vector< std::string > & flist)
Read the headers from a list of FITS files.
In each case, if the header is not empty then only the keywords already in head are updated. Otherwise the complete header is read.
Returns
0 on success
-1 on error
Parameters
flist A vector of fitsHeader objects to read into. [in] A list of files, each of which is passed to fileName
Definition at line 1253 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::fileName(), and mx::improc::fitsFile< dataT >::readHeader().
template<typename dataT > void mx::improc::fitsFile< dataT >::setReadSize ()
Set to read all the pixels in the file.
Definition at line 1425 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_x0, mx::improc::fitsFile< dataT >::_xpix, mx::improc::fitsFile< dataT >::_y0, and mx::improc::fitsFile< dataT >::_ypix.
Referenced by mx::improc::fitsFile< dataT >::construct(), and mx::improc::HCIobservation< _realT >::readFiles().
template<typename dataT > void mx::improc::fitsFile< dataT >::setReadSize (long x0, long y0, long xpix, long ypix)
Set to read only a subset of the pixels in the file.
Parameters
x0 is the starting x-pixel to read
y0 is the starting y-pixel to read
xpix is the number of x-pixels to read
ypix is the number of y-pixels to read
Definition at line 1434 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_x0, mx::improc::fitsFile< dataT >::_xpix, mx::improc::fitsFile< dataT >::_y0, and mx::improc::fitsFile< dataT >::_ypix.
template<typename dataT > int mx::improc::fitsFile< dataT >::write (const dataT * im, int d1, int d2, int d3, fitsHeader * head)
Write the contents of a raw array to the FITS file.
Returns
0 on success
-1 on error
Parameters
[in] im is the array
[in] d1 is the first dimension
[in] d2 is the second dimension
[in] d3 is the third dimenesion (minimum value is 1)
[in] head a pointer to the header. Set to 0 if not used.
Definition at line 1269 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::_fileName, mx::improc::fitsFile< dataT >::_fptr, mx::improc::fitsFile< dataT >::_isOpen, mx::improc::fitsFile< dataT >::_naxes, mx::improc::fitsFile< dataT >::_naxis, mx::improc::fitsHeader::begin(), mx::improc::fitsFile< dataT >::close(), mx::improc::fitsHeader::end(), MXE_FILEOERR, MXE_FILEWERR, and mxError.
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::analyzePSDGrid(), mx::AO::sim::directPhaseReconstructor< realT >::directPhaseReconstructor(), mx::AO::analysis::fourierVarVec(), mx::improc::ADIobservation< _realT, _derotFunctObj >::makeMaskCube(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC(), mx::improc::HCIobservation< _realT >::outputPreProcessed(), mx::improc::HCIobservation< _realT >::outputPSFSub(), mx::AO::sim::turbAtmosphere< _realT >::setup(), mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix(), mx::improc::fitsFile< dataT >::write(), and mx::improc::HCIobservation< _realT >::writeFinim().
template<typename dataT > int mx::improc::fitsFile< dataT >::write (const dataT * im, int d1, int d2, int d3)
Write the contents of a raw array to the FITS file.
Returns
0 on success
-1 on error
Parameters
[in] im is the array
[in] d1 is the first dimension
[in] d2 is the second dimension
[in] d3 is the third dimenesion (minimum value is 1)
Definition at line 1354 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::write().
template<typename dataT > int mx::improc::fitsFile< dataT >::write (const dataT * im, int d1, int d2, int d3, fitsHeader & head)
Write the contents of a raw array to the FITS file.
Note: the type of the array must match dataT
Returns
0 on success
-1 on error
Parameters
[in] im is the array
[in] d1 is the first dimension
[in] d2 is the second dimension
[in] d3 is the third dimenesion (minimum value is 1)
[in] head is the header
Definition at line 1364 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::write().
template<typename dataT > int mx::improc::fitsFile< dataT >::write (std::string fname, const dataT * im, int d1, int d2, int d3)
Write the contents of a raw array to the FITS file.
Returns
0 on success
-1 on error
Parameters
[in] fname is the name of the file.
[in] im is the array
[in] d1 is the first dimension
[in] d2 is the second dimension
[in] d3 is the third dimenesion (minimum value is 1)
Definition at line 1375 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::fileName(), and mx::improc::fitsFile< dataT >::write().
template<typename dataT > int mx::improc::fitsFile< dataT >::write (std::string fname, const dataT * im, int d1, int d2, int d3, fitsHeader & head)
Write the contents of a raw array to the FITS file.
Returns
0 on success
-1 on error
Parameters
[in] fname is the name of the file.
[in] im is the array
[in] d1 is the first dimension
[in] d2 is the second dimension
[in] d3 is the third dimenesion (minimum value is 1)
[in] head is the header
Definition at line 1387 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::fileName(), and mx::improc::fitsFile< dataT >::write().
template<typename dataT > template<typename arrT > int mx::improc::fitsFile< dataT >::write (std::string fname, const arrT & im)
Write the contents of an Eigen-type array to a FITS file.
The type arrT can be any type with the following members defined:
data() (returns a pointer to the underlying array)
rows() (returrns the number of rows)
cols() (returns the number of columns)
may have planes() defined
Note: as with all write methods, the Scalar type of the array must match dataT
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[in] fname is the name of the file.
[in] im is the array
Definition at line 1402 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::write().
template<typename dataT > template<typename arrT > int mx::improc::fitsFile< dataT >::write (std::string fname, const arrT & im, fitsHeader & head)
Write the contents of an Eigen-type array to a FITS file.
The type arrT can be any type with the following members defined:
data() (returns a pointer to the underlying array)
rows() (returrns the number of rows)
cols() (returns the number of columns)
may have planes() defined.
Note: as with all write methods, the Scalar type of the array must match dataT
Template Parameters
arrT is the type of array, see requirements above.
Returns
0 on success
-1 on error
Parameters
[in] fname is the file path, which is passed to fileName
[in] im is the array
[in] head is a fitsHeader object which is passed to readHeader
Definition at line 1414 of file fitsFile.hpp.
References mx::improc::fitsFile< dataT >::write().
Member Data Documentation
template<typename dataT> int mx::improc::fitsFile< dataT >::_anynul protected
Records whether any null values were replaced.
Definition at line 61 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::construct(), and mx::improc::fitsFile< dataT >::read().
template<typename dataT> std::string mx::improc::fitsFile< dataT >::_fileName protected
The path to the file.
Definition at line 43 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::close(), mx::improc::fitsFile< dataT >::fileName(), mx::improc::fitsFile< dataT >::open(), mx::improc::fitsFile< dataT >::read(), mx::improc::fitsFile< dataT >::readHeader(), and mx::improc::fitsFile< dataT >::write().
template<typename dataT> fitsfile* mx::improc::fitsFile< dataT >::_fptr protected
The cfitsio data structure.
Definition at line 46 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::close(), mx::improc::fitsFile< dataT >::open(), mx::improc::fitsFile< dataT >::read(), mx::improc::fitsFile< dataT >::readHeader(), and mx::improc::fitsFile< dataT >::write().
template<typename dataT> bool mx::improc::fitsFile< dataT >::_isOpen protected
Flag indicating whether the file is open or not.
Definition at line 55 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::close(), mx::improc::fitsFile< dataT >::construct(), mx::improc::fitsFile< dataT >::fileName(), mx::improc::fitsFile< dataT >::getDimensions(), mx::improc::fitsFile< dataT >::getSize(), mx::improc::fitsFile< dataT >::open(), mx::improc::fitsFile< dataT >::read(), mx::improc::fitsFile< dataT >::readHeader(), mx::improc::fitsFile< dataT >::write(), and mx::improc::fitsFile< dataT >::~fitsFile().
template<typename dataT> long* mx::improc::fitsFile< dataT >::_naxes protected
The size of each dimension.
Definition at line 52 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::close(), mx::improc::fitsFile< dataT >::construct(), mx::improc::fitsFile< dataT >::getDimensions(), mx::improc::fitsFile< dataT >::getSize(), mx::improc::fitsFile< dataT >::naxes(), mx::improc::fitsFile< dataT >::open(), mx::improc::fitsFile< dataT >::read(), mx::improc::fitsFile< dataT >::write(), and mx::improc::fitsFile< dataT >::~fitsFile().
template<typename dataT> int mx::improc::fitsFile< dataT >::_naxis protected
The dimensions of the image (1D, 2D, 3D etc)
Definition at line 49 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::getDimensions(), mx::improc::fitsFile< dataT >::getSize(), mx::improc::fitsFile< dataT >::naxis(), mx::improc::fitsFile< dataT >::open(), mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::write().
template<typename dataT> int mx::improc::fitsFile< dataT >::_noComment protected
Flag to control whether the comment string is read.
Definition at line 64 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::construct(), and mx::improc::fitsFile< dataT >::readHeader().
template<typename dataT> dataT mx::improc::fitsFile< dataT >::_nulval protected
The value to replace null values with.
Definition at line 58 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::construct(), and mx::improc::fitsFile< dataT >::read().
template<typename dataT> long mx::improc::fitsFile< dataT >::_x0 protected
The starting x-pixel to read from.
Definition at line 68 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::getSize(), mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::setReadSize().
template<typename dataT> long mx::improc::fitsFile< dataT >::_xpix protected
The number of x-pixels to read.
Definition at line 74 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::getSize(), mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::setReadSize().
template<typename dataT> long mx::improc::fitsFile< dataT >::_y0 protected
The starting y-pixel to read from.
Definition at line 71 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::getSize(), mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::setReadSize().
template<typename dataT> long mx::improc::fitsFile< dataT >::_ypix protected
The number of y-pixels to read.
Definition at line 77 of file fitsFile.hpp.
Referenced by mx::improc::fitsFile< dataT >::getSize(), mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::setReadSize().
The documentation for this class was generated from the following file:
improc/fitsFile.hpp