mxlib: mx::AO::sim::directPhaseReconstructor< realT > Class Template Reference
mx::AO::sim::directPhaseReconstructor< realT > Class Template Reference
template<typename realT>
class mx::AO::sim::directPhaseReconstructor< realT >
A Pyramid Wavefront Sensor slope reconstructor.
Calculates slopes, normalized by total flux in the image.
Definition at line 34 of file directPhaseReconstructor.hpp.
#include <ao/sim/directPhaseReconstructor.hpp>
Public Types
typedef Eigen::Array< realT,-1,-1 > imageT
The type of the measurement (i.e. the slope vector)
typedef Eigen::Array< realT,-1,-1 > rmatT
The type of the response matrix.
typedef Eigen::Array< realT,-1,-1 > imageT
The type of the measurement (i.e. the slope vector)
typedef Eigen::Array< realT,-1,-1 > rmatT
The type of the response matrix.
Public Member Functions
directPhaseReconstructor ()
Default c'tor.
realT calAmp ()
Get the calibration amplitude used in response matrix acquisition (_calAmp)
void calAmp (realT ca)
Set the calibration amplitude used in response matrix acquisition (_calAmp)
int nModes ()
Get the number of modes (_nModes)
int detRows ()
Get the number of detector rows (_detRows)
void detRows (int dr)
Set the number of detector rows (_detRows)
int detCols ()
Get the number of detector columns (_detCols)
void detCols (int dc)
Set the number of detector columns (_detCols)
void loadRecon (std::string fname)
Load the reconstrutor from the specified FITS file.
int measurementSize ()
Return the size of the unbinned measurement.
template<typename measurementT , typename wfsImageT >
void calcMeasurement (measurementT &slopes, wfsImageT &wfsImage)
Calculate the slope measurement.
template<typename measurementT , typename wfsImageT >
void reconstruct (measurementT &commandVect, wfsImageT &wfsImage)
Reconstruct the wavefront from the input image, producing the modal amplitude vector.
void initializeRMat (int nmodes, realT calamp, int detrows, int detcols)
Initialize the response matrix for acquisition.
template<typename measurementT >
void accumulateRMat (int i, measurementT &measureVec)
Accumalte the next measurement in the response matrix.
void saveRMat (std::string fname)
Write the accumulated response matrix to disk.
directPhaseReconstructor ()
Default c'tor.
realT calAmp ()
Get the calibration amplitude used in response matrix acquisition (_calAmp)
void calAmp (realT ca)
Set the calibration amplitude used in response matrix acquisition (_calAmp)
int nModes ()
Get the number of modes (_nModes)
int detRows ()
Get the number of detector rows (_detRows)
void detRows (int dr)
Set the number of detector rows (_detRows)
int detCols ()
Get the number of detector columns (_detCols)
void detCols (int dc)
Set the number of detector columns (_detCols)
void loadRecon (std::string fname)
Load the reconstrutor from the specified FITS file.
int measurementSize ()
Return the size of the unbinned measurement.
template<typename measurementT , typename wfsImageT >
void calcMeasurement (measurementT &slopes, wfsImageT &wfsImage)
Calculate the slope measurement.
template<typename measurementT , typename wfsImageT >
void reconstruct (measurementT &commandVect, wfsImageT &wfsImage)
Reconstruct the wavefront from the input image, producing the modal amplitude vector.
void initializeRMat (int nmodes, realT calamp, int detrows, int detcols)
Initialize the response matrix for acquisition.
template<typename measurementT >
void accumulateRMat (int i, measurementT &measureVec)
Accumalte the next measurement in the response matrix.
void saveRMat (std::string fname)
Write the accumulated response matrix to disk.
Protected Attributes
int _nModes
The number of modes to be reconstructed.
int _detRows
The size of the WFS image, in rows.
int _detCols
The size of the WFS image, in columns.
int _measurementSize
The number of values in the measurement.
imageT _rMat
The response matrix.
Eigen::Array< realT,-1,-1 > _recon
The reconstructor matrix.
Member Typedef Documentation
template<typename realT > typedef Eigen::Array<realT, -1, -1> mx::AO::sim::directPhaseReconstructor< realT >::imageT
The type of the measurement (i.e. the slope vector)
The type of the WFS image
Definition at line 42 of file directPhaseReconstructor.hpp.
template<typename realT > typedef Eigen::Array<realT, -1, -1> mx::AO::sim::directPhaseReconstructor< realT >::imageT
The type of the measurement (i.e. the slope vector)
The type of the WFS image
Definition at line 46 of file directPhaseReconstructorD.hpp.
template<typename realT > typedef Eigen::Array<realT, -1, -1> mx::AO::sim::directPhaseReconstructor< realT >::rmatT
The type of the response matrix.
Definition at line 45 of file directPhaseReconstructor.hpp.
template<typename realT > typedef Eigen::Array<realT, -1, -1> mx::AO::sim::directPhaseReconstructor< realT >::rmatT
The type of the response matrix.
Definition at line 49 of file directPhaseReconstructorD.hpp.
Constructor & Destructor Documentation
template<typename realT > mx::AO::sim::directPhaseReconstructor< realT >::directPhaseReconstructor ()
Default c'tor.
Definition at line 182 of file directPhaseReconstructor.hpp.
References mx::AO::sim::directPhaseReconstructor< realT >::_detCols, mx::sigproc::tukey2d(), and mx::improc::fitsFile< dataT >::write().
template<typename realT > mx::AO::sim::directPhaseReconstructor< realT >::directPhaseReconstructor ()
Default c'tor.
Member Function Documentation
template<typename realT > template<typename measurementT > void mx::AO::sim::directPhaseReconstructor< realT >::accumulateRMat (int i, measurementT & measureVec)
Accumalte the next measurement in the response matrix.
Parameters
i the measurement index
measureVec is the i-th measurement vector
Definition at line 330 of file directPhaseReconstructor.hpp.
template<typename realT > template<typename measurementT > void mx::AO::sim::directPhaseReconstructor< realT >::accumulateRMat (int i, measurementT & measureVec)
Accumalte the next measurement in the response matrix.
Parameters
i the measurement index
measureVec is the i-th measurement vector
template<typename realT > realT mx::AO::sim::directPhaseReconstructor< realT >::calAmp ()
Get the calibration amplitude used in response matrix acquisition (_calAmp)
Definition at line 216 of file directPhaseReconstructor.hpp.
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::calAmp (realT ca)
Set the calibration amplitude used in response matrix acquisition (_calAmp)
Parameters
ca [in] the new calibration amplitude
Definition at line 222 of file directPhaseReconstructor.hpp.
template<typename realT > realT mx::AO::sim::directPhaseReconstructor< realT >::calAmp ()
Get the calibration amplitude used in response matrix acquisition (_calAmp)
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::calAmp (realT ca)
Set the calibration amplitude used in response matrix acquisition (_calAmp)
Parameters
ca [in] the new calibration amplitude
template<typename realT > template<typename measurementT , typename wfsImageT > void mx::AO::sim::directPhaseReconstructor< realT >::calcMeasurement (measurementT & slopes, wfsImageT & wfsImage)
Calculate the slope measurement.
Parameters
slopes [out] a (_measurementSize X 2) array of slopes
wfsImage [in] the WFS image from which to measure the slopes
Definition at line 264 of file directPhaseReconstructor.hpp.
template<typename realT > template<typename measurementT , typename wfsImageT > void mx::AO::sim::directPhaseReconstructor< realT >::calcMeasurement (measurementT & slopes, wfsImageT & wfsImage)
Calculate the slope measurement.
Parameters
slopes [out] a (_measurementSize X 2) array of slopes
wfsImage [in] the WFS image from which to measure the slopes
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::detCols ()
Get the number of detector columns (_detCols)
Definition at line 240 of file directPhaseReconstructor.hpp.
References mx::AO::sim::directPhaseReconstructor< realT >::_detCols.
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::detCols (int dc)
Set the number of detector columns (_detCols)
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::detCols ()
Get the number of detector columns (_detCols)
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::detCols (int dc)
Set the number of detector columns (_detCols)
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::detRows ()
Get the number of detector rows (_detRows)
Definition at line 234 of file directPhaseReconstructor.hpp.
References mx::AO::sim::directPhaseReconstructor< realT >::_detRows.
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::detRows (int dr)
Set the number of detector rows (_detRows)
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::detRows ()
Get the number of detector rows (_detRows)
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::detRows (int dr)
Set the number of detector rows (_detRows)
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::initializeRMat (int nmodes, realT calamp, int detrows, int detcols)
Initialize the response matrix for acquisition.
Parameters
nmodes the number of modes
calamp the calibration amplitude
detrows the number of detector rows
detcols the number of detector columns
Definition at line 315 of file directPhaseReconstructor.hpp.
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::initializeRMat (int nmodes, realT calamp, int detrows, int detcols)
Initialize the response matrix for acquisition.
Parameters
nmodes the number of modes
calamp the calibration amplitude
detrows the number of detector rows
detcols the number of detector columns
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::loadRecon (std::string fname)
Load the reconstrutor from the specified FITS file.
Parameters
fname is the name of the FITS file, including path
Definition at line 246 of file directPhaseReconstructor.hpp.
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::loadRecon (std::string fname)
Load the reconstrutor from the specified FITS file.
Parameters
fname is the name of the FITS file, including path
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::measurementSize ()
Return the size of the unbinned measurement.
Definition at line 257 of file directPhaseReconstructor.hpp.
References mx::AO::sim::directPhaseReconstructor< realT >::_measurementSize.
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::measurementSize ()
Return the size of the unbinned measurement.
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::nModes ()
Get the number of modes (_nModes)
Definition at line 228 of file directPhaseReconstructor.hpp.
References mx::AO::sim::directPhaseReconstructor< realT >::_nModes.
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::nModes ()
Get the number of modes (_nModes)
template<typename realT > template<typename measurementT , typename wfsImageT > void mx::AO::sim::directPhaseReconstructor< realT >::reconstruct (measurementT & commandVect, wfsImageT & wfsImage)
Reconstruct the wavefront from the input image, producing the modal amplitude vector.
Definition at line 271 of file directPhaseReconstructor.hpp.
References mx::AO::sim::directPhaseReconstructor< realT >::_nModes, and mx::improc::eigenCube< dataT >::image().
template<typename realT > template<typename measurementT , typename wfsImageT > void mx::AO::sim::directPhaseReconstructor< realT >::reconstruct (measurementT & commandVect, wfsImageT & wfsImage)
Reconstruct the wavefront from the input image, producing the modal amplitude vector.
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::saveRMat (std::string fname)
Write the accumulated response matrix to disk.
Parameters
fname the name, including path, of the response matrix
Definition at line 336 of file directPhaseReconstructor.hpp.
template<typename realT > void mx::AO::sim::directPhaseReconstructor< realT >::saveRMat (std::string fname)
Write the accumulated response matrix to disk.
Parameters
fname the name, including path, of the response matrix
Member Data Documentation
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::_detCols protected
The size of the WFS image, in columns.
Definition at line 54 of file directPhaseReconstructor.hpp.
Referenced by mx::AO::sim::directPhaseReconstructor< realT >::detCols(), and mx::AO::sim::directPhaseReconstructor< realT >::directPhaseReconstructor().
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::_detRows protected
The size of the WFS image, in rows.
Definition at line 53 of file directPhaseReconstructor.hpp.
Referenced by mx::AO::sim::directPhaseReconstructor< realT >::detRows().
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::_measurementSize protected
The number of values in the measurement.
Definition at line 56 of file directPhaseReconstructor.hpp.
Referenced by mx::AO::sim::directPhaseReconstructor< realT >::measurementSize().
template<typename realT > int mx::AO::sim::directPhaseReconstructor< realT >::_nModes protected
The number of modes to be reconstructed.
Definition at line 51 of file directPhaseReconstructor.hpp.
Referenced by mx::AO::sim::directPhaseReconstructor< realT >::nModes(), and mx::AO::sim::directPhaseReconstructor< realT >::reconstruct().
template<typename realT > Eigen::Array<realT,-1,-1> mx::AO::sim::directPhaseReconstructor< realT >::_recon protected
The reconstructor matrix.
Definition at line 54 of file directPhaseReconstructorD.hpp.
template<typename realT > imageT mx::AO::sim::directPhaseReconstructor< realT >::_rMat protected
The response matrix.
Definition at line 58 of file directPhaseReconstructor.hpp.
The documentation for this class was generated from the following files:
ao/sim/directPhaseReconstructor.hpp
ao/sim/directPhaseReconstructorD.hpp