mxlib: mx::AO::analysis::aoSystem< realT, inputSpectT, iosT > Class Template Reference
mx::AO::analysis::aoSystem< realT, inputSpectT, iosT > Class Template Reference
Wavefront Propagation » Adaptive Optics » Analysis of Adaptive Optics
template<typename realT, class inputSpectT, typename iosT = std::ostream>
class mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >
Describes an analytic adaptive optics (AO) system.
Templatized by the turbulence power spectral density (PSD).
Template Parameters
realT the floating point type used for all calculations
inputSpecT specifies the turbulence spatial PSD type
iosT is an output stream type with operator << defined (default is std::ostream)
Definition at line 47 of file aoSystem.hpp.
#include <ao/analysis/aoSystem.hpp>
Public Member Functions
aoSystem ()
Default c'tor.
~aoSystem ()
Destructor.
void loadGuyon2005 ()
Load the default parameters from Guyon, 2005 [8].
void loadMagAOX ()
Load parameters corresponding to the MagAO-X system.
void loadGMagAOX ()
Load parameters corresponding to the G-MagAO-X system.
void F0 (realT nF0)
Set the value of the 0 magnitude photon rate.
realT F0 ()
Get the value of the 0 magnitude photon rate.
void starMag (realT nmag)
Set the value of the Star's magnitude.
realT starMag ()
Get the value of the Star's magnitude.
realT Fg (realT mag)
The photon flux at a given star magnitude.
realT Fg ()
Get the photon rate at the current Star magnitude.
void D (realT nD)
Set the value of the primary mirror diameter.
realT D ()
Get the value of the primary mirror diamter.
void d_min (realT nd)
Set the value of the minimum subaperture sampling.
realT d_min ()
Get the value of the minimum subaperture sampling.
void optd (bool od)
Set whether or not the value of d is optimized or just set to _d_min.
bool optd ()
Get the value of _optd.
int wfsBetaUnalloc ()
Check for unassigned wfs pointer.
void lam_wfs (realT nlam)
Set the value of the WFS wavelength.
realT lam_wfs ()
Get the value of the WFS wavelength.
void npix_wfs (realT npix)
Set the number of pixels in the WFS.
realT npix_wfs ()
Get the number of pixels in the WFS.
void ron_wfs (realT nron)
Set the value of the WFS readout noise.
realT ron_wfs ()
Get the value of the WFS readout noise.
void Fbg (realT fbg)
Set the value of the background blux.
realT Fbg ()
Get the value of the background flux.
void minTauWFS (realT ntau)
Set the value of the minimum WFS exposure time.
realT minTauWFS ()
Get the value of the minimum WFS exposure time.
void deltaTau (realT ndel)
Set the value of _deltaTau.
realT deltaTau ()
Get the value of _deltaTau.
void optTau (bool ot)
Set the value of _optTau.
bool optTau ()
Get the value of _optTau.
void lam_sci (realT nlam)
Set the science wavelength.
realT lam_sci ()
Get the science wavelength.
void zeta (realT nz)
Set the zenith angle, and its secant.
realT zeta ()
Get the zenith angle.
realT secZeta ()
Get the zecant of the zenith angle.
void fit_mn_max (int mnm)
Set the value of _fit_mn_max.
int fit_mn_max ()
Get the value of _fit_mn_max.
void ncp_wfe (realT nwfe)
Set the value of the non-common path WFE.
realT ncp_wfe ()
Get the value of the non-common path WFE.
void ncp_alpha (realT alpha)
Set the value of the non-common path WFE PSD index.
realT ncp_alpha ()
Get the value of the non-common path WFE PSD index.
realT ncpError (int m, int n)
Calculate the NCP variance at a spatial frequency.
realT ncpError ()
Calculate the total NCP variance in rad^2.
iosT & dumpAOSystem (iosT &ios)
Output current parameters to a stream.
Measurement Error
Calculating the WFE due to WFS measurement noise.
realT signal2Noise2 (realT &tau_wfs)
Calculate the signal to noise ratio squared (S/N)^2 for the WFS measurement.
realT measurementError (realT m, realT n)
Calculate the measurement noise at a spatial frequency.
realT measurementError ()
Calculate the total measurement error over all corrected spatial frequencies.
Time Delay Error
Calculating the WFE due to time delay.
realT timeDelayError (realT m, realT n)
Calculate the time delay at a spatial frequency at the optimum exposure time.
realT timeDelayError ()
Calculate the time delay error over all corrected spatial frequencies.
Fitting Error
Calculating the WFE due to uncorrected spatial frequencies.
realT fittingError (realT m, realT n)
Calculate the fitting error at a specific spatial frequency.
realT fittingError ()
Calculate the total fitting error over all uncorrected spatial frequencies.
Chromatic Errors
Calculating the WFE due to chromaticity in scintillaion, index of refraction, and dispersion.
realT chromScintOPDError ()
Calculate the wavefront error due to scintillation chromaticity in the OPD at a specific spatial frequency.
realT chromScintAmpError ()
Calculate the wavefront error due to scintillation chromaticity in amplitude at a specific spatial frequency.
realT chromIndexError ()
Calculate the wavefront error due to chromaticity in the index of refraction at a specific spatial frequency.
realT dispAnisoOPDError ()
Calculate the wavefront error due to dispersive anisoplanatism in the OPD at a specific spatial frequency.
realT dispAnisoAmpError ()
Calculate the wavefront error due to dispersive anisoplanatism in the amplitude at a specific spatial frequency.
Optimum Parameters
Functions to calculate the optimum integration time and actuator spacing.
realT optimumTauWFS (realT m, realT n)
Calculate the optimum exposure time for a given spatial frequency.
realT d_opt ()
Calculate the optimum actuator spacing.
Contrast
Calculating contrast
template<typename varFuncT >
realT C_ (realT m, realT n, bool normStrehl, varFuncT varFunc, int doFittingError)
Worker function for raw contrast fuctions.
template<typename imageT , typename CfuncT >
void C_Map (imageT &im, CfuncT Cfunc)
Worker function for the contrast-map functions.
realT C0var (realT m, realT n)
Calculate the residual variance due to uncorrected phase at a spatial frequency.
realT C0 (realT m, realT n, bool normStrehl=true)
Calculate the contrast due to uncorrected phase, C0.
template<typename imageT >
void C0Map (imageT &map)
Calculate a 2D map of contrast C0.
realT C1var (realT m, realT n)
Calculate the residual variance due to uncorrected amplitude at a spatial frequency.
realT C1 (realT m, realT n, bool normStrehl=true)
Calculate the contrast due to uncorrected amplitude, C1.
template<typename imageT >
void C1Map (imageT &map)
Calculate a 2D map of contrast C1.
realT C2var (realT m, realT n)
Calculate the residual variance due to measurement and time delay errors in phase/OPD at a spatial frequency.
realT C2 (realT m, realT n, bool normStrehl=true)
Calculate the contrast due to measurement and time delay errors in phase/OPD at a spatial frequency.
template<typename imageT >
void C2Map (imageT &map)
Calculate a 2D map of contrast C2().
realT C3var (realT m, realT n)
Calculate the residual variance due to measurement and time delay errors in amplitude at a spatial frequency.
realT C3 (realT m, realT n, bool normStrehl=true)
Calculate the contrast due to measurement and time delay errors in amplitude at a spatial frequency.
template<typename imageT >
void C3Map (imageT &map)
Calculate a 2D map of contrast C3.
realT C4var (realT m, realT n)
Calculate the residual variance due to scintilation-OPD chromaticity.
realT C4 (realT m, realT n, bool normStrehl=true)
Calculate the contrast due to scintilation-OPD chromaticity.
template<typename imageT >
void C4Map (imageT &map)
Calculate a 2D map of contrast C4.
realT C5var (realT m, realT n)
Calculate the residual variance due to to scintilation-amplitude chromaticity.
realT C5 (realT m, realT n, bool normStrehl=true)
Calculate the contrast due to scintilation-amplitude chromaticity.
template<typename imageT >
void C5Map (imageT &map)
Calculate a 2D map of contrast C5.
realT C6var (realT m, realT n)
Calculate the residual variance due to chromaticity of the index of refraction of air.
realT C6 (realT m, realT n, bool normStrehl=true)
Calculate the contrast due to chromaticity of the index of refraction of air.
template<typename imageT >
void C6Map (imageT &map)
Calculate a 2D map of contrast C6.
realT C7var (realT m, realT n)
Calculate the residual variance due to dispersive anisoplanatism.
realT C7 (realT m, realT n, bool normStrehl=true)
Calculate the contrast due to dispersive anisoplanatism.
template<typename imageT >
void C7Map (imageT &map)
Calculate a 2D map of contrast C7.
Protected Member Functions
void initialize ()
Initialize all members.
Protected Attributes
realT _F0
0 mag flux from star at WFS [photons/sec]
realT _D
Telescope diameter [m].
realT _d_min
Minimum AO system actuator pitch [m].
realT _d_opt
Current optimum AO system actuator pitch [m].
bool _optd
Flag controlling whether actuator pitch is optimized (true) or just uses _d_min (false). Default: true.
wfs< realT, iosT > * _wfsBeta
The WFS beta_p class.
realT _lam_wfs
WFS wavelength [m].
realT _npix_wfs
Number of WFS pixels.
realT _ron_wfs
WFS readout noise [electrons/pix].
realT _Fbg
Background flux, [photons/sec/pixel].
realT _minTauWFS
Minimum WFS exposure time [sec].
realT _deltaTau
Loop latency [sec].
bool _optTau
Flag controlling whether optimum integration time is calculated (true) or if _minTauWFS is used (false). Default: true.
realT _lam_sci
Science wavelength [m].
realT _zeta
Zenith angle [radians].
realT _secZeta
Secant of the Zenith angle (calculated)
int _fit_mn_max
Maximum spatial frequency index to use for fitting error calculation.
realT _ncp_wfe
Static WFE [m rms].
realT _ncp_alpha
Power-law exponent for the NCP aberations. Default is 2.
realT _starMag
The magnitude of the star.
bool _specsChanged
Flag to indicate that a specification has changed.
bool _dminChanged
Flag to indicate that d_min has changed.
realT _wfeMeasurement
Total WFE due to measurement a error [rad^2 at _lam_sci].
realT _wfeTimeDelay
Total WFE due to time delay [rad^2 at _lam_sci].
realT _wfeFitting
Total WFE due to fitting error [rad^2 at _lam_sci].
realT _wfeChromScintOPD
Total WFE due to the chromaticity of scintillation OPD [rad^2 at lam_sc].
realT _wfeChromIndex
Total WFE due to the chromaticity of the index of refraction [rad^2 at lam_Sci].
realT _wfeAnisoOPD
Total WFE due to dispersive anisoplanatism OPD.
realT _wfeNCP
Total WFE due to NCP errors [rad^2 at _lam_sci].
realT _wfeVar
The WFE variance, in meters^2. Never use this directly, instead use wfeVar().
realT _strehl
Strehl ratio, a calculated quantity. Never use this directdy, instead use strehl().
Overall WFE and Strehl Ratio
Functions to calculate the total WFE and Strehl ratio.
realT wfeVar ()
Get the current value of the total WFE variance.
realT strehl ()
Get the current Strehl ratio.
void calcStrehl ()
Calculate the component WFE, total WFE, and Strehl ratio.
Constructor & Destructor Documentation
template<typename realT , class inputSpectT , typename iosT > mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::aoSystem ()
Default c'tor.
Calls initialize().
Definition at line 846 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::~aoSystem ()
Destructor.
Definition at line 852 of file aoSystem.hpp.
Member Function Documentation
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C0 (realT m, realT n, bool normStrehl = true)
Calculate the contrast due to uncorrected phase, C0.
Contrast C0 is the uncorrected phase, with the effects of scintillation included. See Guyon (2005) [8], and the updated derivation in Males & Guyon (2017) [males_guyon_2017].
Returns
C0.
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
[in] normStrehl flag controls whether the contrast is normalized by Strehl ratio
Definition at line 1683 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > template<typename imageT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C0Map (imageT & map)
Calculate a 2D map of contrast C0.
Template Parameters
imageT is an Eigen-like image type.
Parameters
[in] map the map image to be filled in with contrast
Definition at line 1694 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C0var (realT m, realT n)
Calculate the residual variance due to uncorrected phase at a spatial frequency.
Used to calculate contrast C0().
Returns
variance at (m,n).
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
Definition at line 1674 of file aoSystem.hpp.
References mx::astro::constants::k(), mx::AO::analysis::aoAtmosphere< _realT >::lam_0(), and mx::AO::analysis::aoAtmosphere< _realT >::X().
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C1 (realT m, realT n, bool normStrehl = true)
Calculate the contrast due to uncorrected amplitude, C1.
Contrast C1 is the uncorrected amplitude due to scintillation. See Guyon (2005) [8], and the updated derivation in Males & Guyon (2017) [males_guyon_2017].
Returns
C0.
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
[in] normStrehl flag controls whether the contrast is normalized by Strehl ratio
Definition at line 1710 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > template<typename imageT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C1Map (imageT & map)
Calculate a 2D map of contrast C1.
The contrast is Strehl-normalized here.
Template Parameters
imageT is an Eigen-like image type.
Parameters
[in] map the map image to be filled in with contrast
Definition at line 1720 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C1var (realT m, realT n)
Calculate the residual variance due to uncorrected amplitude at a spatial frequency.
Used to calculate contrast C1().
Returns
variance at (m,n).
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
Definition at line 1700 of file aoSystem.hpp.
References mx::astro::constants::k(), mx::AO::analysis::aoAtmosphere< _realT >::lam_0(), and mx::AO::analysis::aoAtmosphere< _realT >::Y().
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C2 (realT m, realT n, bool normStrehl = true)
Calculate the contrast due to measurement and time delay errors in phase/OPD at a spatial frequency.
Contrast C2 is just the total variance due to time delay and measurement errors, divided by the Strehl ratio. See Guyon (2005) [8], and the updated derivation in Males & Guyon (2017) [males_guyon_2017].
Returns
C2.
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
[in] normStrehl flag controls whether the contrast is normalized by Strehl ratio.
Definition at line 1734 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > template<typename imageT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C2Map (imageT & map)
Calculate a 2D map of contrast C2().
The contrast is Strehl-normalized here.
Template Parameters
imageT is an Eigen-like image type.
Parameters
[in] map the map image to be filled in with contrast
Definition at line 1744 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C2var (realT m, realT n)
Calculate the residual variance due to measurement and time delay errors in phase/OPD at a spatial frequency.
Used to calculate contrast C2().
Returns
variance at (m,n).
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
Definition at line 1726 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C3 (realT m, realT n, bool normStrehl = true)
Calculate the contrast due to measurement and time delay errors in amplitude at a spatial frequency.
Contrast C3 is just the total variance due to time delay and measurement errors, divided by the Strehl ratio. See Guyon (2005) [8], and the updated derivation in Males & Guyon (2017) [males_guyon_2017].
Returns
C3.
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
[in] normStrehl flag controls whether the contrast is normalized by Strehl ratio.
template<typename realT, class inputSpectT, typename iosT = std::ostream> template<typename imageT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C3Map (imageT & map)
Calculate a 2D map of contrast C3.
The contrast is Strehl-normalized here.
Template Parameters
imageT is an Eigen-like image type.
Parameters
[in] map the map image to be filled in with contrast
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C3var (realT m, realT n)
Calculate the residual variance due to measurement and time delay errors in amplitude at a spatial frequency.
Used to calculate contrast C3().
Returns
variance at (m,n).
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C4 (realT m, realT n, bool normStrehl = true)
Calculate the contrast due to scintilation-OPD chromaticity.
Contrast C4 is due to the chromaticity of scintillation, causing the ODP measurement to be slightly incorrect at the science wavelength. See Guyon (2005) [8], and the updated derivation in Males & Guyon (2017) [males_guyon_2017].
Returns
C4.
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
[in] normStrehl flag controls whether the contrast is normalized by Strehl ratio.
Definition at line 1761 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > template<typename imageT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C4Map (imageT & map)
Calculate a 2D map of contrast C4.
The contrast is Strehl-normalized here.
Template Parameters
imageT is an Eigen-like image type.
Parameters
[in] map the map image to be filled in with contrast
Definition at line 1771 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C4var (realT m, realT n)
Calculate the residual variance due to scintilation-OPD chromaticity.
Used to calculate contrast C4().
Returns
variance at (m,n).
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
Definition at line 1750 of file aoSystem.hpp.
References mx::AO::analysis::aoAtmosphere< _realT >::dX(), mx::astro::constants::k(), and mx::AO::analysis::aoAtmosphere< _realT >::lam_0().
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C5 (realT m, realT n, bool normStrehl = true)
Calculate the contrast due to scintilation-amplitude chromaticity.
Contrast C5 is due to the chromaticity of scintillation, causing the amplitude measurement to be slightly incorrect at the science wavelength. See Guyon (2005) [8], and the updated derivation in Males & Guyon (2017) [males_guyon_2017].
Returns
C4.
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
[in] normStrehl flag controls whether the contrast is normalized by Strehl ratio.
template<typename realT, class inputSpectT, typename iosT = std::ostream> template<typename imageT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C5Map (imageT & map)
Calculate a 2D map of contrast C5.
The contrast is Strehl-normalized here.
Template Parameters
imageT is an Eigen-like image type.
Parameters
[in] map the map image to be filled in with contrast
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C5var (realT m, realT n)
Calculate the residual variance due to to scintilation-amplitude chromaticity.
Used to calculate contrast C5().
Returns
variance at (m,n).
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C6 (realT m, realT n, bool normStrehl = true)
Calculate the contrast due to chromaticity of the index of refraction of air.
Contrast C6 is due to the index of refraction of air being wavelength dependent, causing the ODP measurement to be slightly incorrect at the science wavelength. See Guyon (2005) [8], and the updated derivation in Males & Guyon (2017) [males_guyon_2017].
Returns
C6.
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
normStrehl flag controls whether the contrast is normalized by Strehl ratio.
Definition at line 1789 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > template<typename imageT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C6Map (imageT & map)
Calculate a 2D map of contrast C6.
The contrast is Strehl-normalized here.
Template Parameters
imageT is an Eigen-like image type.
Parameters
[in] map the map image to be filled in with contrast
Definition at line 1799 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C6var (realT m, realT n)
Calculate the residual variance due to chromaticity of the index of refraction of air.
Used to calculate contrast C6().
Returns
variance at (m,n).
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
Definition at line 1777 of file aoSystem.hpp.
References mx::AO::analysis::aoAtmosphere< _realT >::n_air().
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C7 (realT m, realT n, bool normStrehl = true)
Calculate the contrast due to dispersive anisoplanatism.
Contrast C7 is due to atmospheric dispersion causing light at different wavelengths to take different paths through atmospheric turbulence. See Fitzgerald (2017, in prep) [fitzgerald_2017]
Returns
C7.
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
normStrehl flag controls whether the contrast is normalized by Strehl ratio.
Definition at line 1815 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > template<typename imageT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C7Map (imageT & map)
Calculate a 2D map of contrast C7.
The contrast is Strehl-normalized here.
Template Parameters
imageT is an Eigen-like image type.
Parameters
[in] map the map image to be filled in with contrast
Definition at line 1825 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C7var (realT m, realT n)
Calculate the residual variance due to dispersive anisoplanatism.
Used to calculate contrast C7().
Returns
variance at (m,n).
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
Definition at line 1805 of file aoSystem.hpp.
References mx::astro::constants::k(), mx::AO::analysis::aoAtmosphere< _realT >::lam_0(), and mx::AO::analysis::aoAtmosphere< _realT >::X_Z().
template<typename realT , class inputSpectT , typename iosT > template<typename varFuncT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C_ (realT m, realT n, bool normStrehl, varFuncT varFunc, int doFittingError)
Worker function for raw contrast fuctions.
Most of the logic in this calculation is the same, except for the calculation of variance. The varFunc function pointer is used to calculate the variance. This handles the other details such as Strehl normalization, fitting error (if appropriate), and bounds checking.
Template Parameters
varFuncT is a function-pointer-to-member (of this class) with signature realT(*f)(realT, realT)
Parameters
[in] m is the spatial frequency index in u/
[in] n is the spatial frequency index in v.
[in] normStrehl flag controls whether the contrast is normalized by Strehl ratio/
[in] varFunc the variance function to use.
[in] doFittingError flag to describe how fitting error should be considered for this term: FITTING_ERROR_NO, FITTING_ERROR_ZERO, FITTING_ERROR_X, or FITTING_ERROR_Y.
Definition at line 1599 of file aoSystem.hpp.
References mx::astro::constants::k(), mx::AO::analysis::aoAtmosphere< _realT >::X(), and mx::AO::analysis::aoAtmosphere< _realT >::Y().
template<typename realT , class inputSpectT , typename iosT > template<typename imageT , typename CfuncT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::C_Map (imageT & im, CfuncT Cfunc)
Worker function for the contrast-map functions.
The map calculation is the same for all terms, except for the calculation of contrast at each pixel. The Cfunc function pointer is used to actually get the contrast.
Template Parameters
imageT is an Eigen-like image
CfuncT is a function-pointer-to-member (of this class) with signature realT (*f)(realT, realT, bool)
Parameters
[out] im the map image to be filled in.
[in] Cfunc the raw contrast function to use for filling in the map.
Definition at line 1644 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::calcStrehl () protected
Calculate the component WFE, total WFE, and Strehl ratio.
This should only be called when something changes.
Definition at line 1562 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::chromIndexError ()
Calculate the wavefront error due to chromaticity in the index of refraction at a specific spatial frequency.
Returns
the WFE in rad^2 rms at the science wavelength at (m,n).
Definition at line 1380 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::chromScintAmpError ()
Calculate the wavefront error due to scintillation chromaticity in amplitude at a specific spatial frequency.
Returns
the WFE in rad^2 rms at the science wavelength at (m,n).
Definition at line 1357 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::chromScintOPDError ()
Calculate the wavefront error due to scintillation chromaticity in the OPD at a specific spatial frequency.
Returns
the WFE in rad^2 rms at the science wavelength at (m,n).
Definition at line 1336 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::D (realT nD)
Set the value of the primary mirror diameter.
Parameters
[in] nD is the new value of _D.
Definition at line 997 of file aoSystem.hpp.
References mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::D().
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::D(), and mx::AO::analysis::fourierVarVec().
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::D ()
Get the value of the primary mirror diamter.
Returns
the current value of _D.
Definition at line 1007 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::d_min (realT nd)
Set the value of the minimum subaperture sampling.
Parameters
[in] nd is the new value of _d_min
Definition at line 1014 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::d_min ()
Get the value of the minimum subaperture sampling.
Returns
the new value of _d_min.
Definition at line 1022 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::d_opt ()
Calculate the optimum actuator spacing.
Finds the value of _d_opt where the fitting error is less than than the combined time delay and measurement error.
Returns
the current value of _d_opt.
Definition at line 1506 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::deltaTau (realT ndel)
Set the value of _deltaTau.
Parameters
[in] ndel is the new value of _deltaTau
Definition at line 1112 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::deltaTau ()
Get the value of _deltaTau.
Returns
the current value of _deltaTau.
Definition at line 1120 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::dispAnisoAmpError ()
Calculate the wavefront error due to dispersive anisoplanatism in the amplitude at a specific spatial frequency.
Returns
the WFE in rad^2 rms at the science wavelength at (m,n).
Definition at line 1422 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::dispAnisoOPDError ()
Calculate the wavefront error due to dispersive anisoplanatism in the OPD at a specific spatial frequency.
Returns
the WFE in rad^2 rms at the science wavelength at (m,n).
Definition at line 1401 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > iosT & mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::dumpAOSystem (iosT & ios)
Output current parameters to a stream.
Outputs a formatted list of all current parameters.
Parameters
[in] ios a std::ostream-like stream.
Definition at line 1832 of file aoSystem.hpp.
References mx::AO::analysis::aoAtmosphere< _realT >::dumpAtmosphere(), mx::AO::analysis::wfs< realT, iosT >::dumpWFS(), mxlib_compiled_git_repo_modified(), and mxlib_compiled_git_sha1().
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::F0 (realT nF0)
Set the value of the 0 magnitude photon rate.
This is the photon rate at the WFS, photons/sec.
Parameters
[in] nF0 is the new value of _F0.
Definition at line 956 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::F0 ()
Get the value of the 0 magnitude photon rate.
Returns
the current value of _F0.
Definition at line 964 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::Fbg (realT fbg)
Set the value of the background blux.
Parameters
[in] fbg is the new value of _Fbg
Definition at line 1084 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::Fbg ()
Get the value of the background flux.
Returns
Definition at line 1092 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::Fg (realT mag)
The photon flux at a given star magnitude.
Returns
the photon flux of the star in the bandpass assumed by F0.
Parameters
[in] mag is the magnitude of the star.
Definition at line 984 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::Fg ()
Get the photon rate at the current Star magnitude.
Calculates \(F_\gamma = F_0 10^{-0.4 m} \) where \(F_0 \) is _F0 and \(m \) is _starMag.
Returns
the current value of the current photon rate.
Definition at line 990 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::fit_mn_max (int mnm)
Set the value of _fit_mn_max.
Parameters
[in] mnm is the new value of _fit_mn_max
Definition at line 1176 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > int mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::fit_mn_max ()
Get the value of _fit_mn_max.
Definition at line 1183 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::fittingError (realT m, realT n)
Calculate the fitting error at a specific spatial frequency.
Returns
the fitting error in rad^2 rms at the science wavelength at (m,n).
Parameters
[in] m specifies the u component of the spatial frequency
[in] n specifies the v component of the spatial frequency
Definition at line 1307 of file aoSystem.hpp.
References mx::astro::constants::k(), and mx::AO::analysis::aoAtmosphere< _realT >::lam_0().
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::fittingError ()
Calculate the total fitting error over all uncorrected spatial frequencies.
Returns
the total fitting error.
Definition at line 1316 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::initialize () protected
Initialize all members.
Definition at line 857 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::lam_sci (realT nlam)
Set the science wavelength.
Parameters
[in] nlam is the new value of _lam_sci
Definition at line 1140 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::lam_sci ()
Get the science wavelength.
Returns
the current value of _lam_sci.
Definition at line 1148 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::lam_wfs (realT nlam)
Set the value of the WFS wavelength.
Parameters
[in] nlam is the new value of _lam_wfs
Definition at line 1042 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::lam_wfs ()
Get the value of the WFS wavelength.
Returns
the current value of _lam_wfs.
Definition at line 1050 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::loadGMagAOX ()
Load parameters corresponding to the G-MagAO-X system.
Definition at line 940 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::loadGuyon2005 ()
Load the default parameters from Guyon, 2005 [8].
Definition at line 906 of file aoSystem.hpp.
References mx::AO::analysis::aoAtmosphere< _realT >::loadGuyon2005().
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::loadMagAOX ()
Load parameters corresponding to the MagAO-X system.
Definition at line 921 of file aoSystem.hpp.
References mx::AO::analysis::aoAtmosphere< _realT >::loadLCO().
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::measurementError (realT m, realT n)
Calculate the measurement noise at a spatial frequency.
Calculates the wavefront phase variance due measurement noise at \(k = (m/D)\hat{u} + (n/D)\hat{v} \).
Returns
the measurement noise in rad^2 rms at the science wavelength
Parameters
[in] m specifies the u component of the spatial frequency
[in] n specifies the v component of the spatial frequency
Definition at line 1225 of file aoSystem.hpp.
References mx::AO::analysis::wfs< realT, iosT >::beta_p().
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::measurementError ()
Calculate the total measurement error over all corrected spatial frequencies.
Returns
the total WFE due to measurement error.
Definition at line 1246 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::minTauWFS (realT ntau)
Set the value of the minimum WFS exposure time.
Parameters
[in] ntau is the new value of _minTauWFS
Definition at line 1098 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::minTauWFS ()
Get the value of the minimum WFS exposure time.
Returns
the current value of _minTauWFS.
Definition at line 1106 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::ncp_alpha (realT alpha)
Set the value of the non-common path WFE PSD index.
Parameters
[in] alpha is the new value of _ncp_alpha
Definition at line 1203 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::ncp_alpha ()
Get the value of the non-common path WFE PSD index.
Returns
the current value of _ncp_alpha.
Definition at line 1211 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::ncp_wfe (realT nwfe)
Set the value of the non-common path WFE.
Parameters
[in] nwfe is the new value of _ncp_wfe
Definition at line 1189 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::ncp_wfe ()
Get the value of the non-common path WFE.
Returns
the current value of _ncp_wfe.
Definition at line 1197 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::ncpError (int m, int n)
Calculate the NCP variance at a spatial frequency.
Finds the NCP variance at \(k = (m/D)\hat{u} + (n/D)\hat{v} \).
Returns
the NCP variance at k.
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
Definition at line 1545 of file aoSystem.hpp.
References mx::astro::constants::k().
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::ncpError ()
Calculate the total NCP variance in rad^2.
Returns
the total NCP variance.
Definition at line 1556 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::npix_wfs (realT npix)
Set the number of pixels in the WFS.
Parameters
[in] npix is the new value of _npix_wfs
Definition at line 1056 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::npix_wfs ()
Get the number of pixels in the WFS.
Returns
the current value of _npix_wfs
Definition at line 1064 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::optd (bool od)
Set whether or not the value of d is optimized or just set to _d_min.
Parameters
[in] od is the new value of _optd
Definition at line 1028 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > bool mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::optd ()
Get the value of _optd.
Returns
the new value of _optd.
Definition at line 1036 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::optimumTauWFS (realT m, realT n)
Calculate the optimum exposure time for a given spatial frequency.
Finds the optimum exposure time at \(k = (m/D)\hat{u} + (n/D)\hat{v} \).
Todo:
Check inclusion of X in parameters
Returns
the optimum expsoure time.
Parameters
[in] m is the spatial frequency index in u
[in] n is the spatial frequency index in v
Definition at line 1446 of file aoSystem.hpp.
References mx::AO::analysis::wfs< realT, iosT >::beta_p(), mx::astro::constants::c(), mx::astro::constants::k(), mx::AO::analysis::aoAtmosphere< _realT >::lam_0(), MXE_PARAMNOTSET, mxError, mx::quarticRoots(), mx::AO::analysis::aoAtmosphere< _realT >::v_wind(), and mx::AO::analysis::aoAtmosphere< _realT >::X().
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::optTau (bool ot)
Set the value of _optTau.
Parameters
[in] ot is the new value of _optTau
Definition at line 1126 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > bool mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::optTau ()
Get the value of _optTau.
Returns
the current value of _optTau.
Definition at line 1134 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::ron_wfs (realT nron)
Set the value of the WFS readout noise.
Parameters
[in] nron is the new value of _ron_wfs
Definition at line 1070 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::ron_wfs ()
Get the value of the WFS readout noise.
Returns
the current value of _ron_wfs
Definition at line 1078 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::secZeta ()
Get the zecant of the zenith angle.
Returns
the current value of _secZeta
Definition at line 1170 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::signal2Noise2 (realT & tau_wfs)
Calculate the signal to noise ratio squared (S/N)^2 for the WFS measurement.
The S/N squared is
\[ (S/N)^2 = \frac{ F_\gamma^2 \tau_{wfs}^2 }{ F_\gamma \tau_{wfs} + n_{pix} F_{bg} \tau_{wfs} + n_{pix} \sigma_{ron}^2 } \]
Returns
the S/N squared
Parameters
[in,out] tau_wfs specifies the WFS exposure time. If 0, then optimumTauWFS is used
Definition at line 1217 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::starMag (realT nmag)
Set the value of the Star's magnitude.
Parameters
[in] nmag is the new value of _starMag.
Definition at line 970 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::starMag ()
Get the value of the Star's magnitude.
Returns
the current value of _starMag
Definition at line 978 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::strehl ()
Get the current Strehl ratio.
If no changes, merely returns _strehl. Calls calcStrehl if there are changes. Strehl is calculated using the extended Marechal approximation:
\[ S = e^{-\sigma_{wfe}^2} \]
where \(\sigma_{wfe}^2 \) is the current value of _wfeVar.
Returns
the current value of _strehl.
Definition at line 1590 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::timeDelayError (realT m, realT n)
Calculate the time delay at a spatial frequency at the optimum exposure time.
Calculates the wavefront phase variance due to time delay at \(f = (m/D)\hat{u} + (n/D)\hat{v} \).
Returns
the measurement noise in rad^2 rms at the science wavelength
Parameters
[in] m specifies the u component of the spatial frequency
[in] n specifies the v component of the spatial frequency
Definition at line 1265 of file aoSystem.hpp.
References mx::astro::constants::k(), mx::AO::analysis::aoAtmosphere< _realT >::lam_0(), mx::AO::analysis::aoAtmosphere< _realT >::v_wind(), and mx::AO::analysis::aoAtmosphere< _realT >::X().
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::timeDelayError ()
Calculate the time delay error over all corrected spatial frequencies.
Returns
the total WFE due to time delay.
Definition at line 1285 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::wfeVar ()
Get the current value of the total WFE variance.
If no changes, merely returns _wfeVar. Calls calcStrehl if there are changes.
Returns
the current value of _wfeVar;
Definition at line 1582 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> int mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::wfsBetaUnalloc () inline
Check for unassigned wfs pointer.
Prints error and exit()s.
Definition at line 224 of file aoSystem.hpp.
References MXE_PARAMNOTSET, and mxError.
template<typename realT , class inputSpectT , typename iosT > void mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::zeta (realT nz)
Set the zenith angle, and its secant.
Parameters
[in] nz The new value of _zeta
Definition at line 1154 of file aoSystem.hpp.
template<typename realT , class inputSpectT , typename iosT > realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::zeta ()
Get the zenith angle.
Returns
the current value of _zeta
Definition at line 1164 of file aoSystem.hpp.
Member Data Documentation
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_D protected
Telescope diameter [m].
Definition at line 58 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_d_min protected
Minimum AO system actuator pitch [m].
Definition at line 60 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_d_opt protected
Current optimum AO system actuator pitch [m].
Definition at line 61 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_deltaTau protected
Loop latency [sec].
Definition at line 73 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> bool mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_dminChanged protected
Flag to indicate that d_min has changed.
Definition at line 89 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_F0 protected
0 mag flux from star at WFS [photons/sec]
Definition at line 57 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_Fbg protected
Background flux, [photons/sec/pixel].
Definition at line 69 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> int mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_fit_mn_max protected
Maximum spatial frequency index to use for fitting error calculation.
Definition at line 81 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_lam_sci protected
Science wavelength [m].
Definition at line 76 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_lam_wfs protected
WFS wavelength [m].
Definition at line 66 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_minTauWFS protected
Minimum WFS exposure time [sec].
Definition at line 72 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_ncp_alpha protected
Power-law exponent for the NCP aberations. Default is 2.
Definition at line 84 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_ncp_wfe protected
Static WFE [m rms].
Definition at line 83 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_npix_wfs protected
Number of WFS pixels.
Definition at line 67 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> bool mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_optd protected
Flag controlling whether actuator pitch is optimized (true) or just uses _d_min (false). Default: true.
Definition at line 62 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> bool mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_optTau protected
Flag controlling whether optimum integration time is calculated (true) or if _minTauWFS is used (false). Default: true.
Definition at line 74 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_ron_wfs protected
WFS readout noise [electrons/pix].
Definition at line 68 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_secZeta protected
Secant of the Zenith angle (calculated)
Definition at line 79 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> bool mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_specsChanged protected
Flag to indicate that a specification has changed.
Definition at line 88 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_starMag protected
The magnitude of the star.
Definition at line 86 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_strehl protected
Strehl ratio, a calculated quantity. Never use this directdy, instead use strehl().
Definition at line 101 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_wfeAnisoOPD protected
Total WFE due to dispersive anisoplanatism OPD.
Definition at line 96 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_wfeChromIndex protected
Total WFE due to the chromaticity of the index of refraction [rad^2 at lam_Sci].
Definition at line 95 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_wfeChromScintOPD protected
Total WFE due to the chromaticity of scintillation OPD [rad^2 at lam_sc].
Definition at line 94 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_wfeFitting protected
Total WFE due to fitting error [rad^2 at _lam_sci].
Definition at line 93 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_wfeMeasurement protected
Total WFE due to measurement a error [rad^2 at _lam_sci].
Definition at line 91 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_wfeNCP protected
Total WFE due to NCP errors [rad^2 at _lam_sci].
Definition at line 98 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_wfeTimeDelay protected
Total WFE due to time delay [rad^2 at _lam_sci].
Definition at line 92 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_wfeVar protected
The WFE variance, in meters^2. Never use this directly, instead use wfeVar().
Definition at line 100 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> wfs<realT, iosT>* mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_wfsBeta protected
The WFS beta_p class.
Definition at line 64 of file aoSystem.hpp.
template<typename realT, class inputSpectT, typename iosT = std::ostream> realT mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::_zeta protected
Zenith angle [radians].
Definition at line 78 of file aoSystem.hpp.
The documentation for this class was generated from the following file:
ao/analysis/aoSystem.hpp