mxlib: mx::randomT< typeT, _ranengT, _randistT > Class Template Reference
mx::randomT< typeT, _ranengT, _randistT > Class Template Reference
General Mathematics » Random Numbers
template<class typeT, class _ranengT, class _randistT>
class mx::randomT< typeT, _ranengT, _randistT >
A random number type, which functions like any other arithmetic type.
Combines a random engine, and a random distribution. Using the type conversion operator randomT returns the next random deviate whenever it is referenced.
Example:
//This can also be done using the alias definition mx::normDistT.
randomT<double, std::mt19937_64, std::normal_distribution<double> > norm_distd;
norm_distd.seed(); //
double d1 = norm_distd; //get a normally distributed value
double d2 = norm_distd; //get the next normally distributed value
Definition at line 37 of file randomT.hpp.
#include <randomT.hpp>
Public Types
typedef _randistT randistT
Typedef for the distribution type.
typedef _ranengT ranengT
Typedef for the engine type.
Public Member Functions
randomT ()
Constructor.
operator typeT ()
The conversion operator, returns the next value in the sequence, according to the distribution.
void seed (typename ranengT::result_type seedval)
Set the seed of the random engine.
void seed ()
Seed the random engine with a good value.
Public Attributes
_randistT distribution
The random distribution.
ranengT engine
The random engine.
Member Typedef Documentation
template<class typeT, class _ranengT, class _randistT> typedef _randistT mx::randomT< typeT, _ranengT, _randistT >::randistT
Typedef for the distribution type.
Definition at line 46 of file randomT.hpp.
template<class typeT, class _ranengT, class _randistT> typedef _ranengT mx::randomT< typeT, _ranengT, _randistT >::ranengT
Typedef for the engine type.
Definition at line 49 of file randomT.hpp.
Constructor & Destructor Documentation
template<class typeT, class _ranengT, class _randistT> mx::randomT< typeT, _ranengT, _randistT >::randomT () inline
Constructor.
Definition at line 43 of file randomT.hpp.
Member Function Documentation
template<class typeT, class _ranengT, class _randistT> mx::randomT< typeT, _ranengT, _randistT >::operator typeT () inline
The conversion operator, returns the next value in the sequence, according to the distribution.
Definition at line 58 of file randomT.hpp.
References mx::randomT< typeT, _ranengT, _randistT >::distribution.
template<class typeT, class _ranengT, class _randistT> void mx::randomT< typeT, _ranengT, _randistT >::seed (typename ranengT::result_type seedval) inline
Set the seed of the random engine.
Calls the engines seed member function.
Parameters
[in] seedval the argument to pass to ranengT::seed()
Definition at line 68 of file randomT.hpp.
Referenced by mx::AO::influenceFunctionsGaussian(), and mx::AO::sim::turbAtmosphere< _realT >::setup().
template<class typeT, class _ranengT, class _randistT> void mx::randomT< typeT, _ranengT, _randistT >::seed () inline
Seed the random engine with a good value.
Calls mx::randomSeed to get the value. On linux this uses /dev/urandom. On other sytems, this uses time(0).
Definition at line 76 of file randomT.hpp.
Referenced by mx::randomT< floatT, std::mt19937_64, std::gamma_distribution< floatT > >::seed().
Member Data Documentation
template<class typeT, class _ranengT, class _randistT> _randistT mx::randomT< typeT, _ranengT, _randistT >::distribution
The random distribution.
Definition at line 52 of file randomT.hpp.
Referenced by mx::AO::sim::ccdDetector< _floatT >::exposeImage(), and mx::randomT< typeT, _ranengT, _randistT >::operator typeT().
template<class typeT, class _ranengT, class _randistT> ranengT mx::randomT< typeT, _ranengT, _randistT >::engine
The random engine.
Definition at line 55 of file randomT.hpp.
The documentation for this class was generated from the following file:
randomT.hpp