mxlib: mx::wfp::fraunhoferPropagator< _wavefrontT > Class Template Reference
mx::wfp::fraunhoferPropagator< _wavefrontT > Class Template Reference
Wavefront Propagation
template<typename _wavefrontT>
class mx::wfp::fraunhoferPropagator< _wavefrontT >
Class to perform Fraunhofer propagation between pupil and focal planes.
This class uses the FFT to propagate between planes, and normalizes so that flux is conserved. For propagation from pupil to focal plane, the pupil wavefront is tilted so that the focal-plane image is centered at the geometric center of the array. After propagation from focal plane to pupil plane, the pupil plane wavefront is un-tilted to restore the pupil to its original position.
Template Parameters
_wavefrontT is an Eigen::Array-like type, with std::complex values.
Definition at line 35 of file fraunhoferPropagator.hpp.
#include <wfp/fraunhoferPropagator.hpp>
Public Types
typedef _wavefrontT wavefrontT
The wavefront data type.
typedef wavefrontT::Scalar complexT
The complex data type.
typedef wavefrontT::Scalar::value_type realT
The real data type.
Public Member Functions
fraunhoferPropagator ()
Constructor.
~fraunhoferPropagator ()
Destructor.
void shiftPupil (wavefrontT &complexPupil)
Apply the shift to a pupil wavefront which will center the resultant focal plane image.
void propagatePupilToFocal (wavefrontT &complexFocal, wavefrontT &complexPupil)
Propagate the wavefront from the pupil plane to the focal plane.
void propagateFocalToPupil (wavefrontT &complexPupil, wavefrontT &complexFocal)
Propagate the wavefront from Focal plane to Pupil plane.
void setWavefrontSizePixels (int wfsPix)
Set the size of the wavefront, in pixels.
Protected Member Functions
void initialize ()
Initialize members.
void makeShiftPhase ()
Calculate the complex tilt arrays for centering and normalizing the wavefronts.
Protected Attributes
int wavefrontSizePixels
The size of the wavefront in pixels.
realT xcen
x-coordinate of focal plane center, in pixels
realT ycen
x-coordinate of focal plane center, in pixels
wavefrontT centerFocal
Phase screen for tilting the pupil plane so that the focal plane image is centered.
wavefrontT centerPupil
Phase screen for un-tilting the pupil plane after propagating from a centered focal plane.
Member Typedef Documentation
template<typename _wavefrontT> typedef wavefrontT::Scalar mx::wfp::fraunhoferPropagator< _wavefrontT >::complexT
The complex data type.
Definition at line 44 of file fraunhoferPropagator.hpp.
template<typename _wavefrontT> typedef wavefrontT::Scalar::value_type mx::wfp::fraunhoferPropagator< _wavefrontT >::realT
The real data type.
Definition at line 47 of file fraunhoferPropagator.hpp.
template<typename _wavefrontT> typedef _wavefrontT mx::wfp::fraunhoferPropagator< _wavefrontT >::wavefrontT
The wavefront data type.
Definition at line 41 of file fraunhoferPropagator.hpp.
Constructor & Destructor Documentation
template<typename wavefrontT > mx::wfp::fraunhoferPropagator< wavefrontT >::fraunhoferPropagator ()
Constructor.
Definition at line 128 of file fraunhoferPropagator.hpp.
References mx::wfp::fraunhoferPropagator< _wavefrontT >::initialize().
template<typename wavefrontT > mx::wfp::fraunhoferPropagator< wavefrontT >::~fraunhoferPropagator ()
Destructor.
Definition at line 134 of file fraunhoferPropagator.hpp.
Member Function Documentation
template<typename wavefrontT > void mx::wfp::fraunhoferPropagator< wavefrontT >::initialize () protected
Initialize members.
Definition at line 119 of file fraunhoferPropagator.hpp.
References mx::wfp::fraunhoferPropagator< _wavefrontT >::wavefrontSizePixels, mx::wfp::fraunhoferPropagator< _wavefrontT >::xcen, and mx::wfp::fraunhoferPropagator< _wavefrontT >::ycen.
Referenced by mx::wfp::fraunhoferPropagator< _wavefrontT >::fraunhoferPropagator().
template<typename wavefrontT > void mx::wfp::fraunhoferPropagator< wavefrontT >::makeShiftPhase () protected
Calculate the complex tilt arrays for centering and normalizing the wavefronts.
Definition at line 191 of file fraunhoferPropagator.hpp.
References mx::wfp::fraunhoferPropagator< _wavefrontT >::centerFocal, mx::wfp::fraunhoferPropagator< _wavefrontT >::centerPupil, mx::wfp::fraunhoferPropagator< _wavefrontT >::wavefrontSizePixels, mx::wfp::fraunhoferPropagator< _wavefrontT >::xcen, and mx::wfp::fraunhoferPropagator< _wavefrontT >::ycen.
Referenced by mx::wfp::fraunhoferPropagator< _wavefrontT >::setWavefrontSizePixels().
template<typename wavefrontT > void mx::wfp::fraunhoferPropagator< wavefrontT >::propagateFocalToPupil (wavefrontT & complexPupil, wavefrontT & complexFocal)
Propagate the wavefront from Focal plane to Pupil plane.
After the fourier transform, the output pupil plane wavefront is de-tilted, restoring it to the state prior to calling propagatePupilToFocal
Parameters
[out] complexPupil the pupil plane wavefront. Must be pre-allocated to same size as complexFocal.
[in] complexFocal the focal plane wavefront.
Definition at line 160 of file fraunhoferPropagator.hpp.
References mx::wfp::fraunhoferPropagator< _wavefrontT >::centerPupil, and mx::wfp::fraunhoferPropagator< _wavefrontT >::setWavefrontSizePixels().
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::propagate(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::propagateNC().
template<typename wavefrontT > void mx::wfp::fraunhoferPropagator< wavefrontT >::propagatePupilToFocal (wavefrontT & complexFocal, wavefrontT & complexPupil)
Propagate the wavefront from the pupil plane to the focal plane.
The pupil plane wavefront (complexPupil) is multiplied by a tilt to place the image in the geometric center of the focal plane.
Parameters
[out] complexFocal the focal plane wavefront. Must be pre-allocated to same size as complexPupil.
[in] complexPupil the pupil plane wavefront. Modified due to application of centering tilt.
Definition at line 145 of file fraunhoferPropagator.hpp.
References mx::wfp::fraunhoferPropagator< _wavefrontT >::centerFocal, and mx::wfp::fraunhoferPropagator< _wavefrontT >::setWavefrontSizePixels().
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::propagate(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::propagateNC(), and mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix().
template<typename wavefrontT > void mx::wfp::fraunhoferPropagator< wavefrontT >::setWavefrontSizePixels (int wfsPix)
Set the size of the wavefront, in pixels.
Checks if the size changes, does nothing if no change. Otherwise, calls makeShiftPhase to pre-calculate the tilt arrays and plans the FFTs.
Parameters
[in] wfsPix the desired new size of the wavefront
Definition at line 173 of file fraunhoferPropagator.hpp.
References mx::wfp::fraunhoferPropagator< _wavefrontT >::centerFocal, mx::wfp::fraunhoferPropagator< _wavefrontT >::makeShiftPhase(), mx::wfp::fraunhoferPropagator< _wavefrontT >::wavefrontSizePixels, mx::wfp::fraunhoferPropagator< _wavefrontT >::xcen, and mx::wfp::fraunhoferPropagator< _wavefrontT >::ycen.
Referenced by mx::wfp::fraunhoferPropagator< _wavefrontT >::propagateFocalToPupil(), mx::wfp::fraunhoferPropagator< _wavefrontT >::propagatePupilToFocal(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::wfSz().
template<typename wavefrontT > void mx::wfp::fraunhoferPropagator< wavefrontT >::shiftPupil (wavefrontT & complexPupil)
Apply the shift to a pupil wavefront which will center the resultant focal plane image.
You must have allocated the shift screens first, by calling propagatePupilToFocal, propagateFocalToPupil, or setWavefrontSizePixels.
Parameters
[in,out] complexPupil the complex pupil plane wavefront to shift
Definition at line 139 of file fraunhoferPropagator.hpp.
References mx::wfp::fraunhoferPropagator< _wavefrontT >::centerFocal.
Member Data Documentation
template<typename _wavefrontT> wavefrontT mx::wfp::fraunhoferPropagator< _wavefrontT >::centerFocal protected
Phase screen for tilting the pupil plane so that the focal plane image is centered.
Definition at line 58 of file fraunhoferPropagator.hpp.
Referenced by mx::wfp::fraunhoferPropagator< _wavefrontT >::makeShiftPhase(), mx::wfp::fraunhoferPropagator< _wavefrontT >::propagatePupilToFocal(), mx::wfp::fraunhoferPropagator< _wavefrontT >::setWavefrontSizePixels(), and mx::wfp::fraunhoferPropagator< _wavefrontT >::shiftPupil().
template<typename _wavefrontT> wavefrontT mx::wfp::fraunhoferPropagator< _wavefrontT >::centerPupil protected
Phase screen for un-tilting the pupil plane after propagating from a centered focal plane.
Definition at line 61 of file fraunhoferPropagator.hpp.
Referenced by mx::wfp::fraunhoferPropagator< _wavefrontT >::makeShiftPhase(), and mx::wfp::fraunhoferPropagator< _wavefrontT >::propagateFocalToPupil().
template<typename _wavefrontT> int mx::wfp::fraunhoferPropagator< _wavefrontT >::wavefrontSizePixels protected
The size of the wavefront in pixels.
Definition at line 52 of file fraunhoferPropagator.hpp.
Referenced by mx::wfp::fraunhoferPropagator< _wavefrontT >::initialize(), mx::wfp::fraunhoferPropagator< _wavefrontT >::makeShiftPhase(), and mx::wfp::fraunhoferPropagator< _wavefrontT >::setWavefrontSizePixels().
template<typename _wavefrontT> realT mx::wfp::fraunhoferPropagator< _wavefrontT >::xcen protected
x-coordinate of focal plane center, in pixels
Definition at line 54 of file fraunhoferPropagator.hpp.
Referenced by mx::wfp::fraunhoferPropagator< _wavefrontT >::initialize(), mx::wfp::fraunhoferPropagator< _wavefrontT >::makeShiftPhase(), and mx::wfp::fraunhoferPropagator< _wavefrontT >::setWavefrontSizePixels().
template<typename _wavefrontT> realT mx::wfp::fraunhoferPropagator< _wavefrontT >::ycen protected
x-coordinate of focal plane center, in pixels
Definition at line 55 of file fraunhoferPropagator.hpp.
Referenced by mx::wfp::fraunhoferPropagator< _wavefrontT >::initialize(), mx::wfp::fraunhoferPropagator< _wavefrontT >::makeShiftPhase(), and mx::wfp::fraunhoferPropagator< _wavefrontT >::setWavefrontSizePixels().
The documentation for this class was generated from the following file:
wfp/fraunhoferPropagator.hpp