mxlib: mx::math::fit::fitGaussian2D< fitterT > Class Template Reference
mx::math::fit::fitGaussian2D< fitterT > Class Template Reference
General Mathematics » Data Fitting » Peak Fitting » Gaussians
template<typename fitterT>
class mx::math::fit::fitGaussian2D< fitterT >
Class to manage fitting a 2D Gaussian to data via the levmarInterface.
In addition to the requirements on fitterT specified by levmarInterface this class also requires the following in fitterT
static const int nparams = 7; //where the number 7 is replaced by the number of parameters that fitterT expects to fit.
void paramNormalizer(realT *, int); //A function which converts from input parameters to fitting parameters.  May do nothing.
Template Parameters
fitterT a type meeting the above requirements.
Definition at line 54 of file fitGaussian.hpp.
#include <math/fit/fitGaussian.hpp>
Public Member Functions
void setGuess (realT G0, realT A, realT x0, realT y0, realT sigma)
Set the initial guess for a symmetric Gaussian.
void setGuess (realT G0, realT A, realT x0, realT y0, realT sigma_x, realT sigma_y, realT theta)
Set the initial guess for the general Gaussian.
void setArray (realT *data, int nx, int ny)
Set the data aray.
int fit ()
Do the fit.
realT G0 ()
Get the current value of G0, the constant.
realT A ()
Get the peak scaling.
realT x0 ()
Get the center x-coordinate.
realT y0 ()
Get the center y-coordinate.
realT sigma ()
Return the width parameter.
realT sigma_x ()
Return the width parameter on the long axis.
realT sigma_y ()
Return the width parameter on the short axis.
realT theta ()
Return the orientation of the long axis.
Public Member Functions inherited from mx::math::fit::levmarInterface< fitterT >
double get_deltaT ()
Get the elapsed time of the fit.
void dump_params ()
Dump the parameter vector to stdout.
void dump_report (bool dumpParams=true)
Dump a status report to stdout.
levmarInterface ()
Default constructor.
levmarInterface (realT *i_p, realT *i_x, int i_m, int i_n, void *i_adata)
Setup constructor.
~levmarInterface ()
Destructor.
void set_nparams (int i_m)
Set number of parameters, but don't allocate.
int get_nparams ()
Get the current number of parameters.
void allocate_params ()
Allocate parameters array based on previous call to set_nparams.
void allocate_params (int i_m)
Set number of parameters and allocate.
void point_params (realT *i_p)
Point the parameter pointer at an externally allocated array.
void point_params (realT *i_p, int i_m)
Point the parameter pointer at an externally allocated array.
void set_params (realT *i_p)
Copy parameters to the parameter array.
realT * get_params ()
Get current pointer array address.
void set_itmax (int i_itmax)
Set the maximum number of iterations.
int get_itmax ()
Get the maximum number of iterations.
void allocate_work ()
Allocate the work and covar matrices.
void set_opts (int n, realT val)
Set one of the minimization options to val.
void set_opts_default (int n=-1)
Set one or all of the minimization options to the default.
realT get_opts (int n)
Get the current value of an option.
int fit ()
Perform the fit.
realT get_initial_norm ()
Returns the L2-norm before minimization occurs.
realT get_final_norm ()
Returns the L2-norm at the end of the minimization.
int get_iterations ()
Get the number of iterations taken during the minimization.
int get_reason_code ()
Get a code specifying the reason minimization terminated.
std::string get_reason_string ()
Get the descriptive string describing the reason minimization terminated.
int get_fevals ()
Get the number of function evaluations during the minimization.
int get_jevals ()
Get the number of jacobian evaluations during the minimization.
int get_nlinsys ()
Get the number of linear system solutions during the minimization.
Additional Inherited Members
Public Attributes inherited from mx::math::fit::levmarInterface< fitterT >
realT * x
I: measurement vector. NULL implies a zero vector.
int n
I: measurement vector dimension.
realT opts [LM_OPTS_SZ]
Options passed to the minimization routines. See set_opts for details.
realT info [LM_INFO_SZ]
Information regarding the minimization.
double deltaT
Elapsed time of the fitting procedure.
realT * work
Working memory passed to the levmar routines.
int work_sz
The current size of the work array.
realT * covar
Covariance matrix corresponding to LS solution; mxm.
int covar_sz
The current size of the covar array.
bool getCovar
Controls whether the covar array is allocated.
void * adata
Pointer to possibly additional data, passed uninterpreted to func & jacf.
Protected Attributes inherited from mx::math::fit::levmarInterface< fitterT >
realT * p
Parameter array. On input is the initial estimates. On output has the estimated solution.
realT * init_p
Parameter array on input, saved for comparison.
int m
Parameter vector dimension (i.e. number of unknowns)
bool own_p
Flag indicating whether the p array is owned by this object (for de-allocation).
int itmax
Maximum number of iterations, default is 100.
Member Function Documentation
template<typename fitterT> realT mx::math::fit::fitGaussian2D< fitterT >::A () inline
Get the peak scaling.
Definition at line 163 of file fitGaussian.hpp.
Referenced by mx::math::fit::fitGaussian2D< realT >::setGuess().
template<typename fitterT> int mx::math::fit::fitGaussian2D< fitterT >::fit () inline
Do the fit.
Definition at line 142 of file fitGaussian.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::center().
template<typename fitterT> realT mx::math::fit::fitGaussian2D< fitterT >::G0 () inline
Get the current value of G0, the constant.
Returns
the current value of G0, which is p[0].
Definition at line 157 of file fitGaussian.hpp.
Referenced by mx::math::fit::fitGaussian2D< realT >::setGuess().
template<typename fitterT> void mx::math::fit::fitGaussian2D< fitterT >::setArray (realT * data, int nx, int ny) inline
Set the data aray.
Definition at line 128 of file fitGaussian.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::center().
template<typename fitterT> void mx::math::fit::fitGaussian2D< fitterT >::setGuess (realT G0, realT A, realT x0, realT y0, realT sigma) inline
Set the initial guess for a symmetric Gaussian.
Also works for the general case, setting the same width in both directions.
Parameters
[in] G0 the constant background level
[in] A the peak scaling
[in] x0 the center x-coordinate
[in] y0 the center y-coordinate
[in] sigma the width parameter
Definition at line 83 of file fitGaussian.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::center().
template<typename fitterT> void mx::math::fit::fitGaussian2D< fitterT >::setGuess (realT G0, realT A, realT x0, realT y0, realT sigma_x, realT sigma_y, realT theta) inline
Set the initial guess for the general Gaussian.
Parameters
[in] G0 the constant background level
[in] A the peak scaling
[in] x0 the center x-coordinate
[in] y0 the center y-coordinate
[in] sigma_x the width parameter in the rotated x-direction (the long axis)
[in] sigma_y the width parameter in the rotated y-direction
[in] theta the angle of the long axis (always sigma_x)
Definition at line 106 of file fitGaussian.hpp.
template<typename fitterT> realT mx::math::fit::fitGaussian2D< fitterT >::sigma () inline
Return the width parameter.
As described for the symmetric Gaussian.
For the general Gaussian, this returns \(\sigma = \sqrt{ \sigma_x^2 + \sigma_y^2} \).
Definition at line 185 of file fitGaussian.hpp.
Referenced by mx::math::fit::fitGaussian2D< realT >::setGuess().
template<typename fitterT> realT mx::math::fit::fitGaussian2D< fitterT >::sigma_x () inline
Return the width parameter on the long axis.
Definition at line 198 of file fitGaussian.hpp.
Referenced by mx::math::fit::gaussian2D_sym_fitter< _realT >::paramNormalizer(), mx::improc::imCenterCircleSym< realT >::results(), and mx::math::fit::fitGaussian2D< realT >::setGuess().
template<typename fitterT> realT mx::math::fit::fitGaussian2D< fitterT >::sigma_y () inline
Return the width parameter on the short axis.
Definition at line 205 of file fitGaussian.hpp.
Referenced by mx::math::fit::gaussian2D_sym_fitter< _realT >::paramNormalizer(), mx::improc::imCenterCircleSym< realT >::results(), and mx::math::fit::fitGaussian2D< realT >::setGuess().
template<typename fitterT> realT mx::math::fit::fitGaussian2D< fitterT >::theta () inline
Return the orientation of the long axis.
Definition at line 212 of file fitGaussian.hpp.
Referenced by mx::math::fit::gaussian2D_sym_fitter< _realT >::paramNormalizer(), and mx::math::fit::fitGaussian2D< realT >::setGuess().
template<typename fitterT> realT mx::math::fit::fitGaussian2D< fitterT >::x0 () inline
Get the center x-coordinate.
Definition at line 169 of file fitGaussian.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::center(), mx::improc::imCenterCircleSym< realT >::results(), and mx::math::fit::fitGaussian2D< realT >::setGuess().
template<typename fitterT> realT mx::math::fit::fitGaussian2D< fitterT >::y0 () inline
Get the center y-coordinate.
Definition at line 175 of file fitGaussian.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::center(), mx::improc::imCenterCircleSym< realT >::results(), and mx::math::fit::fitGaussian2D< realT >::setGuess().
The documentation for this class was generated from the following file:
math/fit/fitGaussian.hpp