mxlib: mx::application Class Reference
mx::application Class Reference
General Utilities » An Application Framework
A class for managing application configuration and execution.
Derived classes should implement at a minimum
virtual void setupConfig();
virtual void loadConfig();
virtual int execute();
These are executed in the order shown by the call to main().
This class uses a cascaded configuration system. The application configuration is built up from the following sources, in increasing order of precedence:
A global configuration file
A user configuration file
A local configuration file
A configuration file specified on the command line
The command line
At each step in the above order, values read from that configuration source override any previous settings. So the command line has the highest precedence.
The configuration files are ini-style, with sections. That is
key1=value1
key2=value2
[section1]
key3=value3
key4=value4,value4.1, value4.2, value4.3
[section2]
key3=value5
key3=value5.1
key4=value6_over_
     multiple_lines
such that section1.key3 is distinct from section2.key3 (they must have different config-target names though). Additional entries within one file with the same section and key are appended with a newline to the previous entry. So the value of section2.key3 is "value5\\nvalue5.1". Multi-line values are handled such that in the above example the result is key4=value6_over_multiple_lines. Vectors are input as in section1.key4.
Todo:
add handling of +=
The command line parser handles both short-opt ("-h -vArg -n Arg") and long-opt ("--help --value=Arg --number=Arg") styles.
Note
After loadConfig() but before execute(), the containers in config are de-allocated , so they can not be used inside execute.
Definition at line 65 of file application.hpp.
#include <app/application.hpp>
Public Member Functions
int main (int argc, char **argv)
The application main function.
void setConfigPathGlobal (const std::string &s)
Set the global configuration path.
void setConfigPathUser (const std::string &s)
Set the user configuration path.
void setConfigPathLocal (const std::string &s)
Set the local configuration path.
Protected Member Functions
Required Overrides
These methods should be implemented in derived classes to use an mx::application in its default behavior.
virtual void setupConfig ()
In derived classes this is where the config targets are added to config.
virtual void loadConfig ()
Override this function to extract the configured values and set up the application.
virtual int execute ()
This function is where the derived class should do its work.
Optional Overrides
These methods do not need to be implemented in derived classes unless it is desired to change behavior.
virtual void setup (int argc, char **argv)
Sets up the application by executing the configuration steps.
virtual void setDefaults ()
Set the default search paths for config files.
virtual void setupStandardConfig ()
Set up the help and command-line config options in a standard way.
virtual void loadStandardConfig ()
Loads the values of "help" and "config".
virtual void loadStandardHelp ()
Loads the value of "help" into doHelp.
virtual void optionHelp (configTarget &tgt, textTable &tt)
Format a configTarget for the help message.
virtual void help ()
Print a formatted help message, based on the config target inputs.
Protected Attributes
std::string invokedName
The name used to invoke this application.
std::string configPathGlobal
The path to the gobal configuration file.
std::string configPathUser
The path to the user's configuration file.
std::string configPathLocal
The path to a local configuration file.
std::string configPathCL
The path to a configuration file specified on the command line.
appConfigurator config
The structure used for parsing and storing the configuration.
bool doHelp
Flag to control whether the help message is printed or not.
int helpWidth
The total text width available for the help message.
Member Function Documentation
int mx::application::execute () inline protected virtual
This function is where the derived class should do its work.
Definition at line 244 of file application.hpp.
Referenced by main().
void mx::application::help () inline protected virtual
Print a formatted help message, based on the config target inputs.
Definition at line 385 of file application.hpp.
References mx::appConfigurator::clOnlyTargets, mx::textTable::colSep, mx::textTable::colWidths, config, helpWidth, invokedName, mx::textTable::lineStart, optionHelp(), mx::textTable::outPut(), mx::textTable::rows, mx::textTable::rowSep, and mx::appConfigurator::targets.
Referenced by main().
void mx::application::loadConfig () inline protected virtual
Override this function to extract the configured values and set up the application.
Definition at line 238 of file application.hpp.
Referenced by setup().
void mx::application::loadStandardConfig () inline protected virtual
Loads the values of "help" and "config".
Override this function if you do not want to use these, or have different behavior. See also setupStandardConfig().
Definition at line 330 of file application.hpp.
References config, and configPathCL.
Referenced by setup().
void mx::application::loadStandardHelp () inline protected virtual
Loads the value of "help" into doHelp.
Override this function if you do not want to use this, or have different behavior. See also setupStandardConfig().
Definition at line 336 of file application.hpp.
References config, and doHelp.
Referenced by setup().
int mx::application::main (int argc, char ** argv) inline
The application main function.
Call this from the true main function, passing the command line arguments to be processed. This calls setup(), then checks if the doHelp flag was set. If so, it calls help() and returns. If doHelp is not set, it then clears the config structure, and then calls execute().
Returns
1 if help is executed.
-1 on error.
the value of execute() otherwise.
Parameters
[in] argc standard command line result specifying number of argumetns in argv
[in] argv standard command line result containing the arguments.
Definition at line 196 of file application.hpp.
References mx::appConfigurator::clear(), config, doHelp, execute(), help(), and setup().
void mx::application::optionHelp (configTarget & tgt, textTable & tt) inline protected virtual
Format a configTarget for the help message.
Parameters
[in] tgt The Target
[out] tt the textTable being populated
Definition at line 342 of file application.hpp.
References mx::textTable::addCell(), mx::configTarget::helpExplanation, mx::configTarget::helpType, mx::configTarget::keyword, mx::configTarget::longOpt, mx::configTarget::orderAdded, mx::configTarget::section, and mx::configTarget::shortOpt.
Referenced by help().
void mx::application::setConfigPathGlobal (const std::string & s) inline
Set the global configuration path.
Parameters
[in] s the new path
Definition at line 214 of file application.hpp.
References configPathGlobal.
void mx::application::setConfigPathLocal (const std::string & s) inline
Set the local configuration path.
Parameters
[in] s the new path
Definition at line 226 of file application.hpp.
References configPathLocal.
void mx::application::setConfigPathUser (const std::string & s) inline
Set the user configuration path.
Parameters
[in] s the new path
Definition at line 220 of file application.hpp.
References configPathUser.
void mx::application::setDefaults () inline protected virtual
Set the default search paths for config files.
In general you should not need to redefine this.
Definition at line 280 of file application.hpp.
References configPathGlobal, configPathLocal, and configPathUser.
Referenced by setup().
void mx::application::setup (int argc, char ** argv) inline protected virtual
Sets up the application by executing the configuration steps.
This will not normally need to be implemented by derived clasess. Only do so if you intende to change the configuration process.
Parameters
[in] argc standard command line result specifying number of argumetns in argv
[in] argv standard command line result containing the arguments.
Definition at line 250 of file application.hpp.
References config, configPathCL, configPathGlobal, configPathLocal, configPathUser, invokedName, loadConfig(), loadStandardConfig(), loadStandardHelp(), mx::appConfigurator::parseCommandLine(), mx::appConfigurator::readConfig(), setDefaults(), setupConfig(), and setupStandardConfig().
Referenced by main().
void mx::application::setupConfig () inline protected virtual
In derived classes this is where the config targets are added to config.
Definition at line 232 of file application.hpp.
Referenced by setup().
void mx::application::setupStandardConfig () inline protected virtual
Set up the help and command-line config options in a standard way.
This adds "-h and --help", and "-c --config" as command line options. You can override this function to change this behavior, or simply clear config at the beginning of setupConfig(). If you do this, you should also override loadStandardConfig() and loadStandardHelp().
Definition at line 322 of file application.hpp.
References mx::appConfigurator::add(), and config.
Referenced by setup().
Member Data Documentation
appConfigurator mx::application::config protected
The structure used for parsing and storing the configuration.
Definition at line 77 of file application.hpp.
Referenced by help(), loadStandardConfig(), loadStandardHelp(), main(), setup(), and setupStandardConfig().
std::string mx::application::configPathCL protected
The path to a configuration file specified on the command line.
Definition at line 75 of file application.hpp.
Referenced by loadStandardConfig(), and setup().
std::string mx::application::configPathGlobal protected
The path to the gobal configuration file.
Definition at line 72 of file application.hpp.
Referenced by setConfigPathGlobal(), setDefaults(), and setup().
std::string mx::application::configPathLocal protected
The path to a local configuration file.
Definition at line 74 of file application.hpp.
Referenced by setConfigPathLocal(), setDefaults(), and setup().
std::string mx::application::configPathUser protected
The path to the user's configuration file.
Definition at line 73 of file application.hpp.
Referenced by setConfigPathUser(), setDefaults(), and setup().
bool mx::application::doHelp protected
Flag to control whether the help message is printed or not.
Definition at line 79 of file application.hpp.
Referenced by loadStandardHelp(), and main().
int mx::application::helpWidth protected
The total text width available for the help message.
Definition at line 81 of file application.hpp.
Referenced by help().
std::string mx::application::invokedName protected
The name used to invoke this application.
Definition at line 70 of file application.hpp.
Referenced by help(), and setup().
The documentation for this class was generated from the following file:
app/application.hpp