mxlib: ao/fourierBasis.hpp File Reference
fourierBasis.hpp File Reference
Wavefront Propagation » Adaptive Optics » Adaptive Optics Files
Generating a fourier basis.
Generating a fourier basis.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file fourierBasis.hpp.
#include <mx/fourierModes.hpp>
#include <mx/fitsFile.hpp>
Namespaces
mx
The mxlib c++ namespace.
Functions
template<typename realT >
void mx::AO::makeModfBasis (const std::string &basisName, int dim, int N)
Make the modified Fourier basis.
Function Documentation
template<typename realT > void mx::AO::makeModfBasis (const std::string & basisName, int dim, int N)
Make the modified Fourier basis.
Parameters
[in] basisName the name of the basis (not including the mx::AO path)
[in] dim the linear size of the maps, that is they will be dimxdim in size.
[in] N is the number of degrees of freedom. Number of modes will be (N+1)(N+1) - 1.
Template Parameters
realT the real numeric type for calculations
Definition at line 30 of file fourierBasis.hpp.
References mx::sigproc::makeFourierBasis_Rect(), mx::AO::makeModfBasis(), and MX_FOURIER_MODIFIED.
Referenced by mx::AO::makeModfBasis().