mxlib: ao/analysis/fourierCovariance.hpp File Reference
fourierCovariance.hpp File Reference
Wavefront Propagation » Adaptive Optics » Adaptive Optics Files
Calculation of the modal covariance in the Fourier basis.
Calculation of the modal covariance in the Fourier basis.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file fourierCovariance.hpp.
#include <boost/math/constants/constants.hpp>
#include <gsl/gsl_integration.h>
#include <gsl/gsl_errno.h>
#include "../../math/func/jinc.hpp"
#include "../../fourierModes.hpp"
#include "../../improc/fitsFile.hpp"
#include "../../improc/eigenCube.hpp"
#include "../../mxlib_uncomp_version.h"
#include "../../mxlib.h"
#include "../../ompLoopWatcher.hpp"
#include "../../timeUtils.hpp"
#include "../../math/eigenLapack.hpp"
#include "aoAtmosphere.hpp"
#include "aoPSDs.hpp"
#include "aoSystem.hpp"
#include "mxaoa_version.h"
Classes
struct mx::AO::analysis::fourierCovariance< realT, aosysT >
Structure to manage the Fourier mode covariance calculation.
struct mx::AO::analysis::fourierCovariance< realT, aosysT >
Structure to manage the Fourier mode covariance calculation.
Namespaces
mx
The mxlib c++ namespace.
Macros
#define WSZ 100000
The size of the gsl_integration workspaces.
Functions
template<typename realT , typename aosysT >
realT mx::AO::analysis::phiInt_basic (realT phi, void *params)
Worker for the azimuthal integral (in phi) for the basic Fourier mode covariance.
template<typename realT , typename aosysT >
realT mx::AO::analysis::phiInt_mod (realT phi, void *params)
Worker for the azimuthal integral (in phi) for the modified Fourier mode covariance.
template<typename realT , typename aosysT >
realT mx::AO::analysis::kInt (realT k, void *params)
Worker function for the radial integral in the covariance calculation.
template<typename realT , typename aosysT >
int mx::AO::analysis::fourierVarVec (const std::string &fname, int N, aosysT &aosys, realT absTol, realT relTol, bool modifed=true)
Calculate a vector of Fourier mode variances.
Macro Definition Documentation
#define WSZ 100000
The size of the gsl_integration workspaces.
Definition at line 48 of file fourierCovariance.hpp.
Referenced by mx::AO::analysis::fourierCovariance< realT, aosysT >::fourierCovariance(), mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::fourierTemporalPSD(), mx::AO::analysis::fourierCovariance< realT, aosysT >::getVariance(), mx::AO::analysis::kInt(), and mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::singleLayerPSD().
Function Documentation
template<typename realT , typename aosysT > int mx::AO::analysis::fourierVarVec (const std::string & fname, int N, aosysT & aosys, realT absTol, realT relTol, bool modifed = true)
Calculate a vector of Fourier mode variances.
Definition at line 342 of file fourierCovariance.hpp.
References mx::AO::analysis::fourierCovariance< realT, aosysT >::absTol, mx::AO::analysis::fourierCovariance< realT, aosysT >::aosys, mx::improc::fitsHeader::append(), mx::improc::eigenCube< dataT >::cube(), mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::D(), mx::improc::fitsHeaderGitStatus(), mx::AO::analysis::fourierVarVec(), mx::AO::analysis::fourierCovariance< realT, aosysT >::getVariance(), mx::improc::eigenCube< dataT >::image(), mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::incrementAndOutputStatus(), mx::astro::constants::k(), mx::AO::analysis::aoAtmosphere< _realT >::L_0(), mx::AO::analysis::fourierCovariance< realT, aosysT >::m, mx::sigproc::makeFourierBasis_Rect(), mx::sigproc::makeFourierModeFreqs_Rect(), mx::AO::analysis::fourierCovariance< realT, aosysT >::mnCon, mx::AO::analysis::fourierCovariance< realT, aosysT >::mp, MX_FOURIER_MODIFIED, mxlib_compiled_git_repo_modified(), mxlib_compiled_git_sha1(), mx::AO::analysis::fourierCovariance< realT, aosysT >::n, mx::AO::analysis::fourierCovariance< realT, aosysT >::np, mx::AO::analysis::fourierCovariance< realT, aosysT >::p, mx::AO::analysis::fourierCovariance< realT, aosysT >::pp, mx::AO::analysis::aoAtmosphere< _realT >::r_0(), mx::improc::fitsFile< dataT >::read(), mx::AO::analysis::fourierCovariance< realT, aosysT >::relTol, and mx::improc::fitsFile< dataT >::write().
Referenced by mx::AO::analysis::fourierVarVec().
template<typename realT , typename aosysT > realT mx::AO::analysis::kInt (realT k, void * params)
Worker function for the radial integral in the covariance calculation.
Parameters
k the spatial frequency at which to evaluate the integrand
params a pointer to a object of type fourierCovariance<realT, aosyT>
Template Parameters
realT a floating point type used for all calculations. As of Nov 2016 must be double due to gsl_integration.
aosysT the type of the AO system structure
Definition at line 218 of file fourierCovariance.hpp.
References mx::astro::constants::k(), mx::AO::analysis::fourierCovariance< realT, aosysT >::k, mx::AO::analysis::kInt(), mx::AO::analysis::fourierCovariance< realT, aosysT >::phi_w, mx::AO::analysis::fourierCovariance< realT, aosysT >::useBasic, and WSZ.
Referenced by mx::AO::analysis::kInt().
template<typename realT , typename aosysT > realT mx::AO::analysis::phiInt_mod (realT phi, void * params)
Worker for the azimuthal integral (in phi) for the modified Fourier mode covariance.
Parameters
phi the angle at which to evaluate the integrand
params a pointer to a object of type fourierCovariance<realT, aosyT>
Template Parameters
realT a floating point type used for all calculations
aosysT the type of the AO system structure
Definition at line 135 of file fourierCovariance.hpp.
References mx::AO::analysis::fourierCovariance< realT, aosysT >::aosys, mx::math::func::jinc(), mx::astro::constants::k(), mx::AO::analysis::fourierCovariance< realT, aosysT >::k, mx::AO::analysis::fourierCovariance< realT, aosysT >::m, mx::AO::analysis::fourierCovariance< realT, aosysT >::mnCon, mx::AO::analysis::fourierCovariance< realT, aosysT >::mp, mx::AO::analysis::fourierCovariance< realT, aosysT >::n, mx::AO::analysis::fourierCovariance< realT, aosysT >::np, mx::AO::analysis::fourierCovariance< realT, aosysT >::p, mx::AO::analysis::phiInt_mod(), and mx::AO::analysis::fourierCovariance< realT, aosysT >::pp.
Referenced by mx::AO::analysis::phiInt_mod().