mxlib: Image Padding
Image Padding
Image Processing
Functions for padding images.
Functions for padding images.
These functions pad an image by adding rows and columns, and filling in the new pixels with appropriate values. This can be a constant, or nearest neighbor. A version is also provided which expands an aribtrary 1/0 mask, which is useful when working with, say, circular regions of an image.
template<typename imOutT , typename imInT >
int mx::improc::padImage (imOutT &imOut, imInT &imIn, unsigned int padSz, typename imOutT::Scalar value)
Pad an image with a constant value.
template<typename imOutT , typename imInT >
int mx::improc::padImageRef (imOutT imOut, imInT imIn, unsigned int padSz, typename imOutT::Scalar value)
Pad an image with a constant value.
template<typename imOutT , typename imInT >
int mx::improc::padImage (imOutT &imOut, imInT &imIn, unsigned int padSz)
Pad an image by repeating the values in the edge rows and columns.
template<typename imOutT , typename imInT >
int mx::improc::padImage (imOutT &imOut, imInT &imIn, imInT &imMask, unsigned int padSz)
Pad an image by repeating the values at the edge of a 1/0 mask.
template<typename imOutT , typename imInT >
int mx::improc::cutPaddedImage (imOutT &imOut, const imInT &imIn, unsigned int padSz)
Cut down a padded image.
Function Documentation
template<typename imOutT , typename imInT > int mx::improc::cutPaddedImage (imOutT & imOut, const imInT & imIn, unsigned int padSz)
Cut down a padded image.
Parameters
imOut is resized, and on return contains the cut image.
inIn is the image to be cut.
padSz the size of the pad. The image will shrink by 2*padSz rows and columns.
Return values
0 on success
-1 on error
Template Parameters
imOutT is an Eigen-like array
imInT is an Eigen-like array
Definition at line 288 of file imagePads.hpp.
References MXE_INVALIDARG, and mxError.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake(), and mx::AO::orthogonalizeBasis().
template<typename imOutT , typename imInT > int mx::improc::padImage (imOutT & imOut, imInT & imIn, unsigned int padSz, typename imOutT::Scalar value)
Pad an image with a constant value.
Parameters
[out] imOut is resized, and on return contains the padded image.
[in] imIn the image to be padded.
[in] padSz the size of the pad to be added. The image will grow by 2*padSz rows and columns.
[in] value the value to use for padding.
Return values
0 on success
-1 on error
Template Parameters
imOutT is an Eigen-like array
imInT is an Eigen-like array
Definition at line 43 of file imagePads.hpp.
Referenced by mx::AO::applyPupil2Basis(), mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake(), mx::AO::orthogonalizeBasis(), mx::wfp::idealCoronagraph< _realT >::setPupil(), and mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix().
template<typename imOutT , typename imInT > int mx::improc::padImage (imOutT & imOut, imInT & imIn, unsigned int padSz)
Pad an image by repeating the values in the edge rows and columns.
Allocates imOut to hold 2*padSz more rows and columns, and copies imIn to the center. Then fills in the new pixels by copying the edge pixels outward.
Parameters
[out] imOut is resized, and on return contains the padded image.
[in] imIn the image to be padded.
[in] padSz the size of the pad to be added. The image will grow by 2*padSz rows and columns.
Return values
0 on success
-1 on error
Template Parameters
imOutT is an Eigen-like array
imInT is an Eigen-like array
Definition at line 104 of file imagePads.hpp.
template<typename imOutT , typename imInT > int mx::improc::padImage (imOutT & imOut, imInT & imIn, imInT & imMask, unsigned int padSz)
Pad an image by repeating the values at the edge of a 1/0 mask.
Allocates imOut to match imMask, and copies imIn to the center multiplied by the mask. Then fills in the new pixels by copying the edge pixels outward. For each pixel on the edge of the mask (touching at least one 1-valued pixel in the mask), the value is chosen as the value of the nearest pixel with a 1 in the mask. If the closest pixels are more than one equidistant pixels, their mean value is used.
Parameters
[out] imOut is resized to match imMask, and on return contains the padded image.
[in] imIn the image to be padded.
[in] imMask is the 1/0 mask.
[in] padSz the number of iterations of the padding loop.
Return values
0 on success
-1 on error
Template Parameters
imOutT is an Eigen-like array
imInT is an Eigen-like array
Definition at line 170 of file imagePads.hpp.
References MXE_INVALIDARG, and mxError.
template<typename imOutT , typename imInT > int mx::improc::padImageRef (imOutT imOut, imInT imIn, unsigned int padSz, typename imOutT::Scalar value)
Pad an image with a constant value.
This version can be used with Eigen reference types.
Parameters
[out] imOut is resized, and on return contains the padded image.
[in] imIn the image to be padded.
[in] padSz the size of the pad to be added. The image will grow by 2*padSz rows and columns.
[in] value the value to use for padding.
Return values
0 on success
-1 on error
Template Parameters
imOutT is an Eigen-like array reference
imInT is an Eigen-like array reference
Definition at line 73 of file imagePads.hpp.