mxlib: Astrodynamics
Astrodynamics
Astronomy
Algorithms for astrodynamic calculations.
Algorithms for astrodynamic calculations.
Modules
Orbital Mechanics
Calculations of orbits and related quantities.
Functions
int get_hrminsec_fm_day (int &Dy, int &hr, int &min, double &sec, double day)
Breaks down a decimal day into hours, minutes and decimal point seconds.
int get_GMST (double &GMST, int Yr, int Mo, int Dy, int hr, int min, double sec)
Returns Greenwich Mean Sidereal Time for a given UTC time.
int get_GMST (double &GMST, int Yr, int Mo, double day)
Returns Greenwich Mean Sidereal Time for a given UTC time.
int get_GAST (double &GAST, int Yr, int Mo, int Dy, int hr, int min, double sec)
Returns Greenwich Apparent Sidereal Time for a given UTC time.
int get_GAST (double &GAST, int Yr, int Mo, double day)
Returns Greenwich Mean Sidereal Time for a given UTC time.
int get_LMST (double &LMST, int Yr, int Mo, int Dy, int hr, int min, double sec, double lon)
Returns Local Mean Sidereal Time for a given UTC time and longitude.
int get_LMST (double &LMST, int Yr, int Mo, double day, double lon)
Returns Local Mean Sidereal Time for a given UTC time.
int get_LAST (double &LAST, int Yr, int Mo, int Dy, int hr, int min, double sec, double lon)
Returns Local Apparent Sidereal Time for a given UTC time and longitude.
int get_LAST (double &LAST, int Yr, int Mo, double day, double lon)
Returns Local Apparent Sidereal Time for a given UTC time.
void calc_AZ_EL (double *az, double *el, double ha, double dec, double lat)
Calculates the Azimuth and Elevation for a given Hour-Angle, Declination, and Latitude.
double get_ParAng_deg (double lat, double dec, double ha)
Calculate the Parallactic angle, with angles in degrees.
double get_ParAng_rad (double lat, double dec, double ha)
Calculate the Parallactic angle, with angles in radians.
int latlon_to_ECI (double &x, double &y, double &z, double lat, double lon, double alt, double lst)
Convert from latitude/longitude to Earth-centered inertial x-y-z coordinates.
Function Documentation
void calc_AZ_EL (double * az, double * el, double ha, double dec, double lat)
Calculates the Azimuth and Elevation for a given Hour-Angle, Declination, and Latitude.
References: J. Meeus "Astronomical Algorithms", 1991; V. Pisacane "Fundamentals of Space Systems", 2nd ed., 2005.
Parameters
az is filled in with the azimuth
el is filled in with the elevation
ha is the hour angle
dec is the declination
lat is the latitude
Definition at line 155 of file astrodyn.cpp.
References DPI.
int get_GAST (double & GAST, int Yr, int Mo, int Dy, int hr, int min, double sec)
Returns Greenwich Apparent Sidereal Time for a given UTC time.
Uses the SOFA 2006 GAST function, and a (for now) hardcoded value of dUT1
Parameters
GAST [output] GAST in hours
Yr [input] integer year
Mo [input] integer month (1-12)
Dy [input] integer day (1-31)
hr [input] integer hour (0-23)
min [input] integer minute (0-59)
sec [input] decimal second (0-59)
Return values
0 on success
Definition at line 58 of file astrodyn.cpp.
References DPI.
Referenced by get_GAST(), and get_LAST().
int get_GAST (double & GAST, int Yr, int Mo, double day)
Returns Greenwich Mean Sidereal Time for a given UTC time.
Uses the SOFA 2006 GMST function, and a (for now) hardcoded value of dUT1
Parameters
GAST [output] GAST in hours
Yr [input] integer year
Mo [input] integer month (1-12)
day [input] decimal day (1-31)
Return values
0 on sucess
Definition at line 80 of file astrodyn.cpp.
References get_GAST(), and get_hrminsec_fm_day().
int get_GMST (double & GMST, int Yr, int Mo, int Dy, int hr, int min, double sec)
Returns Greenwich Mean Sidereal Time for a given UTC time.
Uses the SOFA 2006 GMST function, and a (for now) hardcoded value of dUT1
Parameters
GMST [output] GMST in hours
Yr [input] integer year
Mo [input] integer month (1-12)
Dy [input] integer day (1-31)
hr [input] integer hour (0-23)
min [input] integer minute (0-59)
sec [input] decimal second (0-59)
Return values
0 on success
Definition at line 27 of file astrodyn.cpp.
References DPI.
Referenced by get_GMST(), and get_LMST().
int get_GMST (double & GMST, int Yr, int Mo, double day)
Returns Greenwich Mean Sidereal Time for a given UTC time.
Uses the SOFA 2006 GMST function, and a (for now) hardcoded value of dUT1
Parameters
GMST [output] GMST in hours
Yr [input] integer year
Mo [input] integer month (1-12)
day [input] decimal day (1-31)
Return values
0 on sucess
Definition at line 49 of file astrodyn.cpp.
References get_GMST(), and get_hrminsec_fm_day().
int get_hrminsec_fm_day (int & Dy, int & hr, int & min, double & sec, double day)
Breaks down a decimal day into hours, minutes and decimal point seconds.
Assumes 86400 seconds per day, ignoring leap seconds.
Parameters
Dy [output] is the resultant integer day
hr [output] is the resultant integer hr
min [output] is the resultant integer minute
sec [output] is the resultand integer second
day [input] is the decimal day to break down.
Return values
0 on success
-1 on failure.
Definition at line 16 of file astrodyn.cpp.
References mx::astro::constants::day().
Referenced by get_GAST(), get_GMST(), get_LAST(), and get_LMST().
int get_LAST (double & LAST, int Yr, int Mo, int Dy, int hr, int min, double sec, double lon)
Returns Local Apparent Sidereal Time for a given UTC time and longitude.
Uses the SOFA 2006 GAST function, and a (for now) hardcoded value of dUT1
Parameters
LAST [output] LAST in hours
Yr [input] integer year
Mo [input] integer month (1-12)
Dy [input] integer day (1-31)
hr [input] integer hour (0-23)
min [input] integer minute (0-59)
sec [input] decimal second (0-59)
lon [input] longitude in degrees, E+, W-
Return values
0 on success
Definition at line 131 of file astrodyn.cpp.
References get_GAST().
Referenced by get_LAST().
int get_LAST (double & LAST, int Yr, int Mo, double day, double lon)
Returns Local Apparent Sidereal Time for a given UTC time.
Uses the SOFA 2006 GMST function, and a (for now) hardcoded value of dUT1
Parameters
LAST [output] LAST in hours
Yr [input] integer year
Mo [input] integer month (1-12)
day [input] decimal day (1-31)
Return values
0 on sucess
Definition at line 146 of file astrodyn.cpp.
References get_hrminsec_fm_day(), and get_LAST().
int get_LMST (double & LMST, int Yr, int Mo, int Dy, int hr, int min, double sec, double lon)
Returns Local Mean Sidereal Time for a given UTC time and longitude.
Uses the SOFA 2006 GMST function, and a (for now) hardcoded value of dUT1
Parameters
LMST [output] LMST in hours
Yr [input] integer year
Mo [input] integer month (1-12)
Dy [input] integer day (1-31)
hr [input] integer hour (0-23)
min [input] integer minute (0-59)
sec [input] decimal second (0-59)
lon [input] longitude in degrees, E+, W-
Return values
0 on success
Definition at line 108 of file astrodyn.cpp.
References get_GMST().
Referenced by get_LMST().
int get_LMST (double & LMST, int Yr, int Mo, double day, double lon)
Returns Local Mean Sidereal Time for a given UTC time.
Uses the SOFA 2006 GMST function, and a (for now) hardcoded value of dUT1
Parameters
LMST [output] LMST in hours
Yr [input] integer year
Mo [input] integer month (1-12)
day [input] decimal day (1-31)
Return values
0 on sucess
Definition at line 122 of file astrodyn.cpp.
References get_hrminsec_fm_day(), and get_LMST().
double get_ParAng_deg (double lat, double dec, double ha)
Calculate the Parallactic angle, with angles in degrees.
Parameters
lat is the observer latitude
dec is the object declination
ha is the hour angle, in degrees, positive to the east
Definition at line 203 of file astrodyn.cpp.
References mx::math::dtor(), and mx::math::rtod().
double get_ParAng_rad (double lat, double dec, double ha)
Calculate the Parallactic angle, with angles in radians.
Parameters
lat is the observer latitude
dec is the object declination
ha is the hour angle, in radians, positive to the east
Definition at line 211 of file astrodyn.cpp.
int latlon_to_ECI (double & x, double & y, double & z, double lat, double lon, double alt, double lst)
Convert from latitude/longitude to Earth-centered inertial x-y-z coordinates.
Parameters
x [output] x coordinate (meters)
y [output] y coordinate (meters)
z [output] z coordinate (meters)
lat [input] the latitude (radians)
lon [input] the longitude (radians)
alt [input] the altitude of RAD_EARTH (meters)
lst [input] the local sidereal time (radians)
Definition at line 217 of file astrodyn.cpp.