mxlib: Input/Output Utilities
Input/Output Utilities
General Utilities
Various input/output utilities.
Various input/output utilities.
Modules
binVector Binary File Format
A simple binary file format for storing vectors of data on disk.
Files
file readColumns.hpp
A utility to read in columns from a text file.
Functions
template<char space = ' ', bool flush = true, char eol = '\n', typename valT , typename... valTs>
void mx::pout (valT value, const valTs &...values)
A simple formatted output function.
template<char delim = ' ', char comment = '#', char eol = '\n', typename... arrTs>
int mx::readColumns (const std::string &fname, arrTs &...arrays)
Read in columns from a text file.
Function Documentation
template<char space = ' ', bool flush = true, char eol = '\n', typename valT , typename... valTs> void mx::pout (valT value, const valTs &... values)
A simple formatted output function.
This function writes its arguments, of any type and of any number, to stdout. By default, the arguments are separated by a space, the new line '\n' is written at the end, and the std::cout stream is flushed. These behaviors can be altered via template parameters.
Example:
std::string s="output:";
double d=2.567;
int i=3;
pout(s,d,i);
Note that the types of the values do not need to be specified as templated arguments. When run, this code results in
* $output: 2.567 3
* $
*
The behavior can be changed with template arguments like
pout<'\t', false, 0>(s,d,i);
which would use the tab instead of space, and neither flush nor print a newline at the end.
Template Parameters
space is the character to place between the values, by default this is space.
flush controls whether std::cout.flush() is called, by default it is true.
eol is the character to print at end of line, by default it is '\n'.
valT a type which can be output by std::cout
valTs a variadic list of additional types which can be output by std::cout
Parameters
[in] value a value to print.
[in] values a variadic list of additional values. Any number of values can be specified, with any type hangled by std::cout.
Definition at line 61 of file pout.hpp.
template<char delim = ' ', char comment = '#', char eol = '\n', typename... arrTs> int mx::readColumns (const std::string & fname, arrTs &... arrays)
Read in columns from a text file.
This function opens a file containing data formatted in columns and reads in the data row by row. The data are stored in std::vectors, which should not be pre-allocated (though they could be reserve()-ed).
Example:
std::vector<int> i1;
std::vector<float> f1;
std::vector<double> d1;
readColumns("data_file.txt", i1, f1, d1);
Note that the types of the vectors do not need to be specified as template arguments.
The format of the file can be specified with template arguments like
readColumns<',', ';', '\r'>("data_file.csv", i1, f1, d1);
which sets the delimmiter to comma, the comment character to ;, and the end-of-line to \r.
Template Parameters
delim is the character separating columns, by default this is space.
comment is the character starting a comment. by default this is #
eol is the end of line character. by default this is
arrTs a variadic list of array types. this is not specified by the user.
Parameters
[in] fname is the file name to read from
[out] arrays a variadic list of std::vectors. Any number with mixed value_type can be specified. Neither allocated nor cleared, so repeated calls will append data.
Definition at line 108 of file readColumns.hpp.
References MXE_FILECERR, MXE_FILEOERR, MXE_FILERERR, mxError, and mxPError.
Referenced by mx::astrofilt(), mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake(), mx::improc::HCIobservation< _realT >::loadFileList(), mx::improc::HCIobservation< _realT >::readWeights(), and mx::improc::HCIobservation< _realT >::threshold().