mxlib: Error Handling
Error Handling
How mxlib handles errors.
How mxlib handles errors.
Classes
class mxException
The mxlib exception class.
Modules
Error Handling Macros
Macros controlling how mxlib reports errors.
Error Handling Files
Source files for error handling.
mxlib Error Codes
Functions
std::string mx::MXE_CodeToName (int ec, std::string &message)
Return the macro name and a message for an mxlib error code.
std::string mx::errno_CodeToName (int ec, std::string &message)
Return the macro name and a message for a standard errno code.
std::string mx::error_report (const std::string &source, const int &code, const std::string &file, const int &line, const std::string &expl="")
Construct a rich error report given an mxlib error code.
std::string mx::errno_report (const std::string &source, int ec, const std::string &file, const int &line, const std::string &expl="")
Construct a rich error report given a standard errno error code.
Function Documentation
std::string mx::errno_CodeToName (int ec, std::string & message)
Return the macro name and a message for a standard errno code.
Parameters
[in] ec is the error code
[out] message is the human friendly message retrieved using std::strerror
Returns
the name of the macro corresponding to the code.
Definition at line 286 of file mxError.hpp.
Referenced by mx::errno_report().
std::string mx::errno_report (const std::string & source, int ec, const std::string & file, const int & line, const std::string & expl = "")
Construct a rich error report given a standard errno error code.
Parameters
[in] source is intended to identify the component (i.e. the class name)
[in] code is an errno erro code
[in] file should be passed the FILE macro
[in] line should be passed the LINE macro
[in] expl [optional] if more information can be provided, use this to inform the user.
Returns
the formatted error report.
Definition at line 667 of file mxError.hpp.
References mx::errno_CodeToName().
std::string mx::error_report (const std::string & source, const int & code, const std::string & file, const int & line, const std::string & expl = "")
Construct a rich error report given an mxlib error code.
Parameters
[in] source is intended to identify the mxlib component (i.e. the class name)
[in] code is an MXE_* error code
[in] file should be passed the FILE macro
[in] line should be passed the LINE macro
[in] expl [optional] if more information can be provided, use this to inform the user.
Returns
the formatted error report.
Definition at line 629 of file mxError.hpp.
References mx::MXE_CodeToName().
std::string mx::MXE_CodeToName (int ec, std::string & message)
Return the macro name and a message for an mxlib error code.
Parameters
[in] ec is the error code
[out] message is the human friendly message
Returns
the name of the macro corresponding to the error code.
Definition at line 218 of file mxError.hpp.
References MXE_ALLOCERR, MXE_FILECERR, MXE_FILENOTFOUND, MXE_FILEOERR, MXE_FILERERR, MXE_FILEWERR, MXE_FREEERR, MXE_GNUPLOTERR, MXE_INVALIDARG, MXE_LAPACKERR, MXE_NOTFOUND, MXE_NOTIMPL, MXE_PARAMNOTSET, MXE_PROCERR, MXE_SIZEERR, and MXE_TIMEOUT.
Referenced by mx::error_report().