mxlib: Image Filters
Image Filters
Image Processing | Signal Processing
Functions for filtering images.
Functions for filtering images.
Modules
Image Filter Kernels
Kernels to use in image filtering functions.
template<typename imageOutT , typename imageInT , typename kernelT >
void mx::improc::filterImage (imageOutT &fim, imageInT im, kernelT kernel, int maxr=0)
Filter an image with a kernel.
template<typename radprofT , typename eigenimT >
void mx::improc::radprofim (radprofT &radprof, eigenimT &im, radprofT &rad, bool subtract=false)
Form a radial profile image, and optionally subtract it from the input.
template<typename radprofT , typename eigenimT >
void mx::improc::radprofim (radprofT &radprof, eigenimT &im, bool subtract=false)
Form a radial profile image, and optionally subtract it from the input.
template<typename eigenimT >
void mx::improc::stddevImage (eigenimT &stdIm, eigenimT &im, eigenimT &rad, eigenimT &mask, typename eigenimT::Scalar minRad, typename eigenimT::Scalar maxRad, bool divide=false)
Form a standard deviation image, and optionally divide the input by it.
template<typename eigenimT >
void mx::improc::stddevImage (eigenimT &stdIm, eigenimT &im, eigenimT &mask, typename eigenimT::Scalar minRad, typename eigenimT::Scalar maxRad, bool divide=false)
Form a standard deviation image, and optionally divide the input by it.
template<typename eigencubeT , typename eigenimT >
void mx::improc::stddevImageCube (eigencubeT &stdImc, eigencubeT &imc, eigenimT &mask, typename eigenimT::Scalar minRad, typename eigenimT::Scalar maxRad, bool divide=false)
Form a standard deviation image for each imamge in a cube, and optionally divide the input by it.
Function Documentation
template<typename imageOutT , typename imageInT , typename kernelT > void mx::improc::filterImage (imageOutT & fim, imageInT im, kernelT kernel, int maxr = 0)
Filter an image with a kernel.
Applies the kernel to each pixel in the image, storing the filtered result in the output image. The kernel-type (kernelT) must have the following interface:
template<typename _arrayT, size_t kernW=4>
struct filterKernel
{
    typedef _arrayT arrayT;
    typedef typename _arrayT::Scalar arithT;
    filterKernel()
    {
       //constructor
    }
    //The setKernel function is called for each pixel.
    void setKernel(arithT x, arithT y, arrayT & kernel)
    {
       //This must resize and populate the passed in kernel array each time
       //so that it is re-entrant.
       //Note: On output kernel array should be normalized so that sum() = 1.0
       //Note: the width and height of the kernel array should always be odd
    }
};
Parameters
[out] fim will be allocated with resize, and on output contains the filtered image
[in] im is the image to be filtered
[in] kernel a fully configured obect of type kernelT
[in] maxr is the maximum radius from the image center to apply the kernel. pixels outside this radius are set to 0.
Template Parameters
imageOutT the type of the output image (must have an Eigen like interface)
imageInT the type of the input image (must have an Eigen like interface)
kernelT is the kernel type (see above)
Definition at line 193 of file imageFilters.hpp.
Referenced by mx::AO::applyPupil2Basis(), mx::improc::imCenterCircleSym< realT >::center(), mx::AO::orthogonalizeBasis(), and mx::improc::HCIobservation< _realT >::preProcess().
template<typename radprofT , typename eigenimT > void mx::improc::radprofim (radprofT & radprof, eigenimT & im, radprofT & rad, bool subtract = false)
Form a radial profile image, and optionally subtract it from the input.
The radial profile is calculated using linear interpolation on a 1 pixel grid
Parameters
[out] radprof is the radial profile image. This will be resized.
[in] im is the image to form the profile of.
[in] rad is an array of radius values
[in] subtract if true, then on ouput im will have had its radial profile subtracted.
Template Parameters
radprofT the eigen array type of the output
eigenimT the eigen array type of the input
Definition at line 312 of file imageFilters.hpp.
Referenced by mx::improc::HCIobservation< _realT >::preProcess().
template<typename radprofT , typename eigenimT > void mx::improc::radprofim (radprofT & radprof, eigenimT & im, bool subtract = false)
Form a radial profile image, and optionally subtract it from the input.
The radial profile is calculated using linear interpolation on a 1 pixel grid. This version calculates a centered radius image.
Parameters
[out] radprof is the radial profile image. This will be resized.
[in] im is the image to form the profile of.
[in] subtract if true, then on ouput im will have had its radial profile subtracted.
Template Parameters
radprofT the eigen array type of the output
eigenimT the eigen array type of the input
Definition at line 394 of file imageFilters.hpp.
References mx::improc::radiusImage().
template<typename eigenimT > void mx::improc::stddevImage (eigenimT & stdIm, eigenimT & im, eigenimT & rad, eigenimT & mask, typename eigenimT::Scalar minRad, typename eigenimT::Scalar maxRad, bool divide = false)
Form a standard deviation image, and optionally divide the input by it.
The standard deviation profile is calculated using linear interpolation on a 1 pixel grid
Parameters
[out] stdIm is the standard deviation image. This will be resized.
[in] im is the image to form the standard deviation profile of.
[in] rad is an array of radius values
[in] mask is an array which is a 1/0 mask. 0 pixels are excluded from the std-dev calculations.
[in] minRad is the minimum radius to analyze
[in] maxRad is the maximum radius to analyze
[in] divide if true, the input image is divided by the std-def profile
Template Parameters
eigenimT the eigen array type of the output and non-reference images
Definition at line 426 of file imageFilters.hpp.
References mx::vectorVariance().
template<typename eigenimT > void mx::improc::stddevImage (eigenimT & stdIm, eigenimT & im, eigenimT & mask, typename eigenimT::Scalar minRad, typename eigenimT::Scalar maxRad, bool divide = false)
Form a standard deviation image, and optionally divide the input by it.
The standard deviation profile is calculated using linear interpolation on a 1 pixel grid
Parameters
[out] stdIm is the standard deviation image. This will be resized.
[in] im is the image to form the standard deviation profile of.
[in] mask is an array which is a 1/0 mask. 0 pixels are excluded from the std-dev calculations.
[in] minRad is the minimum radius to analyze
[in] maxRad is the maximum radius to analyze
[in] divide if true, the input image is divided by the std-def profile
Template Parameters
eigenimT the eigen array type of the output and non-reference images
Definition at line 524 of file imageFilters.hpp.
References mx::improc::radiusImage().
Referenced by mx::improc::stddevImageCube().
template<typename eigencubeT , typename eigenimT > void mx::improc::stddevImageCube (eigencubeT & stdImc, eigencubeT & imc, eigenimT & mask, typename eigenimT::Scalar minRad, typename eigenimT::Scalar maxRad, bool divide = false)
Form a standard deviation image for each imamge in a cube, and optionally divide the input by it.
The standard deviation profile is calculated using linear interpolation on a 1 pixel grid
Parameters
[out] stdImc is the standard deviation image cube. This will be resized.
[in] imc is the image cube to form the standard deviation profile of.
[in] mask is an array which is a 1/0 mask. 0 pixels are excluded from the std-dev calculations.
[in] minRad is the minimum radius to analyze
[in] maxRad is the maximum radius to analyze
[in] divide if true, the input image is divided by the std-def profile
Template Parameters
eigencubeT is the eigen cube type of the input and output cubes
eigenimT the eigen array type of the output and non-reference images
Definition at line 559 of file imageFilters.hpp.
References mx::improc::radiusImage(), and mx::improc::stddevImage().