mxlib: File System Utilities
File System Utilities
General Utilities
Various file system utilities.
Various file system utilities.
Files
file fileUtils.hpp
Declarations of utilities for working with files.
Functions
std::vector< std::string > mx::getFileNames (const std::string &directory, const std::string &prefix, const std::string &substr, const std::string &extension)
Get a list of file names from the specified directory, specifying a prefix, a substring to match, and an extension.
std::vector< std::string > mx::getFileNames (const std::string &directory, const std::string &extension)
Get a list of file names from the specified directory, specifying the extension.
std::vector< std::string > mx::getFileNames (const std::string &directory)
Get a list of file names from the specified directory.
std::string mx::fileNamePrependAppend (const std::string &fname, const std::string &prepend, const std::string &append)
Prepend and/or append strings to a file name, leaving the directory and extension unaltered.
std::string mx::fileNameAppend (const std::string &fname, const std::string &append)
Append a string to a file name, leaving the directory and extension unaltered.
std::string mx::fileNamePrepend (const std::string &fname, const std::string &prepend)
Prepend strings to a file name, leaving the directory and extension unaltered.
template<int ndigit = 4>
std::string mx::getSequentialFilename (const std::string &basename, const std::string &extension="", const int startat=0)
Get the next file in a numbered sequence.
template<int ndigit = 4>
std::string mx::getSequentialFilename (const std::string &basename, const int startat)
Get the next file in a numbered sequence.
Function Documentation
std::string mx::fileNameAppend (const std::string & fname, const std::string & append) inline
Append a string to a file name, leaving the directory and extension unaltered.
Parameters
fname the original file name, possibly including a directory and extension
append is the string to insert at the end of the file name, before the extension
Returns
the new file name
Definition at line 169 of file fileUtils.hpp.
References mx::fileNamePrependAppend().
std::string mx::fileNamePrepend (const std::string & fname, const std::string & prepend) inline
Prepend strings to a file name, leaving the directory and extension unaltered.
Parameters
fname the original file name, possibly including a directory and extension
prepend is the string to insert at the beginning of the file name after the path
Returns
the new file name
Definition at line 182 of file fileUtils.hpp.
References mx::fileNamePrependAppend().
std::string mx::fileNamePrependAppend (const std::string & fname, const std::string & prepend, const std::string & append) inline
Prepend and/or append strings to a file name, leaving the directory and extension unaltered.
Returns
the new file name
Parameters
[in] fname the original file name, possibly including a directory and extension
[in] prepend is the string to insert at the beginning of the file name after the path
[in] append is the string to insert at the end of the file name, before the extension
Definition at line 143 of file fileUtils.hpp.
Referenced by mx::fileNameAppend(), and mx::fileNamePrepend().
std::vector<std::string> mx::getFileNames (const std::string & directory, const std::string & prefix, const std::string & substr, const std::string & extension) inline
Get a list of file names from the specified directory, specifying a prefix, a substring to match, and an extension.
Returns
a std::vector<std::string> which contains the matching file names.
Parameters
[in] directory the path to the directory to search.
[in] prefix the file name prefix (the beginning characters of the file name) to search for, if "" then not used.
[in] substr a substring of the filename to earch for, if "" then not used.
[in] extension the file name extension to search for, if "" then not used. Note that this must include the ".", as in in ".ext".
Definition at line 38 of file fileUtils.hpp.
Referenced by mx::improc::HCIobservation< _realT >::loadFileList().
std::vector<std::string> mx::getFileNames (const std::string & directory, const std::string & extension) inline
Get a list of file names from the specified directory, specifying the extension.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
a std::vector<std::string> which contains the matching file names.
Parameters
[in] directory the path to the directory to search.
[in] extension the file name extension to search for, if "" then not used. Note that this must include the ".", as in in ".ext".
Definition at line 119 of file fileUtils.hpp.
References mx::getFileNames().
std::vector<std::string> mx::getFileNames (const std::string & directory) inline
Get a list of file names from the specified directory.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
a std::vector<std::string> which contains the matching file names.
Parameters
[in] directory the path to the directory to search.
Definition at line 132 of file fileUtils.hpp.
Referenced by mx::getFileNames().
template<int ndigit = 4> std::string mx::getSequentialFilename (const std::string & basename, const std::string & extension = "", const int startat = 0)
Get the next file in a numbered sequence.
Searches for files in the path designated by basename of the form basenameXXXXextension where the number of digits in XXXX is set by the ndigit template parameter.
Parameters
[in] basename path and initial name of the file
[in] extension [optional] extension to append after the number. Default is empty.
[in] startat [optional] number to start the search from. Default is 0.
Return values
std::string containing the next filename.
Template Parameters
ndigit [optional] number of digits in string representation of the number. Default is 4.
Definition at line 200 of file fileUtils.hpp.
Referenced by mx::improc::HCIobservation< _realT >::writeFinim().
template<int ndigit = 4> std::string mx::getSequentialFilename (const std::string & basename, const int startat)
Get the next file in a numbered sequence.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Searches for files in the path designated by basename of the form basenameXXXX where the number of digits in XXXX is set by the ndigit template parameter.
Parameters
[in] basename path and initial name of the file
[in] startat number to start the search from.
Return values
std::string containing the next filename.
Template Parameters
ndigit [optional] number of digits in string representation of the number. Default is 4.
Definition at line 249 of file fileUtils.hpp.