mxlib: The Zernike Basis
The Zernike Basis
Wavefront Propagation
int mx::sigproc::noll_nm (int &n, int &m, int j)
Get the Zernike coefficients n,m corrresponding the Noll index j.
template<typename realT >
int mx::sigproc::zernikeRCoeffs (std::vector< realT > &c, int n, int m)
Calculate the coefficients of a Zernike radial polynomial.
template<typename realT >
realT mx::sigproc::zernikeR (realT rho, int n, int m, std::vector< realT > &c)
Calculate the value of a Zernike radial polynomial at a given separation.
template<typename realT >
realT mx::sigproc::zernikeR (realT rho, int n, int m)
Calculate the value of a Zernike radial polynomial at a given separation.
template<typename realT >
realT mx::sigproc::zernike (realT rho, realT phi, int n, int m, std::vector< realT > &c)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
template<typename realT >
realT mx::sigproc::zernike (realT rho, realT phi, int n, int m)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
template<typename realT >
realT mx::sigproc::zernike (realT rho, realT phi, int j)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
template<typename arrayT , int overscan = 2>
int mx::sigproc::zernike (arrayT &arr, int n, int m, typename arrayT::Scalar xcen, typename arrayT::Scalar ycen, typename arrayT::Scalar rad=-1)
Fill in an Eigen-like array with a Zernike polynomial.
template<typename arrayT >
int mx::sigproc::zernike (arrayT &arr, int j, typename arrayT::Scalar xcen, typename arrayT::Scalar ycen, typename arrayT::Scalar rad=-1)
Fill in an Eigen-like array with a Zernike polynomial.
template<typename arrayT >
int mx::sigproc::zernike (arrayT &arr, int n, int m, typename arrayT::Scalar rad=-1)
Fill in an Eigen-like array with a Zernike polynomial.
template<typename arrayT >
int mx::sigproc::zernike (arrayT &arr, int j, typename arrayT::Scalar rad=-1)
Fill in an Eigen-like array with a Zernike polynomial.
Function Documentation
int mx::sigproc::noll_nm (int & n, int & m, int j)
Get the Zernike coefficients n,m corrresponding the Noll index j.
Calculates the single index j for (n,m) following Noll (1976) [14] See also: http://en.wikipedia.org/wiki/Zernike_polynomials
Parameters
[out] n the radial index of the Zernike polynomial
[out] m the azimuthal index of the Zernnike polynomial
[in] j the Noll index, \(j > 0\)
Return values
0 on success
-1 on error (j < 1)
Definition at line 49 of file zernike.hpp.
References MXE_INVALIDARG, and mxError.
Referenced by mx::sigproc::zernike().
template<typename realT > realT mx::sigproc::zernike (realT rho, realT phi, int n, int m, std::vector< realT > & c)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
Parameters
[in] rho is the radial coordinate, \(0 \le \rho \le 1 \).
[in] phi is the azimuthal angle (in radians)
[in] n is the radial index of the Zernike polynomial.
[in] m is the azimuthal index of the Zernike polynomial.
[in] c is contains the radial polynomial coeeficients, and must be of length \(0.5(n-m)+1\).
Return values
-9999 indicates a possible error
R the value of the Zernike radial polynomial otherwise
Template Parameters
realT is a real floating type
Definition at line 191 of file zernike.hpp.
References mx::sigproc::zernikeR().
template<typename realT > realT mx::sigproc::zernike (realT rho, realT phi, int n, int m)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
Parameters
[in] rho is the radial coordinate, \(0 \le \rho \le 1 \).
[in] phi is the azimuthal angle (in radians)
[in] n is the radial index of the Zernike polynomial.
[in] m is the azimuthal index of the Zernike polynomial.
Return values
-9999 indicates a possible error
R the value of the Zernike radial polynomial otherwise
Template Parameters
realT is a real floating type
Definition at line 230 of file zernike.hpp.
References mx::astro::constants::c(), and mx::sigproc::zernike().
template<typename realT > realT mx::sigproc::zernike (realT rho, realT phi, int j)
Calculate the value of a Zernike radial polynomial at a given radius and angle.
Parameters
[in] rho is the radial coordinate, \(0 \le \rho \le 1 \).
[in] phi is the azimuthal angle (in radians)
[in] j is the Noll index of the Zernike polynomial.
Return values
-9999 indicates a possible error
R the value of the Zernike radial polynomial otherwise
Template Parameters
realT is a real floating type
Definition at line 252 of file zernike.hpp.
References mx::sigproc::noll_nm(), and mx::sigproc::zernike().
template<typename arrayT , int overscan = 2> int mx::sigproc::zernike (arrayT & arr, int n, int m, typename arrayT::Scalar xcen, typename arrayT::Scalar ycen, typename arrayT::Scalar rad = -1)
Fill in an Eigen-like array with a Zernike polynomial.
Sets any pixel which is at rad <= r < rad+0.5 pixels to rho = 1, to be consistent with mx::circularPupil
Parameters
[out] arr is the allocated array with an Eigen-like interface. The rows() and cols() members are used to size the polynomial.
[in] n is the radial index of the polynomial
[in] m is the azimuthal index of the polynomial
[in] xcen is the x coordinate of the desired center of the polynomial, in pixels
[in] ycen is the y coordinate of the desired center of the polynomial, in pixels
[in] rad [optional] is the desired radius. If rad <= 0, then the maximum radius based on dimensions of m is used.
Definition at line 273 of file zernike.hpp.
References mx::astro::constants::c(), mx::sigproc::zernike(), and mx::sigproc::zernikeRCoeffs().
template<typename arrayT > int mx::sigproc::zernike (arrayT & arr, int j, typename arrayT::Scalar xcen, typename arrayT::Scalar ycen, typename arrayT::Scalar rad = -1)
Fill in an Eigen-like array with a Zernike polynomial.
Sets any pixel which is at rad <= r <= rad+0.5 pixels to rho = 1, to be consistent with mx::circularPupil
Parameters
[out] arr is the allocated array with an Eigen-like interface. The rows() and cols() members are used to size the polynomial.
[in] j is the Noll index of the polynomial
[in] xcen is the x coordinate of the desired center of the polynomial, in pixels
[in] ycen is the y coordinate of the desired center of the polynomial, in pixels
[in] rad [optional] is the desired radius. If rad <= 0, then the maximum radius based on dimensions of m is used.
Definition at line 333 of file zernike.hpp.
References mx::sigproc::noll_nm(), and mx::sigproc::zernike().
template<typename arrayT > int mx::sigproc::zernike (arrayT & arr, int n, int m, typename arrayT::Scalar rad = -1)
Fill in an Eigen-like array with a Zernike polynomial.
The geometric center of the array, 0.5*(arr.rows()-1), 0.5*(arr.cols()-1), is used as the center. Sets any pixel which is at rad <= r < rad+0.5 pixels to rho = 1, to be consistent with mx::circularPupil
Parameters
[out] arr is the allocated array with an Eigen-like interface. The rows() and cols() members are used to size the polynomial.
[in] j is the Noll index of the polynomial
[in] rad [optional] is the desired radius. If rad <= 0, then the maximum radius based on dimensions of m is used.
Definition at line 355 of file zernike.hpp.
References mx::sigproc::zernike().
template<typename arrayT > int mx::sigproc::zernike (arrayT & arr, int j, typename arrayT::Scalar rad = -1)
Fill in an Eigen-like array with a Zernike polynomial.
The geometric center of the array, 0.5*(arr.rows()-1), 0.5*(arr.cols()-1), is used as the center. Sets any pixel which is at rad <= r < rad+0.5 pixels to rho = 1, to be consistent with mx::circularPupil
Parameters
[out] arr is the allocated array with an Eigen-like interface. The rows() and cols() members are used to size the polynomial.
[in] j is the Noll index of the polynomial
[in] rad [optional] is the desired radius. If rad <= 0, then the maximum radius based on dimensions of m is used.
Definition at line 375 of file zernike.hpp.
References mx::astro::constants::k(), and mx::sigproc::noll_nm().
Referenced by mx::sigproc::zernike().
template<typename realT > realT mx::sigproc::zernikeR (realT rho, int n, int m, std::vector< realT > & c)
Calculate the value of a Zernike radial polynomial at a given separation.
Parameters
[in] rho is the radial coordinate, \(0 \le \rho \le 1 \).
[in] n is the radial index of the Zernike polynomial.
[in] m is the azimuthal index of the Zernike polynomial.
[in] c is contains the radial polynomial coeeficients, and must be of length \(0.5(n-m)+1\).
Return values
-9999 indicates a possible error
R the value of the Zernike radial polynomial otherwise
Template Parameters
realT is a real floating type
Definition at line 120 of file zernike.hpp.
References mx::astro::constants::k(), MXE_INVALIDARG, and mxError.
template<typename realT > realT mx::sigproc::zernikeR (realT rho, int n, int m)
Calculate the value of a Zernike radial polynomial at a given separation.
Parameters
[in] rho is the radial coordinate, \(0 \le \rho \le 1 \).
[in] n is the radial index of the Zernike polynomial.
[in] m is the azimuthal index of the Zernike polynomial.
Return values
-9999 indicates a possible error
R the value of the Zernike radial polynomial otherwise
Template Parameters
realT is a real floating type
Definition at line 159 of file zernike.hpp.
References mx::astro::constants::c(), and mx::sigproc::zernikeRCoeffs().
Referenced by mx::sigproc::zernike().
template<typename realT > int mx::sigproc::zernikeRCoeffs (std::vector< realT > & c, int n, int m)
Calculate the coefficients of a Zernike radial polynomial.
Parameters
[out] c is allocated to length \(0.5(n-m)+1\) and filled with the coefficients.
[in] n is the radial index of the Zernike polynomial.
[in] m is the azimuthal index of the Zernike polynomial.
Return values
0 on success
-1 on error
Template Parameters
realT is a real floating type
Definition at line 78 of file zernike.hpp.
References mx::astro::constants::k(), MXE_INVALIDARG, and mxError.
Referenced by mx::sigproc::zernike(), and mx::sigproc::zernikeR().