mxlib: The Gaussian Function
The Gaussian Function
General Mathematics » Special Functions
Utilities for working with the Gaussian function.
Utilities for working with the Gaussian function.
Files
file gaussian.hpp
Declarations for utilities related to the Gaussian function.
Macros
#define twosqrt2log2 2.354820045030949382091484
Constant to convert between the Gaussian width parameter and FWHM.
#define fwhm2sigma(fw) ((fw) / twosqrt2log2)
Convert from FWHM to the Gaussian width parameter.
#define sigma2fwhm(sig) ((sig) * twosqrt2log2)
Convert from Gaussian width parameter to FWHM.
Functions
template<typename realT >
realT mx::math::func::gaussian (const realT &x, const realT G0, const realT A, const realT &x0, const realT &sigma)
Find value at position (x) of the 1D arbitrarily-centered symmetric Gaussian.
template<typename realT >
realT mx::math::func::gaussian2D (const realT x, const realT y, const realT G0, const realT A, const realT x0, const realT y0, const realT sigma)
Find value at position (x,y) of the 2D arbitrarily-centered symmetric Gaussian.
template<typename realT >
void mx::math::func::gaussian2D (realT *arr, size_t nx, size_t ny, const realT &G0, const realT &A, const realT &x0, const realT &y0, const realT &sigma)
Fill in an array with the 2D arbitrarily-centered symmetric Gaussian.
template<typename realT >
realT mx::math::func::gaussian2D (const realT &x, const realT &y, const realT &G0, const realT &A, const realT &x0, const realT &y0, const realT &a, const realT &b, const realT &c)
Find value at position (x,y) of the 2D general elliptical Gaussian.
template<typename realT >
void mx::math::func::gaussian2D_gen2rot (realT &sigma_x, realT &sigma_y, realT &theta, const realT &a, const realT &b, const realT &c)
Convert from (a,b,c) to (\(\sigma_x\), \(\sigma_y\), \(\theta\)) for the elliptical Gaussian.
template<typename realT >
void mx::math::func::gaussian2D_rot2gen (realT &a, realT &b, realT &c, const realT &sigma_x, const realT &sigma_y, const realT &theta)
Convert from (\(\sigma_x\), \(\sigma_y\), \(\theta\)) to (a,b,c) for the elliptical Gaussian.
template<typename realT >
realT mx::math::func::gaussian2D_ang (const realT &x, const realT &y, const realT &G0, const realT &A, const realT &x0, const realT &y0, const realT &sigma_x, const realT &sigma_y, const realT &theta)
Find value at position (x,y) of the 2D rotated elliptical Gaussian.
template<typename realT >
void mx::math::func::gaussian2D (realT *arr, size_t nx, size_t ny, const realT &G0, const realT &A, const realT &x0, const realT &y0, const realT &a, const realT &b, const realT &c)
Fill in an array with the 2D general elliptical Gaussian.
template<typename realT >
void mx::math::func::gaussian2D_ang (realT *arr, size_t nx, size_t ny, const realT &G0, const realT &A, const realT &x0, const realT &y0, const realT &sigma_x, const realT &sigma_y, const realT &theta)
Fill in an array with the 2D general elliptical Gaussian.
template<typename realT >
void mx::math::func::gaussian2D_jacobian (realT *j, const realT &x, const realT &y, const realT &G0, const realT &A, const realT &x0, const realT &y0, const realT &a, const realT &b, const realT &c)
Calculate the Jacobian at position (x,y) for the 2D general elliptical Gaussian.
Macro Definition Documentation
#define fwhm2sigma (fw) ((fw) / twosqrt2log2)
Convert from FWHM to the Gaussian width parameter.
Performs the conversion:
\(\sigma = 2\sqrt{2\log2}FWHM \)
Definition at line 43 of file gaussian.hpp.
Referenced by mx::AO::influenceFunctionsGaussian().
#define sigma2fwhm (sig) ((sig) * twosqrt2log2)
Convert from Gaussian width parameter to FWHM.
Performs the conversion:
\(FWHM = 2\sqrt{2\log2}\sigma \)
Definition at line 51 of file gaussian.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::results().
#define twosqrt2log2 2.354820045030949382091484
Constant to convert between the Gaussian width parameter and FWHM.
Used for
\(FWHM = 2\sqrt{2\log2}\sigma \)
This was calculated in long double precision.
Definition at line 35 of file gaussian.hpp.
Function Documentation
template<typename realT > realT mx::math::func::gaussian (const realT & x, const realT G0, const realT A, const realT & x0, const realT & sigma)
Find value at position (x) of the 1D arbitrarily-centered symmetric Gaussian.
Computes: \(G(x) = G_0 + A\exp[-(0.5/\sigma^2)((x-x_0)^2)]\)
Returns
the value of the 1D arbitrarily-centered symmetric Gaussian at (x)
Template Parameters
realT is type to use for arithmetic
Parameters
[in] x is the x-position at which to evaluate the Gaussian
[in] G0 is the constant to add to the Gaussian
[in] A is the scaling factor (peak = A)
[in] x0 is the x-coordinate of the center
[in] sigma is the width of the Gaussian.
Definition at line 64 of file gaussian.hpp.
template<typename realT > realT mx::math::func::gaussian2D (const realT x, const realT y, const realT G0, const realT A, const realT x0, const realT y0, const realT sigma)
Find value at position (x,y) of the 2D arbitrarily-centered symmetric Gaussian.
Computes:
\[ G(x,y) = G_0 + A\exp[-(0.5/\sigma^2)((x-x_0)^2+(y-y_0)^2)] \]
Returns
the value of the 2D arbitrarily-centered symmetric Gaussian at (x,y)
Template Parameters
realT is type to use for arithmetic
Parameters
[in] x the x-position at which to evaluate the Gaussian
[in] y the y-positoin at which to evaluate the Gaussian
[in] G0 the constant to add to the Gaussian
[in] A the scaling factor (peak height is A-G0)
[in] x0 the x-coordinate of the center
[in] y0 the y-coordinate of the center
[in] sigma the width of the Gaussian.
Definition at line 86 of file gaussian.hpp.
Referenced by mx::AO::influenceFunctionsGaussian().
template<typename realT > void mx::math::func::gaussian2D (realT * arr, size_t nx, size_t ny, const realT & G0, const realT & A, const realT & x0, const realT & y0, const realT & sigma)
Fill in an array with the 2D arbitrarily-centered symmetric Gaussian.
At each pixel (x,y) of the array this computes:
\((x,y) = G_0 + A\exp[-(0.5/\sigma^2)((x-x_0)^2+(y-y_0)^2)] \)
Parameters
arr is the allocated array to fill in
nx is the size of the x dimension of the array
ny is the size of the y dimension of the array
G0 is the constant to add to the Gaussian
A is the scaling factor (peak = A)
x0 is the x-coordinate of the center
y0 is the y-coordinate of the center
sigma is the third rotation and scaling factor
Template Parameters
realT is the type to use for arithmetic
Definition at line 116 of file gaussian.hpp.
References mx::math::func::gaussian2D().
template<typename realT > realT mx::math::func::gaussian2D (const realT & x, const realT & y, const realT & G0, const realT & A, const realT & x0, const realT & y0, const realT & a, const realT & b, const realT & c)
Find value at position (x,y) of the 2D general elliptical Gaussian.
Computes:
\(G(x,y) = G_0 + A\exp [-0.5(a(x-x_0)^2 + b(x-x_0)(y-y_0) + c(y-y_0)^2 ]\)
where, for a counter-clockwise rotation \(\theta \), we have
\(a = \frac{\cos^2 \theta}{\sigma_x^2} + \frac{\sin^2\theta}{\sigma_y^2}\)
\(b = \frac{\sin 2\theta}{2} \left(\frac{1}{\sigma_x^2} - \frac{1}{\sigma_y^2} \right)\)
\(c = \frac{\sin^2 \theta}{\sigma_x^2} + \frac{\cos^2\theta}{\sigma_y^2}\)
In this version the parameters are specified directly as (a,b,c), in particular avoiding the trig function calls. This should be much more efficient, and so this version should be used inside fitting routines, etc. However note that the matrix {a b}{b c} must be positive-definite otherwise infinities can result from the argument of the exponent being positive.
The functions gaussian2D_gen2rot and gaussian2D_rot2gen provide conversions from (a,b,c) to (\(\sigma_x\), \(\sigma_y\), \(\theta\)) and back. The function gaussian2D_ang is a wrapper for this function, which instead accepts (\(\sigma_x\), \(\sigma_y\), \(\theta\)) as inputs.
Parameters
x is the x-position at which to evaluate the Gaussian
y is the y-positoin at which to evaluate the Gaussian
G0 is the constant to add to the Gaussian
A is the scaling factor (peak = A)
x0 is the x-coordinate of the center
y0 is the y-coordinate of the center
a is the first rotation and scaling factor
b is the second rotation and scaling factor
c is the third rotation and scaling factor
Returns
the value of the 2D elliptical Gaussian at (x,y)
Template Parameters
realT is type to use for arithmetic
Definition at line 176 of file gaussian.hpp.
template<typename realT > void mx::math::func::gaussian2D (realT * arr, size_t nx, size_t ny, const realT & G0, const realT & A, const realT & x0, const realT & y0, const realT & a, const realT & b, const realT & c)
Fill in an array with the 2D general elliptical Gaussian.
At each pixel (x,y) of the array this computes:
\(G(x,y) = G_0 + A\exp [-0.5(a(x-x_0)^2 + b(x-x_0)(y-y_0) + c(y-y_0)^2 ]\)
where, for a counter-clockwise rotation \(\theta \), we have
\(a = \frac{\cos^2 \theta}{\sigma_x^2} + \frac{\sin^2\theta}{\sigma_y^2}\)
\(b = \frac{\sin 2\theta}{2} \left(\frac{1}{\sigma_x^2} - \frac{1}{\sigma_y^2} \right)\)
\(c = \frac{\sin^2 \theta}{\sigma_x^2} + \frac{\cos^2\theta}{\sigma_y^2}\)
In this version the parameters are specified directly as (a,b,c), in particular avoiding the trig function calls. This should be much more efficient, and so this version should be used inside fitting routines, etc.
The functions gaussian2D_gen2rot and gaussian2D_rot2gen provide conversions from (a,b,c) to (\(\sigma_x\), \(\sigma_y\), \(\theta\)) and back. The function gaussian2D_ang is a wrapper for this function, which instead accepts (\(\sigma_x\), \(\sigma_y\), \(\theta\)) as inputs.
Parameters
arr is the allocated array to fill in
nx is the size of the x dimension of the array
ny is the size of the y dimension of the array
G0 is the constant to add to the Gaussian
A is the scaling factor (peak = A)
x0 is the x-coordinate (in pixels) of the center
y0 is the y-coordinate (in pixels) of the center
a is the first rotation and scaling factor
b is the second rotation and scaling factor
c is the third rotation and scaling factor
Template Parameters
realT is the type to use for arithmetic
Definition at line 420 of file gaussian.hpp.
Referenced by mx::math::func::gaussian2D(), and mx::math::func::gaussian2D_ang().
template<typename realT > realT mx::math::func::gaussian2D_ang (const realT & x, const realT & y, const realT & G0, const realT & A, const realT & x0, const realT & y0, const realT & sigma_x, const realT & sigma_y, const realT & theta)
Find value at position (x,y) of the 2D rotated elliptical Gaussian.
Computes: \(G(x,y) = G_0 + A\exp [-0.5(a(x-x_0)^2 + b(x-x_0)(y-y_0) + c(y-y_0)^2 ]\)
where, for a counter-clockwise rotation \(\theta \), we have
\(a = \frac{\cos^2 \theta}{\sigma_x^2} + \frac{\sin^2\theta}{\sigma_y^2}\)
\(b = \frac{\sin 2\theta}{2} \left(\frac{1}{\sigma_x^2} - \frac{1}{\sigma_y^2} \right)\)
\(c = \frac{\sin^2 \theta}{\sigma_x^2} + \frac{\cos^2\theta}{\sigma_y^2}\)
This is a convenience wrapper for the general elliptical Gaussian function Gaussian2D, where here (a,b,c) are first calculated from (\(\sigma_x\), \(\sigma_y\), \(\theta\)). This will in general be slower due to the trig function calls, so the (a,b,c) version should be used most of the time.
The functions gaussian2D_gen2rot and gaussian2D_rot2gen provide conversions from (a,b,c) to (\(\sigma_x\), \(\sigma_y\), \(\theta\)) and back. The function gaussian2D_rot is a wrapper for this function, which instead accepts (\(\sigma_x\), \(\sigma_y\), \(\theta\)) as inputs.
Parameters
x is the x-position at which to evaluate the Gaussian
y is the y-positoin at which to evaluate the Gaussian
G0 is the constant to add to the Gaussian
A is the scaling factor (peak = A)
x0 is the x-coordinate of the center
y0 is the y-coordinate of the center
sigma_x is the width in the rotated x direction
sigma_y is the width in the rotated y direction
theta is the counter-clockwise rotation angle
Returns
the value of the 2D elliptical Gaussian at (x,y)
Template Parameters
realT is type to use for arithmetic
Definition at line 368 of file gaussian.hpp.
References mx::astro::constants::c(), mx::math::func::gaussian2D(), and mx::math::func::gaussian2D_rot2gen().
template<typename realT > void mx::math::func::gaussian2D_ang (realT * arr, size_t nx, size_t ny, const realT & G0, const realT & A, const realT & x0, const realT & y0, const realT & sigma_x, const realT & sigma_y, const realT & theta)
Fill in an array with the 2D general elliptical Gaussian.
At each pixel (x,y) of the array this computes:
\(G(x,y) = G_0 + A\exp [-0.5(a(x-x_0)^2 + b(x-x_0)(y-y_0) + c(y-y_0)^2 ]\)
where, for a counter-clockwise rotation \(\theta \), we have
\(a = \frac{\cos^2 \theta}{\sigma_x^2} + \frac{\sin^2\theta}{\sigma_y^2}\)
\(b = \frac{\sin 2\theta}{2} \left(\frac{1}{\sigma_x^2} - \frac{1}{\sigma_y^2} \right)\)
\(c = \frac{\sin^2 \theta}{\sigma_x^2} + \frac{\cos^2\theta}{\sigma_y^2}\)
This is a convenience wrapper for the general elliptical Gaussian function Gaussian2D, where here (a,b,c) are first calculated from (\(\sigma_x\), \(\sigma_y\), \(\theta\)).
The functions gaussian2D_gen2rot and gaussian2D_rot2gen provide conversions from (a,b,c) to (\(\sigma_x\), \(\sigma_y\), \(\theta\)) and back.
Parameters
x is the x-position at which to evaluate the Gaussian
y is the y-positoin at which to evaluate the Gaussian
G0 is the constant to add to the Gaussian
A is the scaling factor (peak = A)
x0 is the x-coordinate of the center
y0 is the y-coordinate of the center
sigma_x is the width in the rotated x direction
sigma_y is the width in the rotated y direction
theta is the counter-clockwise rotation angle
Returns
the value of the 2D elliptical Gaussian at (x,y)
Template Parameters
realT is type to use for arithmetic
Definition at line 480 of file gaussian.hpp.
References mx::astro::constants::c(), mx::math::func::gaussian2D(), and mx::math::func::gaussian2D_rot2gen().
template<typename realT > void mx::math::func::gaussian2D_gen2rot (realT & sigma_x, realT & sigma_y, realT & theta, const realT & a, const realT & b, const realT & c)
Convert from (a,b,c) to (\(\sigma_x\), \(\sigma_y\), \(\theta\)) for the elliptical Gaussian.
The general 2D elliptical Gaussian
\(G(x,y) = G_0 + A\exp [-0.5(a(x-x_0)^2 + b(x-x_0)(y-y_0) + c(y-y_0)^2 ]\)
can be expressed in terms of widths and a rotation angle using:
\(a = \frac{\cos^2 \theta}{\sigma_x^2} + \frac{\sin^2\theta}{\sigma_y^2}\)
\(b = \frac{\sin 2\theta}{2} \left(\frac{1}{\sigma_x^2} - \frac{1}{\sigma_y^2} \right)\)
\(c = \frac{\sin^2 \theta}{\sigma_x^2} + \frac{\cos^2\theta}{\sigma_y^2}\)
where \(\theta \) specifies a counter-clockwise rotation.
This function calculates (\(\sigma_x\), \(\sigma_y\), \(\theta\)) from inputs (a,b,c). It adopts the convention that the long axis of the ellipse is \(\sigma_x\), and \(\theta\) is chosen appropriately. Note that \(-\frac{\pi}{2} < \theta < \frac{\pi}{2}\).
Parameters
sigma_x [output]
sigma_y [output]
theta [output]
a [input]
b [input]
c [input]
Template Parameters
realT is type to use for arithmetic
Definition at line 224 of file gaussian.hpp.
References mx::astro::constants::c().
Referenced by mx::math::fit::gaussian2D_sym_fitter< _realT >::paramNormalizer().
template<typename realT > void mx::math::func::gaussian2D_jacobian (realT * j, const realT & x, const realT & y, const realT & G0, const realT & A, const realT & x0, const realT & y0, const realT & a, const realT & b, const realT & c)
Calculate the Jacobian at position (x,y) for the 2D general elliptical Gaussian.
Given:
\(G(x,y) = G_0 + A\exp [-0.5(a(x-x_0)^2 + b(x-x_0)(y-y_0) + c(y-y_0)^2 ]\)
we calculate
\(\frac{\partial G}{\partial G_0} = 1 \)
\(\frac{\partial G}{\partial A} = (G - G_0)/A \)
\(\frac{\partial G}{\partial x_0} = 0.5(G-G_0)(2a(x-x_0) + b(y-y_0)) \)
\(\frac{\partial G}{\partial y_0} = 0.5(G-G_0) (b(x-x_0) + 2c(y-y_0)) \)
\(\frac{\partial G}{\partial a} = -0.5(G-G_0) ((x-x_0)^2) \)
\(\frac{\partial G}{\partial b} = -0.5(G-G_0) ((x-x_0)(y-y_0)) \)
\(\frac{\partial G}{\partial c} = -0.5(G-G_0) ((y-y_0)^2)\)
Parameters
j is a 7 element vector which is populated with the derivatives
x is the x-position at which to evaluate the Gaussian
y is the y-positoin at which to evaluate the Gaussian
G0 is the constant to add to the Gaussian
A is the scaling factor (peak = A)
x0 is the x-coordinate of the center
y0 is the y-coordinate of the center
a is the first rotation and scaling factor
b is the second rotation and scaling factor
c is the third rotation and scaling factor
Template Parameters
realT is type to use for arithmetic
Definition at line 546 of file gaussian.hpp.
References mx::astro::constants::c().
template<typename realT > void mx::math::func::gaussian2D_rot2gen (realT & a, realT & b, realT & c, const realT & sigma_x, const realT & sigma_y, const realT & theta)
Convert from (\(\sigma_x\), \(\sigma_y\), \(\theta\)) to (a,b,c) for the elliptical Gaussian.
The general 2D elliptical Gaussian
\(G(x,y) = G_0 + A\exp [-0.5(a(x-x_0)^2 + b(x-x_0)(y-y_0) + c(y-y_0)^2 ]\)
can be expressed in terms of widths and a rotation angle using:
\(a = \frac{\cos^2 \theta}{\sigma_x^2} + \frac{\sin^2\theta}{\sigma_y^2}\)
\(b = \frac{\sin 2\theta}{2} \left(\frac{1}{\sigma_x^2} - \frac{1}{\sigma_y^2} \right)\)
\(c = \frac{\sin^2 \theta}{\sigma_x^2} + \frac{\cos^2\theta}{\sigma_y^2}\)
where \(\theta \) specifies a counter-clockwise rotation.
This function calculates (a,b,c) from inputs (\(\sigma_x\), \(\sigma_y\), \(\theta\)).
Parameters
a [output]
b [output]
c [output]
sigma_x [input]
sigma_y [input]
theta [input]
Template Parameters
realT is type to use for arithmetic
Definition at line 313 of file gaussian.hpp.
Referenced by mx::math::func::gaussian2D_ang(), and mx::math::fit::gaussian2D_sym_fitter< _realT >::paramNormalizer().