mxlib: Adaptive Optics Path Management
Adaptive Optics Path Management
Wavefront Propagation » Adaptive Optics » Simulation of Adaptive Optics
Definitions and managemetn of AO related file paths.
Definitions and managemetn of AO related file paths.
Namespaces
mx::AO::path
Namespace for paths.
mx::AO::path::basis
Namespace for basis paths.
Functions
std::string mx::AO::path::basis::root (const std::string &basisName, bool create=false)
The root path for basis files.
Function Documentation
std::string mx::AO::path::basis::root (const std::string & basisName, bool create = false)
The root path for basis files.
Parameters
[in] basisName the name of the basis
[in] create [optional] create the directory if it noes not exist.
Returns
the root path for basis files.
Definition at line 46 of file aoPaths.hpp.
References mx::getEnv().
Referenced by mx::AO::path::dm::actuatorPositions(), mx::AO::path::dm::basisRoot(), mx::AO::path::dm::influenceFunctions(), mx::AO::path::dm::pseudoInverse(), mx::AO::path::pupil::pupilFile(), mx::AO::path::dm::singularValues(), and mx::AO::path::sys::cal::sysResp().