mxlib: FITS Utilities
FITS Utilities
Image Processing » FITS Files
FITS file utilities and wrappers.
FITS file utilities and wrappers.
Functions
template<typename dataT >
void mx::improc::headersToValues (std::vector< dataT > &v, const std::vector< fitsHeader > &heads, const std::string &keyw)
Convert the values in a std::vector of fits headers into a std::vector of values.
template<typename dataT >
std::vector< dataT > mx::improc::headersToValues (const std::vector< fitsHeader > &heads, const std::string &keyw)
Convert the values in a std::vector of fits headers into a std::vector of values.
void mx::improc::fitsHeaderGitStatus (fitsHeader &head, const std::string &repoName, const char *sha1, int modified)
Write the status of a Git repository to HISTORY in a FITS header.
template<typename scalarT >
int mx::improc::getFitsType ()
Return the cfitsio constant for a given data type.
template<typename typeT >
int mx::improc::fits_write_key (fitsfile *fptr, char *keyword, void *value, char *comment)
Write a header card to a file.
template<typename scalarT >
int mx::improc::getFitsBITPIX ()
int mx::improc::fitsStripApost (std::string &s)
Strip the apostrophes from a FITS value string.
void mx::improc::fitsPopulateCard (char headStr[81], char *keyword, char *value, char *comment)
Populate a fits header card with the value string copied verbatim.
Function Documentation
template<typename typeT > int mx::improc::fits_write_key (fitsfile * fptr, char * keyword, void * value, char * comment)
Write a header card to a file.
This is a templatized wrapper for the cfitsio routine fits_write_key.
Template Parameters
typeT is the type of the value
Parameters
fptr is a pointer to an open fits file
keyword is a c-string containing the keyword
value is a pointer to the memory location of the value
comment is a c-string, possibly NULL, containing a comment string
Return values
int containing the status returned by the cfitsio routine.
Definition at line 346 of file fitsUtils.hpp.
References mx::improc::fitsPopulateCard().
void mx::improc::fitsHeaderGitStatus (fitsHeader & head, const std::string & repoName, const char * sha1, int modified) inline
Write the status of a Git repository to HISTORY in a FITS header.
Parameters
[in,out] head the HISTORY cards will be appended to this header
[in] repoName the name of the repository
[in] sha1 is the SHA-1 hash string of the repository
[in] modified whether or not the repository has been modified after the commit referred to by sha1
Definition at line 594 of file fitsHeader.hpp.
References mx::improc::fitsHeader::append().
Referenced by mx::AO::analysis::fourierVarVec(), mx::improc::HCIobservation< _realT >::outputPSFSub(), and mx::improc::HCIobservation< _realT >::writeFinim().
void mx::improc::fitsPopulateCard (char headStr[81], char * keyword, char * value, char * comment) inline
Populate a fits header card with the value string copied verbatim.
Parameters
headStr is a c-string which must be 81 characters in length, including the '
'
keyword is the keyword name
value is the value string
comment is the comment string
Definition at line 294 of file fitsUtils.hpp.
References stdValWidth.
Referenced by mx::improc::fits_write_key().
int mx::improc::fitsStripApost (std::string & s) inline
Strip the apostrophes from a FITS value string.
The argument is modified if the first and/or last non-whitespace character is '
Parameters
s is the string from which to strip apostrophes
Return values
int containing the number of stripped apostrophes
Definition at line 258 of file fitsUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::String(), and mx::improc::fitsHeaderCard::Value().
template<typename scalarT > int mx::improc::getFitsBITPIX ()
Return the cfitsio BITPIX value for a given data type.
Template Parameters
scalarT is the type
Return values
int > 0 if a constant is defined in cfitsio corresponding to the native type
-1 if not a defined type in cfitsio
Definition at line 192 of file fitsUtils.hpp.
template<typename scalarT > int mx::improc::getFitsType ()
Return the cfitsio constant for a given data type.
Template Parameters
scalarT is the type
Return values
int contains a constant defined in cfitsio corresponding to the native type
-1 if not a define type in cfitsio
Definition at line 83 of file fitsUtils.hpp.
template<typename dataT > void mx::improc::headersToValues (std::vector< dataT > & v, const std::vector< fitsHeader > & heads, const std::string & keyw)
Convert the values in a std::vector of fits headers into a std::vector of values.
Resizes the vector of the appropriate type.
Template Parameters
dataT is the type of the header value
Parameters
[out] v will contain the converted values
[in] heads contains the headers
[in] keyw contains the keyword designating which value to convert
Definition at line 554 of file fitsHeader.hpp.
template<typename dataT > std::vector<dataT> mx::improc::headersToValues (const std::vector< fitsHeader > & heads, const std::string & keyw)
Convert the values in a std::vector of fits headers into a std::vector of values.
Creates a vector of the appropriate type and size.
Template Parameters
dataT is the type of the header value
Parameters
[in] heads contains the headers
[in] keyw contains the keyword designating which value to convert
Return values
std::vector<dataT> containing the converted values
Definition at line 576 of file fitsHeader.hpp.