mxlib: Working with time
Working with time
General Utilities
Various tools for working with time.
Various tools for working with time.
Files
file timeUtils.hpp
Utilities for working with time.
file sofa.hpp
Wrapper for the sofa library headers, adding a namespace.
Functions
template<typename typeT = double, clockid_t clk_id = CLOCK_REALTIME>
typeT mx::get_curr_time ()
template<typename floatT >
void mx::parse_hms (const std::string &hmsstr, floatT &h, floatT &m, floatT &s)
double mx::Cal2mjd (int yr, int mon, int day, int hr, int min, double sec)
Converts a Gregorian calendar date into modified Julian date (MJD).
int mx::ISO8601dateBreakdown (int &yr, int &mon, int &day, int &hr, int &min, double &sec, const std::string &fdate)
Parse an ISO8601 date of the form "YYYY-MM-DDTHH:MM:SS.S" into the individual components.
double mx::ISO8601date2mjd (const std::string &fdate)
Parse an ISO8601 date of the form "YYYY-MM-DDTHH:MM:SS.S" and return the modified Julian date (MJD)
template<typename timeT >
std::string mx::ISO8601DateTimeStr (const timeT &timeIn, int timeZone=0)
Get a date-time string in ISO 8601 format.
template<>
std::string mx::ISO8601DateTimeStr< time_t > (const time_t &timeIn, int timeZone)
Get a date-time string in ISO 8601 format for time_t.
template<>
std::string mx::ISO8601DateTimeStr< timespec > (const timespec &timeIn, int timeZone)
Get a date-time string in ISO 8601 format for timespec.
std::string mx::ISO8601DateTimeStr (int timeZone=0)
Get a date-time string in ISO 8601 format for the current UTC time.
std::string mx::ISO8601DateTimeStrMJD (const double &timeIn, int timeZone=0)
Get a date-time string in ISO 8601 format for an MJD.
int mx::timespecUTC2TAIMJD (double &djm, double &djmf, const timespec &tsp, tm *tm0)
Convert a UTC timespec to TAI modified Julian date.
Function Documentation
double mx::Cal2mjd (int yr, int mon, int day, int hr, int min, double sec) inline
Converts a Gregorian calendar date into modified Julian date (MJD).
Uses the SOFA function iauCal2jd. This is not a template in floating point because SOFA is always double precision.
Parameters
[in] yr Gregorian calendar year
[in] mon Gregorian calendar month
[in] day Gregorian calendar day
[in] hr Gregorian calendar hour
[in] min Gregorian calendar minute
[in] sec Gregorian calendar second
Return values
double containing the MJD
<0 on error (-1 = bad year, -2 = bad month, -3 = bad day)
Definition at line 104 of file timeUtils.hpp.
Referenced by mx::ISO8601date2mjd().
template<typename typeT = double, clockid_t clk_id = CLOCK_REALTIME> typeT mx::get_curr_time ()
Get the current system time. Uses timespec, so nanosecond resolution is possible.
Template Parameters
typeT is the type to return the time in [default=double]. must have cast from integer types, and + and / operators defined.
clk_id is the sys/time.h clock identifier [default=CLOCK_REALTIME]
Return values
typeT containing the current time in seconds
Definition at line 35 of file timeUtils.hpp.
Referenced by mx::sigproc::linearPredictor< realT >::calcCoefficients(), mx::improc::HCIobservation< _realT >::coaddImages(), mx::improc::HCIobservation< _realT >::combineFinim(), mx::improc::ADIobservation< _realT, _derotFunctObj >::derotate(), mx::math::fit::levmarInterface< fitterT >::fit(), mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake(), mx::improc::HCIobservation< _realT >::preProcess(), mx::improc::HCIobservation< _realT >::readFiles(), mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix(), and mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::worker().
double mx::ISO8601date2mjd (const std::string & fdate) inline
Parse an ISO8601 date of the form "YYYY-MM-DDTHH:MM:SS.S" and return the modified Julian date (MJD)
Parsing is currently only for the exact form above, which is the form in a FITS file. See https://en.wikipedia.org/?title=ISO_8601. After parsing calls Cal2mjd.
Parameters
[in] fdate is a standard ISO8601 date string
Definition at line 160 of file timeUtils.hpp.
References mx::Cal2mjd(), mx::astro::constants::day(), and mx::ISO8601dateBreakdown().
Referenced by mx::improc::HCIobservation< _realT >::readFiles().
int mx::ISO8601dateBreakdown (int & yr, int & mon, int & day, int & hr, int & min, double & sec, const std::string & fdate) inline
Parse an ISO8601 date of the form "YYYY-MM-DDTHH:MM:SS.S" into the individual components.
Parsing is currently only for the exact form above, which is the form in a FITS file. See https://en.wikipedia.org/?title=ISO_8601.
Parameters
[out] yr Gregorian calendar year
[out] mon Gregorian calendar month
[out] day Gregorian calendar day
[out] hr Gregorian calendar hour
[out] min Gregorian calendar minute
[out] sec Gregorian calendar second
[in] fdate is a standard ISO8601 date string
Definition at line 126 of file timeUtils.hpp.
References mx::parse_hms().
Referenced by mx::ISO8601date2mjd().
template<typename timeT > std::string mx::ISO8601DateTimeStr (const timeT & timeIn, int timeZone = 0)
Get a date-time string in ISO 8601 format.
For recognized time types, returns a string in the ISO 8601 format: YYYY-MM-DDYHH:MM:SS.SS, with optional timezone designation such as Z or +00:00.
Template Parameters
timeT is the time type
Parameters
[in] timeIn is the input time
[in] timeZone specifies whether to include a timezone designation. 0=> none, 1=> letter, 2=>offset.
Return values
std::string containing the format date/time
Definition at line 195 of file timeUtils.hpp.
std::string mx::ISO8601DateTimeStr (int timeZone = 0) inline
Get a date-time string in ISO 8601 format for the current UTC time.
Returns a string in the ISO 8601 format: YYYY-MM-DDYHH:MM:SS.SS, with optional timezone designation such as Z or +00:00.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] timeZone [optional] specifies whether to include a timezone designation. 0=> none, 1=> letter, 2=>offset.
Return values
std::string containing the format date/time
Definition at line 279 of file timeUtils.hpp.
References mx::ISO8601DateTimeStr< time_t >().
template<> std::string mx::ISO8601DateTimeStr< time_t > (const time_t & timeIn, int timeZone) inline
Get a date-time string in ISO 8601 format for time_t.
Returns a string in the ISO 8601 format: YYYY-MM-DDYHH:MM:SS, with optional timezone designation such as Z or +00:00.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] timeIn is the input time
[in] timeZone specifies whether to include a timezone designation. 0=> none, 1=> letter, 2=>offset.
Return values
std::string containing the format date/time
Definition at line 217 of file timeUtils.hpp.
Referenced by mx::ISO8601DateTimeStr(), and mx::ISO8601DateTimeStr< timespec >().
template<> std::string mx::ISO8601DateTimeStr< timespec > (const timespec & timeIn, int timeZone) inline
Get a date-time string in ISO 8601 format for timespec.
Returns a string in the ISO 8601 format: YYYY-MM-DDYHH:MM:SS.SSSSSSSSS, with optional timezone designation such as Z or +00:00.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] timeIn is the input time
[in] timeZone specifies whether to include a timezone designation. 0=> none, 1=> letter, 2=>offset.
Return values
std::string containing the format date/time
Definition at line 248 of file timeUtils.hpp.
References mx::ISO8601DateTimeStr< time_t >().
std::string mx::ISO8601DateTimeStrMJD (const double & timeIn, int timeZone = 0)
Get a date-time string in ISO 8601 format for an MJD.
Returns a string in the ISO 8601 format: YYYY-MM-DDYHH:MM:SS.SSSSSSSSS, with optional timezone designation such as Z or +00:00.
Parameters
[in] timeIn is the input time
[in] timeZone specifies whether to include a timezone designation. 0=> none, 1=> letter, 2=>offset.
Return values
std::string containing the format date/time
Definition at line 295 of file timeUtils.hpp.
References DJM0.
template<typename floatT > void mx::parse_hms (const std::string & hmsstr, floatT & h, floatT & m, floatT & s)
Parse a string of format hh:mm:ss.s Breaks a time string into constituent parts. Handles -h by distributing the sign to m and s.
Parameters
[in] hmsstr is a string of format hh:mm:ss.s where ss.s can be of any precision
[out] h is the hour component coverted to floatT
[out] m is the minute component converted to floatT
[out] s is the second component converted to floatT
Template Parameters
floatT is a floating point type
Definition at line 58 of file timeUtils.hpp.
Referenced by mx::ISO8601dateBreakdown().
int mx::timespecUTC2TAIMJD (double & djm, double & djmf, const timespec & tsp, tm * tm0) inline
Convert a UTC timespec to TAI modified Julian date.
Converts a timespec assumed to be in Coordinated Universal Time (UTC) to a Modified Julian Date (MJD) in International Atomic Time (TAI).
Parameters
[out] djm the modified Julian day number
[out] djmf the fraction of the day
[in] tsp contains the UTC time
[out] tm0 [optional] will be filled with the broken down UTC time
Return values
1 SOFA dubious year [see SOFA documentation for iauDat]
0 success
-1 SOFA bad year [see SOFA documentation for iauDat and iauCal2jd]
-2 SOFA bad month [see SOFA documentation for iauDat and iauCal2jd]
-3 SOFA bad day [see SOFA documentation for iauDat and iauCal2jd]
-4 SOFA bad fractional day [see SOFA documentation for iauDat and iauCal2jd]
-5 SOFA internal error [see SOFA documentation for iauDat and iauCal2jd]
-10 gmtime_r returned error, check errno
Definition at line 347 of file timeUtils.hpp.