mxlib: Working with strings
Working with strings
General Utilities
Various tools for working with strings.
Various tools for working with strings.
Classes
struct mx::textTable
An ascii table formatter.
Files
file stringUtils.hpp
utilities for working with strings
file textTable.hpp
declares and defines a simple text table manager
Functions
template<typename typeT , unsigned width = 0, char pad = ' '>
std::string mx::convertToString (const typeT &value, int precision=0)
Convert a numerical value to a string.
template<>
std::string mx::convertToString< std::string > (const std::string &value, int precision)
Specialization of convertToString to avoid converting a string to a string.
template<typename typeT >
typeT mx::convertFromString (const std::string &str)
Convert a string to a numerical value.
template<>
char mx::convertFromString< char > (const std::string &str)
Template specialization of convertFromString for char.
template<>
unsigned char mx::convertFromString< unsigned char > (const std::string &str)
Template specialization of convertFromString for unsigned char.
template<>
short mx::convertFromString< short > (const std::string &str)
Template specialization of convertFromString for short.
template<>
unsigned short mx::convertFromString< unsigned short > (const std::string &str)
Template specialization of convertFromString for unsigned short.
template<>
int mx::convertFromString< int > (const std::string &str)
Template specialization of convertFromString for int.
template<>
unsigned int mx::convertFromString< unsigned int > (const std::string &str)
Template specialization of convertFromString for unsigned int.
template<>
long mx::convertFromString< long > (const std::string &str)
Template specialization of convertFromString for long.
template<>
unsigned long mx::convertFromString< unsigned long > (const std::string &str)
Template specialization of convertFromString for unsigned long.
template<>
long long mx::convertFromString< long long > (const std::string &str)
Template specialization of convertFromString for long long.
template<>
unsigned long long mx::convertFromString< unsigned long long > (const std::string &str)
Template specialization of convertFromString for unsigned long long.
template<>
float mx::convertFromString< float > (const std::string &str)
Template specialization of convertFromString for float.
template<>
double mx::convertFromString< double > (const std::string &str)
Template specialization of convertFromString for double.
template<>
long double mx::convertFromString< long double > (const std::string &str)
Template specialization of convertFromString for long double.
template<>
bool mx::convertFromString< bool > (const std::string &str)
Template specialization of convertFromString for bool.
void mx::toLower (std::string &outstr, const std::string &instr)
Convert a string to all lower case.
std::string mx::toLower (const std::string &instr)
Convert a string to all lower case.
void mx::toUpper (std::string &outstr, const std::string &instr)
Convert a string to all upper case.
std::string mx::toUpper (const std::string &instr)
Convert a string to all upper case.
void mx::removeWhiteSpace (std::string &outstr, const std::string &instr)
Remove all white space from a string.
std::string mx::removeWhiteSpace (const std::string &instr)
Remove all white space from a string.
int mx::stringWrap (std::vector< std::string > &lines, const std::string &str, int width)
Wrap a string by breaking it into smaller sized portions of a desired width.
void mx::textTable::addCell (int row, int col, const std::string &cell)
Add one cell to the table, overwriting if it already exists.
void mx::textTable::addCell (int row, int col, const char *cell)
template<typename typeT >
void mx::textTable::addCell (int row, int col, const typeT &cell, int precision=0)
Add one cell to the table, overwriting if it already exists.
template<typename iosT >
void mx::textTable::outPut (iosT &ios)
Output the table to a stream.
Function Documentation
void mx::textTable::addCell (int row, int col, const std::string & cell) inline
Add one cell to the table, overwriting if it already exists.
Parameters
[in] row the row of the cell.
[in] col the column of the cell.
[in] cell the new contents of the cell, will be wrapped.
Definition at line 80 of file textTable.hpp.
References mx::textTable::colWidths, mx::textTable::rows, and mx::stringWrap().
Referenced by mx::textTable::addCell(), and mx::application::optionHelp().
void mx::textTable::addCell (int row, int col, const char * cell)
Parameters
[in] row the row of the cell.
[in] col the column of the cell.
[in] cell the new contents of the cell, will be wrapped.
Definition at line 99 of file textTable.hpp.
References mx::textTable::addCell().
template<typename typeT > void mx::textTable::addCell (int row, int col, const typeT & cell, int precision = 0)
Add one cell to the table, overwriting if it already exists.
Parameters
[in] row the row of the cell.
[in] col the column of the cell.
[in] cell the new contents of the cell, will be wrapped.
Definition at line 108 of file textTable.hpp.
References mx::textTable::addCell().
template<typename typeT > typeT mx::convertFromString (const std::string & str)
Convert a string to a numerical value.
The default version attempts to do the conversion with a simple c style cast. The various template specializations handle conversions to the basic types.
Example:
std::string str = "2.34567";
double d;
d = convertFromString<double>(str);
Template Parameters
typeT is the type of the numerical value desired
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 131 of file stringUtils.hpp.
template<> bool mx::convertFromString< bool > (const std::string & str) inline
Template specialization of convertFromString for bool.
First looks for 0/1,f/t, or F/T in the first non-space character of str. otherwise uses convertFromString<int>.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 306 of file stringUtils.hpp.
References mx::astro::constants::c(), and mx::convertFromString< int >().
template<> char mx::convertFromString< char > (const std::string & str) inline
Template specialization of convertFromString for char.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 146 of file stringUtils.hpp.
template<> double mx::convertFromString< double > (const std::string & str)
Template specialization of convertFromString for double.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 281 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::Double().
template<> float mx::convertFromString< float > (const std::string & str)
Template specialization of convertFromString for float.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 268 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::Float().
template<> int mx::convertFromString< int > (const std::string & str) inline
Template specialization of convertFromString for int.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 196 of file stringUtils.hpp.
Referenced by mx::convertFromString< bool >(), and mx::improc::fitsHeaderCard::Int().
template<> long mx::convertFromString< long > (const std::string & str) inline
Template specialization of convertFromString for long.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 220 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::Long().
template<> long double mx::convertFromString< long double > (const std::string & str)
Template specialization of convertFromString for long double.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 293 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::longDouble().
template<> long long mx::convertFromString< long long > (const std::string & str) inline
Template specialization of convertFromString for long long.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 244 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::longLong().
template<> short mx::convertFromString< short > (const std::string & str) inline
Template specialization of convertFromString for short.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 172 of file stringUtils.hpp.
template<> unsigned char mx::convertFromString< unsigned char > (const std::string & str)
Template specialization of convertFromString for unsigned char.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 159 of file stringUtils.hpp.
template<> unsigned int mx::convertFromString< unsigned int > (const std::string & str) inline
Template specialization of convertFromString for unsigned int.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 208 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::unsignedInt().
template<> unsigned long mx::convertFromString< unsigned long > (const std::string & str) inline
Template specialization of convertFromString for unsigned long.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 232 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::unsignedLong().
template<> unsigned long long mx::convertFromString< unsigned long long > (const std::string & str) inline
Template specialization of convertFromString for unsigned long long.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 256 of file stringUtils.hpp.
Referenced by mx::improc::fitsHeaderCard::unsignedLongLong().
template<> unsigned short mx::convertFromString< unsigned short > (const std::string & str) inline
Template specialization of convertFromString for unsigned short.
Returns
the converted numerical value.
Parameters
[in] str is the string to convert
Definition at line 184 of file stringUtils.hpp.
template<typename typeT , unsigned width = 0, char pad = ' '> std::string mx::convertToString (const typeT & value, int precision = 0)
Convert a numerical value to a string.
The default version uses the stream library to convert. A specialization is provided to prevent conversion of std::string.
The precision parameter is only used for floating point types. If the default precision==0 is passed, then the maximum useful precision is used, from the value of std::numeric_limits<typeT>::max_digits10.
The width and pad template parameters can be used to set a fixed maximum width and a pad character.
Examples:
To convert a double precision number to string:
double d = 2.898434;
std::string str;
str = convertToString(d);  //note that you will not normally need to specify <typeT>
To produce a fixed width 0 padded string from an integer:
int i = 23;
std::string str;
str = convertToString<int, 5, '0'>(i);  //result is "00023".
Template Parameters
typeT is the type of value to convert
width specifies the maximum width, not including the '\0'
pad specifies the pad character
Returns
a string representation of value
Parameters
[in] value the value of type typeT to be converted
[in] precision [optional] the precision (see http://www.cplusplus.com/reference/ios/ios_base/precision/) to use for floating point types.
Definition at line 59 of file stringUtils.hpp.
References mx::astro::constants::c().
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::getGridPSD(), mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::makePSDGrid(), mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::takeResponseMatrix(), and mx::AO::sim::simulatedAOSystem< _realT, _wfsT, _reconT, _filterT, _dmT, _turbSeqT >::~simulatedAOSystem().
template<> std::string mx::convertToString< std::string > (const std::string & value, int precision) inline
Specialization of convertToString to avoid converting a string to a string.
Definition at line 104 of file stringUtils.hpp.
template<typename iosT > void mx::textTable::outPut (iosT & ios)
Output the table to a stream.
Prints the table to the stream, with separators, etc.
Template Parameters
iosT is a std::ostream-like type.
Parameters
[in] ios a std::ostream-like stream.
Definition at line 118 of file textTable.hpp.
References mx::textTable::colSep, mx::textTable::colWidths, mx::astro::constants::k(), mx::textTable::lineEnd, mx::textTable::lineStart, mx::textTable::rows, and mx::textTable::rowSep.
Referenced by mx::application::help().
void mx::removeWhiteSpace (std::string & outstr, const std::string & instr) inline
Remove all white space from a string.
Uses std::remove_if.
Parameters
[out] instr will contain the new string with no whitespace. [in] is the string to remove whitespace from
Definition at line 394 of file stringUtils.hpp.
Referenced by mx::astro::numSpType(), and mx::removeWhiteSpace().
std::string mx::removeWhiteSpace (const std::string & instr) inline
Remove all white space from a string.
Uses std::remove_if.
Returns
the modified string.
Parameters
[in] instr is the string to remove whitespace from
Definition at line 410 of file stringUtils.hpp.
References mx::removeWhiteSpace().
int mx::stringWrap (std::vector< std::string > & lines, const std::string & str, int width) inline
Wrap a string by breaking it into smaller sized portions of a desired width.
Whenever possible breaks at spaces. A single space is discarded at the break.
Parameters
[out] lines each new entry contains a wrapped portion of the string. Not cleared, so can accumulate.
[in] str the string to wrap
[in] width the maximum width of the output strings
Definition at line 424 of file stringUtils.hpp.
Referenced by mx::textTable::addCell().
void mx::toLower (std::string & outstr, const std::string & instr) inline
Convert a string to all lower case.
Calls the c tolower function for each character in instr.
Parameters
[out] outstr will be resized and populated with the lower case characters
[in] instr is the string to convert
Definition at line 326 of file stringUtils.hpp.
Referenced by mx::toLower().
std::string mx::toLower (const std::string & instr) inline
Convert a string to all lower case.
Calls the c tolower function for each character in instr.
Returns
the all lower case string
Parameters
[in] instr is the string to convert
Definition at line 346 of file stringUtils.hpp.
References mx::toLower().
void mx::toUpper (std::string & outstr, const std::string & instr) inline
Convert a string to all upper case.
Calls the c toupper function for each character in instr.
Parameters
[out] outstr will be resized and populated with the lower case characters
[in] instr is the string to convert
Definition at line 360 of file stringUtils.hpp.
Referenced by mx::astro::numSpType(), and mx::toUpper().
std::string mx::toUpper (const std::string & instr) inline
Convert a string to all upper case.
Calls the c toupper function for each character in instr.
Returns
the all lower case string
Parameters
[in] instr is the string to convert
Definition at line 380 of file stringUtils.hpp.
References mx::toUpper().