mxlib: Vector Utilities
Vector Utilities
General Mathematics
Utilities for working with std::vector.
Utilities for working with std::vector.
template<typename vectorT >
void mx::math::vectorScale (vectorT &vec, size_t N=0, typename vectorT::value_type scale=0, typename vectorT::value_type offset=0)
Fill in a vector with a regularly spaced scale.
template<typename memberT >
std::vector< size_t > mx::math::vectorSortOrder (std::vector< memberT > const &values)
Return the indices of the vector in sorted order, without altering the vector itself.
template<typename vectorT >
vectorT::value_type mx::math::vectorMean (const vectorT &vec)
Calculate the mean of a vector.
template<typename vectorT >
vectorT::value_type mx::math::vectorMean (const vectorT &vec, const vectorT &w)
Calculate the weighted mean of a vector.
template<typename vectorT >
vectorT::value_type mx::math::vectorMedianInPlace (vectorT &vec)
Calculate median of a vector in-place, altering the vector.
template<typename vectorT >
vectorT::value_type mx::math::vectorMedian (const vectorT &vec, vectorT *work=0)
Calculate median of a vector, leaving the vector unaltered.
template<typename vectorT >
vectorT::value_type mx::math::vectorVariance (const vectorT &vec, typename vectorT::value_type &mean)
Calculate the variance of a vector relative to a supplied mean value.
template<typename vectorT >
vectorT::value_type mx::math::vectorVariance (const vectorT &vec)
Calculate the variance of a vector.
template<typename vectorT >
vectorT::value_type mx::math::vectorSigmaMean (const vectorT &vec, const vectorT *weights, typename vectorT::value_type sigma, int &maxPasses)
Calculate the sigma-clipped mean of a vector.
template<typename vectorT >
vectorT::value_type mx::math::vectorSigmaMean (const vectorT &vec, typename vectorT::value_type sigma)
template<typename vectorT >
vectorT::value_type mx::math::vectorSigmaMean (const vectorT &vec, const vectorT &weights, typename vectorT::value_type sigma, int &maxPasses)
template<typename vectorT >
vectorT::value_type mx::math::vectorSigmaMean (const vectorT &vec, const vectorT &weights, typename vectorT::value_type sigma)
template<typename realT >
int mx::math::vectorSmoothMean (std::vector< realT > &smVec, std::vector< realT > &vec, int win)
Smooth a vector using the mean in a window specified by its full-width.
Function Documentation
template<typename vectorT > vectorT::value_type mx::math::vectorMean (const vectorT & vec)
Calculate the mean of a vector.
Returns
the mean of vec
Template Parameters
vectorT the std::vector type of vec
Parameters
[in] vec the vector
Definition at line 89 of file vectorUtils.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::center(), and mx::improc::eigenCube< dataT >::mean().
template<typename vectorT > vectorT::value_type mx::math::vectorMean (const vectorT & vec, const vectorT & w)
Calculate the weighted mean of a vector.
Returns
the weighted mean of vec
Template Parameters
vectorT the std::vector type of vec and w
Parameters
[in] vec the vector */
[in] w the weights
Definition at line 108 of file vectorUtils.hpp.
Referenced by mx::math::vectorSigmaMean(), and mx::math::vectorVariance().
template<typename vectorT > vectorT::value_type mx::math::vectorMedian (const vectorT & vec, vectorT * work = 0)
Calculate median of a vector, leaving the vector unaltered.
Returns the center element if vec has an odd number of elements. Returns the mean of the center 2 elements if vec has an even number of elements.
Returns
the median of vec
Template Parameters
vectorT the std::vector type of vec
Parameters
[in] vec the vector for which the median is desired
[in] work [optional] an optional vector to use as workspace, use to avoid re-allocation
Definition at line 164 of file vectorUtils.hpp.
References mx::math::vectorMedianInPlace().
Referenced by mx::math::vectorSigmaMean().
template<typename vectorT > vectorT::value_type mx::math::vectorMedianInPlace (vectorT & vec)
Calculate median of a vector in-place, altering the vector.
Returns the center element if vec has an odd number of elements. Returns the mean of the center 2 elements if vec has an even number of elements.
Returns
the median of vec
Template Parameters
vectorT the std::vector type of vec
Parameters
[in] vec the vector, is altered by std::nth_element
Definition at line 135 of file vectorUtils.hpp.
Referenced by mx::improc::imageMedian(), and mx::math::vectorMedian().
template<typename vectorT > void mx::math::vectorScale (vectorT & vec, size_t N = 0, typename vectorT::value_type scale = 0, typename vectorT::value_type offset = 0)
Fill in a vector with a regularly spaced scale.
Fills in the vector with a 0....N-1 scale. The spacing of the points can be changed with the scale parameter, and the starting point can be changed with the offset.
Example:
std::vector vec;
mx::vectorScale(vec, 1000, 0.001, 0.001); // Produces a vector with values 0.001,0.002,.... 1.000
Template Parameters
vectorT is a std::vector type.
Parameters
[out] vec the vector to fill in, can be pre-allocated or not
[in] N [optional] if specified > 0, then vec is resize()-ed. Default is 0, and vec is not resize()-ed.
[in] scale [optional] if specified !=0, then the points are spaced by this value. Default spacing is 1.
[in] offset [optional] if specified !=0, then the starting point of the scale is this value.
Definition at line 39 of file vectorUtils.hpp.
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::makePSDGrid().
template<typename vectorT > vectorT::value_type mx::math::vectorSigmaMean (const vectorT & vec, const vectorT * weights, typename vectorT::value_type sigma, int & maxPasses)
Calculate the sigma-clipped mean of a vector.
Performas sigma-clipping relative to the median, removing any values with deviation from the median > sigma. Continues until either no values are removed, or maxPasses iterations. If maxPasses == 0, then it is ignored.
Returns
the sigma clipped mean of vec
Template Parameters
vectorT the std::vector type of vec
Parameters
[in] vec the vector (unaltered)
[in] weights [optional] the weights (unaltered)
[in] sigma the standard deviation threshold to apply.
[in,out] maxPasses [optional] the maximum number of sigma-clipping passes. Set to actual number of passes on return.
Definition at line 240 of file vectorUtils.hpp.
References mx::astro::constants::sigma(), mx::math::vectorMean(), mx::math::vectorMedian(), and mx::math::vectorVariance().
Referenced by mx::improc::eigenCube< dataT >::sigmaMean().
template<typename vectorT > vectorT::value_type mx::math::vectorSigmaMean (const vectorT & vec, typename vectorT::value_type sigma)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] vec the vector (unaltered)
[in] sigma the standard deviation threshold to apply.
Definition at line 321 of file vectorUtils.hpp.
References mx::math::vectorSigmaMean().
template<typename vectorT > vectorT::value_type mx::math::vectorSigmaMean (const vectorT & vec, const vectorT & weights, typename vectorT::value_type sigma, int & maxPasses)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] vec the vector (unaltered)
[in] weights [optional] the weights (unaltered)
[in] sigma the standard deviation threshold to apply.
[in,out] maxPasses [optional] the maximum number of sigma-clipping passes. Set to actual number of passes on return.
Definition at line 334 of file vectorUtils.hpp.
References mx::math::vectorSigmaMean().
template<typename vectorT > vectorT::value_type mx::math::vectorSigmaMean (const vectorT & vec, const vectorT & weights, typename vectorT::value_type sigma)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] vec the vector (unaltered)
[in] weights [optional] the weights (unaltered)
[in] sigma the standard deviation threshold to apply.
Definition at line 348 of file vectorUtils.hpp.
Referenced by mx::math::vectorSigmaMean().
template<typename realT > int mx::math::vectorSmoothMean (std::vector< realT > & smVec, std::vector< realT > & vec, int win)
Smooth a vector using the mean in a window specified by its full-width.
Parameters
[out] smVec the smoothed version of the vector
[in] vec the input vector, unaltered.
[in] win the full-width of the smoothing window
Definition at line 361 of file vectorUtils.hpp.
template<typename memberT > std::vector<size_t> mx::math::vectorSortOrder (std::vector< memberT > const & values)
Return the indices of the vector in sorted order, without altering the vector itself.
Example:
std::vector<double> x;
// -> fill in x with values
std::vector<size_t> idx;
idx = mx::sortOrder(x);
//Print x to stdout in sorted order
for(int i=0; i< x.size(); ++i) std::cout << x[idx[i]] << "\n";
Template Parameters
memberT is the member type of the vector. Must have < comparison defined.
Returns
the indices of the vector in sorted order.
Parameters
[in] values the vector to sort
Definition at line 69 of file vectorUtils.hpp.
template<typename vectorT > vectorT::value_type mx::math::vectorVariance (const vectorT & vec, typename vectorT::value_type & mean)
Calculate the variance of a vector relative to a supplied mean value.
Returns
the variance of vec w.r.t. mean
Template Parameters
vectorT the std::vector type of vec
Parameters
[in] vec the vector
[in] mean the mean value with which to calculate the variance
Definition at line 199 of file vectorUtils.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::center(), and mx::improc::stddevImage().
template<typename vectorT > vectorT::value_type mx::math::vectorVariance (const vectorT & vec)
Calculate the variance of a vector.
Returns
the variance of vec
Template Parameters
vectorT the std::vector type of vec
Parameters
[in] vec the vector
Definition at line 221 of file vectorUtils.hpp.
References mx::math::vectorMean().
Referenced by mx::math::vectorSigmaMean().