mxlib: Power Spectra
Power Spectra
Signal Processing
Tools for generating and manipulating power spectra.
Tools for generating and manipulating power spectra.
Classes
class mx::sigproc::psdFilter< _realT >
A class for filtering noise with PSDs.
template<class realT >
realT mx::sigproc::freq_sampling (size_t dim, realT f_max)
Calculates the frequency sampling for a grid given maximum dimension and maximum frequency.
template<typename eigenArr >
void mx::sigproc::frequency_grid1D (eigenArr &vec, typename eigenArr::Scalar dt, bool inverse=false)
Create a 1-D frequency grid.
template<typename eigenArr >
void mx::sigproc::frequency_grid (eigenArr &arr, typename eigenArr::Scalar dt)
Create a frequency grid.
template<typename realT >
realT mx::sigproc::oneoverf_norm (realT fmin, realT fmax, realT alpha)
Calculate the normalization for a 1-D \(1/|f|^\alpha \) PSD.
template<typename realT >
realT mx::sigproc::oneoverk_norm (realT kmin, realT kmax, realT alpha)
Calculate the normalization for a 2-D \(1/|k|^\alpha \) PSD.
template<typename eigenArrp , typename eigenArrf >
void mx::sigproc::oneoverf_psd (eigenArrp &psd, eigenArrf &freq, typename eigenArrp::Scalar alpha, typename eigenArrp::Scalar beta=-1)
Generates a \(1/|f|^\alpha \) power spectrum.
template<typename eigenArrp , typename eigenArrf >
void mx::sigproc::vonKarman_psd (eigenArrp &psd, eigenArrf &freq, typename eigenArrp::Scalar alpha, typename eigenArrp::Scalar L0=0, typename eigenArrp::Scalar l0=0, typename eigenArrp::Scalar beta=-1)
Generates a von Karman power spectrum.
template<typename floatT >
void mx::sigproc::averagePeriodogram (std::vector< floatT > &pgram, std::vector< floatT > &ts, floatT dt, floatT avgLen, floatT olap, std::vector< floatT > &w)
Calculate the average periodogram from a time series for a specified averaging interval and overlap.
template<typename vectorTout , typename vectorTin >
void mx::sigproc::augment1SidedPSD (vectorTout &psdTwoSided, vectorTin &psdOneSided, bool zeroFreq=false, typename vectorTin::value_type scale=1)
Augment a 1-sided PSD to standard 2-sided FFT form.
template<typename T >
void mx::sigproc::augment1SidedPSDFreq (std::vector< T > &freqTwoSided, std::vector< T > &freqOneSided)
Augment a 1-sided frequency scale to standard FFT form.
Function Documentation
template<typename vectorTout , typename vectorTin > void mx::sigproc::augment1SidedPSD (vectorTout & psdTwoSided, vectorTin & psdOneSided, bool zeroFreq = false, typename vectorTin::value_type scale = 1)
Augment a 1-sided PSD to standard 2-sided FFT form.
Allocates psdTwoSided to hold a flipped copy of psdOneSided. Default assumes that psdOneSided[0] corresponds to 0 frequency, but this can be changed by setting zeroFreq to a non-zero value. In this case psdTwoSided[0] is set to 0, and the augmented psd is shifted by 1.
Example:
{1,2,3,4,5} –> {0,1,2,3,4,5,-4,-3,-2,-1}
Entries in psdOneSided are cast to the value_type of psdTwoSided, for instance to allow for conversion to complex type.
Parameters
[out] psdTwoSided on return contains the FFT storage order copy of psdOneSided.
[in] psdOneSided the one-sided PSD to augment
[in] zeroFreq [optional] set to true if psdOneSided does not contain a zero frequency component.
[in] scale [optional] value to scale the input by when copying to the output. Use 0.5 if power needs to be re-normalized for 2-sided PSD.
Definition at line 388 of file psdUtils.hpp.
Referenced by mx::AO::analysis::clAOLinearPredictor< _realT >::calcCoefficients().
template<typename T > void mx::sigproc::augment1SidedPSDFreq (std::vector< T > & freqTwoSided, std::vector< T > & freqOneSided)
Augment a 1-sided frequency scale to standard FFT form.
Allocates freqTwoSided to hold a flipped copy of freqOneSided. If freqOneSided[0] is not 0, freqTwoSided[0] is set to 0, and the augmented frequency scale is shifted by 1.
Example:
{1,2,3,4,5} –> {0,1,2,3,4,5,-4,-3,-2,-1}
Parameters
[out] freqTwoSided on return contains the FFT storage order copy of freqOneSided.
[in] freqOneSided the one-sided frequency scale to augment
Definition at line 444 of file psdUtils.hpp.
template<typename floatT > void mx::sigproc::averagePeriodogram (std::vector< floatT > & pgram, std::vector< floatT > & ts, floatT dt, floatT avgLen, floatT olap, std::vector< floatT > & w)
Calculate the average periodogram from a time series for a specified averaging interval and overlap.
The time series should be mean subtracted before passing to this function.
Parameters
[out] pgram the resultant periodogram.
[in] ts is input the time-series.
[in] dt is the sampling time of time-series.
[in] avgLen is the length of the averaging interval, same units as dt.
[in] olap is the length of the overlap region, same units as avgLen.
[in] w a vector of length ((int) avgLen/dt) containing a window. If empty then then the square window is used.
Definition at line 324 of file psdUtils.hpp.
template<class realT > realT mx::sigproc::freq_sampling (size_t dim, realT f_max)
Calculates the frequency sampling for a grid given maximum dimension and maximum frequency.
The freq_sampling is \(\Delta f = f_{max}/ (0.5*dim) \) where \(f_{max} = 1/(2\Delta t) \) is the maximum frequency and \(dim \) is the size of the grid.
Parameters
[in] dim is the size of the grid
[in] f_max is the maximum frequency of the grid
Returns
the sampling interval \(\delta f \)
Template Parameters
realT is the real floating point type used for calculations.
Definition at line 38 of file psdUtils.hpp.
Referenced by mx::sigproc::frequency_grid(), and mx::sigproc::frequency_grid1D().
template<typename eigenArr > void mx::sigproc::frequency_grid (eigenArr & arr, typename eigenArr::Scalar dt)
Create a frequency grid.
Definition at line 90 of file psdUtils.hpp.
References mx::sigproc::freq_sampling().
Referenced by mx::AO::sim::turbAtmosphere< _realT >::setup().
template<typename eigenArr > void mx::sigproc::frequency_grid1D (eigenArr & vec, typename eigenArr::Scalar dt, bool inverse = false)
Create a 1-D frequency grid.
Parameters
[out] vec the pre-allocated Eigen-type 1xN or Nx1 array, on return contains the frequency grid
[in] dt the temporal sampling of the time series
[in] inverse [optional] if true
Template Parameters
eigenArr the Eigen-like array type
Definition at line 53 of file psdUtils.hpp.
References mx::sigproc::freq_sampling().
template<typename realT > realT mx::sigproc::oneoverf_norm (realT fmin, realT fmax, realT alpha)
Calculate the normalization for a 1-D \(1/|f|^\alpha \) PSD.
Parameters
[in] fmin is the minimum non-zero absolute value of frequency
[in] fmax is the maximum absolute value of frequencey
[in] alpha is the power-law exponent, by convention \(\alpha > 0 \).
Returns
the normalization for a 2-sided power law PSD.
Template Parameters
realT is the real floating point type used for calculations.
Definition at line 149 of file psdUtils.hpp.
Referenced by mx::sigproc::oneoverf_psd(), and mx::sigproc::vonKarman_psd().
template<typename eigenArrp , typename eigenArrf > void mx::sigproc::oneoverf_psd (eigenArrp & psd, eigenArrf & freq, typename eigenArrp::Scalar alpha, typename eigenArrp::Scalar beta = -1)
Generates a \(1/|f|^\alpha \) power spectrum.
Populates an Eigen array with
\[ P(|f| = 0) = 0 \]
\[ P(|f| > 0) = \frac{\beta}{|f|^{\alpha}} \]
Parameters
[out] psd is the array to populate
[in] freq is a frequency grid, must be the same logical size as psd
[in] alpha is the power law exponent, by convention \(alpha > 0 \).
[in] beta [optional is a normalization constant to multiply the raw spectrum by. If beta==-1 (default) then the PSD is normalized using oneoverf_norm.
Template Parameters
eigenArrp is the Eigen-like array type of the psd
eigenArrf is the Eigen-like array type of the frequency grid
Definition at line 195 of file psdUtils.hpp.
References mx::sigproc::oneoverf_norm().
template<typename realT > realT mx::sigproc::oneoverk_norm (realT kmin, realT kmax, realT alpha)
Calculate the normalization for a 2-D \(1/|k|^\alpha \) PSD.
Parameters
[in] kmin is the minimum non-zero absolute value of frequency
[in] kmax is the maximum absolute value of frequencey
[in] alpha is the power-law exponent, by convention \(\alpha > 0 \).
Returns
the normalization for a 2-D, 2-sided power law PSD.
Template Parameters
realT is the real floating point type used for calculations.
Definition at line 167 of file psdUtils.hpp.
template<typename eigenArrp , typename eigenArrf > void mx::sigproc::vonKarman_psd (eigenArrp & psd, eigenArrf & freq, typename eigenArrp::Scalar alpha, typename eigenArrp::Scalar L0 = 0, typename eigenArrp::Scalar l0 = 0, typename eigenArrp::Scalar beta = -1)
Generates a von Karman power spectrum.
Populates an Eigen array with
\[ P(k) = \frac{\beta}{ (k^2 + (1/L_0)^2)^{\alpha/2}} e^{ - k^2 l_0^2} \]
If you set \(L_0 \le 0 \) and \(l_0 = 0\) this reverts to a simple \(1/f^\alpha \) law (i.e. it treats this as infinite outer scale and inner scale).
Parameters
[out] psd is the array to populate, allocated.
[in] freq is a frequency grid, must be the same logical size as psd
[in] alpha is the power law exponent, by convention \(alpha > 0 \).
[in] L0 [optional] is the outer scale.
[in] l0 [optional] is the inner scale.
[in] beta [optional] is a normalization constant to multiply the raw spectrum by. If beta==-1 (default) then the PSD is normalized using oneoverf_norm.
Template Parameters
eigenArrp is the Eigen array type of the psd
eigenArrf is the Eigen array type of the frequency grid
Definition at line 263 of file psdUtils.hpp.
References mx::sigproc::oneoverf_norm().