mxlib: Astronomical Photometry
Astronomical Photometry
Astronomy
Files
file astroFilter.hpp
Utilities for working with astronomical filters and spectra.
file astroSpectra.hpp
Type definitions for the astronomical spectral libraries.
Functions
template<typename dataT >
void mx::astrofiltNormalize (std::vector< dataT > &trans)
Normalize a transmission profile to have peak value of 1.0.
template<typename dataT >
void mx::astrofiltTrimWavelength (std::vector< dataT > &lambda, std::vector< dataT > &spectrum, dataT lambda_0, dataT lambda_f)
Erase points at beginning and end to trim unwanted data from a spectrum.
template<typename dataT >
void mx::astrofiltTrimWavelength (std::vector< dataT > &lambda, std::vector< dataT > &spectrum, std::vector< dataT > &lambda_ref)
Erase points at beginning and end to trim unwanted data from a spectrum.
template<typename dataT >
void mx::astrofiltRSR (std::vector< dataT > &lambda, std::vector< dataT > &trans)
Convert a transmission profile to relative spectral response.
template<typename dataT >
void mx::astrofilt (std::vector< dataT > &lambda, std::vector< dataT > &trans, const std::string &filtName, bool rsr=false, const std::string &datadir="")
Read a filter transmission curve from the astrofilt collection.
template<typename dataT >
void mx::astrofiltCharTrans (dataT &lambda0, dataT &fwhm, dataT &weff, std::vector< dataT > &lambda, std::vector< dataT > &trans)
Characterize the wavelength of a filter transmission curve.
template<typename dataT >
void mx::astrofiltCharFlux (dataT &flambda0, dataT &fnu0, dataT &fphot0, std::vector< dataT > &lambda_f, std::vector< dataT > &trans, std::vector< dataT > &lambda_s, std::vector< dataT > &flambda)
Characterize the fluxes of a filter transmission curve w.r.t. a spectrum.
template<typename dataT >
void mx::astrofiltCharVega (dataT &flambda0, dataT &fnu0, dataT &fphot0, std::vector< dataT > &lambda, std::vector< dataT > &trans)
Characterize the fluxes of a filter transmission curve w.r.t. Vega.
template<typename dataT >
void mx::astrofiltMultiply (std::vector< dataT > &spectrum_out, std::vector< dataT > &lambda_1, std::vector< dataT > &spectrum_1, std::vector< dataT > &lambda_2, std::vector< dataT > &spectrum_2)
Multiply two spectra or filter curves.
template<typename dataT >
void mx::astrofiltMultiply (std::vector< dataT > &spectrum, dataT scale, std::vector< dataT > &spectrum_out)
Multiply a spectrum or filter curve by a scalar.
template<typename dataT >
void mx::astrofiltScaleMag (std::vector< dataT > &lambda_s, std::vector< dataT > &spectrum, std::vector< dataT > &lambda_f, std::vector< dataT > &trans, dataT mag, int scaleBy=0)
Scale a spectrum to a specified Vega magnitude in a filter.
template<typename dataT >
void mx::astrofiltScaleMean (std::vector< dataT > &lambda_s, std::vector< dataT > &spectrum, std::vector< dataT > &lambda_f, std::vector< dataT > &trans, dataT mean, int scaleBy=0)
Scale a spectrum to a specified mean value in a filter.
template<typename dataT >
void mx::readPickles (std::vector< dataT > &lambda, std::vector< dataT > &flambda, const std::string &spt, const std::string &datadir="")
Read a Pickles atlas spectrum.
template<typename dataT >
void mx::readCalspec (std::vector< dataT > &lambda, std::vector< dataT > &flambda, const std::string &spName, const std::string &datadir)
Read an HST Calspec spectrum.
template<typename dataT >
void mx::readATRAN (std::vector< dataT > &lambda, std::vector< dataT > &trans, const std::string &site, double pwv, double airmass, const std::string &datadir="")
Read the ATRAN atmospheric transmission spectrum from Gemini.
template<typename dataT >
void mx::readBTRAM (std::vector< dataT > &lambda, std::vector< dataT > &trans, const std::string &site, const std::string &run, double pwv, double zd, const std::string &datadir="")
Read a BTRAM atmospheric transmission spectrum.
template<typename floatT >
void mx::rewritePhoenixSpectrum (const std::string &filename, floatT lmin, floatT lmax)
Read in, crop, and re-write a Phoenix spectrum data file.
template<typename dataT >
void mx::readPhoenix (std::vector< dataT > &lambda, std::vector< dataT > &flambda, const std::string &filename, int scale=1, dataT radius=1)
Read a Phoenix model spectrum.
template<typename dataT >
void mx::readEarthShine (std::vector< dataT > &lambda, std::vector< dataT > &albedo, std::string &datadir="")
Read the Earthshine spectrum.
template<typename dataT >
void mx::readEarthShine (std::vector< dataT > &lambda, std::vector< dataT > &albedo)
Read the Earthshine spectrum.
Function Documentation
template<typename dataT > void mx::astrofilt (std::vector< dataT > & lambda, std::vector< dataT > & trans, const std::string & filtName, bool rsr = false, const std::string & datadir = "")
Read a filter transmission curve from the astrofilt collection.
Reads in a filter transmission curve from the astrofilt collection, usually found via the ASTROFILT_DATADIR environment variable. Astrofilt profiles are in wavelength of microns, and transmission normalized to peak of 1 and airmass 0.
Parameters
lam [out] the profile wavelength scale, in microns. Is cleared.
trans [out] the transmission at each lambda, normalized to a peak of 1 at 0 airmass. Is cleared.
filtName [in] the name of the filter, with no path or extension, e.g. 'J_NIRC2' or 'ip_VisAO'
rsr [in] [optional] if true converts to relative spectral response, appropriate for photon detectors (like CCDs). See Bessell, PASP, 112, 961 (2000).
datadir [in] [optional] specifies the data directory. if not set or empty, the environment is queried for then value of ASTROFILT_DATADIR.
Template Parameters
dataT the type of data to return
Definition at line 181 of file astroFilter.hpp.
References mx::astrofiltRSR(), mx::getEnv(), and mx::readColumns().
template<typename dataT > void mx::astrofiltCharFlux (dataT & flambda0, dataT & fnu0, dataT & fphot0, std::vector< dataT > & lambda_f, std::vector< dataT > & trans, std::vector< dataT > & lambda_s, std::vector< dataT > & flambda)
Characterize the fluxes of a filter transmission curve w.r.t. a spectrum.
Parameters
flambda0 [out] the flux of the star at \(\lambda_0 \) in ergs/sec/um/cm^2
fnu0 [out] the flux of the star at \(\lambda_0 \) in Jy
fphot0 [out] the flux of the star at \(\lambda_0 \) in photons/sec/m^2
lambda_f [in] the wavelength grid of the filter
trans [in] the transmission of the filter at each wavelength
lambda_s [in] the wavelength scale of the spectrum
flambda [in] the spectrum
Template Parameters
dataT the data type in which calculations are performed.
Definition at line 284 of file astroFilter.hpp.
References mx::astro::constants::c(), mx::gsl_interpolate(), and mx::astro::constants::h().
Referenced by mx::astrofiltCharVega(), mx::astrofiltScaleMag(), and mx::astrofiltScaleMean().
template<typename dataT > void mx::astrofiltCharTrans (dataT & lambda0, dataT & fwhm, dataT & weff, std::vector< dataT > & lambda, std::vector< dataT > & trans)
Characterize the wavelength of a filter transmission curve.
For a transmission curve given by \(T(\lambda) \) The central wavelength is defined as \(\lambda_0 = \frac{1}{w_{eff}}\int T(\lambda) \lambda d\lambda \) where the effective width is defined by \(w_{eff} = \int T(\lambda) d\lambda \)
The full-width at half-maximum, FWHM, is the distance between the points at 50% of maximum \(T(\lambda) \).
Parameters
lambda0 [out] the central wavelength of the filter
fwhm [out] the full-width at half-maximum of the filter profile
weff [out] the effective width of the filter
lambda [in] the wavelength grid of the profile
trans [in] the transmission of the profile at each wavelength
Template Parameters
dataT the data type in which calculations are performed.
Definition at line 228 of file astroFilter.hpp.
template<typename dataT > void mx::astrofiltCharVega (dataT & flambda0, dataT & fnu0, dataT & fphot0, std::vector< dataT > & lambda, std::vector< dataT > & trans)
Characterize the fluxes of a filter transmission curve w.r.t. Vega.
Uses the HST Calspec spectrum of Vega.
Parameters
flambda0 [out] the flux of a 0 mag star at \(\lambda_0 \) in ergs/sec/um/cm^2
fnu0 [out] the flux of a 0 mag star at \(\lambda_0 \) in Jy
fphot0 [out] the flux of a 0 mag star at \(\lambda_0 \) in photons/sec/m^2
lambda [in] the wavelength grid of the profile
trans [in] the transmission of the profile at each wavelength
Template Parameters
dataT the data type in which calculations are performed.
Definition at line 369 of file astroFilter.hpp.
References mx::astrofiltCharFlux(), and mx::readCalspec().
Referenced by mx::astrofiltScaleMag().
template<typename dataT > void mx::astrofiltMultiply (std::vector< dataT > & spectrum_out, std::vector< dataT > & lambda_1, std::vector< dataT > & spectrum_1, std::vector< dataT > & lambda_2, std::vector< dataT > & spectrum_2)
Multiply two spectra or filter curves.
Interpolates the 2nd onto the 1st, so that the wavelength scale of the output is lambda_1.
Parameters
[out] spectrum_out the product of spectrum_1 and the re-sampled spectrum_2
[in] lambda_1 the first (higher sampling) wavelength scale
[in] spectrum_1 the first (higher sampling) spectrum
[in] lambda_2 the second wavelength scale
[in] spectrum_2 the second spectrum, will be re-sampled onto lambda_1
Template Parameters
dataT the type of the data
Definition at line 398 of file astroFilter.hpp.
References mx::gsl_interpolate().
template<typename dataT > void mx::astrofiltMultiply (std::vector< dataT > & spectrum, dataT scale, std::vector< dataT > & spectrum_out)
Multiply a spectrum or filter curve by a scalar.
Parameters
spectrum the spectrum
scale the scale to multiply by
spectrum_out the product of spectrum_1 and the re-sampled spectrum_2
Template Parameters
dataT the type of the data
Definition at line 423 of file astroFilter.hpp.
template<typename dataT > void mx::astrofiltNormalize (std::vector< dataT > & trans)
Normalize a transmission profile to have peak value of 1.0.
Parameters
trans the transmission profile to be normalized. Is altered.
Template Parameters
dataT the type of data to return
Definition at line 58 of file astroFilter.hpp.
template<typename dataT > void mx::astrofiltRSR (std::vector< dataT > & lambda, std::vector< dataT > & trans)
Convert a transmission profile to relative spectral response.
The relative spectral response is given by
\(T_{RSR}(\lambda) = T(\lambda)\lambda / \mbox{max}[T(\lambda)\lambda] \)
where \(T(\lambda) \) is the energy transmission profile. This is appropriate for photon detectors (like CCDs). See Bessell, PASP, 112, 961 (2000).
Parameters
lambda [in] The wavelength scale
trans [in] The transmission profile
Template Parameters
dataT the type of the data
Definition at line 148 of file astroFilter.hpp.
Referenced by mx::astrofilt().
template<typename dataT > void mx::astrofiltScaleMag (std::vector< dataT > & lambda_s, std::vector< dataT > & spectrum, std::vector< dataT > & lambda_f, std::vector< dataT > & trans, dataT mag, int scaleBy = 0)
Scale a spectrum to a specified Vega magnitude in a filter.
Scales the spectrum to have the specified Vega magnitude, using the HST Calspec Vega spectrum. The spectrum can be scaled by \(f_\lambda \), \(f_\nu \), or \(f_\gamma \).
Parameters
lambda_s wavelength scale of the spectrum
spectrum the spectrum to scale, will be be altered
lambda_f the wavelength scale of the filter
trans the transmission profile of the filter
mag the desired magnitude in the filter
scaleBy specifies which flux measurement to scale by. \(0 = f_\lambda \), \(1=f_\nu \), or \(2=f_\gamma \)
Template Parameters
dataT the type of the data
Definition at line 452 of file astroFilter.hpp.
References mx::astrofiltCharFlux(), and mx::astrofiltCharVega().
template<typename dataT > void mx::astrofiltScaleMean (std::vector< dataT > & lambda_s, std::vector< dataT > & spectrum, std::vector< dataT > & lambda_f, std::vector< dataT > & trans, dataT mean, int scaleBy = 0)
Scale a spectrum to a specified mean value in a filter.
Scales the spectrum to have the specified mean value. The spectrum can be scaled by \(f_\lambda \), \(f_\nu \), or \(f_\gamma \).
Parameters
lambda_s wavelength scale of the spectrum
spectrum the spectrum to scale, will be be altered
lambda_f the wavelength scale of the filter
trans the transmission profile of the filter
mean the desired mean value in the filter
scaleBy specifies which flux measurement to scale by. \(0 = f_\lambda \), \(1=f_\nu \), or \(2=f_\gamma \)
Template Parameters
dataT the type of the data
Definition at line 503 of file astroFilter.hpp.
References mx::astrofiltCharFlux(), and mx::sigproc::tukey1d().
template<typename dataT > void mx::astrofiltTrimWavelength (std::vector< dataT > & lambda, std::vector< dataT > & spectrum, dataT lambda_0, dataT lambda_f)
Erase points at beginning and end to trim unwanted data from a spectrum.
Parameters
lambda [out] the wavelength points of the spectrum
spectrum [out] the spectrum
lambda_0 [in] the minimum wavelength to be included
lambda_f [in] the maximum wavelength to be include
Template Parameters
dataT the type of the data
Definition at line 76 of file astroFilter.hpp.
Referenced by mx::astrofiltTrimWavelength().
template<typename dataT > void mx::astrofiltTrimWavelength (std::vector< dataT > & lambda, std::vector< dataT > & spectrum, std::vector< dataT > & lambda_ref)
Erase points at beginning and end to trim unwanted data from a spectrum.
Parameters
lambda [out] the wavelength points of the spectrum
spectrum [out] the spectrum
lambda_ref [in] the wavelength grid to use as the reference for min and max.
Template Parameters
dataT the type of the data
Definition at line 127 of file astroFilter.hpp.
References mx::astrofiltTrimWavelength().
template<typename dataT > void mx::readATRAN (std::vector< dataT > & lambda, std::vector< dataT > & trans, const std::string & site, double pwv, double airmass, const std::string & datadir = "")
Read the ATRAN atmospheric transmission spectrum from Gemini.
Parameters
lambda the wavelength scale
trans the transmission
site either "cp" for Cerro Pachon or "mk" for Mauna Kea
pwv precipitable water vaper, for "cp" choices are 2.3, 4.3, 7.6, 10.0. For "mk" choices are 1.0, 1.6, 3.0, 5.0.
airmass airmass, choices are 1.0, 1.5, 2.0.
datadir [optional] the directory containing the Gemini ATRAN files
Template Parameters
dataT the type of data
Definition at line 135 of file astroSpectrum.hpp.
template<typename dataT > void mx::readBTRAM (std::vector< dataT > & lambda, std::vector< dataT > & trans, const std::string & site, const std::string & run, double pwv, double zd, const std::string & datadir = "")
Read a BTRAM atmospheric transmission spectrum.
Parameters
lambda [output] the wavelength scale
trans [output] the transmission
site [input] currently only "manqui", for Cerro Manqui at LCO, is supported.
run [input] the calculation run designation
pwv [input] precipitable water vapor
zd [input] zenith distance
datadir [input] [optional] the directory containing the Gemini ATRAN files
Template Parameters
dataT the type of data
Definition at line 187 of file astroSpectrum.hpp.
template<typename dataT > void mx::readCalspec (std::vector< dataT > & lambda, std::vector< dataT > & flambda, const std::string & spName, const std::string & datadir)
Read an HST Calspec spectrum.
Reads in spectrum from the HST Calspec collection, usually found via the CALSPEC_DATADIR environment variable. Returned spectra are in wavelength of microns, and flux units of ergs/s/um/cm^2 (converted from the native units of Calspec).
Parameters
lambda [output] the profile wavelength scale, in microns.
flambda [output] the spectrum, in ergs/s/micron/cm^2
spName [input] the name of the Calspec star, normally the prefix to the file name.
datadir [input] [optional] the directory containing the Calspec collection
Template Parameters
dataT the type of data to return
Definition at line 68 of file astroSpectrum.hpp.
Referenced by mx::astrofiltCharVega().
template<typename dataT > void mx::readEarthShine (std::vector< dataT > & lambda, std::vector< dataT > & albedo, std::string & datadir = "")
Read the Earthshine spectrum.
Reads the Earthshine spectrum from Turnbull et al (2006) [http://adsabs.harvard.edu/abs/2006ApJ...644..551T].
It is assumed that this is a two column ascii file.
If datadir is empty, looks in the EARTHSHINE_DATADIR environment variable for the path to the data file.
Parameters
lambda [output] the wavelength grid
albedo [output] the albedo in arbitrary units
datadir [input] the directory containing the Earthshine spectrum. If empty will be filled in with environment value of EARTHSHINE_DATADIR
Template Parameters
dataT the data type in which the data file is read and converted from ASCII.
Definition at line 433 of file astroSpectrum.hpp.
template<typename dataT > void mx::readEarthShine (std::vector< dataT > & lambda, std::vector< dataT > & albedo)
Read the Earthshine spectrum.
Reads the Earthshine spectrum from Turnbull et al (2006) [http://adsabs.harvard.edu/abs/2006ApJ...644..551T].
It is assumed that this is a two column ascii file.
Looks in the EARTHSHINE_DATADIR environment variable for the path to the data file.
Parameters
lambda [output] the wavelength grid
albedo [output] the albedo in arbitrary units
Template Parameters
dataT the data type in which the data file is read and converted from ASCII.
Definition at line 468 of file astroSpectrum.hpp.
template<typename dataT > void mx::readPhoenix (std::vector< dataT > & lambda, std::vector< dataT > & flambda, const std::string & filename, int scale = 1, dataT radius = 1)
Read a Phoenix model spectrum.
Reads in a Phoenix model spectrum specified by a filename. Does not prepend PHOENIX_DATADIR.
NOTE: The spectrum must be formatted as if had been processed with rewritePhoenixSpectrum
The units of the spectra are set by the scale parameter, with the following choices
0 == un-changed, returns the raw values from the data files
1 == microns, and ergs/sec/cm^2/micron, assuming the new format
References:
https://phoenix.ens-lyon.fr/Grids/BT-Settl/README
https://phoenix.ens-lyon.fr/Grids/FORMAT
Parameters
lambda [output] the profile wavelength scale, in microns.
flambda [output] the spectrum, in arbitrary f_lambda flux units
filename [input] the subdirectory, specifying which model it is.
scale [input] [optional] whether and how to convert and scale the wavelength and spectrum, default is 1.
radius [input] [optional] if radius >0 and scale !=0 then flux is scaled to 10 pc. In units of Jupiter radii, default is 1 R_jup.
Template Parameters
dataT the type of data to return
Definition at line 392 of file astroSpectrum.hpp.
template<typename dataT > void mx::readPickles (std::vector< dataT > & lambda, std::vector< dataT > & flambda, const std::string & spt, const std::string & datadir = "")
Read a Pickles atlas spectrum.
Reads in spectrum from the Pickles atlas, usually found via the PICKLES_DATADIR environment variable. Returned spectra are in wavelength of microns, and arbitrary f_lambda flux units
Parameters
lambda [output] the wavelength scale, in microns.
flambda [output] the spectrum, in arbitrary f_lambda flux units
spt [input] the spectral type of the star.
datadir [intput] [optional] the directory containing the Pickles atlas
Template Parameters
dataT the type of data to return
Definition at line 29 of file astroSpectrum.hpp.
template<typename floatT > void mx::rewritePhoenixSpectrum (const std::string & filename, floatT lmin, floatT lmax)
Read in, crop, and re-write a Phoenix spectrum data file.
For working with spectra obtained from: http://perso.ens-lyon.fr/france.allard/
The Phoenix spectra contain many columns of line data which are not often used, are not necessarily sorted by wavelength, and are sometimes formated so that points with leading minus signs are not in a separate column. We also have to change the fortan D to e.
This function deals with these issues, producing a two-column space-delimited file in a specified wavelength range.
References:
https://phoenix.ens-lyon.fr/Grids/BT-Settl/README
https://phoenix.ens-lyon.fr/Grids/FORMAT
NOTE: This overwrites the input file!
Parameters
filename [input] complete name of the file to rewrite
lmin [input] minimum wavelength to rewrite [microns]
lmax [input] maximum wavelemngth to rewrite [microns]
Template Parameters
floatT the floating point type in which to work
Definition at line 276 of file astroSpectrum.hpp.