mxlib: Image Masks
Image Masks
Image Processing
Functions for masking images.
Functions for masking images.
Functions
template<class eigenT >
void mx::improc::radiusImage (eigenT &m, typename eigenT::Scalar xc, typename eigenT::Scalar yc, typename eigenT::Scalar scale=1)
Fills in the cells of an Eigen 2D Array with their radius from the center.
template<class eigenT >
void mx::improc::radiusImage (eigenT &m, typename eigenT::Scalar scale=1)
Fills in the cells of Eigen-like 2D Array with their radius from the canonical center.
template<class eigenT >
void mx::improc::angleImage (eigenT &m, typename eigenT::Scalar xc, typename eigenT::Scalar yc, typename eigenT::Scalar scale=radian< typename eigenT::Scalar >())
Fills in the cells of an Eigen-like 2D Array with their angle relative to the center.
template<class eigenT >
void mx::improc::angleImage (eigenT &m, typename eigenT::Scalar scale=radian< typename eigenT::Scalar >())
Fills in the cells of Eigen 2D Array with their angle relative the canonical center.
template<class eigenT >
void mx::improc::radAngImage (eigenT &rIm, eigenT &qIm, typename eigenT::Scalar xc, typename eigenT::Scalar yc, typename eigenT::Scalar rscale=1, typename eigenT::Scalar qscale=radian< typename eigenT::Scalar >())
Fills in the cells of Eigen-like arrays with their radius amd angle relative to the center.
template<typename eigenT >
std::vector< size_t > mx::improc::annulusIndices (eigenT &rIm, eigenT &qIm, typename eigenT::Scalar xcen, typename eigenT::Scalar ycen, typename eigenT::Scalar min_r, typename eigenT::Scalar max_r, typename eigenT::Scalar min_q, typename eigenT::Scalar max_q, eigenT *mask=0)
Get the vector indices of an annular region in an image.
template<class eigenT >
void mx::improc::applyMask (eigenT &maskedIm, const std::vector< size_t > &idx, typename eigenT::Scalar maskval)
Apply a mask to an image.
template<class arrayT >
void mx::improc::maskCircle (arrayT &m, typename arrayT::Scalar xcen, typename arrayT::Scalar ycen, typename arrayT::Scalar rad, typename arrayT::Scalar val=0, typename arrayT::Scalar pixbuf=0.5)
Mask a circle in an image.
template<typename imageTout , typename imageTin >
void mx::improc::cutImageRegion (imageTout &imout, const imageTin &imin, const std::vector< size_t > &idx, bool resize=true)
Cut out a region of an image specified by an index-mask.
template<typename imageTout , typename imageTin >
void mx::improc::insertImageRegion (imageTout imout, const imageTin &imin, const std::vector< size_t > &idx)
Insert a region of an image specified by an index-mask.
Function Documentation
template<class eigenT > void mx::improc::angleImage (eigenT & m, typename eigenT::Scalar xc, typename eigenT::Scalar yc, typename eigenT::Scalar scale = radian<typename eigenT::Scalar>())
Fills in the cells of an Eigen-like 2D Array with their angle relative to the center.
Template Parameters
eigenT is an Eigen-like 2D array type
Parameters
[out] m the allocated angle array. Will be filled in with angle values.
[in] xc the x center
[in] yc the y center
[in] scale [optional] a scaling to apply to each angle value. Default converts to degrees, set to 1 for radians.
Definition at line 87 of file imageMasks.hpp.
template<class eigenT > void mx::improc::angleImage (eigenT & m, typename eigenT::Scalar scale = radian<typename eigenT::Scalar>())
Fills in the cells of Eigen 2D Array with their angle relative the canonical center.
The center is \((x_c, y_c) = (0.5*(dim_1-1), 0.5*(dim_2 -1)) \).
Template Parameters
eigenT is an Eigen-like 2D array type
Parameters
[out] m the allocated angle array. Will be filled in with angle values.
[in] scale [optional] a scaling to apply to each angle value. Default converts to degrees, set to 1 for radians.
Definition at line 121 of file imageMasks.hpp.
template<typename eigenT > std::vector<size_t> mx::improc::annulusIndices (eigenT & rIm, eigenT & qIm, typename eigenT::Scalar xcen, typename eigenT::Scalar ycen, typename eigenT::Scalar min_r, typename eigenT::Scalar max_r, typename eigenT::Scalar min_q, typename eigenT::Scalar max_q, eigenT * mask = 0)
Get the vector indices of an annular region in an image.
Template Parameters
eigenT is an Eigen-like 2D array type
Returns
a vector containing the 1D indices of the region defined by the input parameters
Parameters
[in] rIm a radius image of the type produced by radiusImage
[in] qIm an angle image of the type produce by angleImage
[in] xcen the x center of the image
[in] ycen the y center of the image
[in] min_r the minimum radius of the region
[in] max_r the maximum radius of the region
[in] min_q the minimum angle of the region
[in] max_q the maximum angle of the region
[in] mask [optional] pointer to a mask image, only pixels of value 1 are included in the indices.
Definition at line 182 of file imageMasks.hpp.
template<class eigenT > void mx::improc::applyMask (eigenT & maskedIm, const std::vector< size_t > & idx, typename eigenT::Scalar maskval)
Apply a mask to an image.
The pixels indicated by the indices are set to a value.
Template Parameters
eigenT is an Eigen-like 2D array type
Parameters
[out] maskedIm the image to mask (will be modified)
[in] idx the indices of the pixels to mask
[in] maskval the mask value.
Definition at line 284 of file imageMasks.hpp.
template<typename imageTout , typename imageTin > void mx::improc::cutImageRegion (imageTout & imout, const imageTin & imin, const std::vector< size_t > & idx, bool resize = true)
Cut out a region of an image specified by an index-mask.
The output sill be a row-image containing the pixel values.
Template Parameters
imageTout is the output image Eigen-like type.
imageTin is the input image Eigen-like type.
Parameters
[out] imout a row-image containing the pixel values specified by the indices.
[in] imin a 2-D image
[in] idx the linear indices of the pixel values
[in] resize [optional] flag controls whether imout is resized. It is if true.
Definition at line 383 of file imageMasks.hpp.
template<typename imageTout , typename imageTin > void mx::improc::insertImageRegion (imageTout imout, const imageTin & imin, const std::vector< size_t > & idx)
Insert a region of an image specified by an index-mask.
Both the input and the output are row-images containing the pixel values.
Template Parameters
imageTout is the output image Eigen-like type.
imageTin is the input image Eigen-like type.
Parameters
[out] imout a row-image into which the pixel values specified by the indices are inserted.
[in] imin a row-image containing the pixel values, same size as idx
[in] idx the linear indices of the pixel values
Definition at line 411 of file imageMasks.hpp.
References mx::improc::imageRotate().
Referenced by mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::worker().
template<class arrayT > void mx::improc::maskCircle (arrayT & m, typename arrayT::Scalar xcen, typename arrayT::Scalar ycen, typename arrayT::Scalar rad, typename arrayT::Scalar val = 0, typename arrayT::Scalar pixbuf = 0.5)
Mask a circle in an image.
The circle is describe by its center coordinates and radius. Any value can be set for the mask, with 0 being the default.
Template Parameters
arrayT is an Eigen-like type.
Parameters
[in,out] m the image to be masked, is modified.
[in] xcen the x coordinate of the center of the circle
[in] ycen the y coordinate of the center of the circle
[in] rad the radius of the circle
[in] val [optional] the mask value. Default is 0.
[in] pixbuf [optional] buffer for radius comparison. Default is 0.5 pixels.
Definition at line 305 of file imageMasks.hpp.
template<class eigenT > void mx::improc::radAngImage (eigenT & rIm, eigenT & qIm, typename eigenT::Scalar xc, typename eigenT::Scalar yc, typename eigenT::Scalar rscale = 1, typename eigenT::Scalar qscale = radian<typename eigenT::Scalar>())
Fills in the cells of Eigen-like arrays with their radius amd angle relative to the center.
Template Parameters
eigenT is an Eigen-like 2D array type
Parameters
[out] rIm the allocated radius array, will be filled in with radius values.
[out] qIm the allocated angle array, same size as rIm. Will be filled in with angle values.
[in] xc the x center
[in] yc the y center
[in] rscale [optional] a scaling to apply to each radius value. Default is 1.0.
[in] qscale [optional] a scaling to apply to each angle value. Default converts to degrees, set to 1 for radians.
Definition at line 143 of file imageMasks.hpp.
template<class eigenT > void mx::improc::radiusImage (eigenT & m, typename eigenT::Scalar xc, typename eigenT::Scalar yc, typename eigenT::Scalar scale = 1)
Fills in the cells of an Eigen 2D Array with their radius from the center.
Template Parameters
eigenT is an Eigen-like 2D array type
Parameters
[out] m the allocated radius array, will be filled in with radius values.
[in] xc the x center
[in] yc the y center
[in] scale [optional] a scaling to apply to each value (default = 1)
Definition at line 29 of file imageMasks.hpp.
Referenced by mx::improc::radprofim(), mx::improc::stddevImage(), and mx::improc::stddevImageCube().
template<class eigenT > void mx::improc::radiusImage (eigenT & m, typename eigenT::Scalar scale = 1)
Fills in the cells of Eigen-like 2D Array with their radius from the canonical center.
The center is \((x_c, y_c) = (0.5*(dim_1-1), 0.5*(dim_2 -1)) \).
Template Parameters
eigenT is an Eigen-like 2D array type
Parameters
[out] m the allocated radius array, will be filled in with radius values.
[in] scale [optional] a scaling to apply to each value (default = 1)
Definition at line 64 of file imageMasks.hpp.