mxlib: The Airy Pattern
The Airy Pattern
General Mathematics » Special Functions
Utilities for working with the Airy Pattern.
Utilities for working with the Airy Pattern.
Functions
template<typename realT >
realT mx::math::func::airyPattern (realT x)
The classical Airy pattern.
template<typename realT >
realT mx::math::func::airyPattern (realT x, realT eps)
The centrally obscured Airy pattern.
template<typename realT >
realT mx::math::func::airyPattern (realT x, realT y, realT A0, realT A, realT x0, realT y0, realT ps, realT eps)
The general centrally obscured Airy pattern, with arbitrary center and platescale.
template<typename realT >
realT mx::math::func::seeingHalo (realT x, realT fwhm)
Seeing Halo Profile.
Function Documentation
template<typename realT > realT mx::math::func::airyPattern (realT x)
The classical Airy pattern.
Returns the intensity distribution of the Airy pattern at a given \(\lambda/D \)
References: [1], [11], https://en.wikipedia.org/wiki/Airy_disk.
Template Parameters
realT is the floating point type used for arithmetic.
Parameters
[in] x is the separation in units of \(\lambda/D \).
Definition at line 37 of file airyPattern.hpp.
References mx::math::func::jinc().
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::analyzePSDGrid().
template<typename realT > realT mx::math::func::airyPattern (realT x, realT eps)
The centrally obscured Airy pattern.
Returns the intensity distribution of the centrally obscured Airy pattern at a given \(\lambda/D \)
References: [1], [11], https://en.wikipedia.org/wiki/Airy_disk.
Template Parameters
realT is the floating point type used for arithmetic.
Parameters
[in] x is the separation in units of \(\lambda/D \).
[in] eps is the ratio of the circular central obscuration diameter to the diameter.
Definition at line 53 of file airyPattern.hpp.
References mx::math::func::jinc().
template<typename realT > realT mx::math::func::airyPattern (realT x, realT y, realT A0, realT A, realT x0, realT y0, realT ps, realT eps)
The general centrally obscured Airy pattern, with arbitrary center and platescale.
Returns the intensity distribution of the centrally obscured Airy pattern at a given \(\lambda/D \). This version allows for an arbitrary center, scaling, and platescale.
References: [1], [11], https://en.wikipedia.org/wiki/Airy_disk.
Template Parameters
realT is the floating point type used for arithmetic.
Parameters
[in] x is the x-coordinate in units of pixels
[in] y is the y-coordinate in units of pixels
[in] A0 constant value added to the Airy pattern
[in] A peak scale of the Airy pattern.
[in] x0 is the x-center in units of pixels
[in] y0 is the y-center in units of pixels
[in] ps the platescale in \((\lambda/D)/pixel \)
[in] eps is the ratio of the circular central obscuration diameter to the diameter.
Definition at line 73 of file airyPattern.hpp.
template<typename realT > realT mx::math::func::seeingHalo (realT x, realT fwhm)
Seeing Halo Profile.
A Moffat profile due to Roddier (1981)[17], see also Racine et al (1999)[16], which can be used to describe the seeing limited point-spread function of a telescope imaging through turbulence, or the halo in partially corrected imaging.
Returns
the value of the profile at x, in units of fractional flux per unit area.
Parameters
[in] x the separation in the same units as fwhm.
[in] fwhm the fwhm in arbitrary units. Note that this defines the area units of the density.
Definition at line 99 of file airyPattern.hpp.