mxlib: Interpolation
Interpolation
General Mathematics
Various tools for interpolating data and discrete functions.
Various tools for interpolating data and discrete functions.
Modules
Image Transforms
Functions for transforming images by rotating, translating, and magnifying.
Files
file gslInterpolation.hpp
Wrappers for using the GNU Scientific Library 1-D interpolation functions.
Functions
int mx::gsl_interpolate (const gsl_interp_type *interpT, double *xin, double *yin, size_t Nin, double *xout, double *yout, size_t Nout)
Interpolate a 1-D data X vs Y discrete function onto a new X axis.
int mx::gsl_interpolate (const gsl_interp_type *interpT, std::vector< double > &xin, std::vector< double > &yin, std::vector< double > &xout, std::vector< double > &yout)
Interpolate a 1-D data X vs Y discrete function onto a new X axis (vector version)
Function Documentation
int mx::gsl_interpolate (const gsl_interp_type * interpT, double * xin, double * yin, size_t Nin, double * xout, double * yout, size_t Nout)
Interpolate a 1-D data X vs Y discrete function onto a new X axis.
Parameters
interpT one of the gsl interpolation types.
[in] xin the input x-axis
[in] yin the input y-values
[in] Nin the size of the input x-y data series
[in] xout the desired x-axis
[out] yout the output interpolated y-values, pre-allocated
[in] Nout the size of the output x-y axis
Return values
Definition at line 86 of file gslInterpolation.hpp.
Referenced by mx::astrofiltCharFlux(), mx::astrofiltMultiply(), mx::gsl_interpolate(), and mx::astro::astroSpectrum< _spectrumT, freq >::setSpectrum().
int mx::gsl_interpolate (const gsl_interp_type * interpT, std::vector< double > & xin, std::vector< double > & yin, std::vector< double > & xout, std::vector< double > & yout)
Interpolate a 1-D data X vs Y discrete function onto a new X axis (vector version)
Parameters
interpT of the gsl interpolation types.
[in] xin the input x-axis
[in] yin the input y-values
[in] xout the desired x-axis
[out] yout the output interpolated y-values, does not need to be allocated
Return values
Definition at line 122 of file gslInterpolation.hpp.
References mx::gsl_interpolate().