mxlib: System Programming
System Programming
General Utilities
Tools for system programming.
Tools for system programming.
Modules
Interprocess Communication
Tools for managing interprocess communication (IPC)
Functions
std::string mx::getEnv (const std::string &estr)
Return the value of an environment variable.
Function Documentation
std::string mx::getEnv (const std::string & estr) inline
Return the value of an environment variable.
Call the standard getenv function, but handles the null pointer as an empty string.
Returns
the value of the environment varialbe, or empty string if it doesn't exist
Parameters
[in] estr is the name of the environment variable to query
Definition at line 26 of file environment.hpp.
Referenced by mx::astrofilt(), mx::fftw_wisdom_filename(), mx::AO::path::basis::root(), mx::AO::path::dm::root(), mx::AO::path::pupil::root(), mx::AO::path::sys::root(), and mx::astro::astroSpectrum< _spectrumT, freq >::setParameters().