mxlib: Shared Memory
Shared Memory
General Utilities » System Programming » Interprocess Communication
Tools for managing shared memory.
Tools for managing shared memory.
Classes
struct sharedmem_segment
A c structure to manage a shared memory segment with memory mapping.
class sharedMemSegment
A c++ class to manage a shared memory segment with memory mapping.
Files
file sharedmem_segment.h
Declarations for the mxlib c shared memory facilities.
file sharedmem_segment.h
Declarations for the mxlib c shared memory facilities.
Functions
void sharedmem_segment_initialize (sharedmem_segment *seg)
Initialize a sharedmem_segment structure.
key_t sharedmem_segment_set_key (sharedmem_segment *seg, const char *path, const int id)
Set the key for a sharedmem_segment structure.
int sharedmem_segment_create (sharedmem_segment *seg, size_t sz)
Create and attach to the segment described by a sharedmem_segment.
int sharedmem_segment_attach (sharedmem_segment *seg, int donot_set_addr)
Attach to a segment without creating it.
int sharedmem_segment_detach (sharedmem_segment *seg)
Detach from the segment.
void sharedMemSegment::initialize ()
Initialize the class.
key_t sharedMemSegment::setKey (const char *path, const int id)
Set the key.
int sharedMemSegment::create (size_t sz)
Create and attach to the segment.
int sharedMemSegment::attach (bool donot_set_addr=false)
Attach to a segment without creating it.
Function Documentation
int sharedMemSegment::attach (bool donot_set_addr = false) inline
Attach to a segment without creating it.
If donot_set_addr == false, then the address is mapped to match that stored in the first uintptr_t of the segment.
Parameters
donot_set_addr if > 0 (true) then the address is not mapped to match that stored in the segment
Definition at line 162 of file sharedMemSegment.hpp.
References sharedMemSegment::addr, sharedMemSegment::attached, sharedMemSegment::key, sharedMemSegment::shmemid, and sharedMemSegment::size.
Referenced by sharedMemSegment::create().
int sharedMemSegment::create (size_t sz) inline
Create and attach to the segment.
A segment of size = sz + sizeof(uintptr_t) is actually created.
Note
key must be set before calling this function.
Parameters
sz the size of the segment to create
Definition at line 133 of file sharedMemSegment.hpp.
References sharedMemSegment::addr, sharedMemSegment::attach(), sharedMemSegment::key, and sharedMemSegment::shmemid.
void sharedMemSegment::initialize () inline
Initialize the class.
Definition at line 97 of file sharedMemSegment.hpp.
References sharedMemSegment::addr, sharedMemSegment::attached, sharedMemSegment::key, sharedMemSegment::key_id, sharedMemSegment::shmemid, and sharedMemSegment::size.
key_t sharedMemSegment::setKey (const char * path, const int id) inline
Set the key.
If path == 0, then the key is set directly to id, without using ftok.
Parameters
path is the full path to use in a call to ftok
id is the id number to use in a call to ftok
Returns
the key value, which is also set in the msgq
Definition at line 110 of file sharedMemSegment.hpp.
References sharedMemSegment::key, sharedMemSegment::key_id, sharedMemSegment::key_path, and MX_IPC_KEYLEN.
int sharedmem_segment_attach (sharedmem_segment * seg, int donot_set_addr)
Attach to a segment without creating it.
If donot_set_addr == 0, then the address is mapped to match that stored in the first uintptr_t of the segment.
Parameters
seg is the sharedmem_segment to use
donot_set_addr if > 0 (true) then the address is not mapped to match that stored in the segment
Definition at line 69 of file sharedmem_segment.c.
References sharedmem_segment::addr, sharedmem_segment::attached, sharedmem_segment::key, sharedmem_segment_detach(), sharedmem_segment::shmemid, and sharedmem_segment::size.
Referenced by sharedmem_segment_create().
int sharedmem_segment_create (sharedmem_segment * seg, size_t sz)
Create and attach to the segment described by a sharedmem_segment.
A segment of size = sz + sizeof(uintptr_t) is actually created.
Note
seg->key must be set before calling this function (see sharedmem_segment_set_key).
Parameters
seg is the sharedmem_segment meta to use
sz the size of the segment to create
Definition at line 41 of file sharedmem_segment.c.
References sharedmem_segment::addr, sharedmem_segment::key, sharedmem_segment_attach(), and sharedmem_segment::shmemid.
Referenced by mx::improc::ds9Interface::display().
int sharedmem_segment_detach (sharedmem_segment * seg)
Detach from the segment.
Parameters
seg is the sharedmem_segment to use
Definition at line 225 of file sharedMemSegment.hpp.
References sharedmem_segment::addr, and sharedmem_segment::attached.
Referenced by mx::improc::ds9Interface::display(), sharedmem_segment_attach(), and mx::improc::ds9Interface::shutdown().
void sharedmem_segment_initialize (sharedmem_segment * seg)
Initialize a sharedmem_segment structure.
Parameters
seg is the sharedmem_segment to initialize
Definition at line 9 of file sharedmem_segment.c.
References sharedmem_segment::addr, sharedmem_segment::attached, sharedmem_segment::key, sharedmem_segment::key_id, sharedmem_segment::shmemid, and sharedmem_segment::size.
Referenced by mx::improc::ds9Interface::addsegment().
key_t sharedmem_segment_set_key (sharedmem_segment * seg, const char * path, const int id)
Set the key for a sharedmem_segment structure.
If path == 0, then the key is set directly to id, without using ftok.
Parameters
seg is a pointer to a sharedmem_segment structure
path is the full path to use in a call to ftok
id is the id number to use in a call to ftok
Returns
the key value, which is also set in the msgq
Definition at line 21 of file sharedmem_segment.c.
References sharedmem_segment::key, sharedmem_segment::key_id, sharedmem_segment::key_path, and MX_IPC_KEYLEN.
Referenced by mx::improc::ds9Interface::addsegment().