mxlib: Eigen Lapack interfaces
Eigen Lapack interfaces
General Mathematics
Interfaces to Lapack and BLAS for Eigen-like arrays.
Interfaces to Lapack and BLAS for Eigen-like arrays.
Functions
template<typename eigenT1 , typename eigenT2 >
void mx::math::eigenSYRK (eigenT1 &cv, const eigenT2 &ims)
Calculates the lower triangular part of the covariance matrix of ims.
template<typename cvT , typename calcT >
MXLAPACK_INT mx::math::eigenSYEVR (Eigen::Array< calcT, Eigen::Dynamic, Eigen::Dynamic > &eigvec, Eigen::Array< calcT, Eigen::Dynamic, Eigen::Dynamic > &eigval, Eigen::Array< cvT, Eigen::Dynamic, Eigen::Dynamic > &X, int ev0=0, int ev1=-1, char UPLO= 'L', syevrMem< calcT > *mem=0)
Calculate select eigenvalues and eigenvectors of an Eigen Array.
template<typename _evCalcT = double, typename eigenT , typename eigenT1 >
MXLAPACK_INT mx::math::calcKLModes (eigenT &klModes, eigenT &cv, const eigenT1 &Rims, int n_modes=0, syevrMem< _evCalcT > *mem=0)
Calculate the K-L modes, or principle components, given a covariance matrix.
template<typename dataT >
MXLAPACK_INT mx::math::eigenGESDD (Eigen::Array< dataT,-1,-1 > &U, Eigen::Array< dataT,-1,-1 > &S, Eigen::Array< dataT,-1,-1 > &VT, Eigen::Array< dataT,-1,-1 > &A)
Compute the SVD of an Eigen::Array using LAPACK's xgesdd.
template<typename dataT >
int mx::math::eigenPseudoInverse (Eigen::Array< dataT,-1,-1 > &PInv, dataT &condition, int &nRejected, Eigen::Array< dataT,-1,-1 > &U, Eigen::Array< dataT,-1,-1 > &S, Eigen::Array< dataT,-1,-1 > &VT, Eigen::Array< dataT,-1,-1 > &A, dataT &maxCondition, int MXLAPACK_INTeract=MX_PINV_NO_INTERACT)
Calculate the pseudo-inverse of a patrix using the SVD.
template<typename dataT >
int mx::math::eigenPseudoInverse (Eigen::Array< dataT,-1,-1 > &PInv, dataT &condition, int &nRejected, Eigen::Array< dataT,-1,-1 > &A, dataT &maxCondition, int MXLAPACK_INTeract=MX_PINV_NO_INTERACT)
Calculate the pseudo-inverse of a patrix using the SVD.
Function Documentation
template<typename _evCalcT = double, typename eigenT , typename eigenT1 > MXLAPACK_INT mx::math::calcKLModes (eigenT & klModes, eigenT & cv, const eigenT1 & Rims, int n_modes = 0, syevrMem< _evCalcT > * mem = 0)
Calculate the K-L modes, or principle components, given a covariance matrix.
Eigen-decomposition of the covariance matrix is performed using eigenSYEVR().
Template Parameters
evCalcT is the type in which to perform eigen-decomposition.
eigenT is a 2D Eigen-like type
eigenT1 is a 2D Eigen-like type.
Parameters
[out] klModes on exit contains the K-L modes (or P.C.s)
[in] cv a lower-triangle (in the Lapack sense) square covariance matrix.
[in] Rims The reference data. cv.rows() == Rims.cols().
[in] n_modes [optional] Tbe maximum number of modes to solve for. If 0 all modes are solved for.
[in] mem [optional] A memory structure which can be re-used by SYEVR for efficiency.
Definition at line 241 of file eigenLapack.hpp.
Referenced by mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::worker().
template<typename dataT > MXLAPACK_INT mx::math::eigenGESDD (Eigen::Array< dataT,-1,-1 > & U, Eigen::Array< dataT,-1,-1 > & S, Eigen::Array< dataT,-1,-1 > & VT, Eigen::Array< dataT,-1,-1 > & A)
Compute the SVD of an Eigen::Array using LAPACK's xgesdd.
Computes the SVD of A, \(A = U S V^T \).
Parameters
[out] U the A.rows() x A.rows() left matrix
[out] S the A.cols() x 1 matrix of singular values
[out] VT the A.cols() x A.cols() right matrix, note this is the transpose.
[in] A the input matrix to be decomposed
Returns
0 on success -i on error in ith parameter (from LAPACK xgesdd) >0 did not converge (from LAPACK xgesdd)
Template Parameters
dataT is either float or double.
Definition at line 327 of file eigenLapack.hpp.
Referenced by mx::math::eigenPseudoInverse().
template<typename dataT > int mx::math::eigenPseudoInverse (Eigen::Array< dataT,-1,-1 > & PInv, dataT & condition, int & nRejected, Eigen::Array< dataT,-1,-1 > & U, Eigen::Array< dataT,-1,-1 > & S, Eigen::Array< dataT,-1,-1 > & VT, Eigen::Array< dataT,-1,-1 > & A, dataT & maxCondition, int MXLAPACK_INTeract = MX_PINV_NO_INTERACT)
Calculate the pseudo-inverse of a patrix using the SVD.
First computes the SVD of A, \(A = U S V^T \), using eigenGESDD. Then the psuedo-inverse is calculated as \(A^+ = V S^+ U^T\).
Parameters
[out] PInv the pseudo-inverse of A
[out] condition The final condition number.
[out] nRejected the number of eigenvectors rejected
[out] U
[out] S
[out] VT
[in] A the matrix to invert
[in] maxCondition he maximum condition number desired, which is used to threshold the singular values. Set to 0 use include all eigenvalues/vectors. This is ignored if MXLAPACK_INTeractive.
[in] MXLAPACK_INTeract [optional] a bitmask controlling MXLAPACK_INTeraction. If (MXLAPACK_INTeract & MX_PINV_PLOT) is true, then gnuPlot is used to display the singular values. If (MXLAPACK_INTeract & MX_PINV_ASK) is true then the minimum singular value threshold is requested from the user using stdin.
Template Parameters
dataT is either float or double.
Definition at line 382 of file eigenLapack.hpp.
References mx::gnuPlot::command(), mx::math::eigenGESDD(), mx::gnuPlot::logy(), mx::gnuPlot::plot(), and mx::astro::constants::sigma().
Referenced by mx::sigproc::linearPredictor< realT >::calcCoefficients(), and mx::AO::ifPInv().
template<typename dataT > int mx::math::eigenPseudoInverse (Eigen::Array< dataT,-1,-1 > & PInv, dataT & condition, int & nRejected, Eigen::Array< dataT,-1,-1 > & A, dataT & maxCondition, int MXLAPACK_INTeract = MX_PINV_NO_INTERACT)
Calculate the pseudo-inverse of a patrix using the SVD.
First computes the SVD of A, \(A = U S V^T \), using eigenGESDD. Then the psuedo-inverse is calculated as \(A^+ = V S^+ U^T\). This MXLAPACK_INTerface does not provide access to U, S and VT.
Parameters
PInv [out] the pseudo-inverse of A
condition [out] The final condition number.
nRejected [out] the number of eigenvectors rejected
A [in] the matrix to invert
maxCondition [in] the maximum condition number desired, whichis used to threshold the singular values. Set to 0 use include all eigenvalues/vectors. This is ignored if MXLAPACK_INTeractive.
MXLAPACK_INTeract [in] [optional] a bitmask controlling MXLAPACK_INTeraction. If (MXLAPACK_INTeract & MX_PINV_PLOT) is true, then gnuPlot is used to display the eigenvalues. If (MXLAPACK_INTeract & MX_PINV_ASK) is true then the minimum eigenvaue threshold is requested from the user using stdin.
Template Parameters
dataT is either float or double.
Definition at line 502 of file eigenLapack.hpp.
template<typename cvT , typename calcT > MXLAPACK_INT mx::math::eigenSYEVR (Eigen::Array< calcT, Eigen::Dynamic, Eigen::Dynamic > & eigvec, Eigen::Array< calcT, Eigen::Dynamic, Eigen::Dynamic > & eigval, Eigen::Array< cvT, Eigen::Dynamic, Eigen::Dynamic > & X, int ev0 = 0, int ev1 = -1, char UPLO = 'L', syevrMem< calcT > * mem = 0)
Calculate select eigenvalues and eigenvectors of an Eigen Array.
Uses the templateLapack wrapper for syevr.
Template Parameters
cvT is the scalar type of X (a.k.a. the covariance matrix)
calcT is the type in which to calculate the eigenvectors/eigenvalues
Returns
-1000 on an malloc allocation error.
the return code from syevr (info) otherwise.
Parameters
[out] eigvec will contain the eigenvectors as columns
[out] eigval will contain the eigenvalues
[in] X is a square matrix which is either upper or lower (default) triangular
[in] ev0 [optional] is the first desired eigenvalue (default = 0)
[in] ev1 [optional] if >= ev0 then this is the last desired eigenvalue. If -1 all eigenvalues are returned.
[in] UPLO [optional] specifies whether X is upper ('U') or lower ('L') triangular. Default is ('L').
[in] mem [optional] holds the working memory arrays, can be re-passed to avoid unnecessary re-allocations
Definition at line 119 of file eigenLapack.hpp.
References MXE_ALLOCERR, MXE_LAPACKERR, and mxError.
template<typename eigenT1 , typename eigenT2 > void mx::math::eigenSYRK (eigenT1 & cv, const eigenT2 & ims)
Calculates the lower triangular part of the covariance matrix of ims.
Uses cblas_ssyrk. cv is resized to ims.cols() X ims.cols(). Calculates \(cv = A^T*A \).
Template Parameters
eigenT1 is the eigen matrix/array type of cv.
eigenT2 is the eigen matrix/array type of ims
Parameters
[out] cv is the eigen matrix/array where to store the result
[in] ims is the eigen matrix/array (images as columns) to calculate the covariance of
Definition at line 43 of file eigenLapack.hpp.
Referenced by mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::worker().