mxlib: Analysis of Adaptive Optics
Analysis of Adaptive Optics
Wavefront Propagation » Adaptive Optics
Tools for analytic evaluaiton of AO systems.
Tools for analytic evaluaiton of AO systems.
Classes
class mx::AO::analysis::aoAtmosphere< _realT >
A class to specify atmosphere parameters and perform related calculations.
struct mx::AO::analysis::vonKarmanSpectrum< realT >
Manage calculations using the von Karman spatial power spectrum.
class mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >
Describes an analytic adaptive optics (AO) system.
struct mx::AO::analysis::wfs< realT, iosT >
The ideal wavefront sensor sensitivity function.
struct mx::AO::analysis::pywfsUnmod< realT, iosT >
The unmodulated pyramid wavefront sensor sensitivity function.
struct mx::AO::analysis::pywfsModAsymptotic< realT, iosT >
The asymptotic modulated pyramid wavefront sensor sensitivity function.
struct mx::AO::analysis::clAOLinearPredictor< _realT >
Class to manage the calculation of linear predictor coefficients for a closed-loop AO system.
struct mx::AO::analysis::clGainOpt< _realT >
A class to manage optimizing closed-loop gains.
struct mx::AO::analysis::fourierTemporalPSD< realT, aosysT >
Class to manage the calculation of temporal PSDs of the Fourier modes in atmospheric turbulence.
Modules
AO Constants
A collection of constants useful for AO analysis.
Functions
template<typename realT , typename aosysT >
realT mx::AO::analysis::phiInt_basic (realT phi, void *params)
Worker for the azimuthal integral (in phi) for the basic Fourier mode covariance.
template<typename realT , typename aosysT >
realT mx::AO::analysis::F_basic (realT kv, void *params)
Worker function for GSL Integration for the basic sin/cos Fourier modes.
template<typename realT , typename aosysT >
realT mx::AO::analysis::F_mod (realT kv, void *params)
Worker function for GSL Integration for the modified Fourier modes.
template<typename realT , typename aosysT >
realT mx::AO::analysis::F_projMod (realT kv, void *params)
Worker function for GSL Integration for a basis projected onto the modified Fourier modes.
template<typename imageT >
void mx::AO::analysis::varmapToImage (imageT &im, imageT &varmap, imageT &psf)
Convert a wavefront variance map to an intensity image by convolving with the PSF.
template<typename realT >
void mx::AO::wfsNoisePSD (std::vector< realT > &PSD, realT beta_p_k, realT Fg, realT tau, realT npx, realT Fb, realT ron)
Populate a vector with the PSD of measurement noise given WFS parameters.
Function Documentation
template<typename realT , typename aosysT > realT mx::AO::analysis::F_basic (realT kv, void * params)
Worker function for GSL Integration for the basic sin/cos Fourier modes.
Definition at line 1015 of file fourierTemporalPSD.hpp.
References mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_aosys, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_f, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_layer_i, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_m, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_n, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_p, and mx::math::func::jinc().
template<typename realT , typename aosysT > realT mx::AO::analysis::F_mod (realT kv, void * params)
Worker function for GSL Integration for the modified Fourier modes.
Definition at line 1049 of file fourierTemporalPSD.hpp.
References mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_aosys, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_f, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_layer_i, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_m, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_n, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_p, and mx::math::func::jinc().
template<typename realT , typename aosysT > realT mx::AO::analysis::F_projMod (realT kv, void * params)
Worker function for GSL Integration for a basis projected onto the modified Fourier modes.
Definition at line 1085 of file fourierTemporalPSD.hpp.
References mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_aosys, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_f, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_layer_i, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_mode_i, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_modeCoeffs, and mx::math::func::jinc().
template<typename realT , typename aosysT > realT mx::AO::analysis::phiInt_basic (realT phi, void * params)
Worker for the azimuthal integral (in phi) for the basic Fourier mode covariance.
Parameters
phi the angle at which to evaluate the integrand
params a pointer to a object of type fourierCovariance<realT, aosyT>
Template Parameters
realT a floating point type used for all calculations
aosysT the type of the AO system structure
Definition at line 68 of file fourierCovariance.hpp.
References mx::AO::analysis::fourierCovariance< realT, aosysT >::aosys, mx::math::func::jinc(), mx::astro::constants::k(), mx::AO::analysis::fourierCovariance< realT, aosysT >::k, mx::AO::analysis::fourierCovariance< realT, aosysT >::m, mx::AO::analysis::fourierCovariance< realT, aosysT >::mp, mx::AO::analysis::fourierCovariance< realT, aosysT >::n, mx::AO::analysis::fourierCovariance< realT, aosysT >::np, mx::AO::analysis::fourierCovariance< realT, aosysT >::p, and mx::AO::analysis::fourierCovariance< realT, aosysT >::pp.
template<typename imageT > void mx::AO::analysis::varmapToImage (imageT & im, imageT & varmap, imageT & psf)
Convert a wavefront variance map to an intensity image by convolving with the PSF.
The PSF should have odd dimensions, and the peak pixel should be in the center pixel defined by [0.5*psf.rows(), 0.5*psf.cols()]. The platescale (lambda/D per pixel) of the PSF should match that of the variance map. The PSF should be normalized such that the center/peak pixel has value 1 (not so that the sum of pixels is 1).
Template Parameters
imageT is an Eigen-array-like type.
Parameters
[out] im is the intensity image, resized to match varmap
[in] varmap is the wavefront variance map
[in] psf is the point spread function
Definition at line 29 of file varmapToImage.hpp.
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::analyzePSDGrid().
template<typename realT > void mx::AO::wfsNoisePSD (std::vector< realT > & PSD, realT beta_p_k, realT Fg, realT tau, realT npx, realT Fb, realT ron)
Populate a vector with the PSD of measurement noise given WFS parameters.
Template Parameters
realT is the real floating point type for calculations
Parameters
[out] PSD A pre-allocated vector which will be filled with the PSD value.
[in] beta_p_k The WFS \(\beta_p \) parameter (see Guyon, 2005 [8]}).
[in] Fg Total photons/sec used by the WFS
[in] tau WFS Integration time [sec]
[in] npx Number of pixesl used by the WFS
[in] Fb Background flux, in photons/sec/pixel.
[in] ron Readout noise, in photons/pixel/read.
Definition at line 23 of file wfsNoisePSD.hpp.
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::analyzePSDGrid().