mxlib: Image Transforms
Image Transforms
Image ProcessingGeneral Mathematics » | Interpolation
Functions for transforming images by rotating, translating, and magnifying.
Functions for transforming images by rotating, translating, and magnifying.
Classes
struct mx::improc::bilinearTransform< _arithT >
Transformation by bi-linear interpolation.
struct mx::improc::cubicConvolTransform< _arithT >
Transformation by cubic convolution interpolation.
Typedefs
typedef bilinearTransform< float > mx::improc::bilinearTransf
Typedef for bilinearTransform with single precision.
typedef bilinearTransform< double > mx::improc::bilinearTransd
Typedef for bilinearTransform with double precision.
typedef cubicConvolTransform< float > mx::improc::cubicConvolTransf
Typedef for cubicConvolTransform with single precision.
typedef cubicConvolTransform< double > mx::improc::cubicConvolTransd
Typedef for cubicConvolTransform with double precision.
template<typename transformT , typename arrT , typename arrT2 , typename floatT >
void mx::improc::imageRotate (arrT &transim, const arrT2 &im, floatT dq, transformT trans)
Rotate an image represented as an eigen array.
template<typename outputArrT , typename inputArrT >
void mx::improc::imageShiftWP (outputArrT &out, inputArrT &in, int dx, int dy)
Shift an image by whole pixels, wrapping around..
template<typename arrOutT , typename arrInT , typename floatT , typename transformT >
void mx::improc::imageShift (arrOutT &transim, const arrInT &im, floatT dx, floatT dy, transformT trans)
Shift an image.
template<typename arrOutT , typename arrInT , typename transformT >
void mx::improc::imageMagnify (arrOutT &transim, const arrInT &im, transformT trans)
Magnify an image.
template<typename imageOutT , typename imageInT >
void mx::improc::imageDownSample (imageOutT &imout, const imageInT &imin)
Down-sample an image, reducing its size while conserving the total flux.
Typedef Documentation
typedef bilinearTransform<double> mx::improc::bilinearTransd
Typedef for bilinearTransform with double precision.
Definition at line 53 of file imageTransforms.hpp.
typedef bilinearTransform<float> mx::improc::bilinearTransf
Typedef for bilinearTransform with single precision.
Definition at line 48 of file imageTransforms.hpp.
typedef cubicConvolTransform<double> mx::improc::cubicConvolTransd
Typedef for cubicConvolTransform with double precision.
Definition at line 142 of file imageTransforms.hpp.
typedef cubicConvolTransform<float> mx::improc::cubicConvolTransf
Typedef for cubicConvolTransform with single precision.
Definition at line 137 of file imageTransforms.hpp.
Function Documentation
template<typename imageOutT , typename imageInT > void mx::improc::imageDownSample (imageOutT & imout, const imageInT & imin)
Down-sample an image, reducing its size while conserving the total flux.
If the old size is an integer multiple of the new size, this is just a re-bin. If not an integer multiple, the image is interpolated after performing the closest re-bin, and then re-normalized to conserve flux.
Todo:
Allow selection of interpolator, providing a default version.
Definition at line 497 of file imageTransforms.hpp.
Referenced by mx::AO::sim::pywfsSlopeReconstructor< _floatT >::calcMeasurement(), and mx::AO::sim::ccdDetector< _floatT >::exposeImage().
template<typename arrOutT , typename arrInT , typename transformT > void mx::improc::imageMagnify (arrOutT & transim, const arrInT & im, transformT trans)
Magnify an image.
Uses the given transformation type to magnify the input image to the size of the output image.
Here we assume that the image center is the mxlib standard:
x_center = 0.5*(im.rows()-1);
y_center = 0.5*(im.cols()-1);
Some care is necessary to prevent magnification from shifting with respect to this center. The main result is that the magnification factors (which can be different in x and y) are defined thus:
x_mag = (transim.rows()-1.0) / (im.rows()-1.0);
y_mag = (transim.cols()-1.0) / (im.cols()-1.0);
Template Parameters
arrOutT is the eigen array type of the output.
arrInT is the eigen array type of the input.
transformT specifies the transformation to use.
Parameters
[out] transim contains the magnified image. Must be pre-allocated.
[in] im is the image to be magnified.
[in] trans is the transformation to use
Definition at line 410 of file imageTransforms.hpp.
template<typename transformT , typename arrT , typename arrT2 , typename floatT > void mx::improc::imageRotate (arrT & transim, const arrT2 & im, floatT dq, transformT trans)
Rotate an image represented as an eigen array.
Uses the given transformation type to rotate an image.
Template Parameters
arrOutT is the eigen array type of the output [will be resolved by compiler]
arrInT is the eigen array type of the input [will be resolved by compiler]
floatT is a floating point type [will be resolved by compiler in most cases]
transformT specifies the transformation to use [will be resolved by compiler]
Parameters
[out] transim contains the shifted image. Must be pre-allocated.
[in] im is the image to be shifted.
[in] dq is the amount in radians to rotate in the c.c.w. direction
[in] trans is the transformation to use
Definition at line 163 of file imageTransforms.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::derotate(), and mx::improc::insertImageRegion().
template<typename arrOutT , typename arrInT , typename floatT , typename transformT > void mx::improc::imageShift (arrOutT & transim, const arrInT & im, floatT dx, floatT dy, transformT trans)
Shift an image.
Uses the given transformation type to shift an image.
Template Parameters
arrOutT is the eigen array type of the output [will be resolved by compiler]
arrInT is the eigen array type of the input [will be resolved by compiler]
floatT is a floating point type [will be resolved by compiler in most cases]
transformT specifies the transformation to use [will be resolved by compiler]
Parameters
[out] transim contains the shifted image. Must be pre-allocated.
[in] im is the image to be shifted.
[in] dx is the amount to shift in the x direction
[in] dy is the amount to shift in the y direction
[in] trans is the transformation to use
Definition at line 308 of file imageTransforms.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake(), mx::AO::sim::turbLayer< _realT >::shift(), and mx::AO::sim::turbLayer< _realT >::shiftRandom().
template<typename outputArrT , typename inputArrT > void mx::improc::imageShiftWP (outputArrT & out, inputArrT & in, int dx, int dy)
Shift an image by whole pixels, wrapping around..
The output image can be smaller than the input image, in which case the wrapping still occurs for the input image, but only output images worth of pixels are actually shifted. This is useful, for instance, when propagating large turbulence phase screens where one only needs a small section at a time.
Parameters
[out] out contains the shifted image. Must be pre-allocated, but can be smaller than the in array.
[in] in is the image to be shifted.
[in] dx is the amount to shift in the x direction
[in] dy is the amount to shift in the y direction
Template Parameters
outputArrT is the eigen array type of the output [will be resolved by compiler]
inputArrT is the eigen array type of the input [will be resolved by compiler]
Definition at line 260 of file imageTransforms.hpp.
Referenced by mx::AO::sim::turbLayer< _realT >::shift(), and mx::AO::sim::turbLayer< _realT >::shiftRandom().