mxlib: binVector Binary File Format
binVector Binary File Format
General Utilities » Input/Output Utilities
A simple binary file format for storing vectors of data on disk.
A simple binary file format for storing vectors of data on disk.
The binVector file format is very simple: the first 8 bytes contain a unit64_t integer which specifies the type of the data. The second 8 bytes contain a uint64_t integer which specifies the length L of the data vector. The remaining L*sizeof(dataT) bytes contain the data.
The suggested extension for BinVector files is ".binv".
Namespaces
mx::binVTypes
Namespace fo the bin-vector type-codes.
Typedefs
typedef uint64_t mx::binVTypeT
The type of binVector type codes.
Enumerations
Functions
template<typename dataT >
binVTypeT mx::binVectorTypeCode ()
Get the integer type code corresponding to the type.
template<typename dataT >
int mx::readBinVector (std::vector< dataT > &vec, const std::string &fname)
Read a BinVector file from disk.
template<typename dataT >
int mx::writeBinVector (const std::string &fname, std::vector< dataT > &vec)
Write a BinVector file to disk.
Typedef Documentation
typedef uint64_t mx::binVTypeT
The type of binVector type codes.
Definition at line 37 of file binVector.hpp.
Enumeration Type Documentation
anonymous enum : binVTypeT
The pre-defined type codes for binVector.
Definition at line 48 of file binVector.hpp.
Function Documentation
template<typename dataT > binVTypeT mx::binVectorTypeCode ()
Get the integer type code corresponding to the type.
Returns
an integer which uniquely identifies the type.
Template Parameters
dataT is the type
template<typename dataT > int mx::readBinVector (std::vector< dataT > & vec, const std::string & fname)
Read a BinVector file from disk.
Note
dataT must match what was stored in the file.
Returns
0 on success.
-1 if an error occurs.
Parameters
[out] vec vec is a vector which will be resized and populated.
[in] fname fname is the name (full-path) of the file.
Definition at line 201 of file binVector.hpp.
References MXE_FILERERR, MXE_SIZEERR, mxError, and mxPError.
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::getGridFreq(), and mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::getGridPSD().
template<typename dataT > int mx::writeBinVector (const std::string & fname, std::vector< dataT > & vec)
Write a BinVector file to disk.
Returns
0 on success.
-1 if an error occurs.
Parameters
[in] fname fname is the name (full-path) of the file.
[in] vec vec is the vector which will be written to disk.
Definition at line 294 of file binVector.hpp.
References mxPError.
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::makePSDGrid().