mxlib: mxlib.h File Reference
mxlib.h File Reference
Declarations of some libarary wide utilities.
Declarations of some libarary wide utilities.
Author
Jared R. Males
Definition in file mxlib.h.
#include "mxlib_uncomp_version.h"
Functions
char * mxlib_compiled_git_sha1 ()
Get the compile-time git repository SHA-1.
int mxlib_compiled_git_repo_modified ()
Get the compile-time git repository modification status.
Function Documentation
int mxlib_compiled_git_repo_modified ()
Get the compile-time git repository modification status.
Returns a pointer to a static int, if 1 then at compile time there were modifications not committed.
Return values
int denoting whether the repo contained uncommitted modifications at compile time.
Definition at line 21 of file mxlib.c.
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::dumpAOSystem(), mx::AO::analysis::fourierVarVec(), mx::improc::HCIobservation< _realT >::outputPSFSub(), and mx::improc::HCIobservation< _realT >::writeFinim().
char* mxlib_compiled_git_sha1 ()
Get the compile-time git repository SHA-1.
Returns a pointer to a static string containing the SHA-1 hash of the mxlib git repository at compile time. This pointer should not be modified.
Return values
char* which points to a string containing the SHA-1 hash
Definition at line 13 of file mxlib.c.
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::dumpAOSystem(), mx::AO::analysis::fourierVarVec(), mx::improc::HCIobservation< _realT >::outputPSFSub(), and mx::improc::HCIobservation< _realT >::writeFinim().