mxlib: mx Namespace Reference
mx Namespace Reference
The mxlib c++ namespace.
The mxlib c++ namespace.
Namespaces
binVTypes
Namespace fo the bin-vector type-codes.
Classes
struct appConfigurator
Class to manage a set of configurable values, and read their values from config/ini files and the command line.
class application
A class for managing application configuration and execution.
struct clOptions
Command line options parser.
struct configTarget
A configuration target.
class fftT< _inputT, _outputT, _dim, 0 >
Fast Fourier Transforms using the FFTW library.
struct fftwEnvironment
Manage the FFTW environment and wisdom using RAII.
struct fftwPlanSpec
Specify the type of the plan based on the real type of the data.
struct fftwPlanSpec< __float128 >
Specialization of fftwPlanSpec for __float128.
struct fftwPlanSpec< double >
Specialization of fftwPlanSpec for double.
struct fftwPlanSpec< float >
Specialization of fftwPlanSpec for float.
struct fftwPlanSpec< long double >
Specialization of fftwPlanSpec for long double.
struct fftwTypeSpec
A structure specifying various types based on the FFT input and output data types.
struct fftwTypeSpec< __float128, complexQT >
Specialization of fftwTypeSpec for real-quad input and complex-quad output.
struct fftwTypeSpec< complexDT, complexDT >
Specialization of fftwTypeSpec for complex-double input and complex-double output.
struct fftwTypeSpec< complexDT, double >
Specialization of fftwTypeSpec for complex-double input and double output.
struct fftwTypeSpec< complexFT, complexFT >
Specialization of fftwTypeSpec for complex-float input and complex-float output.
struct fftwTypeSpec< complexFT, float >
Specialization of fftwTypeSpec for complex-float input and real-float output.
struct fftwTypeSpec< complexLT, complexLT >
Specialization of fftwTypeSpec for complex-long-double input and complex-long-double output.
struct fftwTypeSpec< complexLT, long double >
Specialization of fftwTypeSpec for complex-long-double input and real-long-double output.
struct fftwTypeSpec< complexQT, __float128 >
Specialization of fftwTypeSpec for complex-quad input and real-quad output.
struct fftwTypeSpec< complexQT, complexQT >
Specialization of fftwTypeSpec for complex-quad input and complex-quad output.
struct fftwTypeSpec< double, complexDT >
Specialization of fftwTypeSpec for real-double input and complex-double output.
struct fftwTypeSpec< float, complexFT >
Specialization of fftwTypeSpec for real-float input and complex-float output.
struct fftwTypeSpec< long double, complexLT >
Specialization of fftwTypeSpec for real-long-double input and complex-long-double output.
class gnuPlot
A c++ interface to gnuplot.
struct is_imagingArray
Test whether a type is an imagingArray by testing whether it has a typedef of "is_imagingArray".
class laplace_distribution
The Laplace (double exponential) continuous distribution for random numbers.
class ompLoopWatcher
A class to track the number of iterations in an OMP parallelized loop.
class randomT
A random number type, which functions like any other arithmetic type.
struct textTable
An ascii table formatter.
Typedefs
typedef uint64_t binVSizeT
The type used for binVector sizes.
typedef uint64_t binVTypeT
The type of binVector type codes.
typedef std::complex< float > complexFT
The complex float data type.
typedef std::complex< double > complexDT
The complex double data type.
typedef std::complex< long double > complexLT
The complex long double data type.
typedef std::complex< __float128 > complexQT
The complex __float128 data type.
template<typename realT >
using uniDistT = randomT< realT, std::mt19937_64, std::uniform_real_distribution< realT >>
Alias for a uniform random variate.
template<typename realT >
using normDistT = randomT< realT, std::mt19937_64, std::normal_distribution< realT >>
Alias for a standard normal random variate.
template<typename realT >
using expDistT = randomT< realT, std::mt19937_64, std::exponential_distribution< realT >>
Alias for an exponential random variate.
template<typename realT >
using lapDistT = randomT< realT, std::mt19937_64, laplace_distribution< realT >>
Alias for a laplace random variate.
Enumerations
Functions
template<typename dataT >
void readCalspec (std::vector< dataT > &lambda, std::vector< dataT > &flambda, const std::string &spName, const std::string &datadir)
Read an HST Calspec spectrum.
template<typename dataT >
void astrofiltNormalize (std::vector< dataT > &trans)
Normalize a transmission profile to have peak value of 1.0.
template<typename dataT >
void astrofiltTrimWavelength (std::vector< dataT > &lambda, std::vector< dataT > &spectrum, dataT lambda_0, dataT lambda_f)
Erase points at beginning and end to trim unwanted data from a spectrum.
template<typename dataT >
void astrofiltTrimWavelength (std::vector< dataT > &lambda, std::vector< dataT > &spectrum, std::vector< dataT > &lambda_ref)
Erase points at beginning and end to trim unwanted data from a spectrum.
template<typename dataT >
void astrofiltRSR (std::vector< dataT > &lambda, std::vector< dataT > &trans)
Convert a transmission profile to relative spectral response.
template<typename dataT >
void astrofilt (std::vector< dataT > &lambda, std::vector< dataT > &trans, const std::string &filtName, bool rsr=false, const std::string &datadir="")
Read a filter transmission curve from the astrofilt collection.
template<typename dataT >
void astrofiltCharTrans (dataT &lambda0, dataT &fwhm, dataT &weff, std::vector< dataT > &lambda, std::vector< dataT > &trans)
Characterize the wavelength of a filter transmission curve.
template<typename dataT >
void astrofiltCharFlux (dataT &flambda0, dataT &fnu0, dataT &fphot0, std::vector< dataT > &lambda_f, std::vector< dataT > &trans, std::vector< dataT > &lambda_s, std::vector< dataT > &flambda)
Characterize the fluxes of a filter transmission curve w.r.t. a spectrum.
template<typename dataT >
void astrofiltCharVega (dataT &flambda0, dataT &fnu0, dataT &fphot0, std::vector< dataT > &lambda, std::vector< dataT > &trans)
Characterize the fluxes of a filter transmission curve w.r.t. Vega.
template<typename dataT >
void astrofiltMultiply (std::vector< dataT > &spectrum_out, std::vector< dataT > &lambda_1, std::vector< dataT > &spectrum_1, std::vector< dataT > &lambda_2, std::vector< dataT > &spectrum_2)
Multiply two spectra or filter curves.
template<typename dataT >
void astrofiltMultiply (std::vector< dataT > &spectrum, dataT scale, std::vector< dataT > &spectrum_out)
Multiply a spectrum or filter curve by a scalar.
template<typename dataT >
void astrofiltScaleMag (std::vector< dataT > &lambda_s, std::vector< dataT > &spectrum, std::vector< dataT > &lambda_f, std::vector< dataT > &trans, dataT mag, int scaleBy=0)
Scale a spectrum to a specified Vega magnitude in a filter.
template<typename dataT >
void astrofiltScaleMean (std::vector< dataT > &lambda_s, std::vector< dataT > &spectrum, std::vector< dataT > &lambda_f, std::vector< dataT > &trans, dataT mean, int scaleBy=0)
Scale a spectrum to a specified mean value in a filter.
template<typename dataT >
void readPickles (std::vector< dataT > &lambda, std::vector< dataT > &flambda, const std::string &spt, const std::string &datadir="")
Read a Pickles atlas spectrum.
template<typename dataT >
void readATRAN (std::vector< dataT > &lambda, std::vector< dataT > &trans, const std::string &site, double pwv, double airmass, const std::string &datadir="")
Read the ATRAN atmospheric transmission spectrum from Gemini.
template<typename dataT >
void readBTRAM (std::vector< dataT > &lambda, std::vector< dataT > &trans, const std::string &site, const std::string &run, double pwv, double zd, const std::string &datadir="")
Read a BTRAM atmospheric transmission spectrum.
template<typename floatT >
void rewritePhoenixSpectrum (const std::string &filename, floatT lmin, floatT lmax)
Read in, crop, and re-write a Phoenix spectrum data file.
template<typename dataT >
void readPhoenix (std::vector< dataT > &lambda, std::vector< dataT > &flambda, const std::string &filename, int scale=1, dataT radius=1)
Read a Phoenix model spectrum.
template<typename dataT >
void readEarthShine (std::vector< dataT > &lambda, std::vector< dataT > &albedo, std::string &datadir="")
Read the Earthshine spectrum.
template<typename dataT >
void readEarthShine (std::vector< dataT > &lambda, std::vector< dataT > &albedo)
Read the Earthshine spectrum.
template<typename dataT >
binVTypeT binVectorTypeCode ()
Get the integer type code corresponding to the type.
template<typename dataT >
int readBinVector (std::vector< dataT > &vec, const std::string &fname)
Read a BinVector file from disk.
template<typename dataT >
int writeBinVector (const std::string &fname, std::vector< dataT > &vec)
Write a BinVector file to disk.
std::string getEnv (const std::string &estr)
Return the value of an environment variable.
std::vector< std::string > getFileNames (const std::string &directory, const std::string &prefix, const std::string &substr, const std::string &extension)
Get a list of file names from the specified directory, specifying a prefix, a substring to match, and an extension.
std::vector< std::string > getFileNames (const std::string &directory, const std::string &extension)
Get a list of file names from the specified directory, specifying the extension.
std::vector< std::string > getFileNames (const std::string &directory)
Get a list of file names from the specified directory.
std::string fileNamePrependAppend (const std::string &fname, const std::string &prepend, const std::string &append)
Prepend and/or append strings to a file name, leaving the directory and extension unaltered.
std::string fileNameAppend (const std::string &fname, const std::string &append)
Append a string to a file name, leaving the directory and extension unaltered.
std::string fileNamePrepend (const std::string &fname, const std::string &prepend)
Prepend strings to a file name, leaving the directory and extension unaltered.
template<int ndigit = 4>
std::string getSequentialFilename (const std::string &basename, const std::string &extension="", const int startat=0)
Get the next file in a numbered sequence.
template<int ndigit = 4>
std::string getSequentialFilename (const std::string &basename, const int startat)
Get the next file in a numbered sequence.
int gsl_interpolate (const gsl_interp_type *interpT, double *xin, double *yin, size_t Nin, double *xout, double *yout, size_t Nout)
Interpolate a 1-D data X vs Y discrete function onto a new X axis.
int gsl_interpolate (const gsl_interp_type *interpT, std::vector< double > &xin, std::vector< double > &yin, std::vector< double > &xout, std::vector< double > &yout)
Interpolate a 1-D data X vs Y discrete function onto a new X axis (vector version)
std::string MXE_CodeToName (int ec, std::string &message)
Return the macro name and a message for an mxlib error code.
std::string errno_CodeToName (int ec, std::string &message)
Return the macro name and a message for a standard errno code.
std::string error_report (const std::string &source, const int &code, const std::string &file, const int &line, const std::string &expl="")
Construct a rich error report given an mxlib error code.
std::string errno_report (const std::string &source, int ec, const std::string &file, const int &line, const std::string &expl="")
Construct a rich error report given a standard errno error code.
template<char space = ' ', bool flush = true, char eol = '\n', typename valT , typename... valTs>
void pout (valT value, const valTs &...values)
A simple formatted output function.
template<typename intT >
int randomSeed (intT &seedval)
Get a value to use as a random seed.
template<typename _RealType >
bool operator== (const mx::laplace_distribution< _RealType > &__d1, const mx::laplace_distribution< _RealType > &__d2)
Return true if two exponential distributions have the same parameters.
template<typename _RealType >
bool operator!= (const mx::laplace_distribution< _RealType > &__d1, const mx::laplace_distribution< _RealType > &__d2)
Return true if two exponential distributions have different parameters.
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &, const mx::laplace_distribution< _RealType > &)
Inserts a laplace_distribution random number distribution __x into the output stream __os.
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &, mx::laplace_distribution< _RealType > &)
Extracts a laplace_distribution random number distribution __x from the input stream __is.
template<char delim = ' ', char comment = '#', char eol = '\n', typename... arrTs>
int readColumns (const std::string &fname, arrTs &...arrays)
Read in columns from a text file.
template<typename typeT , unsigned width = 0, char pad = ' '>
std::string convertToString (const typeT &value, int precision=0)
Convert a numerical value to a string.
template<>
std::string convertToString< std::string > (const std::string &value, int precision)
Specialization of convertToString to avoid converting a string to a string.
template<typename typeT >
typeT convertFromString (const std::string &str)
Convert a string to a numerical value.
template<>
char convertFromString< char > (const std::string &str)
Template specialization of convertFromString for char.
template<>
unsigned char convertFromString< unsigned char > (const std::string &str)
Template specialization of convertFromString for unsigned char.
template<>
short convertFromString< short > (const std::string &str)
Template specialization of convertFromString for short.
template<>
unsigned short convertFromString< unsigned short > (const std::string &str)
Template specialization of convertFromString for unsigned short.
template<>
int convertFromString< int > (const std::string &str)
Template specialization of convertFromString for int.
template<>
unsigned int convertFromString< unsigned int > (const std::string &str)
Template specialization of convertFromString for unsigned int.
template<>
long convertFromString< long > (const std::string &str)
Template specialization of convertFromString for long.
template<>
unsigned long convertFromString< unsigned long > (const std::string &str)
Template specialization of convertFromString for unsigned long.
template<>
long long convertFromString< long long > (const std::string &str)
Template specialization of convertFromString for long long.
template<>
unsigned long long convertFromString< unsigned long long > (const std::string &str)
Template specialization of convertFromString for unsigned long long.
template<>
float convertFromString< float > (const std::string &str)
Template specialization of convertFromString for float.
template<>
double convertFromString< double > (const std::string &str)
Template specialization of convertFromString for double.
template<>
long double convertFromString< long double > (const std::string &str)
Template specialization of convertFromString for long double.
template<>
bool convertFromString< bool > (const std::string &str)
Template specialization of convertFromString for bool.
void toLower (std::string &outstr, const std::string &instr)
Convert a string to all lower case.
std::string toLower (const std::string &instr)
Convert a string to all lower case.
void toUpper (std::string &outstr, const std::string &instr)
Convert a string to all upper case.
std::string toUpper (const std::string &instr)
Convert a string to all upper case.
void removeWhiteSpace (std::string &outstr, const std::string &instr)
Remove all white space from a string.
std::string removeWhiteSpace (const std::string &instr)
Remove all white space from a string.
int stringWrap (std::vector< std::string > &lines, const std::string &str, int width)
Wrap a string by breaking it into smaller sized portions of a desired width.
template<typename typeT = double, clockid_t clk_id = CLOCK_REALTIME>
typeT get_curr_time ()
template<typename floatT >
void parse_hms (const std::string &hmsstr, floatT &h, floatT &m, floatT &s)
double Cal2mjd (int yr, int mon, int day, int hr, int min, double sec)
Converts a Gregorian calendar date into modified Julian date (MJD).
int ISO8601dateBreakdown (int &yr, int &mon, int &day, int &hr, int &min, double &sec, const std::string &fdate)
Parse an ISO8601 date of the form "YYYY-MM-DDTHH:MM:SS.S" into the individual components.
double ISO8601date2mjd (const std::string &fdate)
Parse an ISO8601 date of the form "YYYY-MM-DDTHH:MM:SS.S" and return the modified Julian date (MJD)
template<typename timeT >
std::string ISO8601DateTimeStr (const timeT &timeIn, int timeZone=0)
Get a date-time string in ISO 8601 format.
template<>
std::string ISO8601DateTimeStr< time_t > (const time_t &timeIn, int timeZone)
Get a date-time string in ISO 8601 format for time_t.
template<>
std::string ISO8601DateTimeStr< timespec > (const timespec &timeIn, int timeZone)
Get a date-time string in ISO 8601 format for timespec.
std::string ISO8601DateTimeStr (int timeZone=0)
Get a date-time string in ISO 8601 format for the current UTC time.
std::string ISO8601DateTimeStrMJD (const double &timeIn, int timeZone=0)
Get a date-time string in ISO 8601 format for an MJD.
int timespecUTC2TAIMJD (double &djm, double &djmf, const timespec &tsp, tm *tm0)
Convert a UTC timespec to TAI modified Julian date.
template<typename realT >
std::string fftw_typename ()
Return a string corresponding the fftw real floating point type.
template<typename realT >
std::string fftw_wisdom_filename ()
Create the mxlib standard wisdom filename for the type.
template<typename realT >
int fftw_import_system_wisdom ()
Template wrapper for fftwX_import_system_wisdom();.
template<typename realT >
int fftw_import_wisdom_from_filename (const char *filename)
Template wrapper for fftwX_import_wisdom_from_filename(const char *);.
template<typename realT >
int fftw_export_wisdom_to_filename (const char *filename)
Template wrapper for fftwX_export_wisdom_to_filename(const char *);.
template<typename realT >
realT * fftw_malloc (size_t n)
Call to fftw_malloc, with type cast.
template<typename realT >
void fftw_free (realT *p)
Call to fftw_free.
template<typename realT >
void fftw_make_planner_thread_safe ()
Wrapper for fftwX_make_planner_thread_safe()
template<typename realT >
void fftw_plan_with_nthreads (int nthreads)
Tell the FFTW planner how many threads to use.
template<typename inputDataT , typename outputDataT >
fftwTypeSpec< inputDataT, outputDataT >::planT fftw_plan_dft (std::vector< int > n, inputDataT *in, outputDataT *out, int sign, unsigned flags)
Wrapper for the fftwX_plan_dft functions.
template<typename realT >
void fftw_cleanup ()
Cleanup persistent planner data.
template<typename realT >
void fftw_cleanup_threads ()
Cleanup persistent planner data and threads data.
template<typename inputDataT , typename outputDataT >
void fftw_execute_dft (typename fftwTypeSpec< inputDataT, outputDataT >::planT plan, inputDataT *in, outputDataT *out)
Execute the given plan on the given arrays.
template<typename realT >
void fftw_destroy_plan (typename fftwPlanSpec< realT >::planT plan)
Destroy the given plan.
template<typename realT >
void quarticRoots (std::vector< std::complex< realT > > &x, realT a, realT b, realT c, realT d, realT e)
Find the roots of the general quartic equation.
template<typename vectorT >
void vectorScale (vectorT &vec, size_t N=0, typename vectorT::value_type scale=0, typename vectorT::value_type offset=0)
Fill in a vector with a regularly spaced scale.
template<typename memberT >
std::vector< size_t > vectorSortOrder (std::vector< memberT > const &values)
Return the indices of the vector in sorted order, without altering the vector itself.
template<typename vectorT >
vectorT::value_type vectorMean (const vectorT &vec)
Calculate the mean of a vector.
template<typename vectorT >
vectorT::value_type vectorMean (const vectorT &vec, const vectorT &w)
Calculate the weighted mean of a vector.
template<typename vectorT >
vectorT::value_type vectorMedianInPlace (vectorT &vec)
Calculate median of a vector in-place, altering the vector.
template<typename vectorT >
vectorT::value_type vectorMedian (const vectorT &vec, vectorT *work=0)
Calculate median of a vector, leaving the vector unaltered.
template<typename vectorT >
vectorT::value_type vectorVariance (const vectorT &vec, typename vectorT::value_type &mean)
Calculate the variance of a vector relative to a supplied mean value.
template<typename vectorT >
vectorT::value_type vectorVariance (const vectorT &vec)
Calculate the variance of a vector.
template<typename vectorT >
vectorT::value_type vectorSigmaMean (const vectorT &vec, const vectorT *weights, typename vectorT::value_type sigma, int &maxPasses)
Calculate the sigma-clipped mean of a vector.
template<typename vectorT >
vectorT::value_type vectorSigmaMean (const vectorT &vec, typename vectorT::value_type sigma)
template<typename vectorT >
vectorT::value_type vectorSigmaMean (const vectorT &vec, const vectorT &weights, typename vectorT::value_type sigma, int &maxPasses)
template<typename vectorT >
vectorT::value_type vectorSigmaMean (const vectorT &vec, const vectorT &weights, typename vectorT::value_type sigma)
template<typename realT >
int vectorSmoothMean (std::vector< realT > &smVec, std::vector< realT > &vec, int win)
Smooth a vector using the mean in a window specified by its full-width.
Typedef Documentation
typedef uint64_t mx::binVSizeT
The type used for binVector sizes.
Definition at line 32 of file binVector.hpp.
Enumeration Type Documentation
enum mx::argType
Argument types.
Definition at line 24 of file clOptions.hpp.
Function Documentation
template<typename _RealType > bool mx::operator!= (const mx::laplace_distribution< _RealType > & __d1, const mx::laplace_distribution< _RealType > & __d2) inline
Return true if two exponential distributions have different parameters.
Definition at line 236 of file randomT.hpp.
References operator>>().
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream<_CharT, _Traits>& mx::operator<< (std::basic_ostream< _CharT, _Traits > & , const mx::laplace_distribution< _RealType > &)
Inserts a laplace_distribution random number distribution __x into the output stream __os.
Parameters
__os An output stream.
__x A laplace_distribution random number distribution.
Returns
The output stream with the state of __x inserted or in an error state.
template<typename _RealType > bool mx::operator== (const mx::laplace_distribution< _RealType > & __d1, const mx::laplace_distribution< _RealType > & __d2) inline
Return true if two exponential distributions have the same parameters.
Definition at line 226 of file randomT.hpp.
References mx::laplace_distribution< _RealType >::param().
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream<_CharT, _Traits>& mx::operator>> (std::basic_istream< _CharT, _Traits > & , mx::laplace_distribution< _RealType > &)
Extracts a laplace_distribution random number distribution __x from the input stream __is.
Parameters
__is An input stream.
__x A laplace_distribution random number generator engine.
Returns
The input stream with __x extracted or in an error state.
Referenced by operator!=().