mxlib: mx::improc::imCenterCircleSym< realT > Struct Template Reference
mx::improc::imCenterCircleSym< realT > Struct Template Reference
Image Processing » Image Registration
template<typename realT>
struct mx::improc::imCenterCircleSym< realT >
Find the center of the image of a point source using circular symmetry of the PSF.
Conducts a grid search through possible center positions. Finds the point with the minimum total variance around concentric circles about that point. The cost grid is fit with a Gaussian.
Template Parameters
realT is a real floating point type.
Definition at line 32 of file imCenterCircleSym.hpp.
#include <improc/imCenterCircleSym.hpp>
Public Member Functions
int init (realT maxP, realT dP, realT minR, realT maxR, realT dR)
Initialize the grid.
int center (realT &x, realT &y, eigenImage< realT > &im, realT x0, realT y0)
Peform the grid search and fit.
void results ()
Dump the results to std::cout.
Public Attributes
eigenImage< realT > * mask
An optional pointer to a mask. If not NULL and the same size as the input image, any 0 pixels in this image are ignored.
eigenImage< realT > grid
The cost grid.
eigenImage< realT > smGrid
The smoothed cost grid.
realT maxPix
The maximum range of the grid search, the grid will be +/- maxPix. Default: 5.0.
realT dPix
The spacing of the points in the grid search. Default: 0.1.
realT minRad
The minimum radius to include in the cost function. Default: 1.0.
realT maxRad
The maximum radius to include in the cost function Default: 20.0.
realT dRad
The spacing of the radii. Default: 1.0.
realT smWidth
FWHM of the Guassian smoothing kernel. Default is 10 (seems to work well regardless of dPix). Set to 0 for no smoothing.
realT guessWidth
Guess in original pixels for the FWHM of the cost grid. Default is 0.5, which seems to work well in most cases.
mx::math::fit::fitGaussian2Dgen< realT > fit
The fitter for finding the centroid of the grid. You can use this to inspect the details of the fit if desired.
realT _x0
Internal storage of the guess center position.
realT _y0
Internal storage of the guess center position.
Member Function Documentation
template<typename realT > int mx::improc::imCenterCircleSym< realT >::center (realT & x, realT & y, eigenImage< realT > & im, realT x0, realT y0) inline
Peform the grid search and fit.
Todo:
This needs to be able to handle highly non-symmetric peaks much better.
Parameters
[out] x the x-coordinate of the estimated center of rotational symmetry
[out] y the y-coordinate estimated center of rotational symmetry
[in] im the image to centroid
[in] x0 an initial guess at the x-coordinate, the grid is centered about this point.
[in] y0 an initial guess at the y-coordinate, the grid is centered about this point.
Definition at line 87 of file imCenterCircleSym.hpp.
References mx::improc::imCenterCircleSym< realT >::dPix, mx::improc::filterImage(), mx::math::fit::fitGaussian2D< fitterT >::fit(), mx::improc::imCenterCircleSym< realT >::grid, mx::astro::constants::k(), mx::improc::imCenterCircleSym< realT >::maxRad, mx::improc::imCenterCircleSym< realT >::minRad, mx::math::fit::fitGaussian2D< fitterT >::setArray(), mx::math::fit::fitGaussian2D< fitterT >::setGuess(), mx::vectorMean(), mx::vectorVariance(), mx::math::fit::fitGaussian2D< fitterT >::x0(), and mx::math::fit::fitGaussian2D< fitterT >::y0().
template<typename realT > int mx::improc::imCenterCircleSym< realT >::init (realT maxP, realT dP, realT minR, realT maxR, realT dR) inline
Initialize the grid.
Parameters
[in] maxP the new value of maxPix
[in] dP the new value of dPix
[in] minR the new value of minRad
[in] maxR the new value of maxRad
[in] dR the new value of dRad
Definition at line 71 of file imCenterCircleSym.hpp.
template<typename realT > void mx::improc::imCenterCircleSym< realT >::results () inline
Dump the results to std::cout.
Definition at line 205 of file imCenterCircleSym.hpp.
References mx::improc::imCenterCircleSym< realT >::dPix, mx::math::fit::levmarInterface< fitterT >::dump_report(), sigma2fwhm, mx::math::fit::fitGaussian2D< fitterT >::sigma_x(), mx::math::fit::fitGaussian2D< fitterT >::sigma_y(), mx::math::fit::fitGaussian2D< fitterT >::x0(), and mx::math::fit::fitGaussian2D< fitterT >::y0().
Member Data Documentation
template<typename realT > realT mx::improc::imCenterCircleSym< realT >::_x0
Internal storage of the guess center position.
Definition at line 55 of file imCenterCircleSym.hpp.
template<typename realT > realT mx::improc::imCenterCircleSym< realT >::_y0
Internal storage of the guess center position.
Definition at line 56 of file imCenterCircleSym.hpp.
template<typename realT > realT mx::improc::imCenterCircleSym< realT >::dPix
The spacing of the points in the grid search. Default: 0.1.
Definition at line 42 of file imCenterCircleSym.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::center(), and mx::improc::imCenterCircleSym< realT >::results().
template<typename realT > realT mx::improc::imCenterCircleSym< realT >::dRad
The spacing of the radii. Default: 1.0.
Definition at line 46 of file imCenterCircleSym.hpp.
template<typename realT > mx::math::fit::fitGaussian2Dgen<realT> mx::improc::imCenterCircleSym< realT >::fit
The fitter for finding the centroid of the grid. You can use this to inspect the details of the fit if desired.
Definition at line 53 of file imCenterCircleSym.hpp.
template<typename realT > eigenImage<realT> mx::improc::imCenterCircleSym< realT >::grid
The cost grid.
Definition at line 37 of file imCenterCircleSym.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::center().
template<typename realT > realT mx::improc::imCenterCircleSym< realT >::guessWidth
Guess in original pixels for the FWHM of the cost grid. Default is 0.5, which seems to work well in most cases.
Definition at line 49 of file imCenterCircleSym.hpp.
template<typename realT > eigenImage<realT>* mx::improc::imCenterCircleSym< realT >::mask
An optional pointer to a mask. If not NULL and the same size as the input image, any 0 pixels in this image are ignored.
Definition at line 35 of file imCenterCircleSym.hpp.
template<typename realT > realT mx::improc::imCenterCircleSym< realT >::maxPix
The maximum range of the grid search, the grid will be +/- maxPix. Default: 5.0.
Definition at line 41 of file imCenterCircleSym.hpp.
template<typename realT > realT mx::improc::imCenterCircleSym< realT >::maxRad
The maximum radius to include in the cost function Default: 20.0.
Definition at line 45 of file imCenterCircleSym.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::center().
template<typename realT > realT mx::improc::imCenterCircleSym< realT >::minRad
The minimum radius to include in the cost function. Default: 1.0.
Definition at line 44 of file imCenterCircleSym.hpp.
Referenced by mx::improc::imCenterCircleSym< realT >::center().
template<typename realT > eigenImage<realT> mx::improc::imCenterCircleSym< realT >::smGrid
The smoothed cost grid.
Definition at line 38 of file imCenterCircleSym.hpp.
template<typename realT > realT mx::improc::imCenterCircleSym< realT >::smWidth
FWHM of the Guassian smoothing kernel. Default is 10 (seems to work well regardless of dPix). Set to 0 for no smoothing.
Definition at line 48 of file imCenterCircleSym.hpp.
The documentation for this struct was generated from the following file:
improc/imCenterCircleSym.hpp