mxlib: mx::AO::analysis::fourierTemporalPSD< realT, aosysT > Struct Template Reference
mx::AO::analysis::fourierTemporalPSD< realT, aosysT > Struct Template Reference
Wavefront Propagation » Adaptive Optics » Analysis of Adaptive Optics
template<typename realT, typename aosysT>
struct mx::AO::analysis::fourierTemporalPSD< realT, aosysT >
Class to manage the calculation of temporal PSDs of the Fourier modes in atmospheric turbulence.
Works with both basic (sines/cosines) and modified Fourier modes.
Template Parameters
realT is a real floating point type for calculations. Currently must be double due to gsl_integration.
aosysT is an AO system type, usually of type ao_system.
Todo:
Split off the integration parameters in a separate structure.
once integration parameters are in a separate structure, make this a class with protected members.
Definition at line 90 of file fourierTemporalPSD.hpp.
#include <ao/analysis/fourierTemporalPSD.hpp>
Public Member Functions
fourierTemporalPSD ()
Default c'tor.
fourierTemporalPSD (bool allocate)
Constructor with workspace allocation.
~fourierTemporalPSD ()
Destructor.
realT fastestPeak (int m, int n)
Determine the frequency of the highest V-dot-k peak.
int singleLayerPSD (std::vector< realT > &PSD, std::vector< realT > &freq, realT m, realT n, int layer_i, int p, realT fmax=0)
Calculate the temporal PSD for a Fourier mode for a single layer.
template<bool parallel = true>
int multiLayerPSD (std::vector< realT > &PSD, std::vector< realT > &freq, realT m, realT n, int p, realT fmax=0)
Calculate the temporal PSD for a Fourier mode in a multi-layer model.
void makePSDGrid (std::string dir, int mnMax, realT dFreq, realT maxFreq, realT fmax=0)
Calculate PSDs over a grid of spatial frequencies.
int analyzePSDGrid (std::string subDir, std::string psdDir, int mnMax, int mnCon, int lpNc, std::vector< realT > &mags, std::vector< int > &intTimes)
Analyze a PSD grid under closed-loop control.
GSL Integration Tolerances
For good results it seems that absolute tolerance (absTol) needs to be 1e-10. Lower tolerances cause some frequencies to drop out, etc. Relative tolerance (relTol) seems to be less sensitive, and 1e-4 works on cases tested as of 1 Jan, 2017.
See the documentation for the GSL Library integrators at (https://www.gnu.org/software/gsl/manual/html_node/QAGI-adaptive-integration-on-infinite-intervals.html)
void absTol (realT at)
Set absolute tolerance.
realT absTol ()
Get the current absolute tolerance.
void relTol (realT rt)
Set relative tolerance.
realT relTol ()
Get the current relative tolerance.
Disk Storage
These methods handle writing to and reading from disk. The calculated PSDs are store in the mx::BinVector binary format.
A grid of PSDs is specified by its directory name. The directory contains one frequency file (freq.binv), and a set of PSD files, named according to psd_<m>_<n>_.binv.
void getGridFreq (std::vector< realT > &freq, const std::string &dir)
Get the frequency scale for a PSD grid.
void getGridPSD (std::vector< realT > &psd, const std::string &dir, int m, int n)
Get a single PSD from a PSD grid.
void getGridPSD (std::vector< realT > &freq, std::vector< realT > &psd, const std::string &dir, int m, int n)
Get both the frequency scale and a single PSD from a PSD grid.
Public Attributes
aosysT * _aosys
Pointer to an AO system structure.
realT _f
the current temporal frequency
realT _m
the spatial frequency m index
realT _n
the spatial frequency n index
int _p
The parity of the mode, +/- 1. If _useBasis==MXAO_FTPSD_BASIS_BASIC then +1 indicates cosine, -1 indicates sine.
int _layer_i
The index of the current layer.
int _useBasis
Set to MXAO_FTPSD_BASIS_BASIC/MODIFIED/PROJECTED_* to use the basic sin/cos modes, the modified Fourier modes, or a projection of them.
gsl_integration_workspace * _w
Worskspace for the gsl integrators, allocated to WSZ if constructed as worker (with allocate == true).
realT _absTol
The absolute tolerance to use in the GSL integrator.
realT _relTol
The relative tolerance to use in the GSL integrator.
int _mode_i
Projected basis mode index.
Eigen::Array< realT,-1,-1 > _modeCoeffs
Coeeficients of the projection onto the Fourier modes.
Protected Member Functions
void initialize ()
Initialize parameters to default values.
Constructor & Destructor Documentation
template<typename realT , typename aosysT > mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::fourierTemporalPSD ()
Default c'tor.
Definition at line 351 of file fourierTemporalPSD.hpp.
template<typename realT , typename aosysT > mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::fourierTemporalPSD (bool allocate)
Constructor with workspace allocation.
Parameters
allocate if true, then the workspace for GSL integrators is allocated.
Definition at line 357 of file fourierTemporalPSD.hpp.
References WSZ.
template<typename realT , typename aosysT > mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::~fourierTemporalPSD ()
Destructor.
Frees GSL workspace if it was allocated.
Definition at line 368 of file fourierTemporalPSD.hpp.
Member Function Documentation
template<typename realT , typename aosysT > void mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::absTol (realT at)
Set absolute tolerance.
Parameters
at is the new absolute tolerance.
Definition at line 387 of file fourierTemporalPSD.hpp.
template<typename realT , typename aosysT > realT mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::absTol ()
Get the current absolute tolerance.
Returns
_absTol
Definition at line 393 of file fourierTemporalPSD.hpp.
template<typename realT , typename aosysT > int mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::analyzePSDGrid (std::string subDir, std::string psdDir, int mnMax, int mnCon, int lpNc, std::vector< realT > & mags, std::vector< int > & intTimes)
Analyze a PSD grid under closed-loop control.
This always analyzes the simple integrator, and can also analyze the linear preditor controller.
Parameters
[in] subDir the sub-directory of psdDir where to write the results.
[in] psdDir the directory containing the grid of PSDs.
[in] mnMax the maximum value of m and n in the grid.
[in] mnCon the maximum value of m and n which can be controlled.
[in] lpNc the number of linear predictor coefficients to analyze. If 0 then LP is not analyzed.
[in] mags the guide star magnitudes to analyze for.
[in] intTimes the integration times, in units of aosysT::minTauWFS.
Definition at line 713 of file fourierTemporalPSD.hpp.
References mx::AO::analysis::clGainOpt< _realT >::a(), mx::math::func::airyPattern(), mx::AO::analysis::clGainOpt< _realT >::b(), mx::AO::analysis::clGainOpt< _realT >::f(), gmax, mx::astro::constants::k(), mx::sigproc::makeFourierModeFreqs_Rect(), mx::AO::analysis::clGainOpt< _realT >::optGainOpenLoop(), mx::AO::analysis::clAOLinearPredictor< _realT >::regularizeCoefficients(), mx::AO::analysis::varmapToImage(), mx::AO::wfsNoisePSD(), and mx::improc::fitsFile< dataT >::write().
template<typename realT , typename aosysT > realT mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::fastestPeak (int m, int n)
Determine the frequency of the highest V-dot-k peak.
Parameters
m the spatial frequency u index
n the spatial frequency v index
Returns
the frequency of the fastest peak
Definition at line 411 of file fourierTemporalPSD.hpp.
template<typename realT , typename aosysT > void mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::getGridFreq (std::vector< realT > & freq, const std::string & dir)
Get the frequency scale for a PSD grid.
Parameters
[out] freq is the vector to populate with the frequency scale.
[in] dir specifies the directory containing the grid.
Definition at line 981 of file fourierTemporalPSD.hpp.
References mx::readBinVector().
template<typename realT , typename aosysT > void mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::getGridPSD (std::vector< realT > & psd, const std::string & dir, int m, int n)
Get a single PSD from a PSD grid.
Parameters
[out] psd is the vector to populate with the PSD.
[in] dir specifies the directory containing the grid.
[in] m specifies the u component of spatial frequency.
[in] n specifies the v component of spatial frequency.
Definition at line 990 of file fourierTemporalPSD.hpp.
References mx::convertToString(), and mx::readBinVector().
template<typename realT , typename aosysT > void mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::getGridPSD (std::vector< realT > & freq, std::vector< realT > & psd, const std::string & dir, int m, int n)
Get both the frequency scale and a single PSD from a PSD grid.
Parameters
[out] freq is the vector to populate with the frequency scale.
[out] psd is the vector to populate with the PSD.
[in] dir specifies the directory containing the grid.
[in] m specifies the u component of spatial frequency.
[in] n specifies the v component of spatial frequency.
Definition at line 1001 of file fourierTemporalPSD.hpp.
template<typename realT , typename aosysT > void mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::initialize () protected
Initialize parameters to default values.
Definition at line 377 of file fourierTemporalPSD.hpp.
template<typename realT , typename aosysT > void mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::makePSDGrid (std::string dir, int mnMax, realT dFreq, realT maxFreq, realT fmax = 0)
Calculate PSDs over a grid of spatial frequencies.
The grid of spatial frequencies is square, set by the maximum value of m and n.
The PSDs are written as mx::binVector binary files to a directory. We do not use FITS since this adds overhead and cfitisio handles parallelization poorly due to the limitation on number of created file pointers.
Parameters
[in] dir the directory for output of the PSDs
[in] mnMax the maximum value of m and n in the grid.
[in] dFreq the temporal frequency spacing.
[in] maxFreq the maximum temporal frequency to calculate
[in] fmax [optional] set the maximum temporal frequency for the calculation. The PSD is filled in with a -17/3 power law past this frequency. If 0, then it is taken to be 150 Hz + 2*fastestPeak(m,n).
Definition at line 633 of file fourierTemporalPSD.hpp.
References mx::convertToString(), mx::ompLoopWatcher< _outputT, _printPretty, _printLoops, _printPercent, _printNLine >::incrementAndOutputStatus(), mx::sigproc::makeFourierModeFreqs_Rect(), mx::vectorScale(), and mx::writeBinVector().
template<typename realT , typename aosysT > template<bool parallel> int mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::multiLayerPSD (std::vector< realT > & PSD, std::vector< realT > & freq, realT m, realT n, int p, realT fmax = 0)
Calculate the temporal PSD for a Fourier mode in a multi-layer model.
Template Parameters
parallel controls whether layers are calculated in parallel. Default is true. Set to false if this is called inside a parallelized loop, as in makePSDGrid.
Todo:
implement error checking
handle reports of convergence failures form singleLayerPSD when implemented.
Parameters
[out] PSD the calculated PSD
[in] freq the populated temporal frequency grid defining at which frequencies the PSD is calculated
[in] m the first index of the spatial frequency
[in] n the second index of the spatial frequency
[in] p sets which mode is calculated (if basic modes, p = -1 for sine, p = +1 for cosine)
[in] fmax [optional] set the maximum temporal frequency for the calculation. The PSD is filled in with a -17/3 power law past this frequency. If 0, then it is taken to be 150 Hz + 2*fastestPeak(m,n).
Definition at line 612 of file fourierTemporalPSD.hpp.
template<typename realT , typename aosysT > void mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::relTol (realT rt)
Set relative tolerance.
Parameters
rt is the new relative tolerance.
Definition at line 399 of file fourierTemporalPSD.hpp.
template<typename realT , typename aosysT > realT mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::relTol ()
Get the current relative tolerance.
Returns
_relTol
Definition at line 405 of file fourierTemporalPSD.hpp.
template<typename realT , typename aosysT > int mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::singleLayerPSD (std::vector< realT > & PSD, std::vector< realT > & freq, realT m, realT n, int layer_i, int p, realT fmax = 0)
Calculate the temporal PSD for a Fourier mode for a single layer.
Parameters
[out] PSD is the calculated PSD
[in] freq is the populated temporal frequency grid defining the frequencies at which the PSD is calculated
[in] m is the first index of the spatial frequency
[in] n is the second index of the spatial frequency
[in] layer_i the index of the layer, for accessing the atmosphere parameters
[in] p sets which mode is calculated (if basic modes, p = -1 for sine, p = +1 for cosine)
[in] fmax [optional] set the maximum temporal frequency for the calculation. The PSD is filled in with a -17/3 power law past this frequency.
Todo:
implement error checking.
need a way to track convergence failures in integral without throwing an error.
need better handling of averaging for the -17/3 extension.
Definition at line 434 of file fourierTemporalPSD.hpp.
References mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_aosys, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_f, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_layer_i, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_m, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_mode_i, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_modeCoeffs, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_n, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_p, mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_w, mx::astro::constants::k(), MXE_INVALIDARG, MXE_NOTIMPL, mxError, and WSZ.
Member Data Documentation
template<typename realT, typename aosysT> realT mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_absTol
The absolute tolerance to use in the GSL integrator.
Definition at line 106 of file fourierTemporalPSD.hpp.
template<typename realT, typename aosysT> aosysT* mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_aosys
Pointer to an AO system structure.
Definition at line 93 of file fourierTemporalPSD.hpp.
Referenced by mx::AO::analysis::F_basic(), mx::AO::analysis::F_mod(), mx::AO::analysis::F_projMod(), and mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::singleLayerPSD().
template<typename realT, typename aosysT> realT mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_f
the current temporal frequency
Definition at line 95 of file fourierTemporalPSD.hpp.
Referenced by mx::AO::analysis::F_basic(), mx::AO::analysis::F_mod(), mx::AO::analysis::F_projMod(), and mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::singleLayerPSD().
template<typename realT, typename aosysT> int mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_layer_i
The index of the current layer.
Definition at line 99 of file fourierTemporalPSD.hpp.
Referenced by mx::AO::analysis::F_basic(), mx::AO::analysis::F_mod(), mx::AO::analysis::F_projMod(), and mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::singleLayerPSD().
template<typename realT, typename aosysT> realT mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_m
the spatial frequency m index
Definition at line 96 of file fourierTemporalPSD.hpp.
Referenced by mx::AO::analysis::F_basic(), mx::AO::analysis::F_mod(), and mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::singleLayerPSD().
template<typename realT, typename aosysT> int mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_mode_i
Projected basis mode index.
Definition at line 109 of file fourierTemporalPSD.hpp.
Referenced by mx::AO::analysis::F_projMod(), and mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::singleLayerPSD().
template<typename realT, typename aosysT> Eigen::Array<realT, -1, -1> mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_modeCoeffs
Coeeficients of the projection onto the Fourier modes.
Definition at line 111 of file fourierTemporalPSD.hpp.
Referenced by mx::AO::analysis::F_projMod(), and mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::singleLayerPSD().
template<typename realT, typename aosysT> realT mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_n
the spatial frequency n index
Definition at line 97 of file fourierTemporalPSD.hpp.
Referenced by mx::AO::analysis::F_basic(), mx::AO::analysis::F_mod(), and mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::singleLayerPSD().
template<typename realT, typename aosysT> int mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_p
The parity of the mode, +/- 1. If _useBasis==MXAO_FTPSD_BASIS_BASIC then +1 indicates cosine, -1 indicates sine.
Definition at line 98 of file fourierTemporalPSD.hpp.
Referenced by mx::AO::analysis::F_basic(), mx::AO::analysis::F_mod(), and mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::singleLayerPSD().
template<typename realT, typename aosysT> realT mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_relTol
The relative tolerance to use in the GSL integrator.
Definition at line 107 of file fourierTemporalPSD.hpp.
template<typename realT, typename aosysT> int mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_useBasis
Set to MXAO_FTPSD_BASIS_BASIC/MODIFIED/PROJECTED_* to use the basic sin/cos modes, the modified Fourier modes, or a projection of them.
Definition at line 101 of file fourierTemporalPSD.hpp.
template<typename realT, typename aosysT> gsl_integration_workspace* mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::_w
Worskspace for the gsl integrators, allocated to WSZ if constructed as worker (with allocate == true).
Definition at line 104 of file fourierTemporalPSD.hpp.
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::singleLayerPSD().
The documentation for this struct was generated from the following file:
ao/analysis/fourierTemporalPSD.hpp