mxlib: mx::improc::fitsHeaderCard Struct Reference
mx::improc::fitsHeaderCard Struct Reference
Image Processing » FITS Files
Simple structure to hold the three components of a FITS header card.
Is a struct so all members are public for easy access. Several string-to-number conversions are provided.
Definition at line 27 of file fitsHeaderCard.hpp.
#include <improc/fitsHeaderCard.hpp>
Public Member Functions
Constructors
fitsHeaderCard ()
Basic c'tor.
fitsHeaderCard (std::string k, const void *v, std::string c)
Construct from the three components, when value's type is unknown.
fitsHeaderCard (std::string k, void *v, std::string c)
Construct from the three components, when value's type is unknown.
fitsHeaderCard (std::string k, fitsCommentType v, std::string c)
Construct from the three components, when it's really a comment card.
fitsHeaderCard (std::string k, fitsHistoryType v, std::string c)
Construct from the three components, when it's really a history card.
template<typename typeT >
fitsHeaderCard (std::string k, const typeT v, std::string c)
Construct from the three components for a known type.
fitsHeaderCard (std::string k, void *v)
Construct from just two components, when value's type is unknown.
fitsHeaderCard (std::string k, const void *v)
Construct from just two components, when value's type is unknown.
template<typename typeT >
fitsHeaderCard (std::string k, const typeT v)
Construct from just two components when value's type is known.
fitsHeaderCard (std::string k)
Construct from just keyword, when value's type is unknown.
Setting Components
template<typename typeT >
void setValue (const typeT v)
Set the value string, applying the appropriate conversion and setting the FITS type.
Conversions
template<typename typeT >
typeT Value () const
Get value converted to the specified type.
std::string String ()
Convert value to an string, stripping apostrophes if necessary.
int Int ()
Convert value to an integer.
unsigned int unsignedInt ()
Convert value to an unsigned integer.
long Long ()
Convert value to a long integer.
unsigned long unsignedLong ()
Convert value to an unsigned long integer.
long long longLong ()
Convert value to a long long integer.
unsigned long long unsignedLongLong ()
Convert value to an unsigned long long integer.
float Float ()
Convert value to a float.
double Double ()
Convert value to a double.
long double longDouble ()
Convert value to a long double.
Output
int write (fitsfile *fptr)
Writes this card to a FITS file, using mx::improc::fits_write_key<typename typeT>(fitsfile * fptr, char * keyword, void * value, char * comment).
Public Attributes
std::string keyword
The keyword.
std::string value
The value.
std::string comment
The comment.
int type
The FITS type.
Constructor & Destructor Documentation
mx::improc::fitsHeaderCard::fitsHeaderCard () inline
Basic c'tor.
Definition at line 47 of file fitsHeaderCard.hpp.
References mx::astro::constants::c(), Double(), Float(), Int(), mx::astro::constants::k(), Long(), longDouble(), longLong(), setValue(), String(), unsignedInt(), unsignedLong(), unsignedLongLong(), Value(), and write().
mx::improc::fitsHeaderCard::fitsHeaderCard (std::string k, const void * v, std::string c) inline
Construct from the three components, when value's type is unknown.
Parameters
k is the keyword
v is the value, must be cast-able to char*
c is the comment
Definition at line 238 of file fitsHeaderCard.hpp.
References mx::astro::constants::c(), comment, mx::astro::constants::k(), keyword, type, and value.
mx::improc::fitsHeaderCard::fitsHeaderCard (std::string k, void * v, std::string c) inline
Construct from the three components, when value's type is unknown.
Parameters
k is the keyword
v is the value, must be cast-able to char*
c is the comment
Definition at line 229 of file fitsHeaderCard.hpp.
References mx::astro::constants::c(), comment, mx::astro::constants::k(), keyword, type, and value.
mx::improc::fitsHeaderCard::fitsHeaderCard (std::string k, fitsCommentType v, std::string c) inline
Construct from the three components, when it's really a comment card.
This overload is provided to facilitate handling of comments when re-writing the file.
Parameters
k is the keyword
v is an object of type fitsCommentType
c is the comment
Definition at line 247 of file fitsHeaderCard.hpp.
References mx::astro::constants::c(), comment, mx::astro::constants::k(), keyword, type, and value.
mx::improc::fitsHeaderCard::fitsHeaderCard (std::string k, fitsHistoryType v, std::string c) inline
Construct from the three components, when it's really a history card.
This overload is provided to facilitate handling of history when re-writing the file.
Parameters
k is the keyword
v is an object of type fitsHistoryType
c is the comment
Definition at line 256 of file fitsHeaderCard.hpp.
References mx::astro::constants::c(), comment, mx::astro::constants::k(), keyword, type, and value.
template<typename typeT > mx::improc::fitsHeaderCard::fitsHeaderCard (std::string k, const typeT v, std::string c)
Construct from the three components for a known type.
Parameters
k is the keyword
v is the value
c is the comment
Definition at line 265 of file fitsHeaderCard.hpp.
References mx::astro::constants::c(), comment, mx::astro::constants::k(), keyword, type, and value.
mx::improc::fitsHeaderCard::fitsHeaderCard (std::string k, void * v) inline
Construct from just two components, when value's type is unknown.
Parameters
k is the keyword
v is the value, must be cast-able to char*
Definition at line 275 of file fitsHeaderCard.hpp.
References mx::astro::constants::k(), keyword, type, and value.
mx::improc::fitsHeaderCard::fitsHeaderCard (std::string k, const void * v) inline
Construct from just two components, when value's type is unknown.
Parameters
k is the keyword
v is the value, must be cast-able to char*
Definition at line 284 of file fitsHeaderCard.hpp.
References mx::astro::constants::k(), keyword, type, and value.
template<typename typeT > mx::improc::fitsHeaderCard::fitsHeaderCard (std::string k, const typeT v)
Construct from just two components when value's type is known.
Parameters
k is the keyword
v is the value
Definition at line 300 of file fitsHeaderCard.hpp.
References mx::astro::constants::k(), keyword, type, and value.
mx::improc::fitsHeaderCard::fitsHeaderCard (std::string k) inline
Construct from just keyword, when value's type is unknown.
Parameters
k is the keyword
Definition at line 292 of file fitsHeaderCard.hpp.
References mx::astro::constants::k(), keyword, type, and value.
Member Function Documentation
double mx::improc::fitsHeaderCard::Double () inline
Convert value to a double.
Returns
the result of converting the value string to a double
Definition at line 376 of file fitsHeaderCard.hpp.
References mx::convertFromString< double >(), and value.
Referenced by fitsHeaderCard(), and write().
float mx::improc::fitsHeaderCard::Float () inline
Convert value to a float.
Returns
the result of converting the value string to a float
Definition at line 371 of file fitsHeaderCard.hpp.
References mx::convertFromString< float >(), and value.
Referenced by fitsHeaderCard(), and write().
int mx::improc::fitsHeaderCard::Int () inline
Convert value to an integer.
Returns
the result of converting the value string to an integer
Definition at line 339 of file fitsHeaderCard.hpp.
References mx::convertFromString< int >(), and value.
Referenced by fitsHeaderCard(), and write().
long mx::improc::fitsHeaderCard::Long () inline
Convert value to a long integer.
Returns
the result of converting the value string to a long integer
Definition at line 351 of file fitsHeaderCard.hpp.
References mx::convertFromString< long >(), and value.
Referenced by fitsHeaderCard(), and write().
long double mx::improc::fitsHeaderCard::longDouble () inline
Convert value to a long double.
Returns
the result of converting the value string to a long double
Definition at line 381 of file fitsHeaderCard.hpp.
References mx::convertFromString< long double >(), and value.
Referenced by fitsHeaderCard().
long long mx::improc::fitsHeaderCard::longLong () inline
Convert value to a long long integer.
Returns
the result of converting the value string to a long long integer
Definition at line 361 of file fitsHeaderCard.hpp.
References mx::convertFromString< long long >(), and value.
Referenced by fitsHeaderCard(), and write().
template<typename typeT > void mx::improc::fitsHeaderCard::setValue (const typeT v)
Set the value string, applying the appropriate conversion and setting the FITS type.
Parameters
v the value to convert to string and set
Template Parameters
typeT is the type to convert from
Definition at line 308 of file fitsHeaderCard.hpp.
References type, and value.
Referenced by fitsHeaderCard().
std::string mx::improc::fitsHeaderCard::String () inline
Convert value to an string, stripping apostrophes if necessary.
Returns
the result of converting the value string to a string
Definition at line 330 of file fitsHeaderCard.hpp.
References mx::improc::fitsStripApost(), and value.
Referenced by fitsHeaderCard().
unsigned int mx::improc::fitsHeaderCard::unsignedInt () inline
Convert value to an unsigned integer.
Returns
the result of converting the value string to an unsigned integer
Definition at line 345 of file fitsHeaderCard.hpp.
References mx::convertFromString< unsigned int >(), and value.
Referenced by fitsHeaderCard().
unsigned long mx::improc::fitsHeaderCard::unsignedLong () inline
Convert value to an unsigned long integer.
Returns
the result of converting the value string to an unsigned long integer
Definition at line 356 of file fitsHeaderCard.hpp.
References mx::convertFromString< unsigned long >(), and value.
Referenced by fitsHeaderCard(), and write().
unsigned long long mx::improc::fitsHeaderCard::unsignedLongLong () inline
Convert value to an unsigned long long integer.
Returns
the result of converting the value string to anunsigned long long integer
Definition at line 366 of file fitsHeaderCard.hpp.
References mx::convertFromString< unsigned long long >(), and value.
Referenced by fitsHeaderCard().
template<typename typeT > typeT mx::improc::fitsHeaderCard::Value () const
Get value converted to the specified type.
Uses convertFromString. typeT can be any fundamental type, or any type which can be typecast from std::string. This is specialized for typeT=std::string so that leading and trailing apostrophes are removed.
Definition at line 315 of file fitsHeaderCard.hpp.
References mx::improc::fitsStripApost(), and value.
Referenced by fitsHeaderCard().
int mx::improc::fitsHeaderCard::write (fitsfile * fptr) inline
Writes this card to a FITS file, using mx::improc::fits_write_key<typename typeT>(fitsfile * fptr, char * keyword, void * value, char * comment).
Definition at line 387 of file fitsHeaderCard.hpp.
References comment, Double(), Float(), Int(), keyword, Long(), longLong(), type, unsignedLong(), and value.
Referenced by fitsHeaderCard().
Member Data Documentation
std::string mx::improc::fitsHeaderCard::comment
The comment.
Definition at line 36 of file fitsHeaderCard.hpp.
Referenced by fitsHeaderCard(), and write().
std::string mx::improc::fitsHeaderCard::keyword
The keyword.
Definition at line 30 of file fitsHeaderCard.hpp.
Referenced by mx::improc::fitsHeader::append(), fitsHeaderCard(), mx::improc::fitsHeader::insert_after(), mx::improc::fitsHeader::insert_before(), and write().
int mx::improc::fitsHeaderCard::type
The FITS type.
Definition at line 39 of file fitsHeaderCard.hpp.
Referenced by mx::improc::fitsHeader::append(), fitsHeaderCard(), mx::improc::fitsHeader::insert_after(), mx::improc::fitsHeader::insert_before(), setValue(), and write().
std::string mx::improc::fitsHeaderCard::value
The value.
Definition at line 33 of file fitsHeaderCard.hpp.
Referenced by Double(), fitsHeaderCard(), Float(), Int(), Long(), longDouble(), longLong(), setValue(), String(), unsignedInt(), unsignedLong(), unsignedLongLong(), Value(), and write().
The documentation for this struct was generated from the following file:
improc/fitsHeaderCard.hpp