mxlib: mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT > Struct Template Reference
mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT > Struct Template Reference
Wavefront Propagation » Coronagraphs
template<typename _realT, typename _fpmaskFloatT>
struct mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >
The Lyot Coronagraph.
A generalized Lyot coronagraph, which can include a pupil apodization, a focal plane mask with complex transmission, and a Lyot stop. Light is propagated through the coronagraph plane-by-plane, and the complex wavefront can be accessed at any plane. Also provides functions for optimizing the pupil apodizer and focal plane mask.
Definition at line 36 of file lyotCoronagraph.hpp.
#include <wfp/lyotCoronagraph.hpp>
Public Types
typedef _realT realT
The real floating point type.
typedef _fpmaskFloatT fpmaskFloatT
The real floating point type for mask calculations.
typedef std::complex< realT > complexT
The complex floating point type.
typedef mx::imagingArray< std::complex< realT >, fftwAllocator< std::complex< realT > >, 0 > complexFieldT
The wavefront complex field type.
typedef Eigen::Array< fpmaskFloatT, Eigen::Dynamic, Eigen::Dynamic > fpMaskT
The focal plane mask type.
typedef Eigen::Array< realT, Eigen::Dynamic, Eigen::Dynamic > imageT
The image type.
Public Member Functions
int wfSz ()
Get the wavefront size in pixels.
void wfSz (int sz)
Set the wavefront size in pixels.
void makeFocalMask (realT rad, fpmaskFloatT trans=0.0, int sz=0.0)
Make the focal plane mask.
int loadApodizer (const std::string &apodName)
Load the apodizer from a FITS file.
int loadFocalMask (const std::string &fpmName)
Load the focal plane mask from a FITS file.
int loadLyotStop (const std::string &lyotName)
Load the Lyot stop from a FITS file.
int loadCoronagraph (const std::string &apodName, const std::string &fpmName, const std::string &lyotName)
Load the components of the coronagraph from FITS files.
int loadCoronagraph (const std::string &cName)
Load the components of the coronagraph based in its base name.
void propagate (complexFieldT &pupilPlane)
Propagate the given pupil-plane wavefront through the coronagraph.
void propagateNC (complexFieldT &pupilPlane)
Propagate the given pupil-plane wavefront without the coronagraph.
void optimizeAPLCMC (imageT &geomPupil, realT fpmRadPix, realT relTol, realT absTol, int maxIter, const std::string &cname)
Optimize the pupil amplitude apodization and focal-plane mask complex transmission.
Public Attributes
std::string _fileDir
The directory where coronagraph files are stored.
int _wfSz
The linear size of the wavefront in pixels.
imageT pupilApodizer
Image containing the pupil apodization.
int maskSource
0= read frounobs8m_2048_128_fpm.fitsm file, 1 = constructed by makeFocalMask, 2 = trans optimized.
std::string maskFile
Name of file from which mask was loaded.
realT maskRad
Radius of mask if it was constructed.
realT maskTrans
Transmission of mask if it was constructed.
fpMaskT focalMask
The focal plane mask.
imageT lyotStop
Image containing the lyot stop.
fraunhoferPropagator< complexFieldT > fi
Fraunhofer propagator.
Member Typedef Documentation
template<typename _realT , typename _fpmaskFloatT > typedef mx::imagingArray<std::complex<realT>, fftwAllocator<std::complex<realT> >, 0> mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::complexFieldT
The wavefront complex field type.
Definition at line 48 of file lyotCoronagraph.hpp.
template<typename _realT , typename _fpmaskFloatT > typedef std::complex<realT> mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::complexT
The complex floating point type.
Definition at line 45 of file lyotCoronagraph.hpp.
template<typename _realT , typename _fpmaskFloatT > typedef _fpmaskFloatT mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::fpmaskFloatT
The real floating point type for mask calculations.
Definition at line 42 of file lyotCoronagraph.hpp.
template<typename _realT , typename _fpmaskFloatT > typedef Eigen::Array< fpmaskFloatT, Eigen::Dynamic, Eigen::Dynamic> mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::fpMaskT
The focal plane mask type.
Definition at line 51 of file lyotCoronagraph.hpp.
template<typename _realT , typename _fpmaskFloatT > typedef Eigen::Array< realT, Eigen::Dynamic, Eigen::Dynamic> mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::imageT
The image type.
Definition at line 54 of file lyotCoronagraph.hpp.
template<typename _realT , typename _fpmaskFloatT > typedef _realT mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::realT
The real floating point type.
Definition at line 39 of file lyotCoronagraph.hpp.
Member Function Documentation
template<typename _realT , typename _fpmaskFloatT > int mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadApodizer (const std::string & apodName)
Load the apodizer from a FITS file.
Returns
0 on success.
-1 on error.
Parameters
[in] apodName is the name of the FITS file containing the apodizer.
Definition at line 232 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::pupilApodizer, and mx::improc::fitsFile< dataT >::read().
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph().
template<typename _realT , typename _fpmaskFloatT > int mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph (const std::string & apodName, const std::string & fpmName, const std::string & lyotName)
Load the components of the coronagraph from FITS files.
Returns
0 on success.
-1 on error.
Parameters
[in] apodName is the name of the FITS file containing the apodizer.
[in] fpmName is the name of the FITS file containing the focal plane mask.
[in] lyotName is the name of the FITS file containing the lyot stop.
Definition at line 265 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadApodizer(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadLyotStop().
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph().
template<typename _realT , typename _fpmaskFloatT > int mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph (const std::string & cName)
Load the components of the coronagraph based in its base name.
Looks in _filDir for the files.
Returns
0 on success.
-1 on error.
Parameters
[in] cName is the base name of the coronagraph without directory of file extension.
Definition at line 277 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::_fileDir, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::focalMask, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::lyotStop, MXE_PARAMNOTSET, mxError, and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::pupilApodizer.
template<typename _realT , typename _fpmaskFloatT > int mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask (const std::string & fpmName)
Load the focal plane mask from a FITS file.
Returns
0 on success.
-1 on error.
Parameters
[in] fpmName is the name of the FITS file containing the focal plane mask.
Definition at line 241 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::focalMask, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskFile, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskRad, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskSource, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskTrans, and mx::improc::fitsFile< dataT >::read().
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph().
template<typename _realT , typename _fpmaskFloatT > int mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadLyotStop (const std::string & lyotName)
Load the Lyot stop from a FITS file.
Returns
0 on success.
-1 on error.
Parameters
[in] lyotName is the name of the FITS file containing the lyot stop.
Definition at line 256 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::lyotStop, and mx::improc::fitsFile< dataT >::read().
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph().
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::makeFocalMask (realT rad, fpmaskFloatT trans = 0.0, int sz = 0.0)
Make the focal plane mask.
Definition at line 202 of file lyotCoronagraph.hpp.
References mx::wfp::circularPupil(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::focalMask, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskFile, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskRad, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskSource, and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskTrans.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC().
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC (imageT & geomPupil, realT fpmRadPix, realT relTol, realT absTol, int maxIter, const std::string & cname)
Optimize the pupil amplitude apodization and focal-plane mask complex transmission.
Uses the algorithm in Guyon (2014) [7] for optimizing an Apodized-Pupil Lyot Complex Mask Coronagraph (APLCMC).
Parameters
geomPupil The geometric pupil mask, binary 1/0 transmission.
fpmRadPix The radius in pixels of the FPM.
relTol Relative tolerance for convergence.
absTol Absolute tolerance for convergence.
maxIter Maximum number of iterations to allow.
cname Name of coronagraph, used as base-name for output files in _fileDir.
Definition at line 394 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::_wfSz, mx::improc::fitsHeader::append(), mx::wfp::circularPupil(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::fi, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::focalMask, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::lyotStop, mx::wfp::makeComplexPupil(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::makeFocalMask(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskSource, mx::wfp::fraunhoferPropagator< _wavefrontT >::propagateFocalToPupil(), mx::wfp::fraunhoferPropagator< _wavefrontT >::propagatePupilToFocal(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::pupilApodizer, and mx::improc::fitsFile< dataT >::write().
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::propagate (complexFieldT & pupilPlane)
Propagate the given pupil-plane wavefront through the coronagraph.
Parameters
[in,out] pupilPlane The wavefront at the input pupil plane. It is modified by the coronagraph.
Definition at line 355 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::fi, mx::wfp::fraunhoferPropagator< _wavefrontT >::propagateFocalToPupil(), and mx::wfp::fraunhoferPropagator< _wavefrontT >::propagatePupilToFocal().
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::propagateNC (complexFieldT & pupilPlane)
Propagate the given pupil-plane wavefront without the coronagraph.
For a Lyot coronagraph, this applies the pupil apodization and Lyot stop, but not the FPM, to the given pupil-plane wavefront such that the result will produce the non-coronagraphic (off-axis) PSF.
Parameters
[in,out] pupilPlane The wavefront at the input pupil plane. It is modified by the coronagraph.
Definition at line 380 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::fi, mx::wfp::fraunhoferPropagator< _wavefrontT >::propagateFocalToPupil(), and mx::wfp::fraunhoferPropagator< _wavefrontT >::propagatePupilToFocal().
template<typename _realT , typename _fpmaskFloatT > int mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::wfSz ()
Get the wavefront size in pixels.
Returns
the wavefront size in pixels
Definition at line 186 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::_wfSz.
template<typename _realT , typename _fpmaskFloatT > void mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::wfSz (int sz)
Set the wavefront size in pixels.
Parameters
[in] sz is the new size
Definition at line 192 of file lyotCoronagraph.hpp.
References mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::_wfSz, mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::fi, and mx::wfp::fraunhoferPropagator< _wavefrontT >::setWavefrontSizePixels().
Member Data Documentation
template<typename _realT , typename _fpmaskFloatT > std::string mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::_fileDir
The directory where coronagraph files are stored.
Definition at line 57 of file lyotCoronagraph.hpp.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph().
template<typename _realT , typename _fpmaskFloatT > int mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::_wfSz
The linear size of the wavefront in pixels.
Definition at line 60 of file lyotCoronagraph.hpp.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::wfSz().
template<typename _realT , typename _fpmaskFloatT > fraunhoferPropagator<complexFieldT> mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::fi
Fraunhofer propagator.
Definition at line 89 of file lyotCoronagraph.hpp.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::propagate(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::propagateNC(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::wfSz().
template<typename _realT , typename _fpmaskFloatT > fpMaskT mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::focalMask
The focal plane mask.
Definition at line 72 of file lyotCoronagraph.hpp.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::makeFocalMask(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC().
template<typename _realT , typename _fpmaskFloatT > imageT mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::lyotStop
Image containing the lyot stop.
Definition at line 75 of file lyotCoronagraph.hpp.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadLyotStop(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC().
template<typename _realT , typename _fpmaskFloatT > std::string mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskFile
Name of file from which mask was loaded.
Definition at line 67 of file lyotCoronagraph.hpp.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::makeFocalMask().
template<typename _realT , typename _fpmaskFloatT > realT mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskRad
Radius of mask if it was constructed.
Definition at line 68 of file lyotCoronagraph.hpp.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::makeFocalMask().
template<typename _realT , typename _fpmaskFloatT > int mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskSource
0= read frounobs8m_2048_128_fpm.fitsm file, 1 = constructed by makeFocalMask, 2 = trans optimized.
Definition at line 66 of file lyotCoronagraph.hpp.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::makeFocalMask(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC().
template<typename _realT , typename _fpmaskFloatT > realT mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::maskTrans
Transmission of mask if it was constructed.
Definition at line 69 of file lyotCoronagraph.hpp.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadFocalMask(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::makeFocalMask().
template<typename _realT , typename _fpmaskFloatT > imageT mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::pupilApodizer
Image containing the pupil apodization.
Definition at line 63 of file lyotCoronagraph.hpp.
Referenced by mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadApodizer(), mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::loadCoronagraph(), and mx::wfp::lyotCoronagraph< _realT, _fpmaskFloatT >::optimizeAPLCMC().
The documentation for this struct was generated from the following file:
wfp/lyotCoronagraph.hpp