mxlib: mx::AO::analysis::wfs< realT, iosT > Struct Template Reference
mx::AO::analysis::wfs< realT, iosT > Struct Template Reference
Wavefront Propagation » Adaptive Optics » Analysis of Adaptive Optics
template<typename realT, typename iosT = std::ostream>
struct mx::AO::analysis::wfs< realT, iosT >
The ideal wavefront sensor sensitivity function.
Provides the \(\beta_p \) parameter of Guyon, 2005 [8] for the ideal WFS.
This is the base class for all WFS.
Template Parameters
realT is the floating point type used for calculations
iosT is an output stream type with operator << defined (default is std::ostream)
Definition at line 32 of file aoWFS.hpp.
#include <ao/analysis/aoWFS.hpp>
Public Member Functions
wfs ()
Constructor.
virtual ~wfs ()
Destructor.
virtual realT beta_p (int m, int n, realT D)
Get the sensitivity at a spatial frequency.
virtual iosT & dumpWFS (iosT &ios)
Dump the details of the WFS to an io stream.
Constructor & Destructor Documentation
template<typename realT, typename iosT = std::ostream> mx::AO::analysis::wfs< realT, iosT >::wfs () inline
Constructor.
Only sets the value of _id.
Definition at line 39 of file aoWFS.hpp.
template<typename realT, typename iosT = std::ostream> virtual mx::AO::analysis::wfs< realT, iosT >::~wfs () inline virtual
Destructor.
Declared virtual so more complicated derived types can be created.
Definition at line 47 of file aoWFS.hpp.
Member Function Documentation
template<typename realT, typename iosT = std::ostream> virtual realT mx::AO::analysis::wfs< realT, iosT >::beta_p (int m, int n, realT D) inline virtual
Get the sensitivity at a spatial frequency.
The sensitivity of the ideal WFS is 1 at all k [8].
Returns
the sensitivity to photon noise parameter
Parameters
[in] m the spatial frequency index for u
[in] n the spatial frequency index for v
[in] D the telescope diameter
Reimplemented in mx::AO::analysis::pywfsModAsymptotic< realT, iosT >, and mx::AO::analysis::pywfsUnmod< realT, iosT >.
Definition at line 57 of file aoWFS.hpp.
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::measurementError(), and mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::optimumTauWFS().
template<typename realT, typename iosT = std::ostream> virtual iosT& mx::AO::analysis::wfs< realT, iosT >::dumpWFS (iosT & ios) inline virtual
Dump the details of the WFS to an io stream.
Is virtual so that derived types can add parameters.
Definition at line 68 of file aoWFS.hpp.
Referenced by mx::AO::analysis::aoSystem< realT, inputSpectT, iosT >::dumpAOSystem().
The documentation for this struct was generated from the following file:
ao/analysis/aoWFS.hpp