mxlib: mx::math::fit::gaussian2D_sym_fitter< _realT > Struct Template Reference
mx::math::fit::gaussian2D_sym_fitter< _realT > Struct Template Reference
General Mathematics » Data Fitting » Peak Fitting » Gaussians
template<typename _realT>
struct mx::math::fit::gaussian2D_sym_fitter< _realT >
levmarInterface fitter structure for the symmetric Gaussian.
Definition at line 31 of file fitGaussian.hpp.
#include <math/fit/fitGaussian.hpp>
Public Member Functions
void paramNormalizer (realT *p, int dir)
Does nothing in this case.
Member Function Documentation
template<typename _realT > void mx::math::fit::gaussian2D_sym_fitter< _realT >::paramNormalizer (realT * p, int dir) inline
Does nothing in this case.
Definition at line 256 of file fitGaussian.hpp.
References mx::math::fit::levmarInterface< fitterT >::adata, mx::astro::constants::c(), mx::math::func::gaussian2D_gen2rot(), mx::math::func::gaussian2D_rot2gen(), mx::astro::constants::k(), mx::math::fit::levmarInterface< fitterT >::m, mx::math::fit::levmarInterface< fitterT >::n, mx::math::fit::array2Fit< realT >::nx, mx::math::fit::array2Fit< realT >::ny, mx::math::fit::levmarInterface< fitterT >::p, mx::math::fit::fitGaussian2D< fitterT >::sigma_x(), mx::math::fit::fitGaussian2D< fitterT >::sigma_y(), and mx::math::fit::fitGaussian2D< fitterT >::theta().
The documentation for this struct was generated from the following file:
math/fit/fitGaussian.hpp