mxlib: mx::AO::analysis::clAOLinearPredictor< _realT > Struct Template Reference
mx::AO::analysis::clAOLinearPredictor< _realT > Struct Template Reference
Wavefront Propagation » Adaptive Optics » Analysis of Adaptive Optics
template<typename _realT>
struct mx::AO::analysis::clAOLinearPredictor< _realT >
Class to manage the calculation of linear predictor coefficients for a closed-loop AO system.
Template Parameters
_realT the real floating point type in which to do all arithmetic.
Definition at line 34 of file clAOLinearPredictor.hpp.
#include <ao/analysis/clAOLinearPredictor.hpp>
Public Member Functions
int calcCoefficients (std::vector< realT > &PSDt, std::vector< realT > &PSDn, realT PSDreg, int Nc)
Calculate the LP coefficients for a turbulence PSD and a noise PSD.
template<bool printout = false>
int _regularizeCoefficients (realT &min_var, realT &min_sc, realT precision, realT max_sc, clGainOpt< realT > &go_lp, std::vector< realT > &PSDt, std::vector< realT > &PSDn, int Nc)
Worker function for regularizing the PSD for coefficient calculation.
template<bool printout = false>
int regularizeCoefficients (realT &gmax_lp, realT &gopt_lp, realT &var_lp, clGainOpt< realT > &go_lp, std::vector< realT > &PSDt, std::vector< realT > &PSDn, int Nc)
Regularize the PSD and calculate the associated LP coefficients.
Member Function Documentation
template<typename _realT> template<bool printout = false> int mx::AO::analysis::clAOLinearPredictor< _realT >::_regularizeCoefficients (realT & min_var, realT & min_sc, realT precision, realT max_sc, clGainOpt< realT > & go_lp, std::vector< realT > & PSDt, std::vector< realT > & PSDn, int Nc) inline
Worker function for regularizing the PSD for coefficient calculation.
Template Parameters
printout if true then the results are printed to stdout as they are calculated.
Parameters
[in,out] min_var the minimum variance found. Set to 0 on initial call
[in,out] min_sc the scale factor at the minimum variance.
[in] precision the step-size for the scale factor
[in] max_sc the maximum scale factor to test
[in] go_lp the gain optimization object
[in] PSDt the turbulence PSD
[in] PSDn the WFS noise PSD
[in] Nc the number of coefficients
Definition at line 87 of file clAOLinearPredictor.hpp.
References mx::AO::analysis::clGainOpt< _realT >::a(), mx::AO::analysis::clGainOpt< _realT >::b(), mx::AO::analysis::clAOLinearPredictor< _realT >::calcCoefficients(), mx::AO::analysis::clGainOpt< _realT >::maxStableGain(), and mx::AO::analysis::clGainOpt< _realT >::optGainOpenLoop().
template<typename _realT> int mx::AO::analysis::clAOLinearPredictor< _realT >::calcCoefficients (std::vector< realT > & PSDt, std::vector< realT > & PSDn, realT PSDreg, int Nc) inline
Calculate the LP coefficients for a turbulence PSD and a noise PSD.
This combines the two PSDs, augments to two-sided, and calls the linearPredictor.calcCoefficients method.
A regularization constant can be added to the PSD as well.
Parameters
[in] PSDt the turbulence PSD
[in] PSDn the WFS noise PSD
[in] PSDreg the regularizing constant. Set to 0 to not use.
[in] Nc the number of LP coefficients.
Definition at line 58 of file clAOLinearPredictor.hpp.
References mx::sigproc::augment1SidedPSD(), and mx::sigproc::linearPredictor< _realT >::calcCoefficients().
Referenced by mx::AO::analysis::clAOLinearPredictor< _realT >::_regularizeCoefficients(), and mx::AO::analysis::clAOLinearPredictor< _realT >::regularizeCoefficients().
template<typename _realT> template<bool printout = false> int mx::AO::analysis::clAOLinearPredictor< _realT >::regularizeCoefficients (realT & gmax_lp, realT & gopt_lp, realT & var_lp, clGainOpt< realT > & go_lp, std::vector< realT > & PSDt, std::vector< realT > & PSDn, int Nc) inline
Regularize the PSD and calculate the associated LP coefficients.
The PSD is regularized by adding a constant to it. This constant is found by minimizing the variance of the residual PSD.
Template Parameters
printout if true then the results are printed to stdout as they are calculated.
Parameters
[out] gmax_lp the maximum gain calculated for the regularized PSD
[out] gopt_lp the optimum gain calculated for the regularized PSD
[out] var_lp the variance at the optimum gain.
[in] go_lp the gain optimization object
[in] PSDt the turbulence PSD
[in] PSDn the WFS noise PSD
[in] Nc the number of coefficients
Definition at line 157 of file clAOLinearPredictor.hpp.
References mx::AO::analysis::clGainOpt< _realT >::a(), mx::AO::analysis::clGainOpt< _realT >::b(), mx::AO::analysis::clAOLinearPredictor< _realT >::calcCoefficients(), mx::AO::analysis::clGainOpt< _realT >::maxStableGain(), and mx::AO::analysis::clGainOpt< _realT >::optGainOpenLoop().
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::analyzePSDGrid().
The documentation for this struct was generated from the following file:
ao/analysis/clAOLinearPredictor.hpp