mxlib: mx::appConfigurator Struct Reference
mx::appConfigurator Struct Reference
General Utilities » An Application Framework
Class to manage a set of configurable values, and read their values from config/ini files and the command line.
Bug:
a config=value pair listed in a conf file twice seems to cause a failure, even if they are the same value.
Definition at line 91 of file appConfigurator.hpp.
#include <app/appConfigurator.hpp>
Public Types
typedef std::unordered_map< std::string, configTarget >::iterator targetIterator
Iterator for the targets unordered_map.
typedef std::list< configTarget >::iterator clOnlyTargetIterator
Iterator for the clOnlyTargets list.
Public Member Functions
void clear ()
Clear the containers and free up the associated memory.
void add (const configTarget &tgt)
Add a configTarget.
void add (const std::string &n, const std::string &so, const std::string &lo, int clt, const std::string &s, const std::string &kw, bool isReq=false, const std::string &ht="", const std::string &he="")
Add a configTarget.
void parseCommandLine (int argc, char **argv, const std::string &oneTarget="")
Parse the command line, updating the targets.
void readConfig (const std::string &fname)
Parse a config/ini file, updating the targets.
bool isSet (const std::string &name)
Check if a target has been set by the configuration.
int count (const std::string &name)
Get the number of different values set for the specified config target.
template<typename typeT >
int get (typeT &v, const std::string &name, int i)
Get the i-th value of the target, converted to the specified type.
template<typename typeT >
int get (typeT &v, const std::string &name)
Get the final value of the target, converted to the specified type.
template<typename typeT >
int get (std::vector< typeT > &v, const std::string &name)
Get the i-th value of the target as a vector containing the specified type.
template<typename typeT >
int get (std::vector< typeT > &v, const std::string &name, int i)
Get the i-th value of the target, converted to the specified config target.
template<typename typeT >
typeT get (const std::string &name)
Get the final value of the target, returned as the specified type.
Public Attributes
std::unordered_map< std::string, configTarget > targets
The targets are stored in an unordered_map for fast access by key.
std::list< configTarget > clOnlyTargets
Targets which are only for the command line are stored separately in a list.
Member Typedef Documentation
typedef std::list<configTarget>::iterator mx::appConfigurator::clOnlyTargetIterator
Iterator for the clOnlyTargets list.
Definition at line 97 of file appConfigurator.hpp.
typedef std::unordered_map<std::string, configTarget>::iterator mx::appConfigurator::targetIterator
Iterator for the targets unordered_map.
Definition at line 94 of file appConfigurator.hpp.
Member Function Documentation
void mx::appConfigurator::add (const configTarget & tgt) inline
Add a configTarget.
Note that if name is a duplicate but the section and keyword are empty, it is handled as command-line only.
Parameters
[in] tgt The configuration target to add
Definition at line 267 of file appConfigurator.hpp.
References mx::configTarget::keyword, mx::configTarget::name, and mx::configTarget::section.
Referenced by mx::application::setupStandardConfig().
void mx::appConfigurator::add (const std::string & n, const std::string & so, const std::string & lo, int clt, const std::string & s, const std::string & kw, bool isReq = false, const std::string & ht = "", const std::string & he = "") inline
Add a configTarget.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] n The name of the target
[in] so The command-line short option (e.g. "f" for -f)
[in] lo The command-line long option (e.g. "file" for –file)
[in] clt The command-line option type, argType::false, argType::true, argType::optional, argType::required
[in] s The config file section name, can be empty ""
[in] kw The config file keyword, read in a "keyword=value" pair
[in] isReq Whether or not this is option is required to be set
[in] ht The type to display in the help message
[in] he The explanation to display in the help message
Definition at line 287 of file appConfigurator.hpp.
References mx::configTarget::configTarget().
void mx::appConfigurator::clear () inline
Clear the containers and free up the associated memory.
Definition at line 260 of file appConfigurator.hpp.
Referenced by mx::application::main().
int mx::appConfigurator::count (const std::string & name) inline
Get the number of different values set for the specified config target.
Returns
the number of different values set for name.
Parameters
[in] name the target name
Definition at line 383 of file appConfigurator.hpp.
References mx::configTarget::name.
template<typename typeT > int mx::appConfigurator::get (typeT & v, const std::string & name, int i)
Get the i-th value of the target, converted to the specified type.
The supplied value is only altered if the config target was set, which preserves. default values.
Return values
0 on success
-1 on error
Parameters
[out] v the variable to store the value in
[in] name the config target name
[in] i the number of config specification to get.
Definition at line 389 of file appConfigurator.hpp.
References mx::configTarget::name, and mx::configTarget::values.
template<typename typeT > int mx::appConfigurator::get (typeT & v, const std::string & name)
Get the final value of the target, converted to the specified type.
The supplied value is only altered if the config target was set, which preserves. default values.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Return values
0 on success.
-1 on error.
Parameters
[out] v the variable to store the value in
[in] name the config target name
Definition at line 404 of file appConfigurator.hpp.
References mx::configTarget::name.
template<typename typeT > int mx::appConfigurator::get (std::vector< typeT > & v, const std::string & name)
Get the i-th value of the target as a vector containing the specified type.
The vector is only populated if the config target was set. If it is populated, it is cleared first. Thus if a vector filled with default values is passed in, it will only be overwritten if the user specified new values.
Return values
0 on success.
-1 on error.
Parameters
[out] v the vector to populate
name [in[ the config target name.
Definition at line 458 of file appConfigurator.hpp.
References mx::configTarget::name.
template<typename typeT > int mx::appConfigurator::get (std::vector< typeT > & v, const std::string & name, int i)
Get the i-th value of the target, converted to the specified config target.
The vector is only populated if the config target was set. If it is populated, it is cleared first. Thus if a vector filled with default values is passed in, it will only be overwritten if the user specified new values.
Returns
0 on success
-1 on error
Parameters
[out] v the vector to populate
[in] name the config target name.
[in] i the number of config specification to get.
Definition at line 418 of file appConfigurator.hpp.
References mx::configTarget::values.
template<typename typeT > typeT mx::appConfigurator::get (const std::string & name)
Get the final value of the target, returned as the specified type.
The default-constructed/initialized value is returned if isSet() == false, so this should carefully be used in conjunction with isSet() to avoid overwriting default values.
This works for vectors as well (through tag dispatching). In any case, you must explicitly specify typeT, as in
float f = get<float>(name);
std::vector<float> v = get<std::vector<float>>(name);
Return values
0 on success.
-1 on error.
Parameters
[in] name the config target name
Definition at line 514 of file appConfigurator.hpp.
References mx::configTarget::name.
bool mx::appConfigurator::isSet (const std::string & name) inline
Check if a target has been set by the configuration.
Returns
true if the configuration set at least one value for this target
false if no value was set.
Parameters
[in] name the target name
Definition at line 376 of file appConfigurator.hpp.
References mx::configTarget::name.
void mx::appConfigurator::parseCommandLine (int argc, char ** argv, const std::string & oneTarget = "") inline
Parse the command line, updating the targets.
Parameters
[in] argc standard command line result specifying number of argumetns in argv
[in] argv standard command line result containing the arguments.
[in] oneTarget [optional] if not empty, then only this target is extracted by the parser.
Definition at line 301 of file appConfigurator.hpp.
References mx::clOptions::getAll().
Referenced by mx::application::setup().
void mx::appConfigurator::readConfig (const std::string & fname)
Parse a config/ini file, updating the targets.
Todo:
handle += here, by appending to the last value as if a vector.
Parameters
[in] fname the config file name
Definition at line 356 of file appConfigurator.hpp.
Referenced by mx::application::setup().
Member Data Documentation
std::list<configTarget> mx::appConfigurator::clOnlyTargets
Targets which are only for the command line are stored separately in a list.
Definition at line 103 of file appConfigurator.hpp.
Referenced by mx::application::help().
std::unordered_map<std::string, configTarget> mx::appConfigurator::targets
The targets are stored in an unordered_map for fast access by key.
Definition at line 100 of file appConfigurator.hpp.
Referenced by mx::application::help().
The documentation for this struct was generated from the following file:
app/appConfigurator.hpp