mxlib: mx::improc::HCIobservation< _realT > Struct Template Reference
mx::improc::HCIobservation< _realT > Struct Template Reference
Astronomy | Image Processing » High Contrast Imaging
template<typename _realT>
struct mx::improc::HCIobservation< _realT >
The basic high contrast imaging data type.
This class manages file reading, resizing, co-adding, pre-processing (masking and filtering), and final image combination.
Template Parameters
_realT is the floating point type in which to do all arithmetic.
Definition at line 79 of file HCIobservation.hpp.
#include <improc/HCIobservation.hpp>
Public Types
typedef _realT realT
The arithmetic type used for calculations. Does not have to match the type in images on disk.
typedef Array< realT, Eigen::Dynamic, Eigen::Dynamic > eigenImageT
The Eigen image array type basted on realT.
Public Member Functions
int readFiles ()
Read the list of files, cut to size, and apply the mask.
int readWeights ()
Read the image weights from weightFile.
int threshold ()
Read the image qualities from qualityFile and apply the threshold.
virtual int postReadFiles ()
Perform post-read actions, for use by derived classes.
virtual void makeMaskCube ()
Populate the mask cube. Derived classes can do this as appropriate, e.g. by rotating the mask.
void coaddImages ()
Coadd the images.
void preProcess ()
Do the pre-processing.
void outputPreProcessed ()
Output the pre-processed images.
void combineFinim ()
Combine the images into a single final image.
void writeFinim (fitsHeader *addHead=0)
Write the final combined image to disk.
void outputPSFSub (fitsHeader *addHead=0)
Write the PSF subtracted images to disk.
Construction and Initialization
void initialize ()
Sets defaults for all parameters. Called by each constructor.
HCIobservation ()
Default c'tor.
HCIobservation (const std::string &dir, const std::string &prefix, const std::string ext=".fits")
Construct and load the file list.
HCIobservation (const std::string &fileListFile)
Construct using a file containing the file lise.
void loadFileList (const std::string &fileListFile)
Load the file list from a file.
void loadFileList (const std::string &dir, const std::string &prefix, const std::string &ext)
Load the file list.
Public Attributes
File Reading
Options to control which files are read, how they are read, what meta data is extracted from FITS headers, sizing and masking, etc.
std::vector< std::string > fileList
The list of files to read in.
int deleteFront
Specify how many files from fileList to delete from the front of the list.
int deleteBack
Specify how many files from fileList to delete from the back of the list.
std::string qualityFile
File containing 2 space-delimited columns of fileVame qualityValue pairs.
realT qualityThreshold
Threshold to apply to qualityValues read from qualityFile.
bool thresholdOnly
Just prints the names and qualities of the files which pass threshold, and stop.
std::string MJDKeyword
Name of the keyword to use for the image date.
bool MJDisISO8601
Whether or not the date is in ISO 8601 format.
realT MJDUnits
If the date is not ISO 8601, this specifies the conversion to Julian Days (i.e. seconds to days)
std::vector< std::string > keywords
Vector of FITS header keywords to read from the files in fileList.
int imSize
Set the image size. Images are cut down to this size after reading.
Coadding
These parameters control whether and how the images are coadded after being read. Coadding can be done up to a given number of images, and/or a given elapsed time.
Averages the values of given Keywords as well.
int coaddCombineMethod
Determine how to coadd the raw images.
int coaddMaxImno
Maximum number of images to coadd.
int coaddMaxTime
Maximum elapsed time over which to coadd the images.
std::vector< std::string > coaddKeywords
The values of these keywords will be averaged and replaced.
Masking
A 1/0 mask can be supplied, which is used in pre-processing and in image combination.
std::string maskFile
Specify a mask file to apply.
Pre-Processing
These options control the pre-processing masking and filtering. They are performed in the following order:
mask applied (enabled by preProcess_mask
radial profile subtraction (enabled by preProcess_subradprof)
mask applied (enabled by preProcess_mask
symmetric Gaussian unsharp mask (preProcess_gaussUSM_fwhm)
mask applied (enabled by preProcess_mask
azimuthal unsharp mask (preProcess_azUSM_azW, and preProcess_azUSM_radW)
mask applied (enabled by preProcess_mask)
bool skipPreProcess
Don't do any of the pre-processing steps (including coadding).
bool preProcess_beforeCoadd
controls whether pre-processing takes place before or after coadding
bool preProcess_mask
If true, the mask is applied during each pre-processing step.
bool preProcess_subradprof
If true, a radial profile is subtracted from each image.
realT preProcess_azUSM_azW
Azimuthal boxcar width for azimuthal unsharp mask.
realT preProcess_azUSM_radW
Radial boxcar width for azimuthal unsharp mask.
realT preProcess_gaussUSM_fwhm
Kernel FWHM for symmetric unsharp mask (USM)
std::string preProcess_outputPrefix
Set path and file prefix to output the pre-processed images.
bool preProcess_only
If true, then we stop after pre-processing.
Image Combination
These options control how the final image combination is performed.
int combineMethod
Determine how to combine the PSF subtracted images.
std::string weightFile
Specifies a file containing the image weights, for combining with weighted mean.
realT sigmaThreshold
The standard deviation threshold used if combineMethod == HCI::sigmaMeanCombine.
Output
These options control the ouput fo the final combined images and the individual PSF subtracted images.
int doWriteFinim
Set whether the final combined image is written to disk.
std::string outputDir
The directory where to write output files.
std::string finimName
The base file name of the output final image.
bool exactFinimName
Use finimName exactly as specified, without appending a number or an extension.
bool doOutputPSFSub
Controls whether or not the individual PSF subtracted images are written to disk.
std::string PSFSubPrefix
Prefix of the FITS file names used to write individual PSF subtracted images to disk if doOutputPSFSub is true.
The Raw Data
std::vector< double > imageMJD
Vector image times, in MJD.
std::vector< fitsHeader > heads
Vector of FITS headers,one per file, populated with the values for the keywords.
bool filesRead
Whether or not the fileList has been read.
bool filesDeleted
Whether or not the specified files have been deleted from fileList.
eigenImageT mask
The mask.
eigenCube< realT > maskCube
A cube of masks, one for each input image, which may be modified versions (e.g. rotated) of mask.
std::vector< realT > comboWeights
Vector to hold the imaged weights read from the weightFile.
eigenCube< realT > imc
The image cube.
int Nims
Number of images in imc.
int Nrows
Number of rows of the images in imc.
int Ncols
Number of columns of the images in imc.
int Npix
Pixels per image, that is Nrows*Ncols.
The Reduced Data
std::vector< eigenCube< realT > > psfsub
The PSF subtracted images.
eigenCube< realT > finim
The final combined images, one for each cube in psfsub.
Member Typedef Documentation
template<typename _realT > typedef Array<realT, Eigen::Dynamic, Eigen::Dynamic> mx::improc::HCIobservation< _realT >::eigenImageT
The Eigen image array type basted on realT.
Definition at line 86 of file HCIobservation.hpp.
template<typename _realT > typedef _realT mx::improc::HCIobservation< _realT >::realT
The arithmetic type used for calculations. Does not have to match the type in images on disk.
Definition at line 83 of file HCIobservation.hpp.
Constructor & Destructor Documentation
template<typename _realT > mx::improc::HCIobservation< _realT >::HCIobservation ()
Default c'tor.
Definition at line 554 of file HCIobservation.hpp.
template<typename _realT > mx::improc::HCIobservation< _realT >::HCIobservation (const std::string & dir, const std::string & prefix, const std::string ext = ".fits")
Construct and load the file list.
Populates the fileList vector by searching on disk for files which match "dir/prefix*.ext". See loadFileList
Parameters
[in] dir is the directory to search.
[in] prefix is the initial part of the file name. Can be empty "".
[in] ext is the extension to append to the file name. If ommitted defaults to ".fits"
Definition at line 560 of file HCIobservation.hpp.
template<typename _realT > mx::improc::HCIobservation< _realT >::HCIobservation (const std::string & fileListFile)
Construct using a file containing the file lise.
Populates the fileList vector by reading the file, which should be a single column of new-line delimited file names.
Parameters
[in] fileListFile is a file name to read.
Definition at line 567 of file HCIobservation.hpp.
Member Function Documentation
template<typename _realT > void mx::improc::HCIobservation< _realT >::coaddImages ()
Coadd the images.
Todo:
this should really include end of exposure too.
Todo:
this needs to handle averaging of angles
Definition at line 861 of file HCIobservation.hpp.
References mx::get_curr_time(), mx::improc::eigenCube< dataT >::image(), mx::improc::eigenCube< dataT >::mean(), mx::improc::HCI::meanCombine, mx::improc::eigenCube< dataT >::median(), mx::improc::HCI::medianCombine, and mx::improc::HCI::noCombine.
template<typename _realT > void mx::improc::HCIobservation< _realT >::combineFinim ()
Combine the images into a single final image.
Images are combined by the method specified in combineMethod
Definition at line 1138 of file HCIobservation.hpp.
References mx::get_curr_time(), mx::improc::HCI::meanCombine, mx::improc::HCI::medianCombine, mx::improc::HCI::noCombine, and mx::improc::HCI::sigmaMeanCombine.
template<typename _realT > void mx::improc::HCIobservation< _realT >::initialize ()
Sets defaults for all parameters. Called by each constructor.
Definition at line 486 of file HCIobservation.hpp.
References mx::improc::HCI::meanCombine, and mx::improc::HCI::noCombine.
template<typename _realT > void mx::improc::HCIobservation< _realT >::loadFileList (const std::string & fileListFile) inline
Load the file list from a file.
Populates the fileList vector by reading the file, which should be a single column of new-line delimited file names.
Parameters
[in] fileListFile is a file name to read.
Definition at line 574 of file HCIobservation.hpp.
References mx::readColumns().
template<typename _realT > void mx::improc::HCIobservation< _realT >::loadFileList (const std::string & dir, const std::string & prefix, const std::string & ext) inline
Load the file list.
Populates the fileList vector by searching on disk for files which match the given parameters. Uses mx::getFileNames to search for all files which match "dir/prefix*.ext".
Parameters
[in] dir is the directory to search.
[in] prefix is the initial part of the file name. Can be empty "".
[in] ext is the extension to append to the file name. Can be empty "".
Definition at line 583 of file HCIobservation.hpp.
References mx::getFileNames().
template<typename _realT > void mx::improc::HCIobservation< _realT >::makeMaskCube () virtual
Populate the mask cube. Derived classes can do this as appropriate, e.g. by rotating the mask.
Reimplemented in mx::improc::ADIobservation< _realT, _derotFunctObj >.
Definition at line 850 of file HCIobservation.hpp.
template<typename _realT > void mx::improc::HCIobservation< _realT >::outputPreProcessed ()
Output the pre-processed images.
Todo:
Should add a HISTORY card here
Definition at line 1118 of file HCIobservation.hpp.
References mx::improc::fitsFile< dataT >::write().
template<typename _realT > void mx::improc::HCIobservation< _realT >::outputPSFSub (fitsHeader * addHead = 0) inline
Write the PSF subtracted images to disk.
Definition at line 1327 of file HCIobservation.hpp.
References mx::improc::fitsHeader::append(), mx::improc::fitsHeaderGitStatus(), mx::astro::constants::h(), mxlib_compiled_git_repo_modified(), mxlib_compiled_git_sha1(), mx::improc::HCI::noCombine, and mx::improc::fitsFile< dataT >::write().
template<typename _realT > int mx::improc::HCIobservation< _realT >::postReadFiles () virtual
Perform post-read actions, for use by derived classes.
Reimplemented in mx::improc::ADIobservation< _realT, _derotFunctObj >.
Definition at line 844 of file HCIobservation.hpp.
template<typename _realT > void mx::improc::HCIobservation< _realT >::preProcess ()
Do the pre-processing.
Definition at line 1011 of file HCIobservation.hpp.
References mx::improc::filterImage(), mx::get_curr_time(), and mx::improc::radprofim().
template<typename _realT > int mx::improc::HCIobservation< _realT >::readFiles ()
Read the list of files, cut to size, and apply the mask.
Returns
0 on success, -1 on error.
Bug:
It is this step that is really slow during file reads sometimes
Definition at line 592 of file HCIobservation.hpp.
References mx::improc::fitsHeader::append(), mx::get_curr_time(), mx::ISO8601date2mjd(), MXE_FILENOTFOUND, mxError, mx::improc::HCI::noCombine, mx::improc::fitsFile< dataT >::read(), and mx::improc::fitsFile< dataT >::setReadSize().
template<typename _realT > int mx::improc::HCIobservation< _realT >::readWeights ()
Read the image weights from weightFile.
This is called by readFiles().
Returns
0 on success, -1 on error.
Definition at line 790 of file HCIobservation.hpp.
References MXE_NOTFOUND, MXE_PARAMNOTSET, MXE_SIZEERR, mxError, and mx::readColumns().
template<typename _realT > int mx::improc::HCIobservation< _realT >::threshold ()
Read the image qualities from qualityFile and apply the threshold.
This is called by readFiles().
Returns
0 on success, -1 on error.
Definition at line 746 of file HCIobservation.hpp.
References MXE_PARAMNOTSET, mxError, and mx::readColumns().
template<typename _realT > void mx::improc::HCIobservation< _realT >::writeFinim (fitsHeader * addHead = 0) inline
Write the final combined image to disk.
Definition at line 1248 of file HCIobservation.hpp.
References mx::improc::fitsHeader::append(), mx::improc::fitsHeaderGitStatus(), mx::getSequentialFilename(), mxlib_compiled_git_repo_modified(), mxlib_compiled_git_sha1(), mx::improc::HCI::noCombine, mx::improc::HCI::sigmaMeanCombine, and mx::improc::fitsFile< dataT >::write().
Member Data Documentation
template<typename _realT > int mx::improc::HCIobservation< _realT >::coaddCombineMethod
Determine how to coadd the raw images.
Possibilities are
HCI::noCombine – [default] do not combine. This turns off coadding.
HCI::medianCombine – coadded image is the median
HCI::meanCombine – coadded image is the simple mean
No other types of combination are currently supported for coadding.
Definition at line 168 of file HCIobservation.hpp.
template<typename _realT > std::vector<std::string> mx::improc::HCIobservation< _realT >::coaddKeywords
The values of these keywords will be averaged and replaced.
Definition at line 177 of file HCIobservation.hpp.
template<typename _realT > int mx::improc::HCIobservation< _realT >::coaddMaxImno
Maximum number of images to coadd.
Definition at line 171 of file HCIobservation.hpp.
template<typename _realT > int mx::improc::HCIobservation< _realT >::coaddMaxTime
Maximum elapsed time over which to coadd the images.
Definition at line 174 of file HCIobservation.hpp.
template<typename _realT > int mx::improc::HCIobservation< _realT >::combineMethod
Determine how to combine the PSF subtracted images.
Possibilities are
HCI::noCombine – do not combine
HCI::medianCombine – [default] final image is the median
HCI::meanCombine – final image is the simple mean
HCI::weightedMeanCombine – final image is the weighted mean. weightFile must be provided.
HCI::sigmaMeanCombine – final image is sigma clipped mean. If sigmaThreshold <= 0, then it reverts to meanCombine.
Definition at line 260 of file HCIobservation.hpp.
template<typename _realT > std::vector<realT> mx::improc::HCIobservation< _realT >::comboWeights
Vector to hold the imaged weights read from the weightFile.
After readWeights is executed by readFiles, this will contain the normalized weights.
Definition at line 333 of file HCIobservation.hpp.
template<typename _realT > int mx::improc::HCIobservation< _realT >::deleteBack
Specify how many files from fileList to delete from the back of the list.
Definition at line 103 of file HCIobservation.hpp.
template<typename _realT > int mx::improc::HCIobservation< _realT >::deleteFront
Specify how many files from fileList to delete from the front of the list.
Definition at line 100 of file HCIobservation.hpp.
template<typename _realT > bool mx::improc::HCIobservation< _realT >::doOutputPSFSub
Controls whether or not the individual PSF subtracted images are written to disk.
true – write to disk
false – [default] don't write to disk
Definition at line 303 of file HCIobservation.hpp.
template<typename _realT > int mx::improc::HCIobservation< _realT >::doWriteFinim
Set whether the final combined image is written to disk.
Definition at line 282 of file HCIobservation.hpp.
template<typename _realT > bool mx::improc::HCIobservation< _realT >::exactFinimName
Use finimName exactly as specified, without appending a number or an extension.
Output is still FITS format, regardless of extension. This will overwrite an existing file without asking.
Definition at line 297 of file HCIobservation.hpp.
template<typename _realT > std::vector<std::string> mx::improc::HCIobservation< _realT >::fileList
The list of files to read in.
This can be set on construction or by calling loadFileList
Definition at line 97 of file HCIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake().
template<typename _realT > bool mx::improc::HCIobservation< _realT >::filesDeleted
Whether or not the specified files have been deleted from fileList.
Definition at line 324 of file HCIobservation.hpp.
template<typename _realT > bool mx::improc::HCIobservation< _realT >::filesRead
Whether or not the fileList has been read.
Definition at line 321 of file HCIobservation.hpp.
template<typename _realT > eigenCube<realT> mx::improc::HCIobservation< _realT >::finim
The final combined images, one for each cube in psfsub.
Definition at line 356 of file HCIobservation.hpp.
template<typename _realT > std::string mx::improc::HCIobservation< _realT >::finimName
The base file name of the output final image.
The complete name is formed by combining with a sequential number and the ".fits" extension. that is: finimName0000.fits. This behavior can be modified with exactFinimName.
Definition at line 291 of file HCIobservation.hpp.
template<typename _realT > std::vector<fitsHeader> mx::improc::HCIobservation< _realT >::heads
Vector of FITS headers,one per file, populated with the values for the keywords.
Definition at line 318 of file HCIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::postReadFiles(), and mx::improc::ADIobservation< _realT, _derotFunctObj >::readFiles().
template<typename _realT > std::vector<double> mx::improc::HCIobservation< _realT >::imageMJD
Vector image times, in MJD.
Definition at line 315 of file HCIobservation.hpp.
template<typename _realT > eigenCube<realT> mx::improc::HCIobservation< _realT >::imc
The image cube.
Definition at line 337 of file HCIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake().
template<typename _realT > int mx::improc::HCIobservation< _realT >::imSize
Set the image size. Images are cut down to this size after reading.
Set to <= 0 to use images uncut.
Image sizes are not increased if this is larger than their size on disk.
Definition at line 147 of file HCIobservation.hpp.
template<typename _realT > std::vector<std::string> mx::improc::HCIobservation< _realT >::keywords
Vector of FITS header keywords to read from the files in fileList.
Definition at line 140 of file HCIobservation.hpp.
template<typename _realT > eigenImageT mx::improc::HCIobservation< _realT >::mask
The mask.
Definition at line 327 of file HCIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::makeMaskCube().
template<typename _realT > eigenCube<realT> mx::improc::HCIobservation< _realT >::maskCube
A cube of masks, one for each input image, which may be modified versions (e.g. rotated) of mask.
Definition at line 328 of file HCIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::makeMaskCube().
template<typename _realT > std::string mx::improc::HCIobservation< _realT >::maskFile
Specify a mask file to apply.
No mask is applied if this is empty.
Definition at line 190 of file HCIobservation.hpp.
template<typename _realT > bool mx::improc::HCIobservation< _realT >::MJDisISO8601
Whether or not the date is in ISO 8601 format.
Definition at line 134 of file HCIobservation.hpp.
template<typename _realT > std::string mx::improc::HCIobservation< _realT >::MJDKeyword
Name of the keyword to use for the image date.
Specifies the keyword corresponding to the date. This is the "DATE" keyword for file write time, and usually "DATE-OBS" for actual observation time.
Default is "DATE-OBS".
If empty "", then image date is not read.
Definition at line 131 of file HCIobservation.hpp.
template<typename _realT > realT mx::improc::HCIobservation< _realT >::MJDUnits
If the date is not ISO 8601, this specifies the conversion to Julian Days (i.e. seconds to days)
Definition at line 137 of file HCIobservation.hpp.
template<typename _realT > int mx::improc::HCIobservation< _realT >::Ncols
Number of columns of the images in imc.
Definition at line 341 of file HCIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::makeMaskCube().
template<typename _realT > int mx::improc::HCIobservation< _realT >::Nims
Number of images in imc.
Definition at line 339 of file HCIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::makeMaskCube().
template<typename _realT > int mx::improc::HCIobservation< _realT >::Npix
Pixels per image, that is Nrows*Ncols.
Definition at line 342 of file HCIobservation.hpp.
template<typename _realT > int mx::improc::HCIobservation< _realT >::Nrows
Number of rows of the images in imc.
Definition at line 340 of file HCIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::makeMaskCube().
template<typename _realT > std::string mx::improc::HCIobservation< _realT >::outputDir
The directory where to write output files.
Definition at line 285 of file HCIobservation.hpp.
template<typename _realT > realT mx::improc::HCIobservation< _realT >::preProcess_azUSM_azW
Azimuthal boxcar width for azimuthal unsharp mask.
If this is 0 then azimuthal-USM is not performed.
Definition at line 222 of file HCIobservation.hpp.
template<typename _realT > realT mx::improc::HCIobservation< _realT >::preProcess_azUSM_radW
Radial boxcar width for azimuthal unsharp mask.
If this is 0 then azimuthal-USM is not performed.
Definition at line 227 of file HCIobservation.hpp.
template<typename _realT > bool mx::improc::HCIobservation< _realT >::preProcess_beforeCoadd
controls whether pre-processing takes place before or after coadding
Definition at line 213 of file HCIobservation.hpp.
template<typename _realT > realT mx::improc::HCIobservation< _realT >::preProcess_gaussUSM_fwhm
Kernel FWHM for symmetric unsharp mask (USM)
USM is not performed if this is 0.
Definition at line 233 of file HCIobservation.hpp.
template<typename _realT > bool mx::improc::HCIobservation< _realT >::preProcess_mask
If true, the mask is applied during each pre-processing step.
Definition at line 215 of file HCIobservation.hpp.
template<typename _realT > bool mx::improc::HCIobservation< _realT >::preProcess_only
If true, then we stop after pre-processing.
Definition at line 241 of file HCIobservation.hpp.
template<typename _realT > std::string mx::improc::HCIobservation< _realT >::preProcess_outputPrefix
Set path and file prefix to output the pre-processed images.
If empty, then pre-processed images are not output.
Definition at line 238 of file HCIobservation.hpp.
template<typename _realT > bool mx::improc::HCIobservation< _realT >::preProcess_subradprof
If true, a radial profile is subtracted from each image.
Definition at line 217 of file HCIobservation.hpp.
template<typename _realT > std::vector<eigenCube<realT> > mx::improc::HCIobservation< _realT >::psfsub
The PSF subtracted images.
This is a vector of cubes so that it can contain results from different reductions, e.g. different modes when using KLIP.
Definition at line 353 of file HCIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::derotate().
template<typename _realT > std::string mx::improc::HCIobservation< _realT >::PSFSubPrefix
Prefix of the FITS file names used to write individual PSF subtracted images to disk if doOutputPSFSub is true.
Definition at line 306 of file HCIobservation.hpp.
template<typename _realT > std::string mx::improc::HCIobservation< _realT >::qualityFile
File containing 2 space-delimited columns of fileVame qualityValue pairs.
If this is not empty and qualityThreshold is > 0, then only images where qualityValue >= qualityThreshold.
The only restriction on qualityTValue is that it is > 0. It is intendend to be something like Strehl ratio.
Definition at line 113 of file HCIobservation.hpp.
template<typename _realT > realT mx::improc::HCIobservation< _realT >::qualityThreshold
Threshold to apply to qualityValues read from qualityFile.
If <= 0, then thresholding is not performed.
Definition at line 118 of file HCIobservation.hpp.
template<typename _realT > realT mx::improc::HCIobservation< _realT >::sigmaThreshold
The standard deviation threshold used if combineMethod == HCI::sigmaMeanCombine.
Definition at line 271 of file HCIobservation.hpp.
template<typename _realT > bool mx::improc::HCIobservation< _realT >::skipPreProcess
Don't do any of the pre-processing steps (including coadding).
Definition at line 211 of file HCIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::postReadFiles().
template<typename _realT > bool mx::improc::HCIobservation< _realT >::thresholdOnly
Just prints the names and qualities of the files which pass threshold, and stop.
Definition at line 121 of file HCIobservation.hpp.
template<typename _realT > std::string mx::improc::HCIobservation< _realT >::weightFile
Specifies a file containing the image weights, for combining with weighted mean.
This 2-column space-delimited ASCII file containing filenames and weights. It must be specified before readFiles() is executed. In readFiles this is loaded after the fileList is cutdown and matched to the remaining files.
Definition at line 266 of file HCIobservation.hpp.
The documentation for this struct was generated from the following file:
improc/HCIobservation.hpp