mxlib: mx::improc::ADIobservation< _realT, _derotFunctObj > Struct Template Reference
mx::improc::ADIobservation< _realT, _derotFunctObj > Struct Template Reference
Astronomy | Image Processing » High Contrast Imaging
template<typename _realT, class _derotFunctObj>
struct mx::improc::ADIobservation< _realT, _derotFunctObj >
Process an angular differential imaging (ADI) observation.
Angular differential imaging (ADI) uses sky rotation to differentiate real objects from speckles.
Template Parameters
realT is the floating point type in which to do calculations
_derotFunctObj is the derotation object with the following minimum interface:
template<typename _realT>
struct derotF
{
   typedef  _realT realT;
   //Vector of keywords to extract from the fits headers
   std::vector<std::string> keywords;
   //Vector(s) to hold the keyword values
   std::vector<realT> keyValue1;
   ///To allow ADIobservation to check for errors.
   bool isSetup()
   {
     if( <any condition indicatint not set up>) return false;
     return true;
   }
   //Method called by HCIobservation to get keyword-values
   void extractKeywords(vector<fitsHeader> & heads)
   {
      keyValue1 = headersToValues<float>(heads, "KEYWORD1");
   }
   //Calculate the derotation angle for a given image number
   realT derotAngle(size_t imno) const
   {
      return some_function_of(keyValue1[imno]); //This function uses keyValue1[imno] to produce the derotation angle in radians.
   }
};
Definition at line 111 of file ADIobservation.hpp.
#include <improc/ADIobservation.hpp>
Public Member Functions
int readFiles ()
Read in the files.
virtual int postReadFiles ()
Post read actions, including fake injection.
virtual void makeMaskCube ()
Populate the mask cube. Derived classes can do this as appropriate, e.g. by rotating the mask.
void derotate ()
De-rotate the PSF subtracted images.
Public Member Functions inherited from mx::improc::HCIobservation< _realT >
int readFiles ()
Read the list of files, cut to size, and apply the mask.
int readWeights ()
Read the image weights from weightFile.
int threshold ()
Read the image qualities from qualityFile and apply the threshold.
void coaddImages ()
Coadd the images.
void preProcess ()
Do the pre-processing.
void outputPreProcessed ()
Output the pre-processed images.
void combineFinim ()
Combine the images into a single final image.
void writeFinim (fitsHeader *addHead=0)
Write the final combined image to disk.
void outputPSFSub (fitsHeader *addHead=0)
Write the PSF subtracted images to disk.
void initialize ()
Sets defaults for all parameters. Called by each constructor.
HCIobservation ()
Default c'tor.
HCIobservation (const std::string &dir, const std::string &prefix, const std::string ext=".fits")
Construct and load the file list.
HCIobservation (const std::string &fileListFile)
Construct using a file containing the file lise.
void loadFileList (const std::string &fileListFile)
Load the file list from a file.
void loadFileList (const std::string &dir, const std::string &prefix, const std::string &ext)
Load the file list.
Public Attributes
Rotation Setup
Configuration of the rotation system.
std::string angleKeyword
realT angleScale
realT angleConstant
Public Attributes inherited from mx::improc::HCIobservation< _realT >
std::vector< std::string > fileList
The list of files to read in.
int deleteFront
Specify how many files from fileList to delete from the front of the list.
int deleteBack
Specify how many files from fileList to delete from the back of the list.
std::string qualityFile
File containing 2 space-delimited columns of fileVame qualityValue pairs.
realT qualityThreshold
Threshold to apply to qualityValues read from qualityFile.
bool thresholdOnly
Just prints the names and qualities of the files which pass threshold, and stop.
std::string MJDKeyword
Name of the keyword to use for the image date.
bool MJDisISO8601
Whether or not the date is in ISO 8601 format.
realT MJDUnits
If the date is not ISO 8601, this specifies the conversion to Julian Days (i.e. seconds to days)
std::vector< std::string > keywords
Vector of FITS header keywords to read from the files in fileList.
int imSize
Set the image size. Images are cut down to this size after reading.
int coaddCombineMethod
Determine how to coadd the raw images.
int coaddMaxImno
Maximum number of images to coadd.
int coaddMaxTime
Maximum elapsed time over which to coadd the images.
std::vector< std::string > coaddKeywords
The values of these keywords will be averaged and replaced.
std::string maskFile
Specify a mask file to apply.
bool skipPreProcess
Don't do any of the pre-processing steps (including coadding).
bool preProcess_beforeCoadd
controls whether pre-processing takes place before or after coadding
bool preProcess_mask
If true, the mask is applied during each pre-processing step.
bool preProcess_subradprof
If true, a radial profile is subtracted from each image.
realT preProcess_azUSM_azW
Azimuthal boxcar width for azimuthal unsharp mask.
realT preProcess_azUSM_radW
Radial boxcar width for azimuthal unsharp mask.
realT preProcess_gaussUSM_fwhm
Kernel FWHM for symmetric unsharp mask (USM)
std::string preProcess_outputPrefix
Set path and file prefix to output the pre-processed images.
bool preProcess_only
If true, then we stop after pre-processing.
int combineMethod
Determine how to combine the PSF subtracted images.
std::string weightFile
Specifies a file containing the image weights, for combining with weighted mean.
realT sigmaThreshold
The standard deviation threshold used if combineMethod == HCI::sigmaMeanCombine.
int doWriteFinim
Set whether the final combined image is written to disk.
std::string outputDir
The directory where to write output files.
std::string finimName
The base file name of the output final image.
bool exactFinimName
Use finimName exactly as specified, without appending a number or an extension.
bool doOutputPSFSub
Controls whether or not the individual PSF subtracted images are written to disk.
std::string PSFSubPrefix
Prefix of the FITS file names used to write individual PSF subtracted images to disk if doOutputPSFSub is true.
std::vector< double > imageMJD
Vector image times, in MJD.
std::vector< fitsHeader > heads
Vector of FITS headers,one per file, populated with the values for the keywords.
bool filesRead
Whether or not the fileList has been read.
bool filesDeleted
Whether or not the specified files have been deleted from fileList.
eigenImageT mask
The mask.
eigenCube< realT > maskCube
A cube of masks, one for each input image, which may be modified versions (e.g. rotated) of mask.
std::vector< realT > comboWeights
Vector to hold the imaged weights read from the weightFile.
eigenCube< realT > imc
The image cube.
int Nims
Number of images in imc.
int Nrows
Number of rows of the images in imc.
int Ncols
Number of columns of the images in imc.
int Npix
Pixels per image, that is Nrows*Ncols.
std::vector< eigenCube< realT > > psfsub
The PSF subtracted images.
eigenCube< realT > finim
The final combined images, one for each cube in psfsub.
Fake Planets
int fakeMethod
std::string fakeFileName
FITS file containing the fake planet PSF to inject or a list of fake images.
std::string fakeScaleFileName
One-column text file containing a scale factor for each point in time.
std::vector< realT > fakeSep
Separation(s) of the fake planet(s)
std::vector< realT > fakePA
Position angles(s) of the fake planet(s)
std::vector< realT > fakeContrast
Contrast(s) of the fake planet(s)
int injectFake ()
Inect the fake plants.
int injectFake (eigenImageT &fakePSF, int image_i, realT PA, realT sep, realT contrast, realT scale=1.0)
Additional Inherited Members
Public Types inherited from mx::improc::HCIobservation< _realT >
typedef _realT realT
The arithmetic type used for calculations. Does not have to match the type in images on disk.
typedef Array< realT, Eigen::Dynamic, Eigen::Dynamic > eigenImageT
The Eigen image array type basted on realT.
Member Function Documentation
template<typename _realT , class _derotFunctObj > void mx::improc::ADIobservation< _realT, _derotFunctObj >::derotate ()
De-rotate the PSF subtracted images.
Definition at line 421 of file ADIobservation.hpp.
References mx::improc::fitsHeader::append(), mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeContrast, mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeFileName, mx::improc::ADIobservation< _realT, _derotFunctObj >::fakePA, mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeScaleFileName, mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeSep, mx::get_curr_time(), mx::improc::imageRotate(), and mx::improc::HCIobservation< _realT >::psfsub.
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake ()
Inect the fake plants.
Definition at line 277 of file ADIobservation.hpp.
References mx::improc::cutPaddedImage(), mx::math::dtor(), mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeContrast, mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeFileName, mx::improc::ADIobservation< _realT, _derotFunctObj >::fakePA, mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeScaleFileName, mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeSep, mx::improc::HCIobservation< _realT >::fileList, mx::get_curr_time(), mx::improc::eigenCube< dataT >::image(), mx::improc::imageShift(), mx::improc::HCIobservation< _realT >::imc, mx::improc::padImage(), mx::improc::fitsFile< dataT >::read(), and mx::readColumns().
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::postReadFiles().
template<typename _realT , class _derotFunctObj > void mx::improc::ADIobservation< _realT, _derotFunctObj >::makeMaskCube () virtual
Populate the mask cube. Derived classes can do this as appropriate, e.g. by rotating the mask.
Reimplemented from mx::improc::HCIobservation< _realT >.
Definition at line 404 of file ADIobservation.hpp.
References mx::improc::eigenCube< dataT >::image(), mx::improc::HCIobservation< _realT >::mask, mx::improc::HCIobservation< _realT >::maskCube, mx::improc::HCIobservation< _realT >::Ncols, mx::improc::HCIobservation< _realT >::Nims, mx::improc::HCIobservation< _realT >::Nrows, and mx::improc::fitsFile< dataT >::write().
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::postReadFiles () virtual
Post read actions, including fake injection.
Reimplemented from mx::improc::HCIobservation< _realT >.
Definition at line 264 of file ADIobservation.hpp.
References mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeFileName, mx::improc::HCIobservation< _realT >::heads, mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake(), and mx::improc::HCIobservation< _realT >::skipPreProcess.
template<typename _realT , class _derotFunctObj > int mx::improc::ADIobservation< _realT, _derotFunctObj >::readFiles ()
Read in the files.
First sets up the keywords, then calls HCIobservation readFiles
Definition at line 236 of file ADIobservation.hpp.
References mx::improc::HCIobservation< _realT >::heads, MXE_PARAMNOTSET, and mxError.
Member Data Documentation
template<typename _realT, class _derotFunctObj> std::vector<realT> mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeContrast
Contrast(s) of the fake planet(s)
Definition at line 165 of file ADIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::derotate(), and mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake().
template<typename _realT, class _derotFunctObj> std::string mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeFileName
FITS file containing the fake planet PSF to inject or a list of fake images.
Definition at line 158 of file ADIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::derotate(), mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake(), and mx::improc::ADIobservation< _realT, _derotFunctObj >::postReadFiles().
template<typename _realT, class _derotFunctObj> std::vector<realT> mx::improc::ADIobservation< _realT, _derotFunctObj >::fakePA
Position angles(s) of the fake planet(s)
Definition at line 164 of file ADIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::derotate(), and mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake().
template<typename _realT, class _derotFunctObj> std::string mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeScaleFileName
One-column text file containing a scale factor for each point in time.
Definition at line 161 of file ADIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::derotate(), and mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake().
template<typename _realT, class _derotFunctObj> std::vector<realT> mx::improc::ADIobservation< _realT, _derotFunctObj >::fakeSep
Separation(s) of the fake planet(s)
Definition at line 163 of file ADIobservation.hpp.
Referenced by mx::improc::ADIobservation< _realT, _derotFunctObj >::derotate(), and mx::improc::ADIobservation< _realT, _derotFunctObj >::injectFake().
The documentation for this struct was generated from the following file:
improc/ADIobservation.hpp