mxlib: mx::astro::mainSequence< realT > Struct Template Reference
mx::astro::mainSequence< realT > Struct Template Reference
template<typename realT>
struct mx::astro::mainSequence< realT >
Provide various characteristics of main sequence stars according to their spectral type.
Interpolates on "A Modern Mean Dwarf Stellar Color and Effective Temperature Sequence" by Eric Mamajek, available at http://www.pas.rochester.edu/~emamajek/EEM_dwarf_UBVIJHK_colors_Teff.txt.
Loads values of the sequence at construction (hard coded), and then provides interpolation in between the points.
Version of the sequence used: 2017.03.14
Definition at line 105 of file stars.hpp.
#include <astro/stars.hpp>
Public Member Functions
realT Teff (realT numType)
Get the interpolated effective temperature.
realT Teff (const std::string &spType)
Get the interpolated effective temperature.
realT logL (realT numType)
Get the interpolated log of luminosity.
realT logL (const std::string &spType)
Get the interpolated log of luminosity.
realT Mv (realT numType)
Get the interpolated absolute V magnitude.
realT Mv (const std::string &spType)
Get the interpolated absolute V magnitude.
realT V_Rc (realT numType)
Get the interpolated absolute V-Rc color.
realT V_Rc (const std::string &spType)
Get the interpolated absolute V-Rc color.
realT V_Ic (realT numType)
Get the interpolated absolute V-Ic color.
realT V_Ic (const std::string &spType)
Get the interpolated absolute V-Ic color.
realT V_Ks (realT numType)
Get the interpolated absolute V-Ks color.
realT V_Ks (const std::string &spType)
Get the interpolated absolute V-Ks color.
realT J_H (realT numType)
Get the interpolated absolute J-H color.
realT J_H (const std::string &spType)
Get the interpolated absolute J-H color.
realT H_Ks (realT numType)
Get the interpolated absolute H-Ks color.
realT H_Ks (const std::string &spType)
Get the interpolated absolute H-Ks color.
Public Attributes
std::vector< double > numTypes
The numeric spectral type codes from the sequence.
std::vector< double > Teffs
The effective temperatures from the sequence.
std::vector< double > logLs
The log10 luminosities from the sequence.
std::vector< double > Mvs
The absolute V magnitudes from the sequence.
std::vector< double > V_Rcs
The V-Rc colors from the sequence.
std::vector< double > V_Ics
The V-Ic colors from the sequence.
std::vector< double > V_Kss
The V-Ks colors from the sequence.
std::vector< double > J_Hs
The J-H colors from the sequence.
std::vector< double > H_Kss
The H-Ks colors from the sequence.
gslInterpolator interpT
The interpolator for effective Temperature.
double minT
The minimum numeric spectral type for effective Temperature.
double maxT
The maximum numeric spectral type for effective Temperature.
gslInterpolator interpL
The interpolator for log luminosity.
double minL
The minimum numeric spectral type for log luminosity.
double maxL
The maximum numeric spectral type for log luminosity.
gslInterpolator interpMv
The interpolator for absolute V magnitude.
double minMv
The minimum numeric spectral type for absolute V magnitude.
double maxMv
The maximum numeric spectral type for absolute V magnitude.
gslInterpolator interpVRc
The interpolator for V-Rc color.
double minVRc
The minimum numeric spectral type for V-Rc color.
double maxVRc
The maximum numeric spectral type for V-Rc color.
gslInterpolator interpVIc
The interpolator for V-Ic color.
double minVIc
The minimum numeric spectral type for V-Ic color.
double maxVIc
The maximum numeric spectral type for V-Ic color.
gslInterpolator interpVKs
The interpolator for V-Ks color.
double minVKs
The minimum numeric spectral type for V-Ks color.
double maxVKs
The maximum numeric spectral type for V-Ks color.
gslInterpolator interpJH
The interpolator for J-H color.
double minJH
The minimum numeric spectral type for J-H color.
double maxJH
The maximum numeric spectral type for J-H color.
gslInterpolator interpHKs
The interpolator for H-Ks color.
double minHKs
The minimum numeric spectral type for H-Ks color.
double maxHKs
The maximum numeric spectral type for H-Ks color.
Member Function Documentation
template<typename realT > realT mx::astro::mainSequence< realT >::H_Ks (realT numType) inline
Get the interpolated absolute H-Ks color.
Returns
the aboslute H-Ks color
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 383 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::H_Ks().
template<typename realT > realT mx::astro::mainSequence< realT >::H_Ks (const std::string & spType) inline
Get the interpolated absolute H-Ks color.
Returns
the aboslute H-Ks color
-999 if the input type is out of range.
Get the interpolated absolute H-Ks color
Returns
the aboslute H-Ks color
-999 if the input type code is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 398 of file stars.hpp.
References mx::astro::mainSequence< realT >::H_Ks(), and mx::astro::numSpType().
template<typename realT > realT mx::astro::mainSequence< realT >::J_H (realT numType) inline
Get the interpolated absolute J-H color.
Returns
the aboslute J-H color
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 358 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::J_H().
template<typename realT > realT mx::astro::mainSequence< realT >::J_H (const std::string & spType) inline
Get the interpolated absolute J-H color.
Returns
the aboslute J-H color
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 373 of file stars.hpp.
References mx::astro::mainSequence< realT >::J_H(), and mx::astro::numSpType().
template<typename realT > realT mx::astro::mainSequence< realT >::logL (realT numType) inline
Get the interpolated log of luminosity.
Returns
the log of luminosity.
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 233 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::logL().
template<typename realT > realT mx::astro::mainSequence< realT >::logL (const std::string & spType) inline
Get the interpolated log of luminosity.
Returns
the log of luminosity.
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 248 of file stars.hpp.
References mx::astro::mainSequence< realT >::logL(), and mx::astro::numSpType().
template<typename realT > realT mx::astro::mainSequence< realT >::Mv (realT numType) inline
Get the interpolated absolute V magnitude.
Returns
the aboslute V magnitude
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 258 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::Mv().
template<typename realT > realT mx::astro::mainSequence< realT >::Mv (const std::string & spType) inline
Get the interpolated absolute V magnitude.
Returns
the aboslute V magnitude
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 273 of file stars.hpp.
References mx::astro::mainSequence< realT >::Mv(), and mx::astro::numSpType().
template<typename realT > realT mx::astro::mainSequence< realT >::Teff (realT numType) inline
Get the interpolated effective temperature.
Returns
the effective temperature.
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 208 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::Teff().
template<typename realT > realT mx::astro::mainSequence< realT >::Teff (const std::string & spType) inline
Get the interpolated effective temperature.
Returns
the effective temperature.
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 223 of file stars.hpp.
References mx::astro::numSpType(), and mx::astro::mainSequence< realT >::Teff().
template<typename realT > realT mx::astro::mainSequence< realT >::V_Ic (realT numType) inline
Get the interpolated absolute V-Ic color.
Returns
the aboslute V-Ic color
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 308 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::V_Ic().
template<typename realT > realT mx::astro::mainSequence< realT >::V_Ic (const std::string & spType) inline
Get the interpolated absolute V-Ic color.
Returns
the aboslute V-Ic color
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 323 of file stars.hpp.
References mx::astro::numSpType(), and mx::astro::mainSequence< realT >::V_Ic().
template<typename realT > realT mx::astro::mainSequence< realT >::V_Ks (realT numType) inline
Get the interpolated absolute V-Ks color.
Returns
the aboslute V-Ks color
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 333 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::V_Ks().
template<typename realT > realT mx::astro::mainSequence< realT >::V_Ks (const std::string & spType) inline
Get the interpolated absolute V-Ks color.
Returns
the aboslute V-Ks color
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 348 of file stars.hpp.
References mx::astro::numSpType(), and mx::astro::mainSequence< realT >::V_Ks().
template<typename realT > realT mx::astro::mainSequence< realT >::V_Rc (realT numType) inline
Get the interpolated absolute V-Rc color.
Returns
the aboslute V-Rc color
-999 if the input type code is out of range.
Parameters
[in] numType the numeric spectral type code, see mx::astro::numSpType()
Definition at line 283 of file stars.hpp.
Referenced by mx::astro::mainSequence< realT >::V_Rc().
template<typename realT > realT mx::astro::mainSequence< realT >::V_Rc (const std::string & spType) inline
Get the interpolated absolute V-Rc color.
Returns
the aboslute V-Rc color
-999 if the input type is out of range.
Parameters
[in] spType the spectral type in standard format
Definition at line 298 of file stars.hpp.
References mx::astro::numSpType(), and mx::astro::mainSequence< realT >::V_Rc().
Member Data Documentation
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::H_Kss
The H-Ks colors from the sequence.
Definition at line 115 of file stars.hpp.
template<typename realT > gslInterpolator mx::astro::mainSequence< realT >::interpHKs
The interpolator for H-Ks color.
Definition at line 145 of file stars.hpp.
template<typename realT > gslInterpolator mx::astro::mainSequence< realT >::interpJH
The interpolator for J-H color.
Definition at line 141 of file stars.hpp.
template<typename realT > gslInterpolator mx::astro::mainSequence< realT >::interpL
The interpolator for log luminosity.
Definition at line 121 of file stars.hpp.
template<typename realT > gslInterpolator mx::astro::mainSequence< realT >::interpMv
The interpolator for absolute V magnitude.
Definition at line 125 of file stars.hpp.
template<typename realT > gslInterpolator mx::astro::mainSequence< realT >::interpT
The interpolator for effective Temperature.
Definition at line 117 of file stars.hpp.
template<typename realT > gslInterpolator mx::astro::mainSequence< realT >::interpVIc
The interpolator for V-Ic color.
Definition at line 133 of file stars.hpp.
template<typename realT > gslInterpolator mx::astro::mainSequence< realT >::interpVKs
The interpolator for V-Ks color.
Definition at line 137 of file stars.hpp.
template<typename realT > gslInterpolator mx::astro::mainSequence< realT >::interpVRc
The interpolator for V-Rc color.
Definition at line 129 of file stars.hpp.
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::J_Hs
The J-H colors from the sequence.
Definition at line 114 of file stars.hpp.
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::logLs
The log10 luminosities from the sequence.
Definition at line 109 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::maxHKs
The maximum numeric spectral type for H-Ks color.
Definition at line 147 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::maxJH
The maximum numeric spectral type for J-H color.
Definition at line 143 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::maxL
The maximum numeric spectral type for log luminosity.
Definition at line 123 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::maxMv
The maximum numeric spectral type for absolute V magnitude.
Definition at line 127 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::maxT
The maximum numeric spectral type for effective Temperature.
Definition at line 119 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::maxVIc
The maximum numeric spectral type for V-Ic color.
Definition at line 135 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::maxVKs
The maximum numeric spectral type for V-Ks color.
Definition at line 139 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::maxVRc
The maximum numeric spectral type for V-Rc color.
Definition at line 131 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::minHKs
The minimum numeric spectral type for H-Ks color.
Definition at line 146 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::minJH
The minimum numeric spectral type for J-H color.
Definition at line 142 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::minL
The minimum numeric spectral type for log luminosity.
Definition at line 122 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::minMv
The minimum numeric spectral type for absolute V magnitude.
Definition at line 126 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::minT
The minimum numeric spectral type for effective Temperature.
Definition at line 118 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::minVIc
The minimum numeric spectral type for V-Ic color.
Definition at line 134 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::minVKs
The minimum numeric spectral type for V-Ks color.
Definition at line 138 of file stars.hpp.
template<typename realT > double mx::astro::mainSequence< realT >::minVRc
The minimum numeric spectral type for V-Rc color.
Definition at line 130 of file stars.hpp.
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::Mvs
The absolute V magnitudes from the sequence.
Definition at line 110 of file stars.hpp.
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::numTypes
The numeric spectral type codes from the sequence.
Definition at line 107 of file stars.hpp.
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::Teffs
The effective temperatures from the sequence.
Definition at line 108 of file stars.hpp.
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::V_Ics
The V-Ic colors from the sequence.
Definition at line 112 of file stars.hpp.
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::V_Kss
The V-Ks colors from the sequence.
Definition at line 113 of file stars.hpp.
template<typename realT > std::vector<double> mx::astro::mainSequence< realT >::V_Rcs
The V-Rc colors from the sequence.
Definition at line 111 of file stars.hpp.
The documentation for this struct was generated from the following file:
astro/stars.hpp