mxlib: mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT > Struct Template Reference
mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT > Struct Template Reference
Astronomy | Image Processing » High Contrast Imaging
template<typename _realT, class _derotFunctObj, typename _evCalcT = double>
struct mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >
An implementation of the Karhunen-Loeve Image Processing (KLIP) algorithm.
KLIP[21] is a principle components analysis (PCA) based technique for PSF estimation.
Template Parameters
_realT is the floating point type in which to do calculations
_derotFunctObj the ADIobservation derotator class.
_evCalcT the real type in which to do eigen-decomposition. Should generally be double for stable results.
Definition at line 60 of file KLIPreduction.hpp.
#include <improc/KLIPreduction.hpp>
Public Member Functions
void worker (eigenCube< realT > &rims, std::vector< size_t > &idx, realT dang)
Public Member Functions inherited from mx::improc::ADIobservation< _realT, _derotFunctObj >
int readFiles ()
Read in the files.
virtual int postReadFiles ()
Post read actions, including fake injection.
virtual void makeMaskCube ()
Populate the mask cube. Derived classes can do this as appropriate, e.g. by rotating the mask.
void derotate ()
De-rotate the PSF subtracted images.
int injectFake ()
Inect the fake plants.
int injectFake (eigenImageT &fakePSF, int image_i, realT PA, realT sep, realT contrast, realT scale=1.0)
Public Member Functions inherited from mx::improc::HCIobservation< _realT >
int readFiles ()
Read the list of files, cut to size, and apply the mask.
int readWeights ()
Read the image weights from weightFile.
int threshold ()
Read the image qualities from qualityFile and apply the threshold.
void coaddImages ()
Coadd the images.
void preProcess ()
Do the pre-processing.
void outputPreProcessed ()
Output the pre-processed images.
void combineFinim ()
Combine the images into a single final image.
void writeFinim (fitsHeader *addHead=0)
Write the final combined image to disk.
void outputPSFSub (fitsHeader *addHead=0)
Write the PSF subtracted images to disk.
void initialize ()
Sets defaults for all parameters. Called by each constructor.
HCIobservation ()
Default c'tor.
HCIobservation (const std::string &dir, const std::string &prefix, const std::string ext=".fits")
Construct and load the file list.
HCIobservation (const std::string &fileListFile)
Construct using a file containing the file lise.
void loadFileList (const std::string &fileListFile)
Load the file list from a file.
void loadFileList (const std::string &dir, const std::string &prefix, const std::string &ext)
Load the file list.
Public Attributes
std::vector< int > Nmodes
Specifies the number of modes to include in the PSF.
realT mindpx
Specify the minimum pixel difference at the inner edge of the search region.
int excludeMethod
Controls how reference images are excluded, if at all, from the covariance matrix for each target image.
int includeRefNum
Number of reference images to include in the covariance matrix.
double t_worker_begin
Calculate the KL images for a given covariance matrix.
Public Attributes inherited from mx::improc::ADIobservation< _realT, _derotFunctObj >
std::string angleKeyword
realT angleScale
realT angleConstant
int fakeMethod
std::string fakeFileName
FITS file containing the fake planet PSF to inject or a list of fake images.
std::string fakeScaleFileName
One-column text file containing a scale factor for each point in time.
std::vector< realT > fakeSep
Separation(s) of the fake planet(s)
std::vector< realT > fakePA
Position angles(s) of the fake planet(s)
std::vector< realT > fakeContrast
Contrast(s) of the fake planet(s)
Public Attributes inherited from mx::improc::HCIobservation< _realT >
std::vector< std::string > fileList
The list of files to read in.
int deleteFront
Specify how many files from fileList to delete from the front of the list.
int deleteBack
Specify how many files from fileList to delete from the back of the list.
std::string qualityFile
File containing 2 space-delimited columns of fileVame qualityValue pairs.
realT qualityThreshold
Threshold to apply to qualityValues read from qualityFile.
bool thresholdOnly
Just prints the names and qualities of the files which pass threshold, and stop.
std::string MJDKeyword
Name of the keyword to use for the image date.
bool MJDisISO8601
Whether or not the date is in ISO 8601 format.
realT MJDUnits
If the date is not ISO 8601, this specifies the conversion to Julian Days (i.e. seconds to days)
std::vector< std::string > keywords
Vector of FITS header keywords to read from the files in fileList.
int imSize
Set the image size. Images are cut down to this size after reading.
int coaddCombineMethod
Determine how to coadd the raw images.
int coaddMaxImno
Maximum number of images to coadd.
int coaddMaxTime
Maximum elapsed time over which to coadd the images.
std::vector< std::string > coaddKeywords
The values of these keywords will be averaged and replaced.
std::string maskFile
Specify a mask file to apply.
bool skipPreProcess
Don't do any of the pre-processing steps (including coadding).
bool preProcess_beforeCoadd
controls whether pre-processing takes place before or after coadding
bool preProcess_mask
If true, the mask is applied during each pre-processing step.
bool preProcess_subradprof
If true, a radial profile is subtracted from each image.
realT preProcess_azUSM_azW
Azimuthal boxcar width for azimuthal unsharp mask.
realT preProcess_azUSM_radW
Radial boxcar width for azimuthal unsharp mask.
realT preProcess_gaussUSM_fwhm
Kernel FWHM for symmetric unsharp mask (USM)
std::string preProcess_outputPrefix
Set path and file prefix to output the pre-processed images.
bool preProcess_only
If true, then we stop after pre-processing.
int combineMethod
Determine how to combine the PSF subtracted images.
std::string weightFile
Specifies a file containing the image weights, for combining with weighted mean.
realT sigmaThreshold
The standard deviation threshold used if combineMethod == HCI::sigmaMeanCombine.
int doWriteFinim
Set whether the final combined image is written to disk.
std::string outputDir
The directory where to write output files.
std::string finimName
The base file name of the output final image.
bool exactFinimName
Use finimName exactly as specified, without appending a number or an extension.
bool doOutputPSFSub
Controls whether or not the individual PSF subtracted images are written to disk.
std::string PSFSubPrefix
Prefix of the FITS file names used to write individual PSF subtracted images to disk if doOutputPSFSub is true.
std::vector< double > imageMJD
Vector image times, in MJD.
std::vector< fitsHeader > heads
Vector of FITS headers,one per file, populated with the values for the keywords.
bool filesRead
Whether or not the fileList has been read.
bool filesDeleted
Whether or not the specified files have been deleted from fileList.
eigenImageT mask
The mask.
eigenCube< realT > maskCube
A cube of masks, one for each input image, which may be modified versions (e.g. rotated) of mask.
std::vector< realT > comboWeights
Vector to hold the imaged weights read from the weightFile.
eigenCube< realT > imc
The image cube.
int Nims
Number of images in imc.
int Nrows
Number of rows of the images in imc.
int Ncols
Number of columns of the images in imc.
int Npix
Pixels per image, that is Nrows*Ncols.
std::vector< eigenCube< realT > > psfsub
The PSF subtracted images.
eigenCube< realT > finim
The final combined images, one for each cube in psfsub.
Additional Inherited Members
Public Types inherited from mx::improc::HCIobservation< _realT >
typedef _realT realT
The arithmetic type used for calculations. Does not have to match the type in images on disk.
typedef Array< realT, Eigen::Dynamic, Eigen::Dynamic > eigenImageT
The Eigen image array type basted on realT.
Member Function Documentation
template<typename _realT , class _derotFunctObj , typename _evCalcT > void mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::worker (eigenCube< realT > & rims, std::vector< size_t > & idx, realT dang)
Bug:
2017-07-18 this omp critical is necessary on jetstream install. Investigation needed.
omp_get_num_threads();
Definition at line 658 of file KLIPreduction.hpp.
References mx::improc::eigenCube< dataT >::asVectors(), mx::math::calcKLModes(), mx::improc::eigenCube< dataT >::cube(), mx::math::eigenSYRK(), mx::improc::HCI::excludeNone, mx::get_curr_time(), and mx::improc::insertImageRegion().
Member Data Documentation
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> int mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::excludeMethod
Controls how reference images are excluded, if at all, from the covariance matrix for each target image.
Can have the following values:
HCI::excludeNone = no exclusion, all images included
HCI::excludePixel = exclude based on pixels of rotation at the inner edge of the region
HCI::excludeAngle = exclude based on degrees of rotation at the inner edge of the region
HCI::excludeImno = exclude based on number of images
Definition at line 96 of file KLIPreduction.hpp.
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> int mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::includeRefNum
Number of reference images to include in the covariance matrix.
If > 0, then at most this many images, determined by highest cross-correlation, are included. This is determined after rotational/image-number exclusion. If == 0, then all reference images are included.
Definition at line 103 of file KLIPreduction.hpp.
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> realT mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::mindpx
Specify the minimum pixel difference at the inner edge of the search region.
Definition at line 86 of file KLIPreduction.hpp.
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> std::vector<int> mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::Nmodes
Specifies the number of modes to include in the PSF.
The output image is a cube with a plane for each entry in Nmodes. Only the number of eigenvalues required for the maximum value of Nmodes are calculated, so this can have an important impact on speed.
Can be initialized as:
red.Nmodes={5,10,15,20};
Definition at line 81 of file KLIPreduction.hpp.
template<typename _realT , class _derotFunctObj , typename _evCalcT = double> double mx::improc::KLIPreduction< _realT, _derotFunctObj, _evCalcT >::t_worker_begin
Calculate the KL images for a given covariance matrix.
Definition at line 186 of file KLIPreduction.hpp.
The documentation for this struct was generated from the following file:
improc/KLIPreduction.hpp