mxlib: mx::wfp::idealCoronagraph< _realT > Struct Template Reference
mx::wfp::idealCoronagraph< _realT > Struct Template Reference
Wavefront Propagation » Coronagraphs
template<typename _realT>
struct mx::wfp::idealCoronagraph< _realT >
The Ideal Coronagraph.
A simple toy coronagraph which operates only the pupil plane, subtracting the energy-minimizing wavefront [2]. For an on-axis source with a perfectly flat wavefront this results in perfect extinction. This coronagraph is not physically realizable, but it is often useful for modeling and analysis, and it has been shown that real-world optimized coronagraphs often approach ideal performance [19] [and Males in prep].
Definition at line 34 of file idealCoronagraph.hpp.
#include <wfp/idealCoronagraph.hpp>
Public Types
typedef _realT realT
The real floating point type.
typedef std::complex< realT > complexT
The complex floating point type.
typedef imagingArray< std::complex< realT >, fftwAllocator< std::complex< realT > >, 0 > complexFieldT
The wavefront complex field type.
typedef Eigen::Array< realT, Eigen::Dynamic, Eigen::Dynamic > imageT
The image type.
Public Member Functions
int wfSz ()
Get the wavefront size in pixels.
void wfSz (int sz)
Set the wavefront size in pixels.
int setPupil (imageT &pupil)
Set the real pupil mask.
int loadPupil (const std::string &pupilFile)
Load the real pupil mask from a FITS file.
int loadCoronagraph (const std::string &cName)
Load the components of the coronagraph (just a pupil) based in its base name.
int propagate (complexFieldT &pupilPlane)
Propagate the given pupil-plane wavefront through the coronagraph.
int propagateNC (complexFieldT &pupilPlane)
Propagate the given pupil-plane wavefront without the coronagraph.
Public Attributes
std::string _fileDir
The directory where coronagraph files are stored.
int _wfSz
The linear size of the wavefront in pixels.
Member Typedef Documentation
template<typename _realT > typedef imagingArray<std::complex<realT>, fftwAllocator<std::complex<realT> >, 0> mx::wfp::idealCoronagraph< _realT >::complexFieldT
The wavefront complex field type.
Definition at line 43 of file idealCoronagraph.hpp.
template<typename _realT > typedef std::complex<realT> mx::wfp::idealCoronagraph< _realT >::complexT
The complex floating point type.
Definition at line 40 of file idealCoronagraph.hpp.
template<typename _realT > typedef Eigen::Array< realT, Eigen::Dynamic, Eigen::Dynamic> mx::wfp::idealCoronagraph< _realT >::imageT
The image type.
Definition at line 46 of file idealCoronagraph.hpp.
template<typename _realT > typedef _realT mx::wfp::idealCoronagraph< _realT >::realT
The real floating point type.
Definition at line 37 of file idealCoronagraph.hpp.
Member Function Documentation
template<typename _realT > int mx::wfp::idealCoronagraph< _realT >::loadCoronagraph (const std::string & cName)
Load the components of the coronagraph (just a pupil) based in its base name.
Looks in _filDir for the files.
Returns
0 on success.
-1 on error.
Parameters
cName The name of the coronagraph, without directory or file extensions
Definition at line 154 of file idealCoronagraph.hpp.
References mx::wfp::idealCoronagraph< _realT >::_fileDir, mx::wfp::idealCoronagraph< _realT >::loadPupil(), MXE_PARAMNOTSET, and mxError.
template<typename _realT > int mx::wfp::idealCoronagraph< _realT >::loadPupil (const std::string & pupilFile)
Load the real pupil mask from a FITS file.
The input mask does not have to be the same size as wfSz, as the stored mask will be padded.
Returns
0 on success.
-1 on error.
Parameters
[in] pupilFile the FITS file containing the pupil mask.
Definition at line 139 of file idealCoronagraph.hpp.
References mx::improc::fitsFile< dataT >::read(), and mx::wfp::idealCoronagraph< _realT >::setPupil().
Referenced by mx::wfp::idealCoronagraph< _realT >::loadCoronagraph().
template<typename _realT > int mx::wfp::idealCoronagraph< _realT >::propagate (complexFieldT & pupilPlane)
Propagate the given pupil-plane wavefront through the coronagraph.
Parameters
[in,out] pupilPlane The wavefront at the input pupil plane. It is modified by the coronagraph.
Definition at line 170 of file idealCoronagraph.hpp.
References MXE_SIZEERR, and mxError.
template<typename _realT > int mx::wfp::idealCoronagraph< _realT >::propagateNC (complexFieldT & pupilPlane)
Propagate the given pupil-plane wavefront without the coronagraph.
For the ideal coronagraph nothing is done. This method is included for compliance with with the coronagraph interface.
Parameters
[in,out] pupilPlane The wavefront at the input pupil plane. It is un-modified.
Definition at line 187 of file idealCoronagraph.hpp.
template<typename _realT > int mx::wfp::idealCoronagraph< _realT >::setPupil (imageT & pupil)
Set the real pupil mask.
The input mask does not have to be the same size as wfSz, as the stored mask will be padded.
Returns
0 on success.
-1 on error.
Parameters
[in] pupil the pupil mask.
Definition at line 124 of file idealCoronagraph.hpp.
References mx::wfp::idealCoronagraph< _realT >::_wfSz, MXE_PARAMNOTSET, mxError, and mx::improc::padImage().
Referenced by mx::wfp::idealCoronagraph< _realT >::loadPupil().
template<typename _realT > int mx::wfp::idealCoronagraph< _realT >::wfSz ()
Get the wavefront size in pixels.
Returns
the wavefront size in pixels
Definition at line 112 of file idealCoronagraph.hpp.
References mx::wfp::idealCoronagraph< _realT >::_wfSz.
template<typename _realT > void mx::wfp::idealCoronagraph< _realT >::wfSz (int sz)
Set the wavefront size in pixels.
Parameters
[in] sz is the new size
Definition at line 118 of file idealCoronagraph.hpp.
References mx::wfp::idealCoronagraph< _realT >::_wfSz.
Member Data Documentation
template<typename _realT > std::string mx::wfp::idealCoronagraph< _realT >::_fileDir
The directory where coronagraph files are stored.
Definition at line 49 of file idealCoronagraph.hpp.
Referenced by mx::wfp::idealCoronagraph< _realT >::loadCoronagraph().
template<typename _realT > int mx::wfp::idealCoronagraph< _realT >::_wfSz
The linear size of the wavefront in pixels.
Definition at line 52 of file idealCoronagraph.hpp.
Referenced by mx::wfp::idealCoronagraph< _realT >::setPupil(), and mx::wfp::idealCoronagraph< _realT >::wfSz().
The documentation for this struct was generated from the following file:
wfp/idealCoronagraph.hpp