mxlib: mx::astro::astroSpectrum< _spectrumT, freq > Struct Template Reference
mx::astro::astroSpectrum< _spectrumT, freq > Struct Template Reference
template<typename _spectrumT, bool freq = false>
struct mx::astro::astroSpectrum< _spectrumT, freq >
Class to manage an astronomical spectrum.
Details of the spectra, including units, file-location, and how they are read from disk, are specified by template parameter _spectrumT. Spectra are loaded and immediately interpolated onto a wavelength grid. This is to facilitate manipulation of spectra, i.e. for multiplying by filters, etc.
Definition at line 27 of file astroSpectrum.hpp.
#include <astro/astroSpectrum.hpp>
Public Member Functions
astroSpectrum ()
Default c'tor.
astroSpectrum (const std::string &name)
Constructor specifying name, the enivronment will be queried for data directory.
astroSpectrum (const std::string &name, const std::string &dataDir)
Constructor specifying name and data directory.
void setParameters (const std::string &name)
void setParameters (const std::string &name, const std::string &dataDir)
template<typename gridT >
int setSpectrum (gridT &lambda)
Load the spectrum and interpolate it on a wavelength scale.
Public Attributes
std::string _dataDir
The directory containing the spectrum.
std::string _name
The name of the spectrum.
std::vector< realT > _spectrum
Contains the spectrum after it is set.
Constructor & Destructor Documentation
template<typename _spectrumT , bool freq = false> mx::astro::astroSpectrum< _spectrumT, freq >::astroSpectrum () inline
Default c'tor.
Definition at line 40 of file astroSpectrum.hpp.
template<typename _spectrumT , bool freq = false> mx::astro::astroSpectrum< _spectrumT, freq >::astroSpectrum (const std::string & name) inline
Constructor specifying name, the enivronment will be queried for data directory.
Parameters
[in] name The name of the spectrum
Definition at line 43 of file astroSpectrum.hpp.
References mx::astro::astroSpectrum< _spectrumT, freq >::setParameters().
template<typename _spectrumT , bool freq = false> mx::astro::astroSpectrum< _spectrumT, freq >::astroSpectrum (const std::string & name, const std::string & dataDir) inline
Constructor specifying name and data directory.
Parameters
[in] name The name of the spectrum
[in] dataDir The directory containing the spectrum
Definition at line 49 of file astroSpectrum.hpp.
References mx::astro::astroSpectrum< _spectrumT, freq >::setParameters().
Member Function Documentation
template<typename _spectrumT , bool freq = false> void mx::astro::astroSpectrum< _spectrumT, freq >::setParameters (const std::string & name) inline
Parameters
[in] name The name of the spectrum
Definition at line 56 of file astroSpectrum.hpp.
References mx::getEnv().
Referenced by mx::astro::astroSpectrum< _spectrumT, freq >::astroSpectrum().
template<typename _spectrumT , bool freq = false> void mx::astro::astroSpectrum< _spectrumT, freq >::setParameters (const std::string & name, const std::string & dataDir) inline
Parameters
[in] name The name of the spectrum
[in] dataDir The directory containing the spectrum
Definition at line 66 of file astroSpectrum.hpp.
template<typename _spectrumT , bool freq = false> template<typename gridT > int mx::astro::astroSpectrum< _spectrumT, freq >::setSpectrum (gridT & lambda) inline
Load the spectrum and interpolate it on a wavelength scale.
Definition at line 76 of file astroSpectrum.hpp.
References mx::gsl_interpolate().
Member Data Documentation
template<typename _spectrumT , bool freq = false> std::string mx::astro::astroSpectrum< _spectrumT, freq >::_dataDir
The directory containing the spectrum.
Definition at line 33 of file astroSpectrum.hpp.
template<typename _spectrumT , bool freq = false> std::string mx::astro::astroSpectrum< _spectrumT, freq >::_name
The name of the spectrum.
Definition at line 35 of file astroSpectrum.hpp.
template<typename _spectrumT , bool freq = false> std::vector<realT> mx::astro::astroSpectrum< _spectrumT, freq >::_spectrum
Contains the spectrum after it is set.
Definition at line 37 of file astroSpectrum.hpp.
The documentation for this struct was generated from the following file:
astro/astroSpectrum.hpp