mxlib: mx::AO::analysis::clGainOpt< _realT > Struct Template Reference
mx::AO::analysis::clGainOpt< _realT > Struct Template Reference
Wavefront Propagation » Adaptive Optics » Analysis of Adaptive Optics
template<typename _realT>
struct mx::AO::analysis::clGainOpt< _realT >
A class to manage optimizing closed-loop gains.
Template Parameters
_realT the real floating point type in which to do all arithmetic. Is used to define the complex type as well.
Definition at line 40 of file clGainOpt.hpp.
#include <ao/analysis/clGainOpt.hpp>
Public Types
typedef _realT realT
The real data type.
typedef std::complex< _realT > complexT
The complex data type.
Public Member Functions
clGainOpt ()
Default c'tor.
clGainOpt (realT Ti, realT tau)
C'tor setting the loop timings.
void init ()
Initialize this instance.
int N ()
Get the number of integrations in the (optional) moving average.
void N (int newN)
Set the number of integrations in the moving average.
realT Ti ()
Get the loop sampling interval.
void Ti (realT newTi)
Set the loop sampling interval.
realT tau ()
Get the loop delay.
void tau (realT newTau)
Set the loop delay.
void b (const std::vector< realT > &newB)
Set the vector of FIR coefficients.
void b (const Eigen::Array< realT,-1,-1 > &newB)
Set the vector of FIR coefficients.
void a (const std::vector< realT > &newA)
Set the vector of IIR coefficients.
void a (const Eigen::Array< realT,-1,-1 > &newA)
Set the vector of IIR coefficients.
void setLeakyIntegrator (realT remember)
Set the FIR and IIR coefficients so that the control law is a leaky integrator.
void f (realT *newF, size_t nF)
Set the vector of frequencies.
void f (std::vector< realT > &newF)
Set the vector of frequencies.
size_t f_size ()
Get the size of the frequency vector.
realT f (size_t i)
Get the i-th value of frequency.
complexT olXfer (int fi, complexT &H_dm, complexT &H_del, complexT &H_con)
Calculate the open-loop transfer function.
complexT olXfer (int fi)
Calculate the open-loop transfer function.
complexT clETF (int fi, realT g)
Return the closed loop error transfer function (ETF) at frequency f for gain g.
realT clETF2 (int fi, realT g)
Return the norm of the closed loop error transfer function (ETF) at frequency f for gain g.
realT clNTF2 (int fi, realT g)
Return the norm of the closed loop noise transfer function (NTF) at frequency f for gain g.
void clTF2 (realT &ETF, realT &NTF, int fi, realT g)
Return the norm of the closed loop transfer functions at frequency f for gain g.
realT clVariance (realT &varErr, realT &varNoise, std::vector< realT > &PSDerr, std::vector< realT > &PSDnoise, realT g)
Calculate the closed loop variance given open-loop PSDs and gain.
realT clVariance (std::vector< realT > &PSDerr, std::vector< realT > &PSDnoise, realT g)
Calculate the closed loop variance given open-loop PSDs and gain.
realT maxStableGain (realT &ll, realT &ul)
Find the maximum stable gain for the loop parameters.
realT maxStableGain (const realT &ll, const realT &ul)
Find the maximum stable gain for the loop parameters.
realT maxStableGain ()
Find the maximum stable gain for the loop parameters.
realT optGainOpenLoop (realT &var, std::vector< realT > &PSDerr, std::vector< realT > &PSDnoise)
Return the optimum closed loop gain given an open loop PSD.
realT optGainOpenLoop (realT &var, std::vector< realT > &PSDerr, std::vector< realT > &PSDnoise, realT &gmax)
Return the optimum closed loop gain given an open loop PSD.
int pseudoOpenLoop (std::vector< realT > &PSD, realT g)
Calculate the pseudo open-loop PSD given a closed loop PSD.
Public Attributes
realT _maxFindMin
The Minimum value for the maximum stable gain finding algorithm.
realT _minFindMin
The Minimum value for the minimum finding algorithm.
realT _minFindMaxFact
The maximum value, as a multiplicative factor of maximum gain.
int _minFindBits
The bits of precision to use for minimum finding. Defaults to std::numeric_limits<realT>::digits.
boost::uintmax_t _minFindMaxIter
The maximum iterations allowed for minimization.
Protected Attributes
int _N
Number of integrations in the (optional) moving average. Default is 1.
realT _Ti
The loop sampling interval.
realT _tau
The loop delay.
std::vector< realT > _b
Vector of FIR coefficients.
std::vector< realT > _a
Vector of IIR coefficients.
std::vector< realT > _f
Vector of frequencies.
bool _fChanged
True if frequency or max size of _a and _b changes.
bool _changed
True if any of the members which make up the basic transfer functions are changed.
Member Typedef Documentation
template<typename _realT> typedef std::complex<_realT> mx::AO::analysis::clGainOpt< _realT >::complexT
The complex data type.
Definition at line 43 of file clGainOpt.hpp.
template<typename _realT> typedef _realT mx::AO::analysis::clGainOpt< _realT >::realT
The real data type.
Definition at line 42 of file clGainOpt.hpp.
Constructor & Destructor Documentation
template<typename realT > mx::AO::analysis::clGainOpt< realT >::clGainOpt ()
Default c'tor.
Definition at line 351 of file clGainOpt.hpp.
template<typename realT > mx::AO::analysis::clGainOpt< realT >::clGainOpt (realT Ti, realT tau)
C'tor setting the loop timings.
Parameters
[in] Ti the desired loop sampling interval.
[in] tau the desired loop delay.
Definition at line 357 of file clGainOpt.hpp.
Member Function Documentation
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::a (const std::vector< realT > & newA)
Set the vector of IIR coefficients.
Parameters
[in] newA a vector of coefficients, which is copied to _a.
Definition at line 457 of file clGainOpt.hpp.
Referenced by mx::AO::analysis::clAOLinearPredictor< _realT >::_regularizeCoefficients(), mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::analyzePSDGrid(), and mx::AO::analysis::clAOLinearPredictor< _realT >::regularizeCoefficients().
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::a (const Eigen::Array< realT,-1,-1 > & newA)
Set the vector of IIR coefficients.
Parameters
[in] newA a column-vector Eigen::Array of coefficients, which is copied to _a.
Definition at line 469 of file clGainOpt.hpp.
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::b (const std::vector< realT > & newB)
Set the vector of FIR coefficients.
Parameters
[in] newB a vector of coefficients, which is copied to _b.
Definition at line 427 of file clGainOpt.hpp.
Referenced by mx::AO::analysis::clAOLinearPredictor< _realT >::_regularizeCoefficients(), mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::analyzePSDGrid(), and mx::AO::analysis::clAOLinearPredictor< _realT >::regularizeCoefficients().
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::b (const Eigen::Array< realT,-1,-1 > & newB)
Set the vector of FIR coefficients.
Parameters
[in] newB a column-vector Eigen::Array of coefficients, which is copied to _b.
Definition at line 439 of file clGainOpt.hpp.
template<typename realT > std::complex< realT > mx::AO::analysis::clGainOpt< realT >::clETF (int fi, realT g)
Return the closed loop error transfer function (ETF) at frequency f for gain g.
Returns
the closed loop ETF at f and g.
Parameters
[in] fi the index of the frequency at which to calculate the ETF
[in] g the loop gain.
Definition at line 658 of file clGainOpt.hpp.
template<typename realT > realT mx::AO::analysis::clGainOpt< realT >::clETF2 (int fi, realT g)
Return the norm of the closed loop error transfer function (ETF) at frequency f for gain g.
Returns
the norm of the closed loop ETF at f and g.
Parameters
[in] fi the index of the frequency at which to calculate the ETF.
[in] g the loop gain.
Definition at line 666 of file clGainOpt.hpp.
template<typename realT > realT mx::AO::analysis::clGainOpt< realT >::clNTF2 (int fi, realT g)
Return the norm of the closed loop noise transfer function (NTF) at frequency f for gain g.
Returns
the value of the closed loop NTF at f and g.
Parameters
[in] fi the index of the frequency at which to calculate the NTF
[in] g the loop gain.
Definition at line 674 of file clGainOpt.hpp.
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::clTF2 (realT & ETF, realT & NTF, int fi, realT g)
Return the norm of the closed loop transfer functions at frequency f for gain g.
Calculates both the error transfer function (ETF) and the noise transfer function (NTF). This minimizes the various complex number operations, compared to calling both clETF2 and clNTF2.
Parameters
[out] ETF is set to the ETF at f and g
[out] NTF is set to the NTF at f and g
[in] fi is the index of the frequency at which to calculate the ETF
[in] g is the loop gain.
Definition at line 688 of file clGainOpt.hpp.
template<typename realT > realT mx::AO::analysis::clGainOpt< realT >::clVariance (realT & varErr, realT & varNoise, std::vector< realT > & PSDerr, std::vector< realT > & PSDnoise, realT g)
Calculate the closed loop variance given open-loop PSDs and gain.
Calculates the following quantities.
\[ \sigma_{err}^2 = \sum_i \left| ETF(f_i) \right|^2 PSD_{err}(fi) \Delta f\\ \sigma_{noise}^2 = \sum_i \left| NTF(f_i) \right|^2 PSD_{noise}(fi) \Delta f\\ \sigma^2 = \sigma_{err}^2 + \sigma_{noise}^2 \]
\(\sigma^2 \) is returned, and \(\sigma_{err}^2 \) and \(\sigma_{noise}^2 \) are available as the optional arguments varErr and varNoise.
Returns
the total variance (error + noise) in closed loop
Parameters
[out] varErr the variance in the residual process error.
[out] varNoise the variance in the residual measurement noise.
[in] PSDerr the open-loop process error PSD.
[in] PSDnoise the open-loop measurement noise PSD.
[in] g the gain.
Definition at line 707 of file clGainOpt.hpp.
Referenced by mx::AO::analysis::clGainOpt< _realT >::pseudoOpenLoop().
template<typename realT > realT mx::AO::analysis::clGainOpt< realT >::clVariance (std::vector< realT > & PSDerr, std::vector< realT > & PSDnoise, realT g)
Calculate the closed loop variance given open-loop PSDs and gain.
Overload of clVariance without the varErr and varNoise output parameters.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
the total variance (error + noise) in closed loop
Parameters
[in] PSDerr the open-loop process error PSD.
[in] PSDnoise the open-loop measurement noise PSD.
[in] g the gain.
Definition at line 746 of file clGainOpt.hpp.
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::f (realT * newF, size_t nF)
Set the vector of frequencies.
Parameters
[in] newF a pointer to an array containing the new frequencies
[in] nF the number of elements of size(realT) in newF.
Definition at line 500 of file clGainOpt.hpp.
Referenced by mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::analyzePSDGrid().
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::f (std::vector< realT > & newF)
Set the vector of frequencies.
Parameters
[in] newF a vector containing the new frequencies
Definition at line 510 of file clGainOpt.hpp.
template<typename realT > realT mx::AO::analysis::clGainOpt< realT >::f (size_t i)
Get the i-th value of frequency.
No range checks are conducted.
Returns
the value of _f[i]
Parameters
[in] i the index of the frequency to return
Definition at line 519 of file clGainOpt.hpp.
template<typename _realT> size_t mx::AO::analysis::clGainOpt< _realT >::f_size () inline
Get the size of the frequency vector.
Returns
_f.size()
Definition at line 176 of file clGainOpt.hpp.
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::init ()
Initialize this instance.
Definition at line 366 of file clGainOpt.hpp.
template<typename realT > realT mx::AO::analysis::clGainOpt< realT >::maxStableGain (realT & ll, realT & ul)
Find the maximum stable gain for the loop parameters.
Returns
the maximum stable gain for the loop parametersFind the maximum stable gain for the loop parameters Conducts a search along the Nyquist contour of the open-loop transfer function to find the most-negative crossing of the real axis.
the maximum stable gain for the loop parameters
Parameters
[in,out] ll the lower limit used for the search
[in,out] ul the upper limit used for hte search
Definition at line 759 of file clGainOpt.hpp.
Referenced by mx::AO::analysis::clAOLinearPredictor< _realT >::_regularizeCoefficients(), and mx::AO::analysis::clAOLinearPredictor< _realT >::regularizeCoefficients().
template<typename _realT> realT mx::AO::analysis::clGainOpt< _realT >::maxStableGain (const realT & ll, const realT & ul)
Find the maximum stable gain for the loop parameters.
Conducts a search along the Nyquist contour of the open-loop transfer function to find the most-negative crossing of the real axis.
This version allows constant arguments. This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
the maximum stable gain for the loop parameters
Parameters
[in] ll the lower limit used for the search
[in] ul the upper limit used for hte search
template<typename realT > realT mx::AO::analysis::clGainOpt< realT >::maxStableGain ()
Find the maximum stable gain for the loop parameters.
Conducts a search along the Nyquist contour of the open-loop transfer function to find the most-negative crossing of the real axis.
This version uses _maxFindMin for the lower limit and no upper limit.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
the maximum stable gain for the loop parameters
Definition at line 794 of file clGainOpt.hpp.
template<typename realT > int mx::AO::analysis::clGainOpt< realT >::N ()
Get the number of integrations in the (optional) moving average.
Returns
the current value of _N.
Definition at line 388 of file clGainOpt.hpp.
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::N (int newN)
Set the number of integrations in the moving average.
Parameters
[in] newN the value of _N.
Definition at line 394 of file clGainOpt.hpp.
template<typename realT > std::complex< realT > mx::AO::analysis::clGainOpt< realT >::olXfer (int fi, complexT & H_dm, complexT & H_del, complexT & H_con)
Calculate the open-loop transfer function.
Returns
the complex value of the open-loop transfer function at f.
Parameters
[in] fi the index of the frequency
[out] H_dm the transfer function of the DM
[out] H_del the delay transfer function
[out] H_con the controller transfer function.
Definition at line 540 of file clGainOpt.hpp.
template<typename realT > std::complex< realT > mx::AO::analysis::clGainOpt< realT >::olXfer (int fi)
Calculate the open-loop transfer function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
the complex value of the open-loop transfer function at f[fi].
Parameters
[in] fi the index of the frequency
Definition at line 526 of file clGainOpt.hpp.
template<typename realT > realT mx::AO::analysis::clGainOpt< realT >::optGainOpenLoop (realT & var, std::vector< realT > & PSDerr, std::vector< realT > & PSDnoise)
Return the optimum closed loop gain given an open loop PSD.
Uses _gmax for the upper limit.
Returns
the optimum gain
Parameters
[out] var the variance at the optimum gain
[in] PSDerr open loop error PSD
[in] PSDnoise open loop measurement noise PSD
Definition at line 803 of file clGainOpt.hpp.
References gmax.
Referenced by mx::AO::analysis::clAOLinearPredictor< _realT >::_regularizeCoefficients(), mx::AO::analysis::fourierTemporalPSD< realT, aosysT >::analyzePSDGrid(), and mx::AO::analysis::clAOLinearPredictor< _realT >::regularizeCoefficients().
template<typename realT > realT mx::AO::analysis::clGainOpt< realT >::optGainOpenLoop (realT & var, std::vector< realT > & PSDerr, std::vector< realT > & PSDnoise, realT & gmax)
Return the optimum closed loop gain given an open loop PSD.
Returns
the optimum gain.
Parameters
[out] var the variance at the optimum gain
[in] PSDerr open loop error PSD
[in] PSDnoise open loop measurement noise PSD
[in] gmax maximum gain to consider. If 0, then _gmax is used.
Definition at line 813 of file clGainOpt.hpp.
References gmax.
template<typename realT > int mx::AO::analysis::clGainOpt< realT >::pseudoOpenLoop (std::vector< realT > & PSD, realT g)
Calculate the pseudo open-loop PSD given a closed loop PSD.
Returns
0 on success
Parameters
[in,out] PSD input closed loop PSD, on output contains the pseudo open loop error PSD ,
[in] g the loop gain when PSD was measured.
Definition at line 844 of file clGainOpt.hpp.
References mx::AO::analysis::clGainOpt< _realT >::clVariance().
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::setLeakyIntegrator (realT remember)
Set the FIR and IIR coefficients so that the control law is a leaky integrator.
Set remember to 1.0 for a pure integrator control law.
Parameters
[in] remember a number usually close to 1 setting the amount "remembered" from previous iterations.
Definition at line 487 of file clGainOpt.hpp.
template<typename realT > realT mx::AO::analysis::clGainOpt< realT >::tau ()
Get the loop delay.
Returns
the current value of _tau.
Definition at line 414 of file clGainOpt.hpp.
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::tau (realT newTau)
Set the loop delay.
Parameters
[in] newTau the new value of _tau.
Definition at line 420 of file clGainOpt.hpp.
template<typename realT > realT mx::AO::analysis::clGainOpt< realT >::Ti ()
Get the loop sampling interval.
Returns
the current value of _Ti.
Definition at line 401 of file clGainOpt.hpp.
template<typename realT > void mx::AO::analysis::clGainOpt< realT >::Ti (realT newTi)
Set the loop sampling interval.
Parameters
[in] newTi the new value of _Ti.
Definition at line 407 of file clGainOpt.hpp.
Member Data Documentation
template<typename _realT> std::vector<realT> mx::AO::analysis::clGainOpt< _realT >::_a protected
Vector of IIR coefficients.
Definition at line 52 of file clGainOpt.hpp.
template<typename _realT> std::vector<realT> mx::AO::analysis::clGainOpt< _realT >::_b protected
Vector of FIR coefficients.
Definition at line 51 of file clGainOpt.hpp.
template<typename _realT> bool mx::AO::analysis::clGainOpt< _realT >::_changed protected
True if any of the members which make up the basic transfer functions are changed.
Definition at line 58 of file clGainOpt.hpp.
template<typename _realT> std::vector<realT> mx::AO::analysis::clGainOpt< _realT >::_f protected
Vector of frequencies.
Definition at line 54 of file clGainOpt.hpp.
template<typename _realT> bool mx::AO::analysis::clGainOpt< _realT >::_fChanged protected
True if frequency or max size of _a and _b changes.
Definition at line 56 of file clGainOpt.hpp.
template<typename _realT> realT mx::AO::analysis::clGainOpt< _realT >::_maxFindMin
The Minimum value for the maximum stable gain finding algorithm.
Paramaters for stability analysis
Definition at line 70 of file clGainOpt.hpp.
template<typename _realT> int mx::AO::analysis::clGainOpt< _realT >::_minFindBits
The bits of precision to use for minimum finding. Defaults to std::numeric_limits<realT>::digits.
Definition at line 80 of file clGainOpt.hpp.
template<typename _realT> realT mx::AO::analysis::clGainOpt< _realT >::_minFindMaxFact
The maximum value, as a multiplicative factor of maximum gain.
Definition at line 79 of file clGainOpt.hpp.
template<typename _realT> boost::uintmax_t mx::AO::analysis::clGainOpt< _realT >::_minFindMaxIter
The maximum iterations allowed for minimization.
Definition at line 81 of file clGainOpt.hpp.
template<typename _realT> realT mx::AO::analysis::clGainOpt< _realT >::_minFindMin
The Minimum value for the minimum finding algorithm.
Parameters for minimization finding
Definition at line 78 of file clGainOpt.hpp.
template<typename _realT> int mx::AO::analysis::clGainOpt< _realT >::_N protected
Number of integrations in the (optional) moving average. Default is 1.
Definition at line 47 of file clGainOpt.hpp.
template<typename _realT> realT mx::AO::analysis::clGainOpt< _realT >::_tau protected
The loop delay.
Definition at line 49 of file clGainOpt.hpp.
template<typename _realT> realT mx::AO::analysis::clGainOpt< _realT >::_Ti protected
The loop sampling interval.
Definition at line 48 of file clGainOpt.hpp.
The documentation for this struct was generated from the following file:
ao/analysis/clGainOpt.hpp