#ifndef MXLIB_UNCOMP_VERSION_H
#define MXLIB_UNCOMP_VERSION_H

//This is a placeholder for the final version generated by cmake

#ifndef GITHEAD_NOWARNING
  #define GITHEAD_NOWARNING
  #pragma message ("******************************************")
  #pragma message ("*                                        *")
  #pragma message ("*       WARNING: repository modified     *")
  #pragma message ("*        changes not committed for       *")
  #pragma message ("*                  mxlib                 *")
  #pragma message ("*                                        *")
  #pragma message ("******************************************")
#endif


#endif
