# Verify that explicitly inventoried sources emitted counters into a final LCOV tracefile.

foreach(_required_argument TRACEFILE SOURCE_ROOT MANIFEST)
    if(NOT DEFINED ${_required_argument} OR "${${_required_argument}}" STREQUAL "")
        message(FATAL_ERROR "${_required_argument} is required")
    endif()
endforeach()

if(NOT EXISTS "${TRACEFILE}")
    message(FATAL_ERROR "Coverage tracefile does not exist: ${TRACEFILE}")
endif()
if(NOT EXISTS "${MANIFEST}")
    message(FATAL_ERROR "Coverage-record manifest does not exist: ${MANIFEST}")
endif()

file(REAL_PATH "${SOURCE_ROOT}" _source_root)
file(STRINGS "${MANIFEST}" _manifest_lines)
set(_expected_keys)

foreach(_manifest_line IN LISTS _manifest_lines)
    string(STRIP "${_manifest_line}" _manifest_entry)
    if(_manifest_entry STREQUAL "" OR _manifest_entry MATCHES "^#")
        continue()
    endif()
    if(IS_ABSOLUTE "${_manifest_entry}")
        message(FATAL_ERROR "Coverage-record manifest entries must be source-root-relative: ${_manifest_entry}")
    endif()

    file(REAL_PATH "${_source_root}/${_manifest_entry}" _expected_source)
    file(RELATIVE_PATH _expected_relative "${_source_root}" "${_expected_source}")
    if(_expected_relative MATCHES "^\\.\\./" OR IS_ABSOLUTE "${_expected_relative}")
        message(FATAL_ERROR "Coverage-record manifest entry escapes the source root: ${_manifest_entry}")
    endif()
    if(NOT EXISTS "${_expected_source}" OR IS_DIRECTORY "${_expected_source}")
        message(FATAL_ERROR "Coverage-record manifest entry is not a source file: ${_manifest_entry}")
    endif()

    string(SHA256 _expected_key "${_expected_source}")
    if(_expected_key IN_LIST _expected_keys)
        message(FATAL_ERROR "Duplicate coverage-record manifest entry: ${_manifest_entry}")
    endif()

    list(APPEND _expected_keys "${_expected_key}")
    set(_expected_path_${_expected_key} "${_expected_source}")
endforeach()

if(NOT _expected_keys)
    message(FATAL_ERROR "Coverage-record manifest is empty: ${MANIFEST}")
endif()

file(STRINGS "${TRACEFILE}" _trace_lines)
set(_active_key "")

foreach(_trace_line IN LISTS _trace_lines)
    string(STRIP "${_trace_line}" _trace_line)
    if(_trace_line MATCHES "^SF:(.*)$")
        set(_trace_source "${CMAKE_MATCH_1}")
        if(IS_ABSOLUTE "${_trace_source}")
            file(REAL_PATH "${_trace_source}" _trace_source)
        else()
            file(REAL_PATH "${_source_root}/${_trace_source}" _trace_source)
        endif()
        string(SHA256 _trace_key "${_trace_source}")
        if(_trace_key IN_LIST _expected_keys)
            set(_active_key "${_trace_key}")
            set(_seen_${_active_key} TRUE)
        else()
            set(_active_key "")
        endif()
    elseif(NOT _active_key STREQUAL "" AND _trace_line MATCHES "^LF:([0-9]+)$")
        set(_has_lf_${_active_key} TRUE)
        if(CMAKE_MATCH_1 GREATER 0)
            set(_positive_lf_${_active_key} TRUE)
        endif()
    elseif(NOT _active_key STREQUAL "" AND _trace_line MATCHES "^FNF:([0-9]+)$")
        set(_has_fnf_${_active_key} TRUE)
        if(CMAKE_MATCH_1 GREATER 0)
            set(_positive_fnf_${_active_key} TRUE)
        endif()
    elseif(_trace_line STREQUAL "end_of_record")
        set(_active_key "")
    endif()
endforeach()

set(_coverage_record_failures)
foreach(_expected_key IN LISTS _expected_keys)
    set(_expected_source "${_expected_path_${_expected_key}}")
    file(RELATIVE_PATH _expected_relative "${_source_root}" "${_expected_source}")

    if(NOT DEFINED _seen_${_expected_key})
        list(APPEND _coverage_record_failures "${_expected_relative}: missing SF record")
    elseif(NOT DEFINED _has_lf_${_expected_key})
        list(APPEND _coverage_record_failures "${_expected_relative}: missing LF field")
    elseif(NOT DEFINED _positive_lf_${_expected_key})
        list(APPEND _coverage_record_failures "${_expected_relative}: LF is zero")
    elseif(NOT DEFINED _has_fnf_${_expected_key})
        list(APPEND _coverage_record_failures "${_expected_relative}: missing FNF field")
    elseif(NOT DEFINED _positive_fnf_${_expected_key})
        list(APPEND _coverage_record_failures "${_expected_relative}: FNF is zero")
    endif()
endforeach()

if(_coverage_record_failures)
    list(JOIN _coverage_record_failures "\n  " _coverage_record_failure_text)
    message(FATAL_ERROR "Expected coverage counters were not emitted:\n  ${_coverage_record_failure_text}")
endif()

list(LENGTH _expected_keys _expected_count)
message(STATUS "Verified coverage counters for ${_expected_count} expected source file(s)")
